### ISSUE TITLE
MacOS build check failed

### ISSUE THREAD

**Issue by TE-N-ElvenWang** [openthread/ot-br-posix#1002]
Hi,
    When the github automatic build check for my change which added a single file to enable cross-compile, found that the MacOS build check will always fail due below error in: https://github.com/openthread/ot-br-posix/pull/1000/checks?check_run_id=3528850339

Looks it is not caused by my change. 

==> Reinstalling ninja 
==> Installing dependencies for ninja: python@3.9
==> Installing ninja dependency: python@3.9
==> Pouring python@3.9--3.9.7.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

**Comment by Irving-cl** [comment]
I got the same issue and I noticed that many PRs are affected.
