### ISSUE TITLE
'GetAll'  DBUS request fail to fetch 'Channel Monitor Sample Count' property

### ISSUE THREAD

**Issue by RoyAnupam** [openthread/ot-br-posix#1004]
**Describe the bug** A clear and concise description of what the bug is.

I encountered an issue, in which, 'GetAll' request from the DBUS client fails, when  ot-br-posix service daemon tries to create DBUS reply for 'ChannelMonitorSampleCount' property with following error message.

**[ERR ]-UTILS---: Replied to org.freedesktop.DBus.Properties.GetAll with result io.openthread.Error.NotImplemented**

While debugging the issue, it seems, it happened because the flag:: OPENTHREAD_CONFIG_CHANNEL_MONITOR_ENABLE is not enabled, as a result, :GetChannelMonitorSampleCountHandler() method returns OT_ERROR_NOT_IMPLEMENTED error, which eventually fails the 'GetAll' properties request from the DBUS client.

It seems to me that, even though ChannelMonitorSampleCount property is registered, the functionality fails due to unavailability of the compilation flag. When I checked the registration part, I found that, property is registered by default, as follows..

RegisterGetPropertyHandler(OTBR_DBUS_THREAD_INTERFACE, OTBR_DBUS_PROPERTY_CHANNEL_MONITOR_SAMPLE_COUNT,
                               std::bind(&DBusThreadObject::GetChannelMonitorSampleCountHandler, this, _1));
    RegisterGetPropertyHandler(OTBR_DBUS_THREAD_INTERFACE, OTBR_DBUS_PROPERTY_CHANNEL_MONITOR_ALL_CHANNEL_QUALITIES,
                               std::bind(&DBusThreadObject::GetChannelMonitorAllChannelQualities, this, _1));

**I wonder, if these two registrations should be allowed only if  OPENTHREAD_CONFIG_CHANNEL_MONITOR_ENABLE is enabled?**
**Could following be a probable solution of this issue?  Kindly suggest if I am missing something?**

**#if OPENTHREAD_CONFIG_CHANNEL_MONITOR_ENABLE**
            RegisterGetPropertyHandler(OTBR_DBUS_THREAD_INTERFACE, OTBR_DBUS_PROPERTY_CHANNEL_MONITOR_SAMPLE_COUNT,
                               std::bind(&DBusThreadObject::GetChannelMonitorSampleCountHandler, this, _1));
            RegisterGetPropertyHandler(OTBR_DBUS_THREAD_INTERFACE, OTBR_DBUS_PROPERTY_CHANNEL_MONITOR_ALL_CHANNEL_QUALITIES,
                               std::bind(&DBusThreadObject::GetChannelMonitorAllChannelQualities, this, _1));
**#endif**

BR,

**Comment by wgtdkp** [comment]
@RoyAnupam Thanks for reporting this issue!

The proposed solution looks good to me, would you like to create a pull request?

**Comment by RoyAnupam** [comment]
@wgtdkp , Thank you for quick response~

>The proposed solution looks good to me, would you like to create a pull request?

Yes, sure. But, kindly allow me some time.  (My company OSS policy takes a bit of time). Thanks

**Comment by RoyAnupam** [comment]
> @RoyAnupam Thanks for reporting this issue!
> 
> The proposed solution looks good to me, would you like to create a pull request?

@wgtdkp  Raised a PR. Kindly have a look [PR](https://github.com/openthread/ot-br-posix/pull/1018)
