### ISSUE TITLE
"Operation refused for security reasons" when updating the same SRP host twice in a row

### ISSUE THREAD

**Issue by Damian-Nordic** [openthread/ot-br-posix#1011]
**Describe the bug**
https://github.com/openthread/ot-br-posix/pull/1008 was supposed to solve an issue with duplicate SRP updates but it doesn't help in my case. In fact, it can make things even worse in some scenarios.

Suppose that the following SRP updates are sent within a short period of time:
```
UPDATE1:
    EXISTING_HOST
        SERVICE1
UPDATE2:
    EXISTING_HOST
        SERVICE1
```

Since `PublishServiceHandler` and `PublishHostHandler` simply decrement the number of outstanding operations for a matching SRP update and the handlers can be called synchronously when calling `PublishHost` or `PublishService`, `UPDATE1` will be considered completed after processing `UPDATE2.EXISTING_HOST` even if `UPDATE1.EXISTING_HOST.SERVICE1` is still pending. Moreover, too early removal of `UPDATE1` will invalidate a pointer to `UPDATE2` and `UPDATE2.EXISTING_HOST.SERVICE1` will be put in a wrong place in the memory. As a result, the SRP client will never receive a result of `UPDATE2`. 

**To Reproduce**

1. Build and run OTBR Docker container using commit `685a1e0f483febc26127c8c2f2bd8f922b682a06`.
2. Form a Thread network using default settings.
3. Build and flash [Matter Lock](https://github.com/project-chip/connectedhomeip/tree/master/examples/lock-app/nrfconnect) onto a nRF52840 DK.
4. Press Button 3 on the DK to join the formed Thread network.
5. Reboot the DK. After each reboot the firmware adds a new SRP service and due to the issue described above, an SRP update may fail.

**Expected behavior**
SRP updates succeed no matter how frequently they are sent.

**Console/log output**
To be added.

**Additional context**
I prepared a fix which is available here: https://github.com/Damian-Nordic/ot-br-posix/commit/08cb66612477eb5ceb0574b01e7069e855261807, so I can create a PR, but since it reverts https://github.com/openthread/ot-br-posix/pull/1008 I would like to first discuss if that's a good direction.

**Comment by Damian-Nordic** [comment]
@simonlingoogle Can you help? :)

**Comment by simonlingoogle** [comment]
I am actually aware of the potential issue even with #1008 and was planning to introduce more fixes. 

- We need to use more complex logic than just counting the callbacks to make sure the hosts and services are all published (this should help address this bug)
- We need to make sure there is only one outstanding `PublishHost` or `PublishService`, and subsequent `PublishXxxx` will supersede the previous one


> Moreover, too early removal of `UPDATE1` will invalidate a pointer to `UPDATE2` and `UPDATE2.EXISTING_HOST.SERVICE1` will be put in a wrong place in the memory. As a result, the SRP client will never receive a result of `UPDATE2`.

I need to investigate more on this issue. 

@wgtdkp any suggestions?

**Comment by wgtdkp** [comment]
The key issue is that the callback is identified by the host or service
instance name. We need other techniques to associate an ID with calls to
mdnsResponder and avahi. The idea is to wrap the this pointer which is
passed to DNSServiceRegister to carry the SRP update ID.

Simon Lin ***@***.***>于2021年9月16日 周四09:33写道：

**Comment by simonlingoogle** [comment]
I have created https://github.com/openthread/ot-br-posix/pull/1014 to revert #1008 as a quick fix. 

Will create a more mature fix later.

**Comment by Damian-Nordic** [comment]
Thanks @simonlingoogle although it wasn't your change that caused the issue I hit on. It was existent even before.

**Comment by wgtdkp** [comment]
> Thanks @simonlingoogle although it wasn't your change that caused the issue I hit on. It was existent even before.

Would you submit your private PR for fixing the issues your found?

**Comment by Damian-Nordic** [comment]
@wgtdkp I will submit the PR on Monday after doing some more testing :).

**Comment by simonlingoogle** [comment]
@Damian-Nordic Thanks for revealing the memory issue and the fix.

However, I found that the bug is so tricky that https://github.com/Damian-Nordic/ot-br-posix/commit/08cb66612477eb5ceb0574b01e7069e855261807 still hasn't totally addressed the problem. 
For example, the outstanding update `aUpdate` may be invalidated within the method `PublishHostAndItsServices`, which are used in  `PublishHostAndItsServices` multiple times. 

I think it's quite hard to get everything right if the callbacks can be triggered during the host and services publishing. 
We can use a `TaskRunner` to Post callbacks so that callbacks won't be called during `PublishHostAndItsServices`, so that we don't need to handle these tricky cases.

I can create a fix if you think it's a good idea to use `TaskRunner` to simplify the problem. @wgtdkp @Damian-Nordic

**Comment by jwhui** [comment]
Re-opening since the discussion remains ongoing.

**Comment by Damian-Nordic** [comment]
@simonlingoogle @wgtdkp I think that's a good idea. I modified my change to also run all the handlers asynchronously and in the same thread, and tested that I couldn't break the SRP by re-publishing the same services in a loop. I posted a PR with the change. Let me know if that's what you meant.

Btw, I wonder if it would make sense to implement some kind of recovery mechanism in OTBR - currently when an update is somehow not handled correctly (which I admit should never happen, but things happen ;)) it never gets removed from the list of outstanding updates and if the client sends a new update, the old one is updated first which leaves the new update unfinished (and the cycle repeats). I believe the server should give up an invalid update at some point in case it can't be completed properly. But that's just an idea.

**Comment by wgtdkp** [comment]
> @simonlingoogle @wgtdkp I think that's a good idea. I modified my change to also run all the handlers asynchronously and in the same thread, and tested that I couldn't break the SRP by re-publishing the same services in a loop. I posted a PR with the change. Let me know if that's what you meant.
> 
> Btw, I wonder if it would make sense to implement some kind of recovery mechanism in OTBR - currently when an update is somehow not handled correctly (which I admit should never happen, but things happen ;)) it never gets removed from the list of outstanding updates and if the client sends a new update, the old one is updated first which leaves the new update unfinished (and the cycle repeats). I believe the server should give up an invalid update at some point in case it can't be completed properly. But that's just an idea.

We actually have a plan to bind a unique ID to each service and host registration and in which case we will not mismatch previous failed service.

**Comment by Damian-Nordic** [comment]
@wgtdkp Ok, so should I close my PR?

**Comment by wgtdkp** [comment]
> @wgtdkp Ok, so should I close my PR?

No, It may make some time for us to implement the eventual solution, you current fix makes sense to me, thanks! :)

**Comment by simonlingoogle** [comment]
I think the PR contains two parts:
1. `Post` the callback so that they will always be invoked after publishing
2. Make sure `PublishHost` handler and `PublishService` handlers are called exactly once for each `OutstandingUpdate`.

I think part 1 is useful no matter we use the unique ID or not. And part 1 actually removes the requirement to use unique ID to some extent  because everything works well with 1 alone. 

Part 2 is not a must if we are using unique IDs, nevertheless I find it nice to have (to avoid any future subtle issues).

**Comment by Damian-Nordic** [comment]
Part 2 will no longer be needed when you implement assigning update IDs to Publisher's operations, so that the handler can uniquely identify an update which trigger the operation. Until that Part 2 makes sure that updating the host twice is not the same as updating the host and a service on that host.
