### ISSUE TITLE
NCP support on Rpi based Border router

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/ot-br-posix#1021]
The latest open thread repo for the nrf52840 platform provides support for NCP, but the latest ot-br-posix platform for the Rpi-based border router doesn't support NCP.
Only RCP is supported there. Is there any border router platform that supports NCP as well?
Also, if NCP is removed from the border router side, why it is still considered in openthread platform?

**Comment by jwhui** [comment]
> The latest open thread repo for the nrf52840 platform provides support for NCP, but the latest ot-br-posix platform for the Rpi-based border router doesn't support NCP.

RCP builds are supported in [openthread/ot-nrf528xx](https://github.com/openthread/ot-nrf528xx/).

> Only RCP is supported there. Is there any border router platform that supports NCP as well?

The latest main branch only supports RCP.

We have a [branch](https://github.com/openthread/ot-br-posix/tree/wpantund/master) that supports NCP, but it hasn't been updated for over a year.

> Also, if NCP is removed from the border router side, why it is still considered in openthread platform?

The OpenThread project provides all the pieces to build an NCP-based border router. Note that the RPi platform is a **_reference_** platform, we expect that many end products will integrate OpenThread as they see fit.

**Comment by bhumikaajain** [comment]
@jwhui Thanks for clearing my doubts.
If I take the latest main branch that supports RCP, what changes would it bring in my overall thread mesh network?

What other factors do I need to keep in mind while making this transition on the border router side?

**Comment by jwhui** [comment]
> @jwhui Thanks for clearing my doubts.
> If I take the latest main branch that supports RCP, what changes would it bring in my overall thread mesh network?

From a Thread perspective, but NCP and RCP should be functionally equivalent.

> What other factors do I need to keep in mind while making this transition on the border router side?

The APIs and CLI will be different between OpenThread and `wpantund`.

**Comment by jwhui** [comment]
Closing stale issue.
