### ISSUE TITLE
[question] Receive udp messages via otbr dbus interface

### ISSUE THREAD

**Issue by RoyAnupam** [openthread/ot-br-posix#1034]
Hi,
 I have following setup
 -  Thread accessory device  (running otbr-agent & a DBUS based application)
 -  Thread Target Network device
 
I provisioned the Thread accessory device running otbr-agent via DBUS interface to connect to the target thread network. Then, I opened and bound a UDP channel in the accessory device (via ot-ctl) & started data communication from the Target network. I sent messages from the Target thread network device & able to see the UDP messages received in the accessory device in the otbr-agent debug logs. **My question is, whether it is possible  or is there any way to receive messages to the DBUS application also via otbr-agent's DBUS interface?** 

**Following are UDP messages received**
Jan 01 09:19:00 localhost otbr-agent[1609]: [INFO]-MAC-----: Received IPv6 UDP msg, len:61, chksum:878a, from:0x8000, sec:yes, prio:normal, rss:-72.0, radio:15.4
Jan 01 09:19:00 localhost otbr-agent[1609]: [INFO]-MAC-----:     src:[fd15:43c7:d701:90fa:0:ff:fe00:fc30]:49157
Jan 01 09:19:00 localhost otbr-agent[1609]: [INFO]-MAC-----:     dst:[fd15:43c7:d701:90fa:7d1e:9ba5:739c:3da0]:1212

**Comment by wgtdkp** [comment]
> Then, I opened and bound a UDP channel in the accessory device (via ot-ctl) & started data communication from the Target network.

You don't need to bind a UDP port with `ot-ctl`. otbr-agent already creates a wpan0 interface for IP communication. You can write your accessory application with standard unix socket APIs in a standalone program as if the accessory is communicating via Ethernet or Wi-Fi.

**Comment by RoyAnupam** [comment]
> > Then, I opened and bound a UDP channel in the accessory device (via ot-ctl) & started data communication from the Target network.
> 
> You don't need to bind a UDP port with `ot-ctl`. otbr-agent already creates a wpan0 interface for IP communication. You can write your accessory application with standard unix socket APIs in a standalone program as if the accessory is communicating via Ethernet or Wi-Fi.

@wgtdkp , Thank You for quick response to the query. If I  understood correctly, you meant, that I could open a RAW or TCP IPV6 socket to wpan0 interface and handle the data communication over this interface like standalone client/server socket programs? Please correct me if I am missing something..

Also, while looking for some reference on TCP socket communication on wpan0 interface, I browsed the code and observed tcp handling codes are *not implemented*, while . File: src/core/net/tcp6.cpp.  Is it under development currently?

**Comment by wgtdkp** [comment]
> If I understood correctly, you meant, that I could open a RAW or TCP IPV6 socket to wpan0 interface and handle the data communication over this interface like standalone client/server socket programs?

Yes.

`src/core/net/tcp6.cpp` are for creating tcp socket within openthread, they are not required for you to create standalone BSD socket.

**Comment by RoyAnupam** [comment]
@wgtdkp I tried send/receive over wpan0. It works well. Thanks.

Could you share some light about how a Thread Node can learn about IPV6 addresses & listening ports of all the reachable neighboring nodes in the network? Is there some guide which I can follow?

**Comment by wgtdkp** [comment]
If you want to discover Thread node service from adjacent Wi-Fi or Ethernet network, like from your standalone application, you can follow this codelab: https://openthread.io/codelabs/openthread-border-router. You can just send mDNS queries on the Wi-Fi/Ethernet network with some mDNS libraries (like avahi for linux). This requires that your current discovering device is connecting to the same Wi-Fi/Ethernet network of the Border Router of the Thread network.

**Comment by RoyAnupam** [comment]
@wgtdkp , Actually, in my BR platform, ping6 command works, & I am able to reach the End Device. Below is the result.

sh-3.2# ip -6 fd05:c8e0:98a0:9e72:6b3:da90:274b:d542
Object "fd05:c8e0:98a0:9e72:6b3:da90:274b:d542" is unknown, try "ip help".
sh-3.2# ping6 fd05:c8e0:98a0:9e72:6b3:da90:274b:d542
PING fd05:c8e0:98a0:9e72:6b3:da90:274b:d542 (fd05:c8e0:98a0:9e72:6b3:da90:274b:d542): 56 data bytes.
64 bytes from fd05:c8e0:98a0:9e72:6b3:da90:274b:d542: seq=0 ttl=64 time=15.238 ms
64 bytes from fd05:c8e0:98a0:9e72:6b3:da90:274b:d542: seq=1 ttl=64 time=14.820 ms
64 bytes from fd05:c8e0:98a0:9e72:6b3:da90:274b:d542: seq=2 ttl=64 time=17.312 ms
64 bytes from fd05:c8e0:98a0:9e72:6b3:da90:274b:d542: seq=3 ttl=64 time=37.725 ms
64 bytes from fd05:c8e0:98a0:9e72:6b3:da90:274b:d542: seq=4 ttl=64 time=19.542 ms
64 bytes from fd05:c8e0:98a0:9e72:6b3:da90:274b:d542: seq=5 ttl=64 time=15.703 ms
64 bytes from fd05:c8e0:98a0:9e72:6b3:da90:274b:d542: seq=6 ttl=64 time=15.047 ms

**Comment by wgtdkp** [comment]
There is a [Network Analyzer App](https://play.google.com/store/apps/details?id=net.techet.netanalyzerlite.an) in page 7 of the codelab~

**Comment by wgtdkp** [comment]
okay, this is the problem, I assume you are not using the same raspberry pi os suggested by the codelab, right? a quick workaround is to force enable the IPv6 forwarding with:

```shell
sudo sysctl -w net.ipv6.conf.all.forwarding=1
```

**Comment by RoyAnupam** [comment]
@wgtdkp ,,  I missed another thing which I just realized. When I was using service browser to find the fake tcp service (ot.service) registered by the End Device,  in my above post,, I had by mistake connected the End Device to the same Wi-Fi AP network as that of the BR(unknowingly). After that, I was able to browse the ot.service from both avahi lib in Linux (Ubuntu) as well as ServiceBrowser (Android App).

I just realized it and disconnected the End device from the AP and tried to search for the service again using avahi and servicebrowser apps, but unable to find the service now! The moment I connect the EndDevice back to WiFi AP, the service pops up in search!

I was assuming, BR will keep advertising the service on its own, without any intervention from EndDevice, once the service is registered using SRP. So, I think, even if EndDevice is not connected to any network other than its native Thread mesh,, still I should be able to find the service in mdns or avahi browse.  Please correct me if I am wrong.

I think, I am missing something probably. Do you see anything suspicious?

**Comment by wgtdkp** [comment]
If your end device is a otbr-agent and has infrastructure IP connectivity, I don't see why it's necessary to have another BR device there.

If you want to showcase or verify that you can send commands to an end device which is bridged by a BR device, then I think it's better to use ot-posix rather than otbr-agent. otbr-agent is really just ot-posix plus the BR features you need to disable at runtime on your end device.

**Comment by wgtdkp** [comment]
The outputs look good to me.
@RoyAnupam Didi you forget to start the SRP client? Check the SRP client state with `sudo ot-ctl srp client state`. If it shows `Disabled`, please start the client with commands:
```
sudo ot-ctl srp client stop
sudo ot-ctl srp client autostart enable
```

**Comment by wgtdkp** [comment]
@RoyAnupam Thanks for reporting this. It seems not related to this issue already, may be an issue in the SRP client, Do you mind creating another issue for this?

Providing below information can be very helpful:
1. steps to reproduce the issue
2. BR and end device logs got by command `cat /var/log/syslog | grep otbr-agent`.
