### ISSUE TITLE
[web service] wpantund forgets the on-mesh prefix.

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#104]
Originally reported by Stuart Longland from [openthread-users](https://groups.google.com/d/msg/openthread-users/CQKuQI6o_BQ/nzaJVXyBCwAJ).

**Comment by thcu-gp** [comment]
This is probably an issue for all prefixes served by the border router (on and off mesh).

**Comment by tarunsmalviya** [comment]
I am also facing same issue.

**Comment by sjlongland** [comment]
I found a work-around… I set up this script to run at boot:
```
root@wsg-74fe481fe117:~# cat /usr/local/bin/recommission-ncp 
#!/bin/sh

ROUTER_CONFIG='{
        "networkKey":"aabbccddaabbccddaabbccddaabbccdd",
        "prefix":"fdaa:bbcc:ddee:ff00::",
        "defaultRoute":true,
        "extPanId":"0011223344556677",
        "panId":"0x0123",
        "passphrase":"0123012301",
        "channel":1,
        "networkName":"MyNetwork"
}'

wpanctl reset && sleep 10 && curl -d"${ROUTER_CONFIG}" \
        -H 'Content-Type: application/json;charset=utf-8' \
        http://localhost:8080/form_network
```
That JSON blob is found by using my browser's developer tools to snoop on the front-end to the border router.  It's not pretty, but it gets me going.  The `wpanctl reset` probably isn't needed in most cases, just in our case the NCP is "special" and doesn't seem to want to work first try.

**Comment by sjlongland** [comment]
One thing I observe now, is `wpantund` after commissioning, will then mysteriously "forget" the prefix.  In some cases, mere minutes after assigning it.  e.g.

```
Oct  8 10:31:23 wsg-74fe481fe117 wpantund[498]: wpantund[498]: Pushing a new SLAAC address 2001:db8:1234:5678:248a:784b:f413:756b/64 to NCP
Oct  8 10:31:23 wsg-74fe481fe117 wpantund[498]: wpantund[498]: Adding address "2001:db8:1234:5678:248a:784b:f413:756b/64" to NCP
Oct  8 10:31:23 wsg-74fe481fe117 otbr-agent[2317]: NCP property Daemon:ReadyForHostSleep changed.
Oct  8 10:31:23 wsg-74fe481fe117 otbr-agent[2317]: otbr-agent[2317]: NCP property Daemon:ReadyForHostSleep changed.
Oct  8 10:31:23 wsg-74fe481fe117 otbr-agent[2317]: NCP property Daemon:ReadyForHostSleep changed.
Oct  8 10:31:23 wsg-74fe481fe117 otbr-agent[2317]: otbr-agent[2317]: NCP property Daemon:ReadyForHostSleep changed.
Oct  8 10:33:52 wsg-74fe481fe117 wpantund[498]: Removing SLAAC address 2001:db8:1234:5678:248a:784b:f413:756b/64 from NCP
Oct  8 10:33:52 wsg-74fe481fe117 wpantund[498]: Removing address "2001:db8:1234:5678:248a:784b:f413:756b/64" from NCP
Oct  8 10:33:52 wsg-74fe481fe117 otbr-agent[2317]: NCP property Daemon:ReadyForHostSleep changed.
Oct  8 10:33:52 wsg-74fe481fe117 wpantund[498]: wpantund[498]: Removing SLAAC address 2001:db8:1234:5678:248a:784b:f413:756b/64 from NCP
Oct  8 10:33:52 wsg-74fe481fe117 wpantund[498]: wpantund[498]: Removing address "2001:db8:1234:5678:248a:784b:f413:756b/64" from NCP
```

**Comment by tarunsmalviya** [comment]
I noticed one thing, that when we add on mesh prefix for the first time and after rebooting, the ncp persist the on mesh prefix which is labelled as **origin:ncp**. In this state, my coap message are not able to reach RPi and also I am not able to ping RPi. When I again add the on mesh prefix using Web GUI, new prefix is added into on mesh prefix list with label **origin:user**, and I am able to receive ping and coap messages in RPi.
Can anyone help me regarding this issue.

**Comment by jwhui** [comment]
Closing stale issue.
