### ISSUE TITLE
1.2 DUA routing with docker containers

### ISSUE THREAD

**Issue by suveshpratapa** [openthread/ot-br-posix#1053]
When we set up two OTBRs from scratch (non-docker) and configure them as BBRs for two different meshes, we are able to demonstrate 1.2 DUA connectivity between the two meshes.

However, we cannot demonstrate the same with two OTBR docker containers. Can someone please review our setup and provide some advice?

On both BBRs:

- Created (example) docker bridge network and ran a container using that network:

```
sudo docker network create --ipv6 --subnet fd11:db8:1::/64 -o com.docker.network.bridge.name=otbr0 otbr-network

docker run -d --name "otbr" --network otbr-network --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 --dns=127.0.0.1 -it --volume /dev/ttyACM0:/dev/ttyACM0 -v /dev/bus/usb:/dev/bus/usb --privileged otbr-test:latest --radio-url spinel+hdlc+uart:///dev/ttyACM0
```

- Configured domain prefix `fd00:7d03:7d03:7d03::/64`

This is a test setup, so we are manually configuring routes:

BBR1:
`sudo ip -6 route add fd00:7d03:7d03:7d03::/64 via <ll-addr-of-BBR2-eth0> dev eth0`

BBR2:
`sudo ip -6 route add fd00:7d03:7d03:7d03::/64 via <ll-addr-of-BBR1-eth0> dev eth0`

Doing the above was enough for the non-docker case, but clearly we're missing some additional configuration in the docker case.  How do we inform the docker bridge network about the routing rules for the DUA prefix?  Is there additional docker configuration we could be missing?

**Comment by suveshpratapa** [comment]
@jwhui I'm working with @JaneFromSilabs on testing 1.2 DUA with docker containers, and we're stuck, so looking for advice in this area. We suspect it's a routing rule complication we're missing with docker containers, but can't get a clear answer online.

**Comment by simonlingoogle** [comment]
One hint is that the DUA prefix `fd00:7d03:7d03:7d03::/64` should not be added as routes. 

Instead, `fd00:7d03:7d03:7d03::/64` should be advertised as a on-link prefix, usually by [radvd](https://radvd.litech.org/).

For example, we are using radvd in GitHub Actions to test Thread 1.2 DUA features:
```
# cat /etc/radvd.conf
interface eth0
{
    AdvSendAdvert on;

    MinRtrAdvInterval 3;
    MaxRtrAdvInterval 30;
    AdvDefaultPreference low;

    prefix fd00:7d03:7d03:7d03::/64
    {
        AdvOnLink on;
        AdvAutonomous off;
        AdvRouterAddr off;
    };
};
```

Please verify if radvd can solve the issue. Thanks. @suveshpratapa

**Comment by jwhui** [comment]
Closing stale issue.
