### ISSUE TITLE
[adproxy] error in simutaneous updates to the same serivce/host

### ISSUE THREAD

**Issue by wgtdkp** [openthread/ot-br-posix#1071]
Current Advertising proxy is indexing outstanding SRP updates with their host and service names and this has issues when there are simutaneous updates to the same serivce or host: the underlying mDNS publisher (mDNSResponder and avahi) is terminating previous service registration before registering new service for current update; this will result in previous SRP updates not be notified with service registration callbacks and hence times out, resulting in SRP registration failure. An example failure can be found https://github.com/openthread/openthread/runs/4048259822.

[logs_4048259822.txt](https://github.com/openthread/ot-br-posix/files/7443684/logs_4048259822.txt)

The fix is proposed here https://github.com/openthread/ot-br-posix/issues/1011#issuecomment-920529656 to associate an unique ID to each mDNS service registration so that we will not mismatch outstanding SRP updates by their names.

**Comment by simonlingoogle** [comment]
> the underlying mDNS publisher (mDNSResponder and avahi) is terminating previous service registration before registering new service for current update; this will result in previous SRP updates not be notified with service registration callbacks and hence times out, resulting in SRP registration failure.

I think mDNS publishers should make sure to do callbacks for echo `PublishHost` or `PublishService` call. I checked the mdns_mdnssd.cpp, and it seems to be calling callbacks correctly when updating existing hosts or services. 
Thoughts on why SRP update not notified in mDNSResponder?
