### ISSUE TITLE
OTBR Agent fails with "RadioSpinelNoResponse" error when multiple device connects

### ISSUE THREAD

**Issue by Hard1kPrajapati** [openthread/ot-br-posix#1076]
Hello Team,

I am working on my custom board where I am running the border router created with CC2538 RCP binary. As soon as I connect multiple clients with my BR and start sending UDP packets after sometimes it fails with "RadioSpinelNoResponse" error at a random time.
Environment setup:
- One border router was created using RCP(CC2538).
- 5 end devices(nRF52840 DK as CLI) join the network created by BR(leader).
- OTBR Agent is running in debug mode.
- OTBR Agent and RCP, both the sources are the latest.

I have created an RCP binary for CC2538 with CC2592 enabled and on my host processor I am creating the border router with the help of RCP. And as soon as multiple end devices join the network, it fails. Sometimes, it shows "Framing error" and sometimes it shows a "No message buffer available" error.

I have also tried to increase the buffer size from otbr-agent source(from 256 to 1024) but the issue persisted. Please guide me where this could be the issue. Please check the logs I am attaching.

[OTBR_Agent_radioSpinelFailed_debuglog_2Nov.txt](https://github.com/openthread/ot-br-posix/files/7458387/OTBR_Agent_radioSpinelFailed_debuglog_2Nov.txt)

Thanks,
Hardik

**Comment by jwhui** [comment]
The "Framing error" typically indicates that the serial communication is not reliable for some reason.

What baud rate are you using?

Are you able to reproduce this issue using a Raspberry Pi?

**Comment by Hard1kPrajapati** [comment]
Hi @jwhui,
Thanks for the reply.
I am using a 115200 baud rate on both sides (In OTBR Agent as well as in RCP binary). 
Also, I didn't check using Raspberry Pi but will test and update you.

I have tried the below things as well but the results were the same:
**OTBR-AGENT changes:**
- Increased the buffer size of NUM_MESSAGE_BUFFERS from 256 to 2048
- Increased the TX_WAIT_US time from 5 sec to 60 sec.

**CC2538 RCP changes:**
- Added the support of UART HW Flow control.

Please suggest any possible workaround or solution.

Thanks,
Hardik

**Comment by Hard1kPrajapati** [comment]
Any update on this? Any suggestions would be welcome,

**Comment by jwhui** [comment]
Are you able to reproduce this issue using a Raspberry Pi?

**Comment by Hard1kPrajapati** [comment]
Yes, we are able to reproduce the issue with Raspberry Pi. We have tried the nRF52840 USB dongle with Raspberry Pi. Please check this below log.
[RPi_USB_Dongle_OTBRAgent_FailureLog_15Nov.txt](https://github.com/openthread/ot-br-posix/files/7585937/RPi_USB_Dongle_OTBRAgent_FailureLog_15Nov.txt)

It seems like, the otbr-agent transmit the frame to RCP over spinel, and it does not get the response within the expected time,. Then timeout occurs and it fails with the error message.

**Comment by jwhui** [comment]
Can you provide more information so it is possible to reproduce your issue?

1. Git commit id
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Comment by Hard1kPrajapati** [comment]
Please check my response below.
1. Git last commit IDs are as below
   OTBR Agent: **741a5f75132c6f8074b50086ac77f5843c14def3**
   RCP: **a402cf2c3531418d25e841fb5f537af3dadba10c**
2. IEEE 802.15.4 hardware platform
   The HW platform is CC2538(We are running RCP on it to make my host processor border router).
3. Build steps
   **OTBR Agent build command:**
   > cmake -GNinja ../ -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=<My DIR> -DOTBR_DBUS=ON -DOTBR_WEB=ON -DOTBR_INFRA_IF_NAME=eth0 -DOTBR_BORDER_ROUTING=ON -DOTBR_BACKBONE_ROUTER=ON -DOTBR_REST=ON -DOTBR_SRP_ADVERTISING_PROXY=ON -DOT_LOG_LEVEL=DEBG

     **RCP build command:**
      > script/build cc2538 UART_trans -DOT_THREAD_VERSION=1.2 -DOPENTHREAD_CONFIG_CC2538_WITH_CC2592=1
4. Network topology
    Border Router = AM57XX(Host processor - OTBR Agent) + CC2538(RCP)
    REED device = 5 nRF52840 DK(becomes router after child timeout). These are connected with BR created thread network.

**Comment by jwhui** [comment]
@Hard1kPrajapati , can you see if the problem is reproducible when using the nRF52840 as an RCP in place of the CC2538?

**Comment by Hard1kPrajapati** [comment]
Yes, we have removed CC2538 from our custom board and connected the UART interface with RCP flashed nRF52840 DK board. With this setup as well it was reproduced.

**Comment by jwhui** [comment]
@Hard1kPrajapati , is the problem reproducible when using Raspberry Pi + nRF52840 as RCP?

**Comment by wgtdkp** [comment]
> root@raspberrypi:/home/pi/HP#
root@raspberrypi:/home/pi/HP#
root@raspberrypi:/home/pi/HP# [ 2852.636081] Under-voltage detected! (0x00050005)
>
>root@raspberrypi:/home/pi/HP# [ 2902.556290] Under-voltage detected! (0x00050005)
>
>root@raspberrypi:/home/pi/HP#
root@raspberrypi:/home/pi/HP#

@Hard1kPrajapati This may affect the connection between `otbr-agent` and the RCP device.

**Comment by Hard1kPrajapati** [comment]
@jwhui, Yes we were able to reproduce with RPI+nRF52840 USB dongle(RCP)

**Comment by jwhui** [comment]
@Hard1kPrajapati , can you please provide more information to reproduce with a Raspberry Pi and nRF52840 as RCP?

1. Git commit ids
2. Raspberry Pi hardware platform
3. IEEE 802.15.4 hardware platform
4. Build steps
5. Network topology

**Comment by jwhui** [comment]
> > root@raspberrypi:/home/pi/HP#
> > root@raspberrypi:/home/pi/HP#
> > root@raspberrypi:/home/pi/HP# [ 2852.636081] Under-voltage detected! (0x00050005)
> > root@raspberrypi:/home/pi/HP# [ 2902.556290] Under-voltage detected! (0x00050005)
> > root@raspberrypi:/home/pi/HP#
> > root@raspberrypi:/home/pi/HP#
> 
> @Hard1kPrajapati This may affect the connection between `otbr-agent` and the RCP device.

@Hard1kPrajapati , can you also verify that the RPi power supply is able to provide sufficient current?

**Comment by Hard1kPrajapati** [comment]
Okay, when I get time I will make sure for the power provided to Raspberry Pi.

Meanwhile, can anyone help me to solve the issue I am facing on our board(Explained the setup earlier) 
When any device connects with a Border router, what kind of communication goes between host processor and RCP over spinel? From the debugging logs, it seems like the otbr-agent(host) waits for any data from RCP(CC2538) and could not receive any expected data in time, so dies.

Do you think here that CC2538 hangs or is stuck somewhere so could not process further?

**Comment by jwhui** [comment]
Failure to respond could be due to a number of issues. It may be due to unreliable serial communication, which also triggers the "Framing error" log output. It may also be due to the RCP hanging somewhere. If you have a debugger attached to the RCP, that can help root cause the issue.

**Comment by Hard1kPrajapati** [comment]
One thing I have noticed that is while recovering from RCP failure(updated the OPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT), it fails in setting the maximum transmit power for each channel(while restoring properties). It returned the error like it is not implemented.

This I have commented and it goes ahead but sometimes it fails connecting the existing network.

Why does this error show? Does that mean it is not implemented at all or it does not require the implementation?

**Comment by Hard1kPrajapati** [comment]
Is there any update on this?

**Comment by jwhui** [comment]
> One thing I have noticed that is while recovering from RCP failure(updated the OPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT), it fails in setting the maximum transmit power for each channel(while restoring properties). It returned the error like it is not implemented.

Setting maximum transmit power per channel requires implementation of [`otPlatRadioSetChannelMaxTransmitPower()`](https://github.com/openthread/openthread/blob/e708324c3189cf3ac2f33bfc2d10c61a43a4df6f/include/openthread/platform/radio.h#L1085). The CC2538 platform does not implement this.

**Comment by Hard1kPrajapati** [comment]
Okay, thanks for the reply.

So, in this case, should I just keep commenting and go ahead or it needs the implementation? Because, later, it does not connect the existing network.

I have to dig it more into this code and I see the exact same frame when the host transmits and RCP receives. But when it fails it seems like the host send a command that RCP could not respond in time or did not receive the command frame properly hence it failed.

I am attaching logs here, please check:
[HP_framePrints_9Dec.txt](https://github.com/openthread/ot-br-posix/files/7701365/HP_framePrints_9Dec.txt)

As you can see here in the log file, it seems like it is failed twice with the same common command "**8F 03 71 4B 00 41 D8 EE B5 54 FF**" (Later payload and checksum might be different but the command is the same).

Can you please look into this and guide me? Any help would be appreciated.

Thanks,
Hardik

**Comment by jwhui** [comment]
@Hard1kPrajapati , are you able to attach a debugger to your RCP and determine if it is in a hung state before reset?

**Comment by Hard1kPrajapati** [comment]
Sorry but I don't have a debugger available. That's why I am adding prints in RCP code and running otbr-agent in debug mode.

**Comment by jwhui** [comment]
> Sorry but I don't have a debugger available. That's why I am adding prints in RCP code and running otbr-agent in debug mode.

nRF52840-DK has an integrated debugger, which should give greater visibility into the RCP.

**Comment by Hard1kPrajapati** [comment]
Hello Team,

Sorry for the late reply. 

I want to understand the difference when I run the OTBR Agent with full debug mode **(-v -d 7 option)** and limited debug mode **(-v -d 1 option, only critical mode)**. Sorry for this silly question.

Observation is when I run the Agent with the **"-v -d 7"** option along with RCP, then it fails very quickly(within a few minutes) as soon as all the end devices become routers.

And, when I run the Agent with the **"-v -d 1"** option along with RCP, then it runs well even all devices are connected and sending UDP packets over every second. JFYI, the test is still running for 3 days.

I know with the **-1 option** it prints only critical logs and with the **-7 option**, it prints all debug prints. But why doesn't fail with the **-1 option** and quickly kill with full debug mode? Is it something it occupies something and could not serve more things?

Regards,
Hardik

**Comment by Hard1kPrajapati** [comment]
Hi,

One more finding is when I keep my end device to the child only (does not promote to router or REED disable) then it works well even with full debug mode (-d 7 option). And it doesn't work when router eligibility is enabled.

Do you think it gets more time to respond to the child while updating to the router? Where could possibly be an issue?

Regards,
Hardik

**Comment by Hard1kPrajapati** [comment]
Any update on this?

**Comment by jwhui** [comment]
> Any update on this?

@Hard1kPrajapati , specific to the nRF52840 as RCP, this may be related to the issue raised in https://github.com/openthread/ot-nrf528xx/issues/237.

/cc/ @MarekPorwisz @LuDuda

**Comment by canisLupus1313** [comment]
@Hard1kPrajapati
I ave to ask You few questions before we will start the debugging.
What are the devices and board that You are using to setup the BBR? (from conversation can see that You have tried several but let's focus on Nordic ones)
Whish exactly application are You using to setup RCP?
What are the revisions of the repos that are You using?
And also please whenever You are going to rebuild the RCP application manually remove build folder before.

**Comment by Hard1kPrajapati** [comment]
> 
 Please find my answers below:
1) My environment setup is like this: 
**BR(Agent + RCP):** We have our TI AM5726 based custom board and the CC2538 module is mounted on the same board. So I am running the OTBR Agent on the host(AM5726) and RCP binary on CC2538. Both the binaries are from the Openthread.
**End device:** This is Nordic's nRF52840 DKs (5 in Qty). I have modified the client code to broadcast the onboard temperature every second as a UDP packet.  
2) I am generating the hex file from **ot-cc2538 source** and flashing on the CC2538 to work as an RCP. So the agent can start and form the network.
3) Please refer the below last commit IDs I am using:
For OTBR Agent (ot-br-posix): **72fa16e595af28d2f2a3fbd19c3da9f5c3d397de**
For RCP (ot-cc2538): **63c91b674900bfc6eb31b1d7d433003de43661ae**
For End device (ot-nrf528xx): **5875210398f402e0944b066ec6c864fd9f76e282**

I always remove the build folder and compile the RCP and Agent every time.

Let me know If you need any more information.

**Comment by jwhui** [comment]
@Hard1kPrajapati , you mentioned in https://github.com/openthread/ot-br-posix/issues/1076#issuecomment-976177071 that you are able to reproduce the issue with Raspberry Pi and nRF52840 USB Dongle. As @canisLupus1313 requested, can we focus on that case for now?

**Comment by Hard1kPrajapati** [comment]
If you want I can share my nRF52840's end device binary as well.

Also, as soon as I start I am seeing below errors as well. 
```
sh: ipset: command not found
otbr-agent[1218]: 00:00:00.054 [INFO]-PLAT----: Execute command `ipset flush otbr-ingress-allow-dst-swap` = 32512
otbr-agent[1218]: 00:00:00.054 [INFO]-PLAT----: Got an error when executing command `ipset flush otbr-ingress-allow-dst-swap`: `Resource temporarily unavailable`
otbr-agent[1218]: 00:00:00.055 [WARN]-PLAT----: Failed to update ipsets: Failed
```
What is ipset? And does it play an important role in this?

**Comment by jwhui** [comment]
> If you want I can share my nRF52840's end device binary as well.

That would be helpful, but we also want to focus on debugging the BR with a Raspberry Pi and nRF52840 USB Dongle that you reported in https://github.com/openthread/ot-br-posix/issues/1076#issuecomment-976177071.
 
> Also, as soon as I start I am seeing below errors as well.
> 
> ```
> sh: ipset: command not found
> otbr-agent[1218]: 00:00:00.054 [INFO]-PLAT----: Execute command `ipset flush otbr-ingress-allow-dst-swap` = 32512
> otbr-agent[1218]: 00:00:00.054 [INFO]-PLAT----: Got an error when executing command `ipset flush otbr-ingress-allow-dst-swap`: `Resource temporarily unavailable`
> otbr-agent[1218]: 00:00:00.055 [WARN]-PLAT----: Failed to update ipsets: Failed
> ```
> 
> What is ipset? And does it play an important role in this?

This is installed as part of `./script/bootstrap`
https://github.com/openthread/ot-br-posix/blob/538d61916e6396d4507b7b2aee1ed86bbdda0fd2/script/bootstrap#L103

**Comment by Hard1kPrajapati** [comment]
The nRF52840 end device binary is here:
[nRF52840_CLI_UDPEnabled1Sec_LogDisabled_11Jan.zip](https://github.com/openthread/ot-br-posix/files/7948318/nRF52840_CLI_UDPEnabled1Sec_LogDisabled_11Jan.zip)

On my custom board, I have **iptables** binary but I don't have **ipset**. So, to get rid of the ipset error, I just disabled the Firewall in the Agent code. So, do you think it will affect the OT network communication? Is it okay to disable the firewall? I am assuming that it executes the **ipset** command when any network data changes. Hence, disabled. let me know if my understanding differs.

**Comment by jwhui** [comment]
@Hard1kPrajapati , we would prefer to focus the debugging effort on the Raspberry Pi with nRF25840 USB Dongle, rather than your custom board at this time.

**Comment by canisLupus1313** [comment]
@Hard1kPrajapati it's good  that you have a nRF DK's. Would it be possible to setup BBR as Raspberry pi + nordic DK (RCP)?
in this way we will be able to use DK's embedded debug features to figure out what might be wrong.

**Comment by jwhui** [comment]
Closing stale issue.
