### ISSUE TITLE
Refreshing SRP services fails after OTBR reset

### ISSUE THREAD

**Issue by kkasperczyk-no** [openthread/ot-br-posix#1080]
**Describe the bug** A clear and concise description of what the bug is.
In the Matter project utilizing SRP on the accessory device there is a problem with refreshing already added SRP services on the OTBR. Refreshing services on the server side seems to be working fine, but server doesn't respond to the client, so client claims that operation failed.

**To Reproduce** Information to reproduce the behavior, including:
OTBR revision: 72bb3d45684f837e67e7f1ec20a9a8e3ac4a4419

1. Run OTBR
2. Add SRP services
3. Kill OTBR
4. Run OTBR with the same datasets
5. Wait until the accessory will recognize that the SRP server has changed.
6. The accessory should refresh its services to new OTBR (new SRP server)
7. OTBR receives new records from accessory but it doesn't send response and accessory stucks in srp client state "Refreshing".
8. OT SRP callback is called on the srp client side with OT_ERROR_RESPONSE_TIMEOUT error code.

**Expected behavior** A clear and concise description of what you expected to happen.
No visible errors on the SRP client side

**Console/log output** If applicable, add console/log output to help explain your problem.
SRP client service output
instance:"F0A0518168EE0596", name:"_matterc._udp,_S0,_L3840,_V9050", state:Refreshing, port:5540, priority:0, weight:0 instance:"7A7B078F27577B79-000000000000000A", name:"_matter._tcp,_I7A7B078F27577B79", state:Refreshing, port:5540, priority:0, weight:0

**Additional context** Add any other context about the problem here.

**Comment by wgtdkp** [comment]
Hi, could you provide the otbr log? It can retrieved with `cat /bar/log/syslog | grep otbr-agent`.

**Comment by doublemis1** [comment]
I apologize for the non-compliance. I verified this again in the docker by following these steps:
1. Start OTBR docker
2. Form Topology by WEB GUI
3. Commission device
4. Gather active dataset from current topology network
5. Kill OTBR docker
6. Start OTBR docker 
7. Start Thread Network on OTBR:
    * dataset init tlvs <hex dataset from previous otbr>
    * dataset active commit
    * ifconfig up
    * thread start 
    * prefix add fd11:22::/64 pasor
8. Waiting for refresh services.

Everything goes well.

**Comment by jwhui** [comment]
@doublemis1 , thanks for the update.
