### ISSUE TITLE
How to ping a Thread device from an Android phone?

### ISSUE THREAD

**Issue by OlivierGre** [openthread/ot-br-posix#1147]
I have a Thread device (v1.1) connected to a thread network and I do have created an OMR prefix (thanks to Jonathan's advices in another ticket). I can see with "ipaddr" that the device does have an IP address starting with the OMR prefix.

I now want to ping this device from Android as indicated on https://openthread.io/codelabs/openthread-border-router#6

Unfortunately there is a restriction:
_"Unfortunately, the Android version of the Network Analyzer App doesn't support mDNS queries for the ping utility and we cannot ping the hostname ot-host.local directly (we can ping the hostname with the iOS version of the App)."_

Would you know a solution to be able to ping the thread device on Android? Is there another application that I could use?

I have a Mac so I have also tried to ping the device from my mac but I'm not lucky: My Mac is running "Monterey" whereas "Big Sur" is needed :o(

Is the ping possible from a Windows 10 machine? This would be a temporary solution for me as I, in the end, want to send UPD commands from an Android phone (to control the thread device).

**Comment by OlivierGre** [comment]
I have built ot-br-posix with:

`INFRA_IF_NAME=wlan0 BACKBONE_ROUTER=0 BORDER_ROUTING=1 OTBR_OPTIONS="-DOT_THREAD_VERSION=1.1" ./script/setup`

Then I have rebooted and recreated a new dataset as indicated in https://openthread.io/codelabs/openthread-border-router#2
but I still have nothing in "routes"

```
> netdata show
Prefixes:
Routes:
Services:
44970 5d fd5755a3d3b68e859b9a133d7bda5cf0d11f s 3000
Done
```

**Comment by wgtdkp** [comment]
@OlivierGre Can you upload the otbr-agent log? It will also be helpful if I can get the output of `ip a` on the BR?

**Comment by OlivierGre** [comment]
> @OlivierGre Can you upload the otbr-agent log? 

Here it is.
[otbr_agent.log](https://github.com/openthread/ot-br-posix/files/7692143/otbr_agent.log)

> It will also be helpful if I can get the output of `ip a` on the BR?
What shall I type?

**Comment by wgtdkp** [comment]
The log shows that the BORDER_ROUTING feature is not enabled.
Could you cleanup your build directory before rebuilding `otbr-agent`?
```shell
rm -rf build/
```

And please make sure that ./script/setup exit with success.

**Comment by OlivierGre** [comment]
> The log shows that the BORDER_ROUTING feature is not enabled. Could you cleanup your build directory before rebuilding `otbr-agent`?
> 
> ```shell
> rm -rf build/
> ```
> 
> And please make sure that `./script/setup` exits with success.

@wgtdkp  When recompiling the OTBR agent, shall I stop it first?

```
sudo service otbr-agent stop 
sudo rm -rf `which otbr-agent` 
```

**Comment by wgtdkp** [comment]
If those are the command I gave to you, maybe better to follow.

**Comment by OlivierGre** [comment]
ok :o)
Yes, you gave them to me in another issue.

I have removed the build directory and rebuilt but I still get the same problem. I'm attaching the log of the setup command and the otbr-agent traces;
[setup.txt](https://github.com/openthread/ot-br-posix/files/7693220/setup.txt)

[otbr-agent2.log](https://github.com/openthread/ot-br-posix/files/7693218/otbr-agent2.log)

**Comment by wgtdkp** [comment]
It looks like your Backbone/Infrastructure interface is missing in your configuration file:
```
Dec 10 14:53:46 raspberrypi otbr-agent[709]: [INFO]-UTILS---: Running 0.3.0-a41fc11dc-dirty
Dec 10 14:53:46 raspberrypi otbr-agent[709]: [INFO]-UTILS---: Thread version: 1.1.1
Dec 10 14:53:46 raspberrypi otbr-agent[709]: [INFO]-UTILS---: Thread interface: wpan0
Dec 10 14:53:46 raspberrypi otbr-agent[709]: [INFO]-UTILS---: Backbone interface: 
Dec 10 14:53:46 raspberrypi otbr-agent[709]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB0
```

Can you add `-B wlan0` to your otbr-agent configuration file? For example, my otbr-agent config file is like:
```
☁  ot-br-posix [main] ⚡  cat /etc/default/otbr-agent 
# Default settings for otbr-agent. This file is sourced by systemd

# Options to pass to otbr-agent
OTBR_AGENT_OPTS="-I wpan0 -B wlan0 spinel+hdlc+uart:///dev/ttyACM0 trel://wlan0"
```

**Comment by OlivierGre** [comment]
Great, thank you. I was keeping the same configuration file as before. 
I have just updated src/agent/otbr-agent.default.in
Now I only change the device name. At the end of the build, i get the same file /etc/default/otbr-agent as you (excepted the device name of course).

I have set up a thread network. I can see that I now have a prefix but no routes:
```
> netdata show
Prefixes:
fd2b:8d62:4ff8:a5dc::/64 paos med 3000
Routes:
Services:
44970 5d fd69df0233ac440e9b9a133d7bda5cf0d11f s 3000

```

I can attach the otbr-agent log.

@wgtdkp @jwhui Thank you so much for your precious help!

**Comment by OlivierGre** [comment]
Here is the otbr-agent log
[otbr-agent3.log](https://github.com/openthread/ot-br-posix/files/7693786/otbr-agent3.log)

**Comment by wgtdkp** [comment]
The log shows that the an external route of `fd84:c4cb:75d8:0::/64` has been added:
```
Dec 10 16:34:09 raspberrypi otbr-agent[731]: 00:00:13.575 [INFO]-N-DATA--: Sent server data notification
Dec 10 16:34:09 raspberrypi otbr-agent[731]: 00:00:13.575 [INFO]-BR------: Added external route fd84:c4cb:75d8:0::/64
Dec 10 16:34:09 raspberrypi otbr-agent[731]: 00:00:13.575 [INFO]-BR------: Start advertising new on-link prefix fd84:c4cb:75d8:0::/64 on interface 3
```

There should be IPv6 addresses with this prefix on your wlan0 interface. Can you share the output of command `ip a` or `ifconfig wlan0`?

**Comment by wgtdkp** [comment]
I must mention that there is some delay between the BR becoming active (a leader, router or child) and adding external route. The estimation is around 10 - 15 seconds. I suspect that you run `netdata show` just before the routing manager adding the external route. I think if you try `netdata show` again, the route should be there :)

**Comment by OlivierGre** [comment]
You are completely right, thank you!

```
pi@raspberrypi:~ $ ifconfig wlan0
wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.62  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fd84:c4cb:75d8:0:dea6:32ff:fe21:3e1e  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::dea6:32ff:fe21:3e1e  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::c41b:22f5:e1ad:25a0  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:21:3e:1e  txqueuelen 1000  (Ethernet)
        RX packets 1980  bytes 1019835 (995.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3222  bytes 854358 (834.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

pi@raspberrypi:~ $ sudo ot-ctl netdata show
Prefixes:
fd2b:8d62:4ff8:a5dc::/64 paos med 3000
Routes:
fd84:c4cb:75d8:0::/64 s med 3000
Services:
44970 5d fd69df0233ac440e9b9a133d7bda5cf0d11f s 3000
Done
```

**Comment by OlivierGre** [comment]
Is there a config file somewhere in ot-br-posix where I can specify the settings that I want to get in the dataset? (PAN ID, Ext PAN ID, PSKc...etc)?
By this way, the newly created dataset would use the values that I have given (and I would not have to rebuild my android ot-commissioner).

**Comment by jwhui** [comment]
> Is there a config file somewhere in ot-br-posix where I can specify the settings that I want to get in the dataset? (PAN ID, Ext PAN ID, PSKc...etc)? By this way, the newly created dataset would use the values that I have given (and I would not have to rebuild my android ot-commissioner).

ot-br-posix does not support using a config file to specify the Operational Dataset. You can configure the Operational Dataset using `ot-ctl`. You can also use a script to issue the `ot-ctl` commands.

**Comment by OlivierGre** [comment]
@jwhui Thank you. I have used a bash script and it works well. I'm now able to ping the Thread device from the Wifi network. Thanks again for your help!
