### ISSUE TITLE
"publish meshcop service when thread is not started" segfaults on start for openwrt

### ISSUE THREAD

**Issue by leojrfs** [openthread/ot-br-posix#1149]
The following commit 288fecd56081b0d5bdb7ca5e20075c9ed1e798e4 makes `otbr-agent` segfault on start.

```
[  815.232530] do_page_fault(): sending SIGSEGV to otbr-agent for invalid read access from 00000000
[  815.240027] epc = 004409dd in otbr-agent[400000+77000]
[  815.245048] ra  = 00440a35 in otbr-agent[400000+77000]
Segmentation fault
```

Reproduced on OpenWRT 21.02.1, on the following devices using multiple RCP configurations:
- raspberrypi 4 (aarch64)
- gl.inet ar150 (ath79)

It was built using the OpenWRT build instructions in this repo.

Using the `main` branch head of this repo at the time of writing (a11d76b9bee828167757a764b4b123d90baacd38) and reverting 288fecd56081b0d5bdb7ca5e20075c9ed1e798e4 works.

**Comment by wgtdkp** [comment]
@leojrfs Thanks for raising this issue, I submitted https://github.com/openthread/ot-br-posix/pull/1150 as the fix. Can you help confirm if the PR works for you?

**Comment by leojrfs** [comment]
I can confirm that #1150 fixes it!

Thank you
