### ISSUE TITLE
Border Router setup failed on Rpi gateway

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/ot-br-posix#1157]
Hi,

I am doing openthread border router set-up on rpi based Gateway, and when I run "sudo service otbr -gent status" I get the following error:
```
otbr-agent.service - Border Router Agent
   Loaded: loaded (/lib/systemd/system/otbr-agent.service; enabled; vendor preset: enable
   Active: activating (auto-restart) (Result: exit-code) since Wed 2021-12-15 11:37:46 IS
  Process: 31373 ExecStartPre=/usr/sbin/service mdns start (code=exited, status=0/SUCCESS
  Process: 31396 ExecStart=/usr/sbin/otbr-agent $OTBR_AGENT_OPTS (code=exited, status=1/F
 Main PID: 31396 (code=exited, status=1/FAILURE)
```

I have followed the set-up guide available [here](https://openthread.io/codelabs/openthread-border-router#1)

**Comment by superwhd** [comment]
Could you provide syslog? 
```
tail -n <lines> /var/log/syslog
```

**Comment by bhumikaajain** [comment]
Hi ,

Below are the logs:
`Dec 15 12:17:21 Zenatix-Testing-CBBhumika otbr-agent[20065]: [INFO]-UTILS---: Running 0.3.0-975ace0
Dec 15 12:17:21 Zenatix-Testing-CBBhumika otbr-agent[20065]: [INFO]-UTILS---: Thread version: 1.2.0
Dec 15 12:17:21 Zenatix-Testing-CBBhumika otbr-agent[20065]: [INFO]-UTILS---: Thread interface: wpan0
Dec 15 12:17:21 Zenatix-Testing-CBBhumika otbr-agent[20065]: [INFO]-UTILS---: Backbone interface: wlan0
Dec 15 12:17:21 Zenatix-Testing-CBBhumika otbr-agent[20065]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Dec 15 12:17:21 Zenatix-Testing-CBBhumika otbr-agent[20065]: [INFO]-UTILS---: Radio URL: trel://wlan0
Dec 15 12:17:21 Zenatix-Testing-CBBhumika otbr-agent[20065]: 49d.19:06:57.058 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Dec 15 12:17:21 Zenatix-Testing-CBBhumika otbr-agent[20065]: 49d.19:06:57.065 [NOTE]-PLAT----: RCP API Version: 5
Dec 15 12:17:21 Zenatix-Testing-CBBhumika otbr-agent[20065]: 49d.19:06:57.080 [CRIT]-PLAT----: platformBackboneInit() at ../../third_party/openthread/repo/src/posix/platform/backbone.cpp:62: Failure
Dec 15 12:17:21 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 12:17:21 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Dec 15 12:17:26 Zenatix-Testing-CBBhumika otbr-agent[20105]: [INFO]-UTILS---: Running 0.3.0-975ace0
Dec 15 12:17:26 Zenatix-Testing-CBBhumika otbr-agent[20105]: [INFO]-UTILS---: Thread version: 1.2.0
Dec 15 12:17:26 Zenatix-Testing-CBBhumika otbr-agent[20105]: [INFO]-UTILS---: Thread interface: wpan0
Dec 15 12:17:26 Zenatix-Testing-CBBhumika otbr-agent[20105]: [INFO]-UTILS---: Backbone interface: wlan0
Dec 15 12:17:26 Zenatix-Testing-CBBhumika otbr-agent[20105]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Dec 15 12:17:26 Zenatix-Testing-CBBhumika otbr-agent[20105]: [INFO]-UTILS---: Radio URL: trel://wlan0
Dec 15 12:17:26 Zenatix-Testing-CBBhumika otbr-agent[20105]: 49d.19:07:01.756 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Dec 15 12:17:26 Zenatix-Testing-CBBhumika otbr-agent[20105]: 49d.19:07:01.763 [NOTE]-PLAT----: RCP API Version: 5
Dec 15 12:17:26 Zenatix-Testing-CBBhumika otbr-agent[20105]: 49d.19:07:01.779 [CRIT]-PLAT----: platformBackboneInit() at ../../third_party/openthread/repo/src/posix/platform/backbone.cpp:62: Failure
Dec 15 12:17:26 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 12:17:26 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Dec 15 12:17:31 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Service RestartSec=5s expired, scheduling restart.
Dec 15 12:17:31 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 1.
Dec 15 12:17:34 Zenatix-Testing-CBBhumika otbr-agent[20136]: [INFO]-UTILS---: Running 0.3.0-975ace0
Dec 15 12:17:34 Zenatix-Testing-CBBhumika otbr-agent[20136]: [INFO]-UTILS---: Thread version: 1.2.0
Dec 15 12:17:34 Zenatix-Testing-CBBhumika otbr-agent[20136]: [INFO]-UTILS---: Thread interface: wpan0
Dec 15 12:17:34 Zenatix-Testing-CBBhumika otbr-agent[20136]: [INFO]-UTILS---: Backbone interface: wlan0
Dec 15 12:17:34 Zenatix-Testing-CBBhumika otbr-agent[20136]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Dec 15 12:17:34 Zenatix-Testing-CBBhumika otbr-agent[20136]: [INFO]-UTILS---: Radio URL: trel://wlan0
Dec 15 12:17:34 Zenatix-Testing-CBBhumika otbr-agent[20136]: 49d.19:07:09.414 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Dec 15 12:17:34 Zenatix-Testing-CBBhumika otbr-agent[20136]: 49d.19:07:09.421 [NOTE]-PLAT----: RCP API Version: 5
Dec 15 12:17:34 Zenatix-Testing-CBBhumika otbr-agent[20136]: 49d.19:07:09.437 [CRIT]-PLAT----: platformBackboneInit() at ../../third_party/openthread/repo/src/posix/platform/backbone.cpp:62: Failure
Dec 15 12:17:34 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 12:17:34 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Dec 15 12:17:39 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Service RestartSec=5s expired, scheduling restart.
Dec 15 12:17:39 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 2.
Dec 15 12:17:41 Zenatix-Testing-CBBhumika otbr-agent[20164]: [INFO]-UTILS---: Running 0.3.0-975ace0
Dec 15 12:17:41 Zenatix-Testing-CBBhumika otbr-agent[20164]: [INFO]-UTILS---: Thread version: 1.2.0
Dec 15 12:17:41 Zenatix-Testing-CBBhumika otbr-agent[20164]: [INFO]-UTILS---: Thread interface: wpan0
Dec 15 12:17:41 Zenatix-Testing-CBBhumika otbr-agent[20164]: [INFO]-UTILS---: Backbone interface: wlan0
Dec 15 12:17:41 Zenatix-Testing-CBBhumika otbr-agent[20164]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Dec 15 12:17:41 Zenatix-Testing-CBBhumika otbr-agent[20164]: [INFO]-UTILS---: Radio URL: trel://wlan0
Dec 15 12:17:41 Zenatix-Testing-CBBhumika otbr-agent[20164]: 49d.19:07:17.108 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Dec 15 12:17:41 Zenatix-Testing-CBBhumika otbr-agent[20164]: 49d.19:07:17.114 [NOTE]-PLAT----: RCP API Version: 5
Dec 15 12:17:41 Zenatix-Testing-CBBhumika otbr-agent[20164]: 49d.19:07:17.131 [CRIT]-PLAT----: platformBackboneInit() at ../../third_party/openthread/repo/src/posix/platform/backbone.cpp:62: Failure
Dec 15 12:17:41 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 12:17:41 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Dec 15 12:17:46 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Service RestartSec=5s expired, scheduling restart.
Dec 15 12:17:46 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 3.
Dec 15 12:17:49 Zenatix-Testing-CBBhumika otbr-agent[20307]: [INFO]-UTILS---: Running 0.3.0-975ace0
Dec 15 12:17:49 Zenatix-Testing-CBBhumika otbr-agent[20307]: [INFO]-UTILS---: Thread version: 1.2.0
Dec 15 12:17:49 Zenatix-Testing-CBBhumika otbr-agent[20307]: [INFO]-UTILS---: Thread interface: wpan0
Dec 15 12:17:49 Zenatix-Testing-CBBhumika otbr-agent[20307]: [INFO]-UTILS---: Backbone interface: wlan0
Dec 15 12:17:49 Zenatix-Testing-CBBhumika otbr-agent[20307]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Dec 15 12:17:49 Zenatix-Testing-CBBhumika otbr-agent[20307]: [INFO]-UTILS---: Radio URL: trel://wlan0
Dec 15 12:17:49 Zenatix-Testing-CBBhumika otbr-agent[20307]: 49d.19:07:24.864 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Dec 15 12:17:49 Zenatix-Testing-CBBhumika otbr-agent[20307]: 49d.19:07:24.870 [NOTE]-PLAT----: RCP API Version: 5
Dec 15 12:17:49 Zenatix-Testing-CBBhumika otbr-agent[20307]: 49d.19:07:24.887 [CRIT]-PLAT----: platformBackboneInit() at ../../third_party/openthread/repo/src/posix/platform/backbone.cpp:62: Failure
Dec 15 12:17:49 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 12:17:49 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Dec 15 12:17:54 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Service RestartSec=5s expired, scheduling restart.
Dec 15 12:17:54 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 4.
Dec 15 12:17:57 Zenatix-Testing-CBBhumika otbr-agent[20756]: [INFO]-UTILS---: Running 0.3.0-975ace0
Dec 15 12:17:57 Zenatix-Testing-CBBhumika otbr-agent[20756]: [INFO]-UTILS---: Thread version: 1.2.0
Dec 15 12:17:57 Zenatix-Testing-CBBhumika otbr-agent[20756]: [INFO]-UTILS---: Thread interface: wpan0
Dec 15 12:17:57 Zenatix-Testing-CBBhumika otbr-agent[20756]: [INFO]-UTILS---: Backbone interface: wlan0
Dec 15 12:17:57 Zenatix-Testing-CBBhumika otbr-agent[20756]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Dec 15 12:17:57 Zenatix-Testing-CBBhumika otbr-agent[20756]: [INFO]-UTILS---: Radio URL: trel://wlan0
Dec 15 12:17:57 Zenatix-Testing-CBBhumika otbr-agent[20756]: 49d.19:07:32.823 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Dec 15 12:17:57 Zenatix-Testing-CBBhumika otbr-agent[20756]: 49d.19:07:32.830 [NOTE]-PLAT----: RCP API Version: 5
Dec 15 12:17:57 Zenatix-Testing-CBBhumika otbr-agent[20756]: 49d.19:07:32.846 [CRIT]-PLAT----: platformBackboneInit() at ../../third_party/openthread/repo/src/posix/platform/backbone.cpp:62: Failure
Dec 15 12:17:57 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 12:17:57 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Dec 15 12:18:02 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Service RestartSec=5s expired, scheduling restart.
Dec 15 12:18:02 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 5.
Dec 15 12:18:05 Zenatix-Testing-CBBhumika otbr-agent[21001]: [INFO]-UTILS---: Running 0.3.0-975ace0
Dec 15 12:18:05 Zenatix-Testing-CBBhumika otbr-agent[21001]: [INFO]-UTILS---: Thread version: 1.2.0
Dec 15 12:18:05 Zenatix-Testing-CBBhumika otbr-agent[21001]: [INFO]-UTILS---: Thread interface: wpan0
Dec 15 12:18:05 Zenatix-Testing-CBBhumika otbr-agent[21001]: [INFO]-UTILS---: Backbone interface: wlan0
Dec 15 12:18:05 Zenatix-Testing-CBBhumika otbr-agent[21001]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Dec 15 12:18:05 Zenatix-Testing-CBBhumika otbr-agent[21001]: [INFO]-UTILS---: Radio URL: trel://wlan0
Dec 15 12:18:05 Zenatix-Testing-CBBhumika otbr-agent[21001]: 49d.19:07:40.671 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Dec 15 12:18:05 Zenatix-Testing-CBBhumika otbr-agent[21001]: 49d.19:07:40.678 [NOTE]-PLAT----: RCP API Version: 5
Dec 15 12:18:05 Zenatix-Testing-CBBhumika otbr-agent[21001]: 49d.19:07:40.695 [CRIT]-PLAT----: platformBackboneInit() at ../../third_party/openthread/repo/src/posix/platform/backbone.cpp:62: Failure
Dec 15 12:18:05 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 12:18:05 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Dec 15 12:18:10 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Service RestartSec=5s expired, scheduling restart.
Dec 15 12:18:10 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 6.
Dec 15 12:18:13 Zenatix-Testing-CBBhumika otbr-agent[21103]: [INFO]-UTILS---: Running 0.3.0-975ace0
Dec 15 12:18:13 Zenatix-Testing-CBBhumika otbr-agent[21103]: [INFO]-UTILS---: Thread version: 1.2.0
Dec 15 12:18:13 Zenatix-Testing-CBBhumika otbr-agent[21103]: [INFO]-UTILS---: Thread interface: wpan0
Dec 15 12:18:13 Zenatix-Testing-CBBhumika otbr-agent[21103]: [INFO]-UTILS---: Backbone interface: wlan0
Dec 15 12:18:13 Zenatix-Testing-CBBhumika otbr-agent[21103]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Dec 15 12:18:13 Zenatix-Testing-CBBhumika otbr-agent[21103]: [INFO]-UTILS---: Radio URL: trel://wlan0
Dec 15 12:18:13 Zenatix-Testing-CBBhumika otbr-agent[21103]: 49d.19:07:48.333 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Dec 15 12:18:13 Zenatix-Testing-CBBhumika otbr-agent[21103]: 49d.19:07:48.340 [NOTE]-PLAT----: RCP API Version: 5
Dec 15 12:18:13 Zenatix-Testing-CBBhumika otbr-agent[21103]: 49d.19:07:48.356 [CRIT]-PLAT----: platformBackboneInit() at ../../third_party/openthread/repo/src/posix/platform/backbone.cpp:62: Failure
Dec 15 12:18:13 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 12:18:13 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Dec 15 12:18:18 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Service RestartSec=5s expired, scheduling restart.
Dec 15 12:18:18 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 7.
Dec 15 12:18:20 Zenatix-Testing-CBBhumika otbr-agent[21136]: [INFO]-UTILS---: Running 0.3.0-975ace0
Dec 15 12:18:20 Zenatix-Testing-CBBhumika otbr-agent[21136]: [INFO]-UTILS---: Thread version: 1.2.0
Dec 15 12:18:20 Zenatix-Testing-CBBhumika otbr-agent[21136]: [INFO]-UTILS---: Thread interface: wpan0
Dec 15 12:18:20 Zenatix-Testing-CBBhumika otbr-agent[21136]: [INFO]-UTILS---: Backbone interface: wlan0
Dec 15 12:18:20 Zenatix-Testing-CBBhumika otbr-agent[21136]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Dec 15 12:18:20 Zenatix-Testing-CBBhumika otbr-agent[21136]: [INFO]-UTILS---: Radio URL: trel://wlan0
Dec 15 12:18:20 Zenatix-Testing-CBBhumika otbr-agent[21136]: 49d.19:07:56.091 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Dec 15 12:18:20 Zenatix-Testing-CBBhumika otbr-agent[21136]: 49d.19:07:56.098 [NOTE]-PLAT----: RCP API Version: 5
Dec 15 12:18:20 Zenatix-Testing-CBBhumika otbr-agent[21136]: 49d.19:07:56.115 [CRIT]-PLAT----: platformBackboneInit() at ../../third_party/openthread/repo/src/posix/platform/backbone.cpp:62: Failure
Dec 15 12:18:20 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 12:18:20 Zenatix-Testing-CBBhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.`

**Comment by wgtdkp** [comment]
@bhumikaajain Do you really have a `wlan0` interface on your RPi?

**Comment by bhumikaajain** [comment]
No I don't have wlan0 interface but wwan0 interafce.
Following is ifconfig output:

`eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b8:27:eb:1e:5f:9b  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 22535  bytes 2937541 (2.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22535  bytes 2937541 (2.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo:1: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 10.0.0.1  netmask 255.255.255.0
        loop  txqueuelen 1000  (Local Loopback)

nat64: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 192.168.255.1  netmask 255.255.255.255  destination 192.168.255.1
        inet6 fdaa:bb:1::2  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::8667:c2f3:7043:1f81  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 304 (304.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.8.88.156  netmask 255.255.255.255  destination 10.8.88.157
        inet6 fe80::8d98:485a:ff2d:191a  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 11432  bytes 843862 (824.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10099  bytes 2984592 (2.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wwan0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.239.201.205  netmask 255.255.255.252  destination 10.239.201.205
        inet6 2402:3a80:90a:2d8c:2d0e:db60:9792:97d3  prefixlen 64  scopeid 0x0<global>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 138042  bytes 166446120 (158.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 87325  bytes 8670263 (8.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

and below is iwconfig output:

`tun0      no wireless extensions.

nat64     no wireless extensions.

eth0      no wireless extensions.

wwan0     no wireless extensions.

lo        no wireless extensions.`

**Comment by jwhui** [comment]
@bhumikaajain , you need to select a valid network interface for the infrastructure interface. Which interface are you trying to use as your infrastructure interface?

Can you indicate specifically what model of Raspberry Pi you are trying to use?

**Comment by bhumikaajain** [comment]
I am using "Raspberry Pi Compute Module 3 Rev 1.0".
This is custom Raspberry Pi compute Module based hardware on which we use the Quectel module for GSM interfacing.

**Comment by jwhui** [comment]
> I am using "Raspberry Pi Compute Module 3 Rev 1.0". This is custom Raspberry Pi compute Module based hardware on which we use the Quectel module for GSM interfacing.

Which interface are you trying to use as your infrastructure interface?

**Comment by bhumikaajain** [comment]
If on GSM it's wwan0, wifi - wlan0, ethernet - eth0.

Currently, my board is on GSM.

**Comment by wgtdkp** [comment]
@bhumikaajain Try setting up your OTBR again with
```
INFRA_IF_NAME=wwan0 ./script/setup
```
You have to provide a valid `INFRA_IF_NAME` on your platform.

**Comment by jwhui** [comment]
OTBR is not currently designed to support dynamically selecting the network interface.

Your platform does not appear to have a wlan0 interface, so you cannot select that.

FWIW, we typically use something like Ethernet or Wi-Fi as the infrastructure interface as it allows other devices on the same infrastructure network to communicate directly, including other OTBRs.

**Comment by bhumikaajain** [comment]
So in my current set-up can I again do the set-up with  "INFRA_IF_NAME=wwan0" ? will it work?
Or is there anything else you can suggest?

**Comment by bhumikaajain** [comment]
Since it is not working on my custom board, so I have taken one "Raspberry Pi 3 Model B Rev 1.2" with wlan0 network interface and freshly tried complete ot-br installation steps as mentioned on [link](https://openthread.io/codelabs/openthread-border-router#1). 
I am getting the following error now  when I run "sudo service otbr -gent status" :

````
otbr-agent.service - Border Router Agent
   Loaded: loaded (/lib/systemd/system/otbr-agent.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-12-15 14:15:24 IST; 54min ago
 Main PID: 576 (code=exited, status=255)

Dec 15 10:47:53 Zenatix-Testing-Bhumika otbr-agent[576]: Avahi group change to state 1.
Dec 15 10:47:53 Zenatix-Testing-Bhumika otbr-agent[576]: Group ready.
Dec 15 10:47:54 Zenatix-Testing-Bhumika otbr-agent[576]: Avahi group change to state 2.
Dec 15 10:47:54 Zenatix-Testing-Bhumika otbr-agent[576]: Group established.
Dec 15 14:15:24 Zenatix-Testing-Bhumika systemd[1]: Stopping Border Router Agent...
Dec 15 14:15:24 Zenatix-Testing-Bhumika otbr-agent[576]: select() failed
Dec 15 14:15:24 Zenatix-Testing-Bhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=255/n/a
Dec 15 14:15:24 Zenatix-Testing-Bhumika systemd[1]: Stopped Border Router Agent.
Dec 15 14:15:24 Zenatix-Testing-Bhumika systemd[1]: otbr-agent.service: Unit entered failed state.
Dec 15 14:15:24 Zenatix-Testing-Bhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
```

**Comment by bhumikaajain** [comment]
Added syslog for your reference:

`ec 15 14:15:24 Zenatix-Testing-Bhumika sudo[32727]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/bin/systemctl stop otbr-agent
Dec 15 14:15:24 Zenatix-Testing-Bhumika otbr-agent[576]: select() failed
Dec 15 14:15:24 Zenatix-Testing-Bhumika otbr-agent[576]: MDNS service not available!
Dec 15 14:15:24 Zenatix-Testing-Bhumika systemd[1]: otbr-agent.service: Main process exited, code=exited, status=255/n/a
Dec 15 14:15:24 Zenatix-Testing-Bhumika otbr-agent[576]: Stop publishing service
Dec 15 14:15:24 Zenatix-Testing-Bhumika systemd[1]: otbr-agent.service: Unit entered failed state.
Dec 15 14:15:24 Zenatix-Testing-Bhumika systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Dec 15 14:15:25 Zenatix-Testing-Bhumika sudo[32759]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/bin/systemctl disable otbr-agent
Dec 15 14:15:25 Zenatix-Testing-Bhumika sudo[323]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/bin/systemctl is-enabled otbr-agent
Dec 15 14:15:25 Zenatix-Testing-Bhumika sudo[331]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/usr/bin/killall otbr-web otbr-agent
Dec 15 14:17:51 Zenatix-Testing-Bhumika sudo[2587]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/bin/systemctl stop otbr-agent
Dec 15 14:17:52 Zenatix-Testing-Bhumika sudo[2618]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/bin/systemctl disable otbr-agent
Dec 15 14:17:52 Zenatix-Testing-Bhumika sudo[2648]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/bin/systemctl is-enabled otbr-agent
Dec 15 14:17:52 Zenatix-Testing-Bhumika sudo[2656]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/usr/bin/killall otbr-web otbr-agent
Dec 15 14:18:56 Zenatix-Testing-Bhumika sudo[3852]:       pi : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/usr/sbin/service otbr-agent status
Dec 15 14:33:35 Zenatix-Testing-Bhumika sudo[6495]:       pi : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/usr/sbin/service otbr-agent status
Dec 15 15:04:10 Zenatix-Testing-Bhumika sudo[25241]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/bin/systemctl stop otbr-agent
Dec 15 15:04:10 Zenatix-Testing-Bhumika sudo[25272]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/bin/systemctl disable otbr-agent
Dec 15 15:04:11 Zenatix-Testing-Bhumika sudo[25303]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/bin/systemctl is-enabled otbr-agent
Dec 15 15:04:11 Zenatix-Testing-Bhumika sudo[25311]:     root : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/usr/bin/killall otbr-web otbr-agent
Dec 15 15:04:43 Zenatix-Testing-Bhumika sudo[26385]:       pi : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/usr/sbin/service otbr-agent status
Dec 15 15:10:17 Zenatix-Testing-Bhumika sudo[26950]:       pi : TTY=pts/2 ; PWD=/home/pi/ot-br-posix ; USER=root ; COMMAND=/usr/sbin/service otbr-agent status
Dec 15 15:40:20 Zenatix-Testing-Bhumika sudo[30155]:       pi : TTY=pts/2 ; PWD=/home/pi ; USER=root ; COMMAND=/usr/sbin/service otbr-agent status`

**Comment by wgtdkp** [comment]
try
```
sudo service avahi-daemon restart
sudo service otbr-agent restart
```

**Comment by bhumikaajain** [comment]
Done.
Now I am getting following log:
````
 otbr-agent.service - Border Router Agent
   Loaded: loaded (/lib/systemd/system/otbr-agent.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-12-15 16:56:30 IST; 1min 48s ago
 Main PID: 14203 (otbr-agent)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/otbr-agent.service
           └─14203 /usr/sbin/otbr-agent -I wpan0

Dec 15 16:56:30 Zenatix-Testing-Bhumika otbr-agent[14203]: PSKc is not initialized
Dec 15 16:56:30 Zenatix-Testing-Bhumika otbr-agent[14203]: Check if PSKc is initialized: OK
Dec 15 16:56:30 Zenatix-Testing-Bhumika otbr-agent[14203]: Initialize OpenThread Border Router Agent: OK
Dec 15 16:56:30 Zenatix-Testing-Bhumika otbr-agent[14203]: Border router agent started.
Dec 15 16:56:30 Zenatix-Testing-Bhumika otbr-agent[14203]: Stop publishing service
Dec 15 16:56:30 Zenatix-Testing-Bhumika otbr-agent[14203]: PSKc is not initialized
Dec 15 16:56:43 Zenatix-Testing-Bhumika otbr-agent[14203]: state offline
Dec 15 16:56:43 Zenatix-Testing-Bhumika otbr-agent[14203]: Thread is down
Dec 15 16:56:48 Zenatix-Testing-Bhumika otbr-agent[14203]: state offline
Dec 15 16:56:48 Zenatix-Testing-Bhumika otbr-agent[14203]: Thread is down
pi@Zenatix-Testing-Bhumika ~ $ sudo ot-ctl dataset init new`
```

In the next command, I ran "sudo ot-ctl dataset init new"
i am getting error : sudo: ot-ctl: command not found
Do I need to install something else for ot-ctl interface?

**Comment by jwhui** [comment]
@bhumikaajain , did you try installing OTBR on a fresh [2021-05-07-raspios-buster-armhf-lite](https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip) image?

I just setup an OTBR on RPi 3B+ and fresh 2021-05-07-raspios-buster-armhf-lite image and everything worked as expected.

**Comment by bhumikaajain** [comment]
My Rpi setup has previously wpantund installed. It was working on NCP earlier.

**Comment by jwhui** [comment]
> My Rpi setup has previously wpantund installed. It was working on NCP earlier.

If you are following our [Thread Border Router](https://openthread.io/codelabs/openthread-border-router#0) codelab, I suggest you follow each step exactly as is, including using a fresh 2021-05-07-raspios-buster-armhf-lite image.

**Comment by bhumikaajain** [comment]
ok. But if my existing image already has NCP setup, then is there any guide that I can follow to upgrade it to an RCP based border router setup.

**Comment by jwhui** [comment]
> ok. But if my existing image already has NCP setup, then is there any guide that I can follow to upgrade it to an RCP based border router setup.

I would recommend starting from a fresh RPi image, as already mentioned above.

**Comment by bhumikaajain** [comment]
I have tried on a fresh image and there I didn't face any issues.
But I need to upgrade my existing NCP setup to RCP based border router.
Can you guide me through this process?

**Comment by jwhui** [comment]
You can try to use the [script/setup](https://github.com/openthread/ot-br-posix/blob/main/script/setup) to first uninstall the old version of OTBR, then install the newer version of OTBR. When uninstalling, make sure to use the setup script from the same git commit that you used with the old version.

**Comment by jwhui** [comment]
Closing stale issue.
