### ISSUE TITLE
Can I run both RCP and NCP on single BR

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/ot-br-posix#1159]
On a Rpi based gateway, is it possible;e to run both wpantund and ot-ctl interface?
Can I add 2 nrf52840 devices to rpi USB ports and configure one device as NCP and other as RCP?

**Comment by jwhui** [comment]
> On a Rpi based gateway, is it possible;e to run both wpantund and ot-ctl interface? Can I add 2 nrf52840 devices to rpi USB ports and configure one device as NCP and other as RCP?

It should be possible, you'll need to specify different USB ports and network interfaces. That said, it's not a configuration that we typically see.

**Comment by bhumikaajain** [comment]
where can we specify USB port for RCP interface?

**Comment by jwhui** [comment]
> where can we specify USB port for RCP interface?

See [src/agent/otbr-agent.default.in](https://github.com/openthread/ot-br-posix/blob/main/src/agent/otbr-agent.default.in)

**Comment by bhumikaajain** [comment]
This port assignment is dynamic, if we have 2 USBs on 2 ports, then anyone can assume ACM0/ACM1.
In case of NCP set up to solve this issue, we have added  below configuration in its config file:

```
#ifndef APP_USBD_STRINGS_PRODUCT
#define APP_USBD_STRINGS_PRODUCT APP_USBD_STRING_DESC("nRF52 Thread NCP")
#endif
```

Now additional to ACM port, it forms one "tty/NCP" port, and we have fixed this port in wpantund.conf file as **Config:NCP:SocketPath "/dev/ttyNCP"**
This helps our border router to refer to the correct port each time even if multiple devices are connected to USD port.
So is there the same way to do this in RCP configuration?

**Comment by jwhui** [comment]
How the USB port is presented seems to be independent of whether it is in NCP or RCP mode. Also, `APP_USBD_STRINGS_PRODUCT` is a Nordic-specific configuration.

**Comment by jwhui** [comment]
Closing stale issue.
