### ISSUE TITLE
otbr-agent start failed in OpenWrt

### ISSUE THREAD

**Issue by lancersky** [openthread/ot-br-posix#1207]
**Describe the bug** A clear and concise description of what the bug is.
```
Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: [INFO]-UTILS---: Running 0.3.0-a965a7535
Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: [INFO]-UTILS---: Thread version: 1.2.0
Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: [INFO]-UTILS---: Thread interface: wpan0
Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: [INFO]-UTILS---: Backbone interface:
Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM1?uart-baudrate=460800
Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: 51d.17:01:46.923 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Wed Jan 19 10:12:16 2022 user.notice otbr-agent[1497]: 51d.17:01:46.931 [NOTE]-PLAT----: RCP API Version: 5
Wed Jan 19 10:12:16 2022 user.crit otbr-agent[1497]: 00:00:00.021 [CRIT]-PLAT----: exit(5): SetUp line 205, open, No such file or directory
```
**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
ot-br-posix - https://github.com/openthread/ot-br-posix/commit/a965a7535dad33303585d2080437f3d796e54a81
2. IEEE 802.15.4 hardware platform
nrf52840 USB Dongle
3. Build steps
`make package/openthread-br/compile V=s`
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

I have fixed the problem with the following code. 
```
diff --git a/third_party/openthread/CMakeLists.txt b/third_party/openthread/CMakeLists.txt
index c091663e3..b4940117a 100644
--- a/third_party/openthread/CMakeLists.txt
+++ b/third_party/openthread/CMakeLists.txt
@@ -93,4 +93,5 @@ target_compile_definitions(ot-config INTERFACE
     "-DOPENTHREAD_CONFIG_MAX_STATECHANGE_HANDLERS=3"
     "-DOPENTHREAD_CONFIG_MLE_STEERING_DATA_SET_OOB_ENABLE=1"
     "-DOPENTHREAD_CONFIG_TMF_PROXY_DUA_ENABLE=$<BOOL:${OTBR_DUA_ROUTING}>"
+    "-DOPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME=\"/tmp/run/openthread-%s\""
 )
```

**Comment by mrninhvn** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> ```
> Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: [INFO]-UTILS---: Running 0.3.0-a965a7535
> Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: [INFO]-UTILS---: Thread version: 1.2.0
> Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: [INFO]-UTILS---: Thread interface: wpan0
> Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: [INFO]-UTILS---: Backbone interface:
> Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM1?uart-baudrate=460800
> Wed Jan 19 10:12:16 2022 user.info otbr-agent[1497]: 51d.17:01:46.923 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
> Wed Jan 19 10:12:16 2022 user.notice otbr-agent[1497]: 51d.17:01:46.931 [NOTE]-PLAT----: RCP API Version: 5
> Wed Jan 19 10:12:16 2022 user.crit otbr-agent[1497]: 00:00:00.021 [CRIT]-PLAT----: exit(5): SetUp line 205, open, No such file or directory
> ```
> 
> **To Reproduce** Information to reproduce the behavior, including:
> 
>     1. Git commit id
>        ot-br-posix - [a965a75](https://github.com/openthread/ot-br-posix/commit/a965a7535dad33303585d2080437f3d796e54a81)
> 
>     2. IEEE 802.15.4 hardware platform
>        nrf52840 USB Dongle
> 
>     3. Build steps
>        `make package/openthread-br/compile V=s`
> 
>     4. Network topology
> 
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Console/log output** If applicable, add console/log output to help explain your problem.
> 
> **Additional context** Add any other context about the problem here.
> 
> I have fixed the problem with the following code.
> 
> ```
> diff --git a/third_party/openthread/CMakeLists.txt b/third_party/openthread/CMakeLists.txt
> index c091663e3..b4940117a 100644
> --- a/third_party/openthread/CMakeLists.txt
> +++ b/third_party/openthread/CMakeLists.txt
> @@ -93,4 +93,5 @@ target_compile_definitions(ot-config INTERFACE
>      "-DOPENTHREAD_CONFIG_MAX_STATECHANGE_HANDLERS=3"
>      "-DOPENTHREAD_CONFIG_MLE_STEERING_DATA_SET_OOB_ENABLE=1"
>      "-DOPENTHREAD_CONFIG_TMF_PROXY_DUA_ENABLE=$<BOOL:${OTBR_DUA_ROUTING}>"
> +    "-DOPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME=\"/tmp/run/openthread-%s\""
>  )
> ```

I got same error.
```
root@OpenWrt:~# otbr-agent -v -I wpan0 'spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200'
otbr-agent[2222]: [INFO]-UTILS---: Running 0.3.0-0b75a60c6-dirty
otbr-agent[2222]: [INFO]-UTILS---: Thread version: 1.2.0
otbr-agent[2222]: [INFO]-UTILS---: Thread interface: wpan0
otbr-agent[2222]: [INFO]-UTILS---: Backbone interface: 
otbr-agent[2222]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200
otbr-agent[2222]: 49d.17:06:12.883 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
otbr-agent[2222]: 49d.17:06:12.903 [NOTE]-PLAT----: RCP API Version: 5
otbr-agent[2222]: 00:00:00.033 [CRIT]-PLAT----: exit(5): SetUp line 205, open, No such file or directory
```
HHave you fixed it yet?

**Comment by LancerSky** [comment]
You need to redefine `OPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME` like following code.
```
diff --git a/third_party/openthread/CMakeLists.txt b/third_party/openthread/CMakeLists.txt
index c091663e3..b4940117a 100644
--- a/third_party/openthread/CMakeLists.txt
+++ b/third_party/openthread/CMakeLists.txt
@@ -93,4 +93,5 @@ target_compile_definitions(ot-config INTERFACE
     "-DOPENTHREAD_CONFIG_MAX_STATECHANGE_HANDLERS=3"
     "-DOPENTHREAD_CONFIG_MLE_STEERING_DATA_SET_OOB_ENABLE=1"
     "-DOPENTHREAD_CONFIG_TMF_PROXY_DUA_ENABLE=$<BOOL:${OTBR_DUA_ROUTING}>"
+    "-DOPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME=\"/tmp/run/openthread-%s\""
 )
```
Because OpenWrt does not have /run directory by default. And the original define is
```
/**
 * @def OPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME
 *
 * Define socket basename used by POSIX app daemon.
 *
 */
#ifndef OPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME
#ifdef __linux__
#define OPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME "/run/openthread-%s"
#else
#define OPENTHREAD_POSIX_CONFIG_DAEMON_SOCKET_BASENAME "/tmp/openthread-%s"
#endif
#endif
```

**Comment by mrninhvn** [comment]
> 

I got new error :( I'm running on OpenWRT 21.02.1
```
root@OpenWrt:~# /usr/sbin/otbr-agent -v -I wpan0 'spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200'
otbr-agent[1685]: [INFO]-UTILS---: Running 0.3.0-0b75a60c6-dirty
otbr-agent[1685]: [INFO]-UTILS---: Thread version: 1.2.0
otbr-agent[1685]: [INFO]-UTILS---: Thread interface: wpan0
otbr-agent[1685]: [INFO]-UTILS---: Backbone interface: 
otbr-agent[1685]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200
otbr-agent[1685]: 49d.17:04:55.101 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
otbr-agent[1685]: 49d.17:04:55.108 [NOTE]-PLAT----: RCP API Version: 5
otbr-agent[1685]: 49d.17:04:55.110 [CRIT]-PLAT----: platformConfigureTunDevice() at netif.cpp:1447: No such file or directory
```

**Comment by LancerSky** [comment]
Looking this error, I think you may not have `kmod-tun` installed.

**Comment by mrninhvn** [comment]
> Looking this error, I think you may not have `kmod-tun` installed.

Yeah that it, but still not running :((
```
root@OpenWrt:~# /usr/sbin/otbr-agent -v -I wpan0 'spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200'
otbr-agent[1733]: [INFO]-UTILS---: Running 0.3.0-0b75a60c6-dirty
otbr-agent[1733]: [INFO]-UTILS---: Thread version: 1.2.0
otbr-agent[1733]: [INFO]-UTILS---: Thread interface: wpan0
otbr-agent[1733]: [INFO]-UTILS---: Backbone interface: 
otbr-agent[1733]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200
otbr-agent[1733]: 49d.17:05:35.110 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
otbr-agent[1733]: 49d.17:05:35.110 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
otbr-agent[1733]: 49d.17:05:35.117 [NOTE]-PLAT----: RCP API Version: 5
otbr-agent[1733]: [INFO]-UTILS---: Set state callback: OK
otbr-agent[1733]: [INFO]-APP-----: Border router agent started.
otbr-agent[1733]: 00:00:00.014 [INFO]-CORE----: Notifier: StateChanged (0x00038200) [NetData PanId NetName ExtPanId]
otbr-agent[1733]: [INFO]-UBUS----: Connected as b715574c
otbr-agent[1733]: [INFO]-UBUS----: Uloop run
sh: ipset: not found
otbr-agent[1733]: 00:00:00.017 [INFO]-PLAT----: Execute command `ipset flush otbr-ingress-allow-dst-swap` = 32512
otbr-agent[1733]: 00:00:00.017 [WARN]-PLAT----: Failed to update ipsets: Failed
otbr-agent[1733]: 00:00:00.019 [INFO]-PLAT----: [netif] Host netif is down
```

**Comment by mrninhvn** [comment]
I edit `/etc/init.d/otbr-agent` file to start otbr-agent in startup.
```
START=90
        
USE_PROCD=1
           
start_service() {
        procd_open_instance
        procd_set_param command /usr/sbin/otbr-agent -I wpan0 'spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200'
        procd_close_instance                                                                                        
} 
```
But thread network doesn't save after reboot, and i can't scan border router in thread app, something wrong.

**Comment by bukepo** [comment]
@mrninhvn On OpenWrt, mdns is not enabled, so you cannot scan the border router on a mobile commissioner. By default, Thread network data is persisted in `/var/lib/thread`, could you check if that directory will be wiped out after reboot?

**Comment by mrninhvn** [comment]
> @mrninhvn On OpenWrt, mdns is not enabled, so you cannot scan the border router on a mobile commissioner. By default, Thread network data is persisted in `/var/lib/thread`, could you check if that directory will be wiped out after reboot?

It's not deleted, but i can't see network in web gui, and RCP and RCP is disabled.

**Comment by LancerSky** [comment]
The `/var` directory is a soft link to the `/tmp` directory on OpenWrt.
```
lrwxrwxrwx    1 root     root             3 Feb 15  2021 var -> tmp
```
So, it will be wiped out when you reboot.
You can redefine the storage directory in your OpenWrt `Makefile`
```
CMAKE_OPTIONS = \
	-DOT_POSIX_SETTINGS_PATH=\"/etc/openthread\" \
```

**Comment by mrninhvn** [comment]
Thank you for your help, otbr-agent run on raspberry pi fine, but it does not create network when i run it on xiaomi router 3.

```
otbr-agent[8282]: [INFO]-UBUS----: Uloop run
ipset v7.6: The set with the given name does not exist
otbr-agent[8282]: 00:00:00.196 [INFO]-PLAT----: Execute command `ipset flush otbr-ingress-allow-dst-swap` = 256
otbr-agent[8282]: 00:00:00.197 [INFO]-PLAT----: Got an error when executing command `ipset flush otbr-ingress-allow-dst-swap`: `No such file or directory`
otbr-agent[8282]: 00:00:00.197 [WARN]-PLAT----: Failed to update ipsets: Failed
otbr-agent[8282]: 00:00:00.198 [INFO]-PLAT----: [netif] Host netif is down
otbr-agent[8282]: 00:01:20.430 [INFO]-CORE----: Notifier: StateChanged (0x300c4010) [MLAddr Channel NetworkKey PSKc ActDset PndDset]
otbr-agent[8282]: 00:01:20.430 [INFO]-MLE-----: [announce-sender] StartingChannel:11
otbr-agent[8282]: 00:01:22.431 [CRIT]-PLAT----: HandleRcpTimeout() at radio_spinel_impl.hpp:2226: RadioSpinelNoResponse
```

**Comment by caipiblack** [comment]
> @LancerSky I can't create thread network with `otbr-agent` when run on real router while raspberry pi is ok. And something wrong with `ipset`. Do you have any ideas? Thank you so much.
> 
> ```
> root@X-WRT:~# /usr/sbin/otbr-agent -v -I wpan0 'spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200'
> otbr-agent[9001]: [INFO]-UTILS---: Running 0.3.0-fb0299529
> otbr-agent[9001]: [INFO]-UTILS---: Thread version: 1.2.0
> otbr-agent[9001]: [INFO]-UTILS---: Thread interface: wpan0
> otbr-agent[9001]: [INFO]-UTILS---: Backbone interface:
> otbr-agent[9001]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200
> otbr-agent[9001]: 49d.17:07:35.154 [INFO]-PLAT----: RCP reset: RESET_POWER_ON
> otbr-agent[9001]: 49d.17:07:35.163 [NOTE]-PLAT----: RCP API Version: 5
> otbr-agent[9001]: [INFO]-UTILS---: Set state callback: OK
> otbr-agent[9001]: [INFO]-APP-----: Border router agent started.
> otbr-agent[9001]: 00:00:00.024 [INFO]-CORE----: Notifier: StateChanged (0x00038200) [NetData PanId NetName ExtPanId]
> otbr-agent[9001]: [INFO]-UBUS----: Connected as 06eea988
> otbr-agent[9001]: [INFO]-UBUS----: Uloop run
> ipset v7.6: The set with the given name does not exist
> otbr-agent[9001]: 00:00:00.079 [INFO]-PLAT----: Execute command `ipset flush otbr-ingress-allow-dst-swap` = 256
> otbr-agent[9001]: 00:00:00.079 [WARN]-PLAT----: Failed to update ipsets: Failed
> otbr-agent[9001]: 00:00:00.081 [INFO]-PLAT----: [netif] Host netif is down
> otbr-agent[9001]: 00:00:40.018 [INFO]-CORE----: Notifier: StateChanged (0x300c4010) [MLAddr Channel NetworkKey PSKc ActDset PndDset]
> otbr-agent[9001]: 00:00:40.018 [INFO]-MLE-----: [announce-sender] StartingChannel:11
> otbr-agent[9001]: 00:00:42.019 [CRIT]-PLAT----: HandleRcpTimeout() at radio_spinel_impl.hpp:2226: RadioSpinelNoResponse
> ```

As i said on my issue,
Please try to execute the commands from the script script/otbr-firewall before executing otbr-agent. It will fix some ipset errors (not all in my OpenWRT 21.02 environment)

**Comment by jwhui** [comment]
Closing stale issue.
