### ISSUE TITLE
wpan0 interface is not up

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/ot-br-posix#1213]
I am setting up ot-br-posix on raspberry pi.
After completing all steps described in the border router build guide ( https://openthread.io/guides/border-router/build). My wpan0 interface is not up.
I have connected RCP and it is visible as /dev/ttyACM0 interface.
Is there any step to start wpan0 interface?

**Comment by superwhd** [comment]
There isn't extra step to start the wpan0 interface. Could you verify if `otbr-agent` service is running?

```
service otbr-agent status
```

**Comment by bhumikaajain** [comment]
No, it is not runnig.
Below is the output of it:
`lines 1-6/6 (END)
  otbr-agent.service - Border Router Agent
   Loaded: loaded (/lib/systemd/system/otbr-agent.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2022-01-24 14:52:07 IST; 4s ago
  Process: 27468 ExecStartPre=/usr/sbin/service mdns start (code=exited, status=0/SUCCESS)
  Process: 27491 ExecStart=/usr/sbin/otbr-agent $OTBR_AGENT_OPTS (code=exited, status=1/FAILURE)
 Main PID: 27491 (code=exited, status=1/FAILURE)`

**Comment by wgtdkp** [comment]
Have you ever tried https://openthread.io/codelabs/openthread-border-router?

**Comment by bhumikaajain** [comment]
No.
Let me try it and get back to you on this.

**Comment by bhumikaajain** [comment]
hi,

I have tried that guide freshly but still I am facing the same error.

**Comment by superwhd** [comment]
Could you share your syslog of `otbr-agent`?

For example,
```
tail -n 1000 /var/log/syslog | grep otbr-agent
```

**Comment by jwhui** [comment]
Closing stale issue.
