### ISSUE TITLE
Difference between wpantund and ot-ctl service on border router.

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/ot-br-posix#1216]
Hi,

Is there any elaborated document explaining the implementation difference of wpantund and ot-ctl with respect to border-router? 
I had implemented ot-br-posix in my RPI image. It is currently on wpantund/master.
Now I want to port to ot-br-posix mains and use RCP instead of NCP.
So I need to understand what all files are deprecated and introduced in the latest ot-br-posix repo in comparison to wpantund/master.
One such file is wpantund.conf which is deprecated in the latest one.

**Comment by jwhui** [comment]
Closing stale issue.
