### ISSUE TITLE
SRP clear host request retransmissions are rejected by the SRP server

### ISSUE THREAD

**Issue by kkasperczyk-no** [openthread/ot-br-posix#1224]
In the Matter project device after joining Thread network sets SRP host and invokes clear host request ([otSrpClientRemoveHostAndServices](https://github.com/project-chip/connectedhomeip/blob/master/src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp#L2051)) to clear all services registered within the host before the reboot.

I observed the situation that the first SRP request is sent in a damaged frame that doesn't allow to be decrypted on the MAC layer (known bug in radio driver), so the SRP server drops this frame (what is expected). 
```
otbr-agent[239]: 00:18:05.279 [INFO]-MAC-----: Frame rx failed, error:Security, len:122, seqnum:136, type:Data, src:0x9002, dst:0x9000, sec:yes, ackreq:yes, radio:15.4
```

SRP client after some time gets response timeout, as server was not able to answer that and tries to send SRP request once again. The second request encryption is ok (driver bug appears only on the first attempt), so SRP server spots DNS update message, but then it rejects it and sends back message with `kResponseRefused` error code:
```
Jan 28 07:48:59 8a13a0c5e8b5 otbr-agent[239]: 00:28:43.463 [INFO]-SRP-----: [server] Received DNS update from fd78:44d4:2efd:1879:64cb:adbe:203b:9a26
Jan 28 07:48:59 8a13a0c5e8b5 otbr-agent[239]: 00:28:43.464 [INFO]-SRP-----: [server] send fail response: 5
```
 I investigated that the direct reason is failing this check: https://github.com/openthread/openthread/blob/main/src/core/net/srp_server.cpp#L1034

It seemed to me that receiving damaged frame is normal situation and the following SRP requests should be handled properly by the SRP server. I'm not sure if the problem is related to the way of handling message by the SRP server or maybe creating request by the SRP client. SRP retransmissions are handled by the OpenThread stack, so I don't know whether it is possible that Matter uses OpenThread API in some wrong way and it causes the problem. The following code requests clearing SRP host in Matter: https://github.com/project-chip/connectedhomeip/blob/master/src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.cpp#L2051.

**Comment by abtink** [comment]
@kkasperczyk-no from the description of the issue, I think this is likely the same issue fixed by:
- https://github.com/openthread/openthread/pull/7216

Do you have this commit in the build used?

Before this fix, retx of "remove" could set the incorrect lease interval option. SRP server then thinks it is an "add" request, does address check and fails the check of non-zero address (at [srp_server.cpp#L1034](https://github.com/openthread/openthread/blob/main/src/core/net/srp_server.cpp#L1034))

**Comment by kkasperczyk-no** [comment]
@abtink yes I have it. I built OTBR locally with this OpenThread commit on the top: https://github.com/openthread/openthread/commit/b943b250abe8fe15f9052054e165768110fe7381

**Comment by kkasperczyk-no** [comment]
Btw. my OTBR commit is: https://github.com/openthread/ot-br-posix/commit/ad538055f971ba208a51a400ae0cde8caaa65f66

**Comment by kkasperczyk-no** [comment]
@abtink sorry I misunderstood your comment. You meant the SRP client code not the SRP server. In that case you might be right, I will try to pull this commit and see if this helps.

**Comment by kkasperczyk-no** [comment]
I verified that indeed it works with newer OpenThread version, so I'm closing this issue. Thanks for help in figuring out the reason.
