### ISSUE TITLE
Processing remove host update in server when host info is not registered seems to not work

### ISSUE THREAD

**Issue by kkasperczyk-no** [openthread/ot-br-posix#1272]
**Describe the bug** A clear and concise description of what the bug is.
In the Matter project the `otSrpClientRemoveHostAndServices` is called with `aSendUnregToServer=true` to remove host info from a server even if it wasn't registered. It was working fine, however with this commit it stopped working: https://github.com/openthread/ot-br-posix/commit/6c8f1842f9003f4607497a04f5a10c5314f56667#.

I investigated that this condition is not met: https://github.com/openthread/ot-br-posix/commit/6c8f1842f9003f4607497a04f5a10c5314f56667#diff-da370367776774c6a17541e4b394302b36c437cdc0376e1e5b115d73f9c52a3fR220 if host was not registered, so I suspect it may result in some further problems with processing the request.

**To Reproduce** Information to reproduce the behavior, including:

**Expected behavior** A clear and concise description of what you expected to happen.

I would expect removing host even if it wasn't registered should work fine, as before. Currently the SRP server seems to remove host successfully, but then it drops connection with SRP client, shuts down ot-ctl connection and after a while SRP client changes state from CHILD to DETACHED.

**Console/log output** If applicable, add console/log output to help explain your problem.
OTBR log output:

> Feb 24 07:50:54 5451b2891aa9 otbr-agent[239]: [INFO]-ADPROXY-: Advertise SRP service updates: host=5A7B29BFA401738B.default.service.arpa.
> Feb 24 07:50:54 5451b2891aa9 otbr-agent[239]: [DEBG]-ADPROXY-: Unpublish SRP host '5A7B29BFA401738B.default.service.arpa.'
> Feb 24 07:50:54 5451b2891aa9 otbr-agent[239]: [INFO]-MDNS----: Removing host 5A7B29BFA401738B.local
> Feb 24 07:50:54 5451b2891aa9 otbr-agent[239]: [INFO]-MDNS----: Removing host 5A7B29BFA401738B
> Feb 24 07:50:54 5451b2891aa9 otbr-agent[239]: [INFO]-ADPROXY-: Handle unpublish SRP host '5A7B29BFA401738B.default.service.arpa.': OK
> Feb 24 07:50:54 5451b2891aa9 otbr-agent[239]: 00:01:16.795 [I] SrpServer-----: handler result of SRP update (id = 328188320) is received: OK
> Feb 24 07:50:54 5451b2891aa9 otbr-agent[239]: 00:01:16.795 [I] SrpServer-----: lease timer is stopped
> Feb 24 07:50:54 5451b2891aa9 otbr-agent[239]: 00:01:16.795 [I] SrpServer-----: send success response
> Feb 24 07:50:54 5451b2891aa9 mDNSResponder: 11: ERROR: read_msg errno 104 (Connection reset by peer)
> Feb 24 07:50:54 5451b2891aa9 named[88]: no longer listening on fd9e:b82a:2003:fc47:f579:40c:bcc7:c69c#53
> Feb 24 07:50:54 5451b2891aa9 named[88]: no longer listening on fe80::e8e5:20e9:2d2c:ff06%4#53
> Feb 24 07:50:54 5451b2891aa9 named[88]: no longer listening on fd9e:b82a:2003:fc47:0:ff:fe00:fc00#53
> Feb 24 07:50:54 5451b2891aa9 named[88]: no longer listening on fd9e:b82a:2003:fc47:0:ff:fe00:1c00#53
> Feb 24 07:50:54 5451b2891aa9 named[88]: no longer listening on fd11:22::ad12:31df:49da:c158#53
> Feb 24 07:50:54 5451b2891aa9 named[88]: no longer listening on fd9e:b82a:2003:fc47:0:ff:fe00:fc10#53
> Feb 24 07:50:54 5451b2891aa9 named[88]: no longer listening on fd9e:b82a:2003:fc47:0:ff:fe00:fc38#53
> Feb 24 07:50:54 5451b2891aa9 named[88]: no longer listening on fd9e:b82a:2003:fc47:0:ff:fe00:fc11#53

**Additional context** Add any other context about the problem here.

**Comment by kkasperczyk-no** [comment]
@wgtdkp I see that you are the author of a mentioned commit, so maybe you have any ideas what can be the reason of an issue?

**Comment by wgtdkp** [comment]
@kkasperczyk-no Thanks for reporting this issue! Sure I will take at look soon.

**Comment by wgtdkp** [comment]
@kkasperczyk-no I just submitted https://github.com/openthread/ot-br-posix/pull/1273 to fix this issue. Can you help confirm if this works for you?

**Comment by kkasperczyk-no** [comment]
@wgtdkp yes it solved the remove host issue, thank you!

After removing host and adding services I'm observing some strange behavior that didn't happen before. It looks like the first SRP update request is rejected by the SRP server, but the retransmission is accepted. Maybe that is some other problem not related with that issue, but just I'm letting you know. It looks in a following way:

> Feb 25 12:37:41 458289079bfa otbr-agent[239]: [INFO]-ADPROXY-: Advertise SRP service updates: host=66039F05C3E8F9DA.default.service.arpa.
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: [DEBG]-ADPROXY-: Publish SRP service '04A3C61C27FB6B4F._matterc._udp.default.service.arpa.'
**> Feb 25 12:37:41 458289079bfa otbr-agent[239]: [WARN]-ADPROXY-: Handle publish SRP service '04A3C61C27FB6B4F._matterc._udp.default.service.arpa.': Invalid arguments
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.930 [INFO]-SRP-----: [server] handler result of SRP update (id = 309421696) is received: InvalidArgs
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.930 [INFO]-SRP-----: [server] send fail response: 5**
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: [DEBG]-ADPROXY-: Publish SRP host '66039F05C3E8F9DA.default.service.arpa.'
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: [INFO]-MDNS----: Registering new host 66039F05C3E8F9DA
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.936 [DEBG]-MAC-----: =========================[TX seqno=216 len=061]=========================
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.936 [DEBG]-MAC-----: | 69 98 D8 34 12 02 68 00 | 68 0D 10 00 00 00 01 6E | i.X4..h.h......n
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.936 [DEBG]-MAC-----: | 55 0D ED 86 86 2D 3F 77 | 7B 58 5D A3 F3 EE 11 D0 | U.m..-?w{X]#sn.P
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.936 [DEBG]-MAC-----: | D7 88 A3 67 F0 D1 20 C0 | 02 AB 69 24 B3 A8 05 00 | W.#gpQ @.+i$3(..
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.936 [DEBG]-MAC-----: | 00 00 00 00 00 00 00 66 | 73 8B 8C A7 F5 .. .. .. | .......fs..'u...
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.936 [DEBG]-MAC-----: ------------------------------------------------------------------------
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.936 [INFO]-MAC-----: Sent IPv6 UDP msg, len:60, chksum:ab69, to:0x6802, sec:yes, prio:low
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.936 [INFO]-MAC-----:     src:[fddd:aede:368a:8851:862d:3f77:7b58:5da3]:53536
> Feb 25 12:37:41 458289079bfa otbr-agent[239]: 00:04:08.936 [INFO]-MAC-----:     dst:[fddd:aede:368a:8851:f3ee:11d0:d788:a367]:49154
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: [INFO]-MDNS----: Received reply for host 66039F05C3E8F9DA.local
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: [INFO]-MDNS----: Successfully registered host 66039F05C3E8F9DA.local
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: [INFO]-ADPROXY-: Handle publish SRP host '66039F05C3E8F9DA.default.service.arpa.': OK
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.171 [INFO]-MLE-----: Send Advertisement (ff02:0:0:0:0:0:0:1)
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.179 [DEBG]-MAC-----: =========================[TX seqno=217 len=069]=========================
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.179 [DEBG]-MAC-----: | 41 D8 D9 34 12 FF FF 79 | 61 3A 25 70 3E DD A6 7F | AXY4...ya:%p>]&.
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.179 [DEBG]-MAC-----: | 3B 01 F0 4D 4C 4D 4C 33 | B2 00 15 1A 00 00 00 00 | ;.pMLML32.......
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.179 [DEBG]-MAC-----: | 00 00 00 01 2B 87 3A 25 | 1F 7C AE B2 47 29 30 B5 | ....+.:%.|.2G)05
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.179 [DEBG]-MAC-----: | EB 97 69 B0 02 FE 5E FF | B3 C2 7A C9 AF 94 F5 B0 | k.i0.~^.3BzI/.u0
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.179 [DEBG]-MAC-----: | 59 DD 14 A0 6A .. .. .. | .. .. .. .. .. .. .. .. | Y]. j...........
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.180 [DEBG]-MAC-----: ------------------------------------------------------------------------
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.180 [INFO]-MAC-----: Sent IPv6 UDP msg, len:90, chksum:33b2, to:0xffff, sec:no, prio:net
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.180 [INFO]-MAC-----:     src:[fe80:0:0:0:a4dd:3e70:253a:6179]:19788
> Feb 25 12:37:42 458289079bfa otbr-agent[239]: 00:04:10.180 [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:1]:19788
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.772 [DEBG]-MAC-----: =========================[RX seqno=004 len=122]=========================
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.772 [DEBG]-MAC-----: | 79 98 04 34 12 00 68 02 | 68 0D 09 00 00 00 01 C2 | y..4..h.h......B
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.772 [DEBG]-MAC-----: | 3D 20 71 7E 55 F3 EE 11 | D0 D7 88 A3 67 86 2D 3F | = q~Usn.PW.#g.-?
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.772 [DEBG]-MAC-----: | 77 7B 58 5D A3 F0 C0 02 | D1 20 75 EC 49 3E 28 00 | w{X]#p@.Q ulI>(.
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.772 [DEBG]-MAC-----: | 00 01 00 00 00 0B 00 02 | 07 64 65 66 61 75 6C 74 | .........default
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.772 [DEBG]-MAC-----: | 07 73 65 72 76 69 63 65 | 04 61 72 70 61 00 00 06 | .service.arpa...
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.772 [DEBG]-MAC-----: | 00 01 08 5F 6D 61 74 74 | 65 72 63 04 5F 75 64 70 | ..._matterc._udp
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.772 [DEBG]-MAC-----: | C0 0C 00 0C 00 01 00 00 | 1C 20 00 13 10 30 34 41 | @........ ...04A
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.772 [DEBG]-MAC-----: | 33 43 36 31 72 7A CB 78 | 2C 2D .. .. .. .. .. .. | 3C61rzKx,-......
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.772 [DEBG]-MAC-----: ------------------------------------------------------------------------
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.780 [DEBG]-MAC-----: =========================[RX seqno=005 len=122]=========================
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.780 [DEBG]-MAC-----: | 79 98 05 34 12 00 68 02 | 68 0D 0A 00 00 00 01 E2 | y..4..h.h......b
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.780 [DEBG]-MAC-----: | 3D 20 71 0F 43 32 37 46 | 42 36 42 34 46 C0 26 07 | = q.C27FB6B4F@&.
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.780 [DEBG]-MAC-----: | 5F 56 36 35 35 32 31 04 | 5F 73 75 62 C0 26 00 0C | _V65521._sub@&..
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.780 [DEBG]-MAC-----: | 00 01 00 00 1C 20 00 02 | C0 40 04 5F 53 31 35 C0 | ..... ..@@._S15@
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.780 [DEBG]-MAC-----: | 5B 00 0C 00 01 00 00 1C | 20 00 02 C0 40 06 5F 4C | [....... ..@@._L
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.780 [DEBG]-MAC-----: | 33 38 34 30 C0 5B 00 0C | 00 01 00 00 1C 20 00 02 | 3840@[....... ..
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.780 [DEBG]-MAC-----: | C0 40 03 5F 43 4D C0 5B | 00 0C 00 01 00 00 1C 20 | @@._CM@[....... 
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.780 [DEBG]-MAC-----: | 00 02 C0 40 98 CE 4B CA | 2C 2C .. .. .. .. .. .. | ..@@.NKJ,,......
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.780 [DEBG]-MAC-----: ------------------------------------------------------------------------
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.786 [DEBG]-MAC-----: =========================[RX seqno=006 len=122]=========================
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.786 [DEBG]-MAC-----: | 79 98 06 34 12 00 68 02 | 68 0D 0B 00 00 00 01 E2 | y..4..h.h......b
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.786 [DEBG]-MAC-----: | 3D 20 71 1B C0 40 00 FF | 00 FF 00 00 00 00 00 00 | = q.@@..........
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.786 [DEBG]-MAC-----: | C0 40 00 21 00 01 00 00 | 1C 20 00 19 00 00 00 00 | @@.!..... ......
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.786 [DEBG]-MAC-----: | 15 A4 10 36 36 30 33 39 | 46 30 35 43 33 45 38 46 | .$.66039F05C3E8F
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.786 [DEBG]-MAC-----: | 39 44 41 C0 0C C0 40 00 | 10 00 01 00 00 1C 20 00 | 9DA@.@@....... .
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.786 [DEBG]-MAC-----: | 3A 0E 56 50 3D 36 35 35 | 32 31 2B 33 32 37 37 33 | :.VP=65521+32773
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.786 [DEBG]-MAC-----: | 08 43 52 49 3D 35 30 30 | 30 07 43 52 41 3D 33 30 | .CRI=5000.CRA=30
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.786 [DEBG]-MAC-----: | 30 03 54 3D 76 E9 2C 65 | 2C 2D .. .. .. .. .. .. | 0.T=vi,e,-......
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.786 [DEBG]-MAC-----: ------------------------------------------------------------------------
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.792 [DEBG]-MAC-----: =========================[RX seqno=007 len=122]=========================
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.792 [DEBG]-MAC-----: | 79 98 07 34 12 00 68 02 | 68 0D 0C 00 00 00 01 E2 | y..4..h.h......b
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.792 [DEBG]-MAC-----: | 3D 20 71 27 30 06 44 3D | 33 38 34 30 04 43 4D 3D | = q'0.D=3840.CM=
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.792 [DEBG]-MAC-----: | 31 05 50 48 3D 33 33 03 | 50 49 3D C0 C6 00 FF 00 | 1.PH=33.PI=@F...
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.792 [DEBG]-MAC-----: | FF 00 00 00 00 00 00 C0 | C6 00 1C 00 01 00 00 1C | .......@F.......
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.792 [DEBG]-MAC-----: | 20 00 10 FD 11 00 22 00 | 00 00 00 F4 F7 F3 51 EA |  ..}.."....twsQj
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.792 [DEBG]-MAC-----: | EC 9A F1 C0 C6 00 19 00 | 01 00 00 1C 20 00 44 02 | l.q@F....... .D.
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.792 [DEBG]-MAC-----: | 01 03 0D 79 70 74 28 60 | 40 FB 1E 14 36 0B EF AD | ...ypt(`@{..6.o-
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.792 [DEBG]-MAC-----: | 63 5E 83 A1 2F 33 51 A9 | 2D 2C .. .. .. .. .. .. | c^.!/3Q)-,......
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.792 [DEBG]-MAC-----: ------------------------------------------------------------------------
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.799 [DEBG]-MAC-----: =========================[RX seqno=008 len=122]=========================
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.799 [DEBG]-MAC-----: | 79 98 08 34 12 00 68 02 | 68 0D 0D 00 00 00 01 E2 | y..4..h.h......b
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.799 [DEBG]-MAC-----: | 3D 20 71 33 D5 57 49 4B | C5 9C 7C 60 E2 AF CB C8 | = q3UWIKE.|`b/KH
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.799 [DEBG]-MAC-----: | 45 B3 60 0F 25 64 BE D9 | F6 FE A3 CC B7 03 88 A8 | E3`.%d>Yv~#L7..(
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.799 [DEBG]-MAC-----: | D7 28 CC BC 93 48 86 72 | 6E 92 B2 30 BC 6D E5 FA | W(L<.H.rn.20<mez
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.799 [DEBG]-MAC-----: | 74 02 C0 00 00 29 04 F8 | 00 00 80 00 00 0C 00 02 | t.@..).x........
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.799 [DEBG]-MAC-----: | 00 08 00 00 1C 20 00 12 | 75 00 00 00 18 00 FF 00 | ..... ..u.......
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.799 [DEBG]-MAC-----: | 00 00 00 00 54 00 00 0D | 00 00 00 00 00 00 00 00 | ....T...........
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.799 [DEBG]-MAC-----: | 00 00 00 00 A6 B1 A8 9A | 2C 2D .. .. .. .. .. .. | ....&1(.,-......
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.799 [DEBG]-MAC-----: ------------------------------------------------------------------------
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.804 [DEBG]-MAC-----: =========================[RX seqno=009 len=095]=========================
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.804 [DEBG]-MAC-----: | 69 98 09 34 12 00 68 02 | 68 0D 0E 00 00 00 01 E2 | i..4..h.h......b
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.804 [DEBG]-MAC-----: | 3D 20 71 3F 00 00 00 C0 | C6 CB E4 31 A8 36 94 C8 | = q?...@FKd1(6.H
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.804 [DEBG]-MAC-----: | 03 21 BB 89 8C 0E E6 71 | 51 C1 2B C2 52 5B DA FF | .!;...fqQA+BR[Z.
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.804 [DEBG]-MAC-----: | 18 F6 E2 A2 BC C4 6D 1E | 19 0A 6B 5F 71 1A 5E 24 | .vb"<Dm...k_q.^$
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.804 [DEBG]-MAC-----: | 5C F8 77 1E 55 28 6E 4D | 18 14 DE D0 52 7E D0 4C | \xw.U(nM..^PR~PL
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.804 [DEBG]-MAC-----: | AF C8 FE D5 42 D1 1D DE | CE B1 BE BA F1 2C A8 .. | /H~UBQ.^N1>:q,(.
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.804 [DEBG]-MAC-----: ------------------------------------------------------------------------
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.804 [INFO]-MAC-----: Received IPv6 UDP msg, len:573, chksum:75ec, from:0x6802, sec:yes, prio:normal, rss:-48.125
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.805 [INFO]-MAC-----:     src:[fddd:aede:368a:8851:f3ee:11d0:d788:a367]:49154
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.805 [INFO]-MAC-----:     dst:[fddd:aede:368a:8851:862d:3f77:7b58:5da3]:53536
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.805 [INFO]-SRP-----: [server] Received DNS update from fddd:aede:368a:8851:f3ee:11d0:d788:a367
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: 00:04:10.832 [INFO]-SRP-----: [server] SRP update handler is notified (updatedId = 309421697)
**> Feb 25 12:37:43 458289079bfa otbr-agent[239]: [INFO]-ADPROXY-: Advertise SRP service updates: host=66039F05C3E8F9DA.default.service.arpa.
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: [DEBG]-ADPROXY-: Publish SRP service '04A3C61C27FB6B4F._matterc._udp.default.service.arpa.'
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: [INFO]-MDNS----: Registering new service 04A3C61C27FB6B4F._matterc._udp,_CM,_L3840,_S15,_V65521.local, serviceRef = (nil)
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: [DEBG]-ADPROXY-: Publish SRP host '66039F05C3E8F9DA.default.service.arpa.'
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: [INFO]-MDNS----: Making std::move host 2
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: [INFO]-ADPROXY-: Handle publish SRP host '66039F05C3E8F9DA.default.service.arpa.': OK
> Feb 25 12:37:43 458289079bfa otbr-agent[239]: [INFO]-ADPROXY-: Waiting for more publishing callbacks 1
> Feb 25 12:37:44 458289079bfa otbr-agent[239]: [INFO]-MDNS----: Received reply for service 04A3C61C27FB6B4F._matterc._udp., serviceRef = 0x562ea22bc0a0
> Feb 25 12:37:44 458289079bfa otbr-agent[239]: [INFO]-MDNS----: Successfully registered service 04A3C61C27FB6B4F._matterc._udp.**
> Feb 25 12:37:44 458289079bfa otbr-agent[239]: [INFO]-ADPROXY-: Handle publish SRP service '04A3C61C27FB6B4F._matterc._udp.default.service.arpa.': OK

**Comment by wgtdkp** [comment]
@kkasperczyk-no Thanks for verification, I just pushed update to the PR, can you fetch again and check if the `InvalidArgs` issues disappears?

**Comment by kkasperczyk-no** [comment]
@wgtdkp yes it did. Looks like everything is working fine.
