### ISSUE TITLE
Third party repos not downloading when cloning the project?  Very strange.

### ISSUE THREAD

**Issue by HeneryH** [openthread/ot-br-posix#1282]
**Describe the bug** A clear and concise description of what the bug is.
When installing on raspberry pi 64 bit the git clone does not seem to pull down the third party repos.  The Cmakes are all there but the repo directories are all empty.  Last week I built using raspberry pi 32 bit and it seemed to work fine.

Has anyone seen this before?

When I manually clone the third party repos into the respective directories it seems to make progress on to the next missing repo.

I have no idea if this is related to 64bit.  Oh, and I also recompiled the kernel to get the BlueZ crypto stuff enabled so that is another changed variable.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by jwhui** [comment]
@HeneryH , can you share the commands you are using to build OTBR?

**Comment by HeneryH** [comment]
It is just the git clone.  Could there be a OS type switch that
would prevent a 64bit raspbian from downloading?
I'll try again with the 32b OS to make sure.

**Comment by jwhui** [comment]
> It is just the git clone. Could there be a OS type switch that would prevent a 64bit raspbian from downloading? I'll try again with the 32b OS to make sure.

Third party repos are git submodules. Try using the following command at the root of ot-br-posix:

```
$ git submodule update --init
```

Note that this command is included a part of [script/bootstrap](https://github.com/openthread/ot-br-posix/blob/71a82a5af1ef71877e38ac73ecb9e02813209a80/script/bootstrap#L157)

**Comment by HeneryH** [comment]
It isn't getting executed properly for some reason.  I can manually run it.  I didn't see any errors in the setup script output.  I'll paste it next but it is alot.

rm -rf ot-br-posix
git clone https://github.com/openthread/ot-br-posix
cd ot-br-posix
INFRA_IF_NAME=wlan0 ./script/setup

> CMake Error at third_party/openthread/CMakeLists.txt:90 (add_subdirectory):
>   The source directory
> 
>     /home/pi/ot-br-posix/third_party/openthread/repo
> 
>   does not contain a CMakeLists.txt file.

ls -la /home/pi/ot-br-posix/third_party/openthread/repo

> total 8
> drwxr-xr-x 2 pi pi 4096 Mar  3 15:25 .
> drwxr-xr-x 3 pi pi 4096 Mar  3 15:25 ..

git submodule update --init

> Submodule 'third_party/cJSON/repo' (https://github.com/DaveGamble/cJSON.git) registered for path 'third_party/cJSON/repo'
> Submodule 'third_party/http-parser/repo' (https://github.com/nodejs/http-parser.git) registered for path 'third_party/http-parser/repo'
> Submodule 'third_party/openthread/repo' (https://github.com/openthread/openthread.git) registered for path 'third_party/openthread/repo'
> Cloning into '/home/pi/ot-br-posix/third_party/cJSON/repo'...
> Cloning into '/home/pi/ot-br-posix/third_party/http-parser/repo'...
> Cloning into '/home/pi/ot-br-posix/third_party/openthread/repo'...
> Submodule path 'third_party/cJSON/repo': checked out 'cf97c6f066d81fdbba4ef722cfd327bbbba2365c'
> Submodule path 'third_party/http-parser/repo': checked out '4f15b7d510dc7c6361a26a7c6d2f7c3a17f8d878'
> Submodule path 'third_party/openthread/repo': checked out '6bb9631e804c76a9cd1b61b028239e116d74514c'

ls -la /home/pi/ot-br-posix/third_party/openthread/repo
ls -la /home/pi/ot-br-posix/third_party/openthread/repo

> total 232
> drwxr-xr-x 12 pi pi  4096 Mar  3 15:33 .
> drwxr-xr-x  3 pi pi  4096 Mar  3 15:25 ..
> -rw-r--r--  1 pi pi 36043 Mar  3 15:33 Android.mk
> -rw-r--r--  1 pi pi   639 Mar  3 15:33 AUTHORS
> -rwxr-xr-x  1 pi pi  2511 Mar  3 15:33 bootstrap
> -rw-r--r--  1 pi pi  3351 Mar  3 15:33 BUILD.gn
> -rw-r--r--  1 pi pi  3186 Mar  3 15:33 .clang-format
> -rw-r--r--  1 pi pi  8283 Mar  3 15:33 CMakeLists.txt
> and so on

**Comment by jwhui** [comment]
You should run `./script/bootstrap` before `./script/setup` as suggested in the [Border Router - Build and Configuration guide](https://openthread.io/guides/border-router/build#install-otbr).

Note that `./script/bootstrap` includes the `git submodule` command.

**Comment by HeneryH** [comment]
Ah, there is a mistake in this documentation.  I'll put a PR in for it.

http://194.19.86.155/nRF_Connect_SDK/doc/latest/matter/python_chip_controller_building.html

**Comment by HeneryH** [comment]
My mistake.  I was running from another instruction that had the process separated and I missed that.
http://194.19.86.155/nRF_Connect_SDK/doc/latest/matter/python_chip_controller_building.html#source

**Comment by HeneryH** [comment]
User error
