### ISSUE TITLE
running otbr fails due to otbr_firewall at the second attempt

### ISSUE THREAD

**Issue by doublemis1** [openthread/ot-br-posix#1286]
**Describe the bug**
The OTBR docker fails at the second attempt due to firewall-otbr when docker is connected to host network.
Docker creates ip6tables rules at the first attempt and does not clear them before removing the docker container which impacts the second attempt.

**To Reproduce** 

1. ot-br-posix: f0bd2166467464c3fac23b28f7669179ee9ba332
2. docker build -t otbr:test . -f etc/docker/Dockerfile
3. docker run -it --rm --privileged --name otbr --network host --volume /dev/ttyACM0:/dev/radio otbr:test --radio-url spinel+hdlc+uart:///dev/radio?uart-baudrate=115200 -B wlan0
4. Stop and remove docker container
5. docker run -it --rm --privileged --name otbr --network host --volume /dev/ttyACM0:/dev/radio otbr:test --radio-url spinel+hdlc+uart:///dev/radio?uart-baudrate=115200 -B wlan0

**Expected behavior**

The docker container should handle that the ip6tables are already set.
Or Remove them and add them once again.

**Console/log output**
```
+ ipset create -exist otbr-ingress-deny-src hash:net family inet6
+ ipset create -exist otbr-ingress-deny-src-swap hash:net family inet6
+ ipset create -exist otbr-ingress-allow-dst hash:net family inet6
+ ipset create -exist otbr-ingress-allow-dst-swap hash:net family inet6
+ ip6tables -N OTBR_FORWARD_INGRESS
ip6tables: Chain already exists.
+ die 'Failed to start firewall service'
+ echo ' *** ERROR:  Failed to start firewall service'
 *** ERROR:  Failed to start firewall service
+ exit 1
```
**Additional context**

**Comment by superwhd** [comment]
Thanks for raising this issue! I sent a PR to fix it: https://github.com/openthread/ot-br-posix/pull/1287
