### ISSUE TITLE
mDNS advertise not working when virtual VPN interface added (DPROXY/MDNS issue)

### ISSUE THREAD

**Issue by samuelAN-GH** [openthread/ot-br-posix#1305]
Hello,

I am using avahi to advertise on the border router, and my thread end-devices are able to dnsBrowse and find the advertised service without any problem.

The issue comes when I add a virtual VPN interface on the border router. As soon as this virtual interface is added (visible on ifconfig), the thread end devices are not able to make the mdns  browse (i get a NotFound ot error on the end devices). The wpan0 interface is always correclty listed in ifconfig of the BR. 

Could someone explain why it is not working on this case?
Thanks

**Comment by samuelAN-GH** [comment]
Additionnaly, I see that when I remove eth0 from the allow-interfaces param of avahi, the openthread devices cannot make the DNSBrowse (even whithout any VPN) I don't understand why the eth0 must be enabled to allow thread devices to dnsBrowse on the wpan interface...

**Comment by samuelAN-GH** [comment]
Hello,

The issue seems to be linked to the condition :

`if (GetServiceSubscriptionCount(nameInfo) == 1)`

in discovery_proxy.cpp.

When the VPN is active, is seems that the count is 2, and the two queries are identical (I've added some debug lines in the cpp file) : 

Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: aName name :
Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: queryInfo name :

Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: aName serviceName : _advert._udp
Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: queryInfo serviceName : _advert._udp

Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: aName hostName :
Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: queryInfo mHostName :

==> count = 1

Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: aName name :
Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: queryInfo name :

Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: aName serviceName : _advert._udp
Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: queryInfo serviceName : _advert._udp

Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: aName hostName :
Mar 26 23:32:19 rpi otbr-agent[1258]: [INFO]-DPROXY--: queryInfo mHostName :

==> count = 2

**Comment by jwhui** [comment]
Closing stale issue.
