### ISSUE TITLE
Can NCP and RCP support additional GPIO functionality in their firmware

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/ot-br-posix#1313]
Hi,

We are using nRF52840 SoC for NCP/RCP application at the border router side.
My border router is my custom gateway which has a Rpi Compute module in it.
In my NCP/RCP firmware, can I add additional application to use the nRF52840 hardware as I2C slave and also some GPIOs to use for digital/analog read/write functionality in parallel to running NCP/RCP application.
Will that implementation cause any issue in NCP/RCP smooth functionality?

**Comment by jwhui** [comment]
Yes, it should be possible to add additional logic to the NCP/RCP firmware. As with any SW development, whether the additional SW will interfere with other tasks largely depends on what the additional SW is doing. Ideally, the implementation should avoid long-running critical sections or tasks.

**Comment by jwhui** [comment]
Closing stale issue.
