### ISSUE TITLE
OTBR lost some frames when sending data to multiple end devices at the same time

### ISSUE THREAD

**Issue by Semi-Bin-Blain** [openthread/ot-br-posix#1318]
Hi there, I find that the OTBR lost some frames when it transmits the data from the Cloud Platform to the multiple end devices at the same time.

I have 5 End devices whose Thread Roles are all MED, these End Devices communicate with the Cloud Platform via COAP protocol. I can send commands from the Cloud Platform to the end devices; I sent the same command to the 5 devices at the same time, but not all the devices can receive the command every time, so I caught the network frames in the OTBR wpan0 interface and caught the Thread frames via the sniffer, the result shows that the 5 frames which include the command have arrived the OTBR wpan0 interface, but only 4 of them sent to the end devices by the OTBR via the OpenThread RCP. (like the picture shows)

wpan0 frames:
![image](https://user-images.githubusercontent.com/45001709/160750672-c6f0c136-2772-4205-af67-8446470d3232.png)

sniffer frames:
![image](https://user-images.githubusercontent.com/45001709/160750739-769c47fb-f9c3-454e-8130-824eae712cb5.png)

The information as follow:
1. Git commit id: f0bd2166467464c3fac23b28f7669179ee9ba332
2. IEEE 802.15.4 hardware platform: NRF52833DK
3. Thread Version 1.1
4. RCP software: ncs1.8.0/nrf/samples/openthread/coprocessor ([ncs1.8.0](https://github.com/nrfconnect/sdk-nrf/tree/v1.8.0))
5. OpwnWrt Version: stable release 21.02
6. the Thread network key(Master key): 93864f17ccd7f13f1834a738907994f6
7. the .pcapng files: [pcapng_files.zip](https://github.com/openthread/ot-br-posix/files/8377048/pcapng_files.zip)

I am not sure what is causing the problem, so I come for help.

Thanks in advance

**Comment by Semi-Bin-Blain** [comment]
@jwhui 
Thanks for your reply, I've tried again, and the output is as follows file.  I got the log only when the problem happened, and I noticed that the ”counters IP“ can directly show that the problem happened, the “Tx failed” of “counters IP” would increase by 1, sometimes, so did the "Rx failed" ethier.

[OT_CLI_counters.log](https://github.com/openthread/ot-br-posix/files/8559097/OT_CLI_counters.log)

**Comment by jwhui** [comment]
Closing stale issue.
