### ISSUE TITLE
otbr-agent exit code

### ISSUE THREAD

**Issue by thierryGasque** [openthread/ot-br-posix#1321]
Hi there,

we are in the process of porting otbr-agent on another linux platform.
The ot-br-posix package has been integrated and installed but when executing we got the following exit code :

root@user1:~# systemctl list-unit-files | grep otbr
otbr-agent.service                     enabled
root@user1:~# systemctl status otbr-agent.service | more
* otbr-agent.service - Border Router Agent
     Loaded: loaded (/lib/systemd/system/otbr-agent.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2020-09-20 10:50:09 UTC; 3s ago
    Process: 1209 ExecStartPre=/bin/systemctl start avahi-daemon (code=exited, status=0/SUCCESS)
    **Process: 1210 ExecStart=/usr/sbin/otbr-agent $OTBR_AGENT_OPTS (code=exited, status=2)**
   **Main PID: 1210 (code=exited, status=2)**

Where can we find the meaning of this error ?

ciao

**Comment by superwhd** [comment]
Could you share some syslog of `otbr-agent`? 

```
tail -f /var/log/syslog | grep otbr-agent
```

**Comment by thierryGasque** [comment]
Hi,
the issue came from the RadioURL not available in the system at the launch of otbr-agent.
/dev/ttyUSB0 was not available.
That' fine with this issue now.

thx for support
