### ISSUE TITLE
obtr docker run fail

### ISSUE THREAD

**Issue by TuHuynhthanh** [openthread/ot-br-posix#1327]
I built and run obtr on my rpi3 with RCP using nRF52840. it run successfully. 
When i run docker with this RCP :
docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 --dns=127.0.0.1 -it --volume /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr --radio-url spinel+hdlc+uart:///dev/ttyACM0

i get an error:

net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.tcp_syncookies = 1
* Applying /etc/sysctl.d/10-ptrace.conf ...
* Applying /etc/sysctl.d/10-zeropage.conf ...
vm.mmap_min_addr = 32768
* Applying /etc/sysctl.d/60-otbr-accept-ra.conf ...
net.ipv6.conf.eth0.accept_ra = 2
net.ipv6.conf.eth0.accept_ra_rt_info_max_plen = 64
* Applying /etc/sysctl.d/60-otbr-ip-forward.conf ...
net.ipv6.conf.all.forwarding = 1
net.ipv4.ip_forward = 1
* Applying /etc/sysctl.conf ...
+ nat64_start
+ with NAT64
+ local value
++ printenv NAT64
+ value=1
+ [[ -z 1 ]]
+ [[ 1 == 1 ]]
+ with DOCKER
+ local value
++ printenv DOCKER
+ value=1
+ [[ -z 1 ]]
+ [[ 1 == 1 ]]
+ service tayga start
 * Starting userspace NAT64 tayga                                                            [fail]
+ die 'Failed to start tayga'
+ echo ' *** ERROR:  Failed to start tayga'
 *** ERROR:  Failed to start tayga
+ exit 1
tail: cannot open '/var/log/syslog' for reading: No such file or directory
tail: no files remaining

i don't know why i get this error?

**Comment by jwhui** [comment]
Unfortunately, I was unable to reproduce this issue.

I tried ran through the [Docker setup](https://openthread.io/guides/border-router/docker) steps on a Raspberry Pi 3B+ using a fresh image of `2021-05-07-raspios-buster-armhf-lite` and everything worked as expected.

**Comment by TuHuynhthanh** [comment]
yeah!!! you right @jwhui , i setup as your descript, it run ok. Thank for your reply.
