### ISSUE TITLE
Running as OTBR docker on OSX fails to open RCP /dev file.

### ISSUE THREAD

**Issue by jemdiggity** [openthread/ot-br-posix#1347]
Running OTBR using docker (Docker Desktop) on a Mac fails when accessing the RCP.

Reproduce by following instructions at https://openthread.io/guides/border-router/docker
```
cd ~
git clone https://github.com/openthread/ot-br-posix
cd ot-br-posix
docker build --no-cache -t openthread/otbr -f etc/docker/Dockerfile .
docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 --dns=127.0.0.1 -it --volume /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr --radio-url spinel+hdlc+uart:///dev/ttyACM0

```
Using Nordic nRF52840 dongle as RCP.
OTBR git commit 8aa5377.

Error log reported by OTBR as below:
```
Apr 19 11:42:36 60aa50bc2f81 otbr-agent[211]: 49d.17:24:35.623 [C] Platform------: Radio file '/dev/tty.usbmodemD0A2346EA1362' not supported
Apr 19 11:42:36 60aa50bc2f81 otbr-agent[211]: 49d.17:24:35.623 [C] Platform------: Radio file '/dev/tty.usbmodemD0A2346EA1362' not supported
Apr 19 11:42:36 60aa50bc2f81 otbr-agent[211]: 49d.17:24:35.623 [C] Platform------: Init() at radio.cpp:102: InvalidArgument
Apr 19 11:42:36 60aa50bc2f81 otbr-agent[211]: 49d.17:24:35.623 [C] Platform------: Radio file '/dev/tty.usbmodemD0A2346EA1362' not supported
```

On OSX Host:
`crw-rw-rw-  1 root        wheel      18,   2 Apr 19 20:30 tty.usbmodemD0A2346EA1362
`
On Docker:
`drwxr-xr-x 2 root root       40 Apr 19 11:32 tty.usbmodemD0A2346EA1362
`
As you can see, Docker changes the RCP from a character special file to a directory which is tested in hdlc_inferface.cpp using S_ISCHR which fails and that's why running OTBR in docker for Mac doesn't work.

This isn't a bug with OTBR but an issue with Docker Desktop.

**Comment by jwhui** [comment]
@jemdiggity , last I checked, Docker Desktop does not support USB passthrough.

See https://docs.docker.com/desktop/faqs/#can-i-pass-through-a-usb-device-to-a-container

**Comment by jwhui** [comment]
Closing stale issue.
