### ISSUE TITLE
OTBR 1.3 reference device DUA issue

### ISSUE THREAD

**Issue by edmont** [openthread/ot-br-posix#1358]
I'm trying to validate the OTBR 1.3 reference device as Thread Certification compliant, but some Commercial tests are failing.

This branch https://github.com/openthread/ot-reference-release/compare/main...edmont:pr-add-ncs-1-3 has been used to build the reference device, with this command: `REFERENCE_PLATFORM=ncs REFERENCE_RELEASE_TYPE=1.3 ./script/make-reference-release.bash`

What I found to be the problem in the test C5.9.1 is that the BR_1 device is not forwarding DUA traffic towards the Thread Network. Frame 347 in the attached PCAP. The test logs show the proper solicited Neighbor Advertisement in line 2017, but nothing about the incoming Echo Request.

[C_5_9_1-fail2.zip](https://github.com/openthread/ot-br-posix/files/8618623/C_5_9_1-fail2.zip)

**Comment by edmont** [comment]
Gave a try with `BORDER_ROUTING=0` and the test is still failing in the same way.

**Comment by jwhui** [comment]
Closing stale issue.
