### ISSUE TITLE
OpenThread without LAN connection

### ISSUE THREAD

**Issue by samuelAN-GH** [openthread/ot-br-posix#1359]
Hi,

It seems that otbr with default configuration is not working if the rpi is not connected to a local gateway with active DHCP server.

When this is the case, some part of my application (i.e. coap data transmission) is not working, even if the transmission is done direclty from my openthread end device to my rpi without going in the lan network.

How can I allow otbr to work in "isolated" mode, I.e. without any ethernet connection from my rpi to any router ?

Thanks

**Comment by jwhui** [comment]
@samuelAN-GH , I don't believe DHCP (especially if it's not DHCPv6) has any affect on the Thread network itself. I test with a Raspberry Pi connected to a default gateway providing DHCP all the time with no issues.

Can you provide more information?

1. More detail about your setup so that someone else can replicate your situation?
2. More diagnostic information such as IP addresses, network data, etc. on the Thread network.
3. Packet capture files using tcpdump on the Raspberry Pi and/or 802.15.4 sniffer.

**Comment by samuelAN-GH** [comment]
Hi jonathan,

I have a coap server installed on my rpi on which I send data from thread end-devices.

My test setup is simply constituted by :

Gateway (local router) --(ethernet link)-- RPI --(thread wireless link)-- Thread end-devices

During all my tests, everything worked perfectly. End devices are able to communicated with the RPI, and data, which is sent using coap to the RPI is correclty received and stored.

BUT, for some applications, the RPI has no access to any gateway (and external access to the stored data is not required). This is my "isolated" case : only one RPI and thread end devices :

RPI --(thread wireless link)-- Thread end-devices

In this case, I have noticed that my end-devices are able to register on the thread network, but **no data is stored in the coap server**.

I suppose that this is linked to the fact that, whithout connected gateway, the eth0 interface of the rpi (which is used as infrastructure interface), is not running correclty (since this interface is configured as default, meaning that it is waiting for a DHCP server to assign one local IP(v4) address).

I don't know what is the best solution to make it work correclty, even if no gateway is connected to the RPI.

**Comment by jwhui** [comment]
@samuelAN-GH , I also test regularly with a Raspberry Pi not connected to any external network and everything seems to operate as expected.

As I requested in https://github.com/openthread/ot-br-posix/issues/1359#issuecomment-1117494691, can you help provide more diagnostic information? For example, what are the outputs of the following commands on both the border router and end device:
1. state
2. ipaddrs
3. netdata show

Have you tried pinging the Raspberry Pi from the Thread device?

**Comment by samuelAN-GH** [comment]
Hi,

I can confirm you that as soon as the rpi is disconnected from ethernet and rebooted, the coap communication fails.

However, I have no ot cli available on the end devices, so it is complicated at this stage to request states from the end devices...

In this case I have only one end-device connected on the thread network.

Here are the output of commands from the leader (which is the border router) : 

pi@***:~ $ sudo ot-ctl state
leader
Done

pi@***:~ $ sudo ot-ctl ipaddr
fd0c:e3bf:3a9:5b1c:6270:e939:6b73:8b3c
fdde:ad00:beef:0:0:ff:fe00:fc00
fdde:ad00:beef:0:0:ff:fe00:ec00
fdde:ad00:beef:0:8079:b54e:d48a:e185
fe80:0:0:0:243b:25fe:f6b7:9f4
Done

pi@***:~ $ sudo ot-ctl netdata show
Prefixes:
fd0c:e3bf:3a9:5b1c::/64 paos med fffe
Routes:
2a02:2788:3e4:a60::/64 s med fffe
2a02:2788:3e4:a60::/64 s med ec00
Services:
44970 01 0104b000000e10 s fc10
44970 5d fddead00beef00008079b54ed48ae185d11f s fc11
44970 5d fddead00beef00008079b54ed48ae185d11f s fc11
Done

**Comment by jwhui** [comment]
What IPv6 address is the Thread device using to send CoAP messages to?

Are you able to ping the IPv6 addresses on the Thread device from the border router?

**Comment by samuelAN-GH** [comment]
To be complete, I have retrieved the same informations when the RPI is not connected to ethernet : 

pi@***:~ $ sudo ot-ctl state
leader
Done

pi@***:~ $ sudo ot-ctl ipaddr
fd0c:e3bf:3a9:5b1c:6270:e939:6b73:8b3c
fdde:ad00:beef:0:0:ff:fe00:fc00
fdde:ad00:beef:0:0:ff:fe00:ec00
fdde:ad00:beef:0:8079:b54e:d48a:e185
fe80:0:0:0:243b:25fe:f6b7:9f4
Done

pi@***:~ $ sudo ot-ctl netdata show
Prefixes:
fd0c:e3bf:3a9:5b1c::/64 paos med fffe
Routes:
2a02:2788:3e4:a60::/64 s med fffe

Services:
44970 01 0104b000000e10 s fc10
44970 5d fddead00beef00008079b54ed48ae185d11f s fc11
44970 5d fddead00beef00008079b54ed48ae185d11f s fc11
Done

The ipv6 used is : fd0c:e3bf:3a9:5b1c:6270:e939:6b73:8b3c

The ping of the end device does not seem to work nevertheless...

**Comment by samuelAN-GH** [comment]
I am wondering if the issue is not linked to the DNS service discovery, which is used by the end devices to gather the IP address of the border router..

**Comment by jwhui** [comment]
DNS-SD should have no bearing on whether or not you can ping your Thread device.

Can you see if the Thread device is attached to your border router in any way? The output of `neighbor table` will list directly connected Thread neighbors.

**Comment by samuelAN-GH** [comment]
Yes, the device is correctly listed in the router table (the end device is configured as a router).

Additionally,  I have some debug leds on the end device which confirm that the device state is "connected".

**Comment by jwhui** [comment]
Are you able to ping the Thread device from the border router using multicast addresses like `ff02::1` and `ff03::1`?

**Comment by samuelAN-GH** [comment]
Yes, I am able to ping on both multicast address correclty (delay 35ms).

**Comment by jwhui** [comment]
> Yes, I am able to ping on both multicast address correclty (delay 35ms).

Are you able to ping the IPv6 source address(es) that are returned in the replies?

BTW, it would be helpful if you generally provided more information, such as the commands you tried and the output of the commands. It's very difficult to diagnose without visibility.

**Comment by samuelAN-GH** [comment]
Hi,

Sorry but since the RPI is in isolated mode, I am controlling it using a local display without SSH remote connection, so it is not easy to copy/paste the command lines. I have manually written the outputs here ;

```
sudo ot-ctl ping ff02::2
16 bytes from fe80:0:0:0:c48:ed8a:1dd2:32bf: icmp_seq=1 hlim=64 time=35ms
1 packets transmitted, 1 packet received. Round-trip min/avg/max = 35/35.0/35 ms.
Done

sudo ot-ctl ping ff03::2
16 bytes from fdde:ad00:beef:0:f3cf:dd30:f9dd:ca64:  icmp_seq=2 hlim=64 time=38ms
1 packets transmitted, 1 packet received. Round-trip min/avg/max = 38/38.0/38 ms.
Done

sudo ot-ctl ping ff02::1
16 bytes from fe80:0:0:0:c48:ed8a:1dd2:32bf: icmp_seq=3 hlim=64 time=35ms
1 packets transmitted, 1 packet received. Round-trip min/avg/max = 35/35.0/35 ms.
Done

sudo ot-ctl ping ff03::1
16 bytes from fdde:ad00:beef:0:f3cf:dd30:f9dd:ca64:  icmp_seq=4 hlim=64 time=38ms
1 packets transmitted, 1 packet received. Round-trip min/avg/max = 38/38.0/38 ms.
Done

sudo ot-ctl ping fe80:0:0:0:c48:ed8a:1dd2:32bf:
16 bytes from fe80:0:0:0:c48:ed8a:1dd2:32bf:  icmp_seq=5 hlim=64 time=39ms
1 packets transmitted, 1 packet received. Packet-loss = 0.0%. Round-trip min/avg/max = 39/39.0/39 ms.
Done

sudo ot-ctl ping fdde:ad00:beef:0:f3cf:dd30:f9dd:ca64:
16 bytes from fdde:ad00:beef:0:f3cf:dd30:f9dd:ca64:  icmp_seq=6 hlim=64 time=38ms
1 packets transmitted, 1 packet received. Packet-loss = 0.0%. Round-trip min/avg/max = 38/38.0/38 ms.
Done
```

**Comment by samuelAN-GH** [comment]
Could the issue be linked with avahi daemon? Maybe avahi (for a unknown reason) is not able to advertise the service on eth0 if it is not wired on a gateway... ?

**Comment by samuelAN-GH** [comment]
Hi,

Some advance : the ip that I was exposing to the avahi service was not the correct one. In fact, the adress :

fd0c:e3bf:3a9:5b1c:6270:e939:6b73:8b3c

Does not exist anymore if the rpi is disconnected from the ethernet. Consequently, the avahi service cannot advertise any adress in this case to the end device.

I have modified the avahi service to advertise the mesh-local EID of the border router. 

In this case, it is working, even without ethernet connection. HOWEVER, when there is not ethernet connection, i have a lot of timeouts (error -65536) in the dns process when I check the otbr-agent logs. It seems that the dns resolve process in this case is very slow..

**Comment by jwhui** [comment]
Rather than publishing the service via avahi, can you publish using SRP instead? See [src/cli/README_SRP.md](https://github.com/openthread/openthread/blob/main/src/cli/README_SRP.md) for more detail.

The reason is that avahi is used for publishing services on an infrastructure interface using mDNS. SRP is used for publishing services on a Thread network.

**Comment by samuelAN-GH** [comment]
Hi Jonathan,

Thanks for your answer.

I've read the link, but how can I define the service at the SRP server side ?

I have the impression that it is only possible to do it at client side, but my end devices are not connected through a CLI, or maybe do I have to do it using the openthread stack...? if so, do you have any example of service registering from client side using openthread stack?

Thanks

**Comment by jwhui** [comment]
Service Registration Protocol (SRP) is a mechanism used to publish services with DNS-based Service Discovery. If I understand properly, you just need to publish the service on the border router to send CoAP messages to. My suggestion was to publish the same service using SRP rather than avahi. Since you are on the border router, I assume you can simply use the OpenThread CLI.

Your Thread devices should be able to DNS to resolve the service, in the same way as when the border router was publishing the service via avahi. If your Thread devices are already performing DNS queries, then they should continue to do the same even when the border router is publishing the service via SRP.

[src/cli/README_SRP.md](https://github.com/openthread/openthread/blob/main/src/cli/README_SRP.md) already includes an example of how to publish the service via the OpenThread CLI. The [OpenThread Border Router codelab](https://openthread.io/codelabs/openthread-border-router#0) provides another example.

The OpenThread CLI also serves as an example user of OpenThread APIs. If you look through the OpenThread CLI implementation, you should see that it simply makes calls to OpenThread APIs.

**Comment by samuelAN-GH** [comment]
Thanks for your answer

My border router node, which is accessible via CLI is the srp server. In all the examples, a srp service registration can only be done from a srp client, but not by the server itself.

My end devices are using srp client, but they do not have a CLI interface.

This is why I think that if I want to use srp I need to register the service from one client using the openthread stack direclty.. or I am wrong with something...

Thanks

**Comment by samuelAN-GH** [comment]
Hi,

I have done the modification by adding SRP client option and reinstalling the OTBR.

Everything is OK and I get the following response to the client service command (on the OTBR side) : 

```
> srp client service
instance:"ot-service", name:"_ipps._tcp", state:Registered, port:12345, priority:0, weight:0
Done
```

However, on the thread end device, when I make a : 

`otDnsClientBrowse(client->instance, client->service_name, dns_result_callback, client, NULL);`

where :

- The client is the SRP client (which is running <-> `otSrpClientIsRunning(client->instance) == 1`)
- service_name is "ot-host.default.service.arpa"

The otDnsClientBrowse returns a TimeOut error (the dns_result_callback is executed with error = timeOutError).

I have the same kind of error if I replace the service_name by `"_ipps._tcp"`.
I have also the same error when I replace `otDnsClientBrowse` by `otDnsClientResolveAddress`.

I am not able to make a "dns resolve" as you mention because I have no CLI access to my Thread End device, but I assume that the otDnsClientBrowse should be equivalent ?

Thanks

**Comment by jwhui** [comment]
The DNS client is probably not configured with an appropriate DNS server address.

You can auto-configure the DNS server address by enabling the SRP client's auto start mode - see [`otSrpClientEnableAutoStartMode()`](https://openthread.io/reference/group/api-srp#otsrpclientenableautostartmode).

**Comment by samuelAN-GH** [comment]
Hi Jwhui,

Actually, I already do that : 

`otSrpClientEnableAutoStartMode(instance, srp_client_autostart_callback, &_client);`

Where `instance` is my OT instance.
The callback is correclty called without any error.

Then, I check if the client is well started with 

`otSrpClientIsRunning(client->instance);`

before calling the `otDnsClientBrowse`.

By the way, is there any way to get the SRP server address and print it in char format? Because in this case, since I just want to get the IP address of the Border router device (which is also the SRP server), I would not need to make any DNS browse...

Thanks for your help

**Comment by abtink** [comment]
> By the way, is there any way to get the SRP server address and print it in char format?

On SRP client side, you can use public API to get the selected server address:
- `const otSockAddr *otSrpClientGetServerAddress(otInstance *aInstance);`

This is also provided in CLI `srp client server` (full socket addr) or `srp client server address` or `srp client server port` (for address and port seperately) -> [README_SRP_CLIENT#server](https://github.com/openthread/openthread/blob/c8556dfd6689abc2ff01e7b7d434c8c221ac32a2/src/cli/README_SRP_CLIENT.md#server)

**Comment by jwhui** [comment]
Closing stale issue.
