### ISSUE TITLE
otbr docker failing to run on Ubuntu 20

### ISSUE THREAD

**Issue by jazevedo-trd** [openthread/ot-br-posix#1360]
**Describe the bug** A clear and concise description of what the bug is.
Hello,

I am trying to run the otbr docker with RCP on  a Ubuntu Server 20.04.4 using the command from the OTBR guide https://openthread.io/guides/border-router/docker:

docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 --dns=127.0.0.1 -it --volume /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr --radio-url spinel+hdlc+uart:///dev/ttyACM0

I get the following error:
+ sudo sysctl --system
* Applying /etc/sysctl.d/10-console-messages.conf ...
kernel.printk = 4 4 1 7
* Applying /etc/sysctl.d/10-ipv6-privacy.conf ...
net.ipv6.conf.all.use_tempaddr = 2
net.ipv6.conf.default.use_tempaddr = 2
* Applying /etc/sysctl.d/10-kernel-hardening.conf ...
kernel.kptr_restrict = 1
* Applying /etc/sysctl.d/10-link-restrictions.conf ...
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /etc/sysctl.d/10-magic-sysrq.conf ...
kernel.sysrq = 176
* Applying /etc/sysctl.d/10-network-security.conf ...
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.tcp_syncookies = 1
* Applying /etc/sysctl.d/10-ptrace.conf ...
kernel.yama.ptrace_scope = 1
* Applying /etc/sysctl.d/10-zeropage.conf ...
vm.mmap_min_addr = 65536
* Applying /etc/sysctl.d/60-otbr-accept-ra.conf ...
net.ipv6.conf.eth0.accept_ra = 2
net.ipv6.conf.eth0.accept_ra_rt_info_max_plen = 64
* Applying /etc/sysctl.d/60-otbr-ip-forward.conf ...
net.ipv6.conf.all.forwarding = 1
net.ipv4.ip_forward = 1
* Applying /etc/sysctl.conf ...
+ nat64_start
+ with NAT64
+ local value
++ printenv NAT64
+ value=1
+ [[ -z 1 ]]
+ [[ 1 == 1 ]]
+ with DOCKER
+ local value
++ printenv DOCKER
+ value=1
+ [[ -z 1 ]]
+ [[ 1 == 1 ]]
+ service tayga start
 * Starting userspace NAT64 tayga                                                                                                                                     [fail]
+ die 'Failed to start tayga'
+ echo ' *** ERROR:  Failed to start tayga'
 *** ERROR:  Failed to start tayga
+ exit 1
tail: cannot open '/var/log/syslog' for reading: No such file or directory
tail: no files remaining

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
ot-br-posix-https://github.com/openthread/ot-br-posix/commit/a4ec0d4716c87a4a6c4206d0fca27a74cf69e39e
2. IEEE 802.15.4 hardware platform
 nrf52840 USB Dongle
3. Build steps
docker pull openthread/otbr:latest
sudo modprobe ip6table_filter
docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 --dns=127.0.0.1 -it --volume /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr --radio-url spinel+hdlc+uart:///dev/ttyACM0

I am following the tutorial from openthread; therefore, I was not expecting this error. Can you help me understand what could be happening to cause this?

**Comment by jwhui** [comment]
This seems similar to #1360.

Are you able to test this using a Raspberry Pi using a fresh image of `2021-05-07-raspios-buster-armhf-lite`?

**Comment by jazevedo-trd** [comment]
I have already seen issue #1327, and I think it does not apply to my situation as I am trying to run the otbr docker on a PC running Ubuntu and not on a Raspberry Pi.

**Comment by thavlik** [comment]
Have you tried running `sudo modprobe ip6table_filter` ? It fixed it for me, though I am on raspberry pi. I missed that step at https://openthread.io/guides/border-router/docker/run

> **Note:** Raspberry Pi and Linux users, if you haven't done so already, make sure to run `sudo modprobe ip6table_filter` for OTBR firewall support. This allows OTBR scripts to create rules inside the Docker container before **otbr-agent** starts.

**Comment by gerhardtgao** [comment]
hello, @jwhui , @jazevedo-trd, tayga needs more than 2 seconds to start on slow raspberry pi, we need to add a line
STASRTTIME=10
in pi's /etc/default/tayga to wait for it. (But maybe another value smaller is better for otbr's user experience.)

for more, see line 58~65 of pi's /etc/init.d/tayga:

    49	# Default options, these can be overriden by the information
    50	# at /etc/default/$NAME
    51	DAEMON_OPTS="--nodetach"          # Additional options given to the server
    52	
    53	DIETIME=10              # Time to wait for the server to die, in seconds
    54	                        # If this value is set too low you might not
    55	                        # let some servers to die gracefully and
    56	                        # 'restart' will not work
    57	
    58	STARTTIME=2             # Time to wait for the server to start, in seconds
    59	                        # If this value is set each time the server is
    60	                        # started (on start or restart) the script will
    61	                        # stall to try to determine if it is running
    62	                        # If it is not set and the server takes time
    63	                        # to setup a pid file the log message might
    64	                        # be a false positive (says it did not start
    65	                        # when it actually did)


we can fix this in nat64_install()
