### ISSUE TITLE
Review version checks in CMakeLists.txt

### ISSUE THREAD

**Issue by suveshpratapa** [openthread/ot-br-posix#1392]
After update to protocol version 1.3, are the following two blocks of code still correct in [`third_party/openthread/CMakeLists.txt`?](https://github.com/openthread/ot-br-posix/blob/main/third_party/openthread/CMakeLists.txt#L69)

```
if (OTBR_BACKBONE_ROUTER)
    set(OT_THREAD_VERSION 1.2 CACHE STRING "Backbone Router requires Thread 1.2 or higher" FORCE)
    set(OT_BACKBONE_ROUTER ON CACHE BOOL "Enable Backbone Router feature in OpenThread" FORCE)
    set(OT_SERVICE ON CACHE BOOL "Backbone Router requires Thread network service" FORCE)
endif()

if (OT_THREAD_VERSION STREQUAL "1.2")
    set(OT_MLR ON CACHE BOOL "Enable Thread 1.2 MLR by default")
endif()
```

Should we have it instead be:
```
if (OTBR_BACKBONE_ROUTER)
    set(OT_THREAD_VERSION 1.3 CACHE STRING "Backbone Router requires Thread 1.2 or higher" FORCE)
    set(OT_BACKBONE_ROUTER ON CACHE BOOL "Enable Backbone Router feature in OpenThread" FORCE)
    set(OT_SERVICE ON CACHE BOOL "Backbone Router requires Thread network service" FORCE)
endif()

if (NOT OT_THREAD_VERSION STREQUAL "1.1")
    set(OT_MLR ON CACHE BOOL "Enable Thread 1.2 MLR by default")
endif()
```

**Comment by jwhui** [comment]
@suveshpratapa , thanks for raising this issue. I agree that we need to make further updates.

One comment on the proposal for `OTBR_BACKBONE_ROUTER`. Given that OpenThread now defaults to 1.3, how about simply removing the `OT_THREAD_VERSION` line? Something lie:

```
if (OTBR_BACKBONE_ROUTER)
    set(OT_BACKBONE_ROUTER ON CACHE BOOL "Enable Backbone Router feature in OpenThread" FORCE)
    set(OT_SERVICE ON CACHE BOOL "Backbone Router requires Thread network service" FORCE)
endif()

if (NOT OT_THREAD_VERSION STREQUAL "1.1")
    set(OT_MLR ON CACHE BOOL "Enable Thread 1.2 MLR by default")
endif()
```

**Comment by jwhui** [comment]
> I agree about the version! I can raise a PR to make this change.

Great, thanks!

> Quick question: Do we still want to disable DUA by default for 1.2?

I think we need to enable `OPENTHREAD_CONFIG_TMF_PROXY_DUA_ENABLE` by default on >= 1.2. But we should keep `OTBR_DUA_ROUTING` and `OT_BACKBONE_ROUTER_DUA_NDPROXYING` to off by default. Thoughts?

**Comment by suveshpratapa** [comment]
I agree that `OPENTHREAD_CONFIG_TMF_PROXY_DUA_ENABLE` should always be enabled so we can always register DUA for our MTD children (required as per spec).

As for `OTBR_DUA_ROUTING` and `OT_BACKBONE_ROUTER_DUA_NDPROXYING`, my thought is that these are required for 1.2 OTBR certification, so even if they are optional on a border router per spec, it would be nice to enable these settings by default. I guess we can also tie them to a `REFERENCE_DEVICE` check, as a compromise.
