### ISSUE TITLE
not found ipv6 addr on OTBR

### ISSUE THREAD

**Issue by seagullanddog** [openthread/ot-br-posix#1405]
hi ,everyone
    I refer to the documentation guide "**https://openthread.google.cn/guides/border-router/mdns-discovery**" using the command "**dns-sd -L "OpenThread BorderRouter" _meshcop._udp local**" for mDNS discovery, but it doesn't appear This is "OpenThread\032BorderRouter._meshcop._udp.local" described in the documentation guide, as As shown below .

**Lookup OpenThread BorderRouter._meshcop._udp.local
DATE: ---Thu 02 Jun 2022---
 8:50:00.701  ...STARTING...**

my environment: ubuntu22.04.
OTBR:running normally.
RCP: running normally .

I am very much looking forward to your help, thank you!

**Comment by jwhui** [comment]
@seagullanddog , thanks for raising this issue.

I believe this is due to #1370, which now appends the last 2 bytes of the Extended Address to the service instance name.

One thing you can try is browsing on the service type. For example:
```
dns-sd -B _meshcop._udp local
```

**Comment by seagullanddog** [comment]
> @seagullanddog , thanks for raising this issue.
> 
> I believe this is due to #1370, which now appends the last 2 bytes of the Extended Address to the service instance name.
> 
> One thing you can try is browsing on the service type. For example:
> 
> ```
> dns-sd -B _meshcop._udp local
> ```

Thanks jwhui, I refer to your description to execute the command "ns-sd -L "OpenThread BorderRouter #E224" _meshcop._udp local" and print the following, which should be normal
**Lookup OpenThread BorderRouter #E224._meshcop._udp.local
DATE: ---Thu 02 Jun 2022---
 9:30:40.857  ...STARTING...
 9:30:41.028  OpenThread\032BorderRouter\032#E224._meshcop._udp.local. can be reached at haiou-virtual-machine.local.:49153 (interface 4)
 rv=1 vn=OpenThread mn=BorderRouter nn=OpenThreadDemo xp=\\x11\\x11\\x11\\x11\"\"\"\" tv=1.2.0 xa=j\(��_x�\$ sb=\\\x00\\\x00\\x01� at=\\\x00\\\x00\\\x00\\\x00\\\x00\\\x00\\\x00\\x01 pt=3��\\x1D sq=\\x15 bb=� dn=DefaultDomain**

But when I execute the command "dns-sd -G v4/v6 haiou-virtual-machine.local", the relevant ipv6 is not found, and the print is as follows
**DATE: ---Thu 02 Jun 2022---
 9:33:16.535  ...STARTING...
Timestamp     A/R    Flags if Hostname                               Address                                      TTL
 9:33:16.535  Add 40000003  4 haiou-virtual-machine.local.           0000:0000:0000:0000:0000:0000:0000:0000%<0>  1   No Such Record
 9:33:16.535  Add 40000002  4 haiou-virtual-machine.local.           172.17.0.1                                   120**

Hope to get your help again thanks

**Comment by jwhui** [comment]
Closing stale issue.
