### ISSUE TITLE
OTBR error: "Failed to process Discovery Request: Security" 

### ISSUE THREAD

**Issue by OlivierGre** [openthread/ot-br-posix#1407]
Hi,
I have an OTBR and a Thread device. I'm doing Thread commissioning with an Android phone (used as commissioner) and then I exchange some datagrams between the Thread device (freshly commissioned) and the Android phone.

I have noticed that the commissioning sometimes fails. I think that it is due to the following error, seen on the OTBR. Would you know in which cases the error "Failed to process Discovery Request: Security" happens?

Thank you
Regards

```
Jun 02 11:03:40 raspberrypi otbr-agent[743]: 01:25:34.257 [INFO]-MLE-----: Receive Discovery Request (fe80:0:0:0:a4bc:d717:9d0b:8>
Jun 02 11:03:40 raspberrypi otbr-agent[743]: 01:25:34.257 [NOTE]-CLI-----: Output: ~ Discovery Request from a6bcd7179d0b8a84: ver>
Jun 02 11:03:40 raspberrypi otbr-agent[743]: 01:25:34.257 [WARN]-MLE-----: Failed to process Discovery Request: Security
```

**Comment by jwhui** [comment]
@OlivierGre , this error typically indicates that the Network Data does not include a Commissioning Dataset TLV where the Steering Data value is non-zero.

Relevant code:
- https://github.com/openthread/openthread/blob/9bb09e74e2bfddb8e5272cc8ade6e0fa4f8125f0/src/core/thread/mle_router.cpp#L3032
- https://github.com/openthread/openthread/blob/9bb09e74e2bfddb8e5272cc8ade6e0fa4f8125f0/src/core/thread/network_data_leader.cpp#L456

**Comment by OlivierGre** [comment]
OK thank you Jonathan

**Comment by jwhui** [comment]
> @jwhui Jonathan: A side question. Once a Thread device commissioned, what is the way to disconnect it from Thread network? I'm interested because I want to re-execute the commissioning (for demo purprose). Thanks

Thread does not provide a way to remotely remove a device from the Thread network. You can add some application logic to trigger the equivalent of the `factoryreset` CLI command.

**Comment by OlivierGre** [comment]
Ok thank you

**Comment by jwhui** [comment]
Closing stale issue.

**Comment by Hinalikp** [comment]
Hello,  

I am using esp32h2beta2(ot_cli code) as a joiner and I have made commissioner (esp32s3(ot_br code)+esp32h2beta2(ot_rcp code))OTBR. 
esp-idf =  v5.0.6 with command lines


I am getting this warning continuously when i try to connect joiner to the commissioner: 
> joiner start J01NME
Done
> I(238231) OPENTHREAD:[N] MeshForwarder-: Failed to send IPv6 UDP msg, len:56, chksum:356a, ecn:no, to:None, sec:no, error:Abort, prio:net
I(238231) OPENTHREAD:[N] MeshForwarder-:     src:[fe80:0:0:0:f8f9:8139:2035:b6c5]:19788
I(238241) OPENTHREAD:[N] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
Join failed [Security]
W(247511) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState 
W(274211) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(302401) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(338981) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(362821) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(397621) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(426181) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(459351) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(490131) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(524571) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(557631) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(596081) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(621341) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(651341) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(689561) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
W(725571) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState

**Comment by Hinalikp** [comment]
@jwhui have you solved the issue of security? If you have, would you please share the solution with me. It would be really helpful.

**Comment by jwhui** [comment]
> @jwhui have you solved the issue of security? If you have, would you please share the solution with me. It would be really helpful.

If your issue is related to the original post: https://github.com/openthread/ot-br-posix/issues/1407#issue-1258062725

Then see above comment: https://github.com/openthread/ot-br-posix/issues/1407#issuecomment-1145091364
