### ISSUE TITLE
Join failed [NotFound]?

### ISSUE THREAD

**Issue by seagullanddog** [openthread/ot-br-posix#1411]
hi , everyone
     I have some problems and don't know how to solve it, its process is as follows.

       First, I use mdns discover reference link guide "https://openthread.google.cn/guides/border-router/mdns-discovery"ipv6 address is not found when I execute command "sudo dns-sd -G v4/v6 haiou-virtual-machine.local", the prompt is as follows:
**DATE: ---Mon 06 Jun 2022---
10:33:17.269  ...STARTING...
Timestamp     A/R    Flags if Hostname                               Address                                      TTL
10:33:17.269  Add 40000003  4 haiou-virtual-machine.local.           0000:0000:0000:0000:0000:0000:0000:0000%<0>  1   No Such Record
10:33:17.269  Add 40000002  4 haiou-virtual-machine.local.           172.17.0.1                                   120**

     Second, I have confirmed that otbr-agent and otbr-web are running normally and the thread network has been established, execute the command "sudo ot-ctl commissioner start"
  "sudo ot-ctl commissioner joiner add 588e81fffeb2a0d5 J01NME"
There is no prompt error, refer to the article "https://sunmaysky.blogspot.com/2020/08/running-openthread-border-router-and.html".

      Third, execute the commands "ifconfig up" and "joiner start J01NME" on the terminal of the FTD device, and the log prints as follows:
**ifconfig up
Done
joiner start J01NME
Done
Join failed [NotFound]**

       Fourth, execute the command "scan", the prompt is as follows:
[11:14:51.149]收←◆scan
| J | Network Name     | Extended PAN     | PAN  | MAC Address      | Ch | dBm | LQI |
+---+------------------+------------------+------+------------------+----+-----+-----+
| 0 |                  | 0000000000000000 | 1235 | d6a6c114ed57d9e5 | 15 | -31 | 255 |
Done

environment(OTBR):  ubuntu22.04  vmware 
hareware(RCP FTD): EFR32MG21A

 I need your help ,thanks

**Comment by jwhui** [comment]
Closing stale issue.
