### ISSUE TITLE
Not able to build the otbr-web

### ISSUE THREAD

**Issue by maunishpatel1** [openthread/ot-br-posix#1416]
I am building the otbr-agent in yocto using standard **otbr_git.bb.** I have enabled the macro **"-DOTBR_WEB=ON"** for building the otbr-web. But it is giving the error:

 **"cd /home/dipkumar/Project/Centauri/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/build/src/web/web-service/frontend && cp /home/dipkumar/Project/Centauri/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/git/src/web/web-service/frontend/package.json . && npm install
| /bin/sh: 1: npm: not found
"**
I have used the below commit id for building the otbr-agent.
"**36db8891576a6ed571ad319afca734c5288c4cd9**"

I have modified the otbr_git.bb as per my requirement, I am attaching the same in a zip file.
[otbr-rcp_git.zip](https://github.com/openthread/ot-br-posix/files/8851974/otbr-rcp_git.zip)

**Comment by jwhui** [comment]
Did you try adding `npm` to the `DEPENDS` list?

**Comment by maunishpatel1** [comment]
Yes, I have added nodejs and jansson in DEPENDS but it is giving the same error.

**Comment by maunishpatel1** [comment]
Yes, It's working by inhering "npm-install" and adding nodejs in DEPENDS. 
Actually, the problem is, that I am inhering the npm package with the name  "npm" instead of "npm-install".
Thanks for the help.

**Comment by jwhui** [comment]
@maunishpatel1 , great to hear you got it working.
