### ISSUE TITLE
[Openwrt][OTBR] openthread-br package build failed with OTBR_WEB and OTBR_MDNS option

### ISSUE THREAD

**Issue by BT8385** [openthread/ot-br-posix#1418]
Hello guys, I'm working on the OTBR based on the OpenWrt, and there are two problems I can't figure out, so I put them on the issue to get some advice or help.
The first one is that I can't build the `openthread-br` with the `OTBR_WEB` option， the following log shows the failed reason, then I use a patch file to change the rules in the `CMake` file `src/web/web-service/frontend/CMakeLists.txt` to fix it, the building work is ok but the web GUI does not work, I can access in the web GUI, but it can't form the thread dataset,  the status information is also blank. I checked the status of the thread it's ok, and I can form it by the command.

```
make[5]: Entering directory '/home/ubuntu/ow/build_dir/target-mipsel_24kc_musl/openthread-br'
cp: '/home/ubuntu/ow/build_dir/target-mipsel_24kc_musl/openthread-br/src/web/web-service/frontend/package.json' and './package.json' are the same file
make[5]: *** [src/web/web-service/frontend/CMakeFiles/otbr-web-frontend.dir/build.make:76: src/web/web-service/frontend/CMakeFiles/otbr-web-frontend] Error 1
```

The second one is about the mDNS, in the `Makefile` of the `openthread-br`, setting the option `OTBR_MDNS` to the `avahi` is ok, but when I set it to the value `mDNSResponder`, it shows me the fatal error: `dns_sd.h: No such file or directory`, then I installed the `libavahi-compat-libdnssd-dev`, but it does not work. So I'm a little confused that the mDNS option of `mDNSResponder` can work on the OpenWRT right or not?

commit info: 4b04548
OpenWRT Version: 21.02
Build Environment: Ubuntu 20.04LTS

Make File:

```
include $(TOPDIR)/rules.mk

PKG_NAME:=openthread-br
PKG_VERSION:=1.0

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/openthread/ot-br-posix.git

PKG_SOURCE_DATE:=2022-05-14
PKG_SOURCE_VERSION:=4b045485919f80a58258925134b807ee4a6bca99

PKG_MIRROR_HASH:=skip

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/cmake.mk

define Package/$(PKG_NAME)
	SECTION:=base
	CATEGORY:=Network
	TITLE:=$(PKG_NAME)
	DEPENDS:=+jsoncpp +boost +boost-filesystem +boost-system \
			+libstdcpp +libjson-c +libubus +libblobmsg-json \
			+libavahi-client +kmod-tun +libreadline +libnetfilter-queue +libavahi-compat-libdnssd
endef

define Package/$(PKG_NAME)/description
    A Thread border router for POSIX-based platforms.
endef

CMAKE_OPTIONS += \
	-DOT_THREAD_VERSION="1.2" \
	-DBUILD_TESTING=OFF \
	-DOT_BORDER_AGENT=ON \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DOT_POSIX_SETTINGS_PATH="\"/usr/lib/thread\"" \
	-DOTBR_MDNS="mDNSResponder" \
	-DOT_READLINE=OFF \
	-DOT_BORDER_ROUTER=ON \
	-DOT_SERVICE=ON \
	-DOT_BACKBONE_ROUTER=OFF \
	-DOTBR_OPENWRT=ON \
	-DOTBR_REST=ON \
	-DOTBR_WEB=ON \
	-DOT_RCP=ON 

define Package/$(PKG_NAME)/install
	$(INSTALL_DIR) $(1)/etc/init.d
	$(INSTALL_BIN) ./files/otbr-agent.init $(1)/etc/init.d/otbr-agent
	$(INSTALL_BIN) ./files/otbr-web.init $(1)/etc/init.d/otbr-web

	$(INSTALL_DIR) $(1)/usr/sbin
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/ot-ctl $(1)/usr/sbin
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/otbr-agent $(1)/usr/sbin
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/otbr-web $(1)/usr/sbin
	
	$(INSTALL_DIR) $(1)/usr/share/otbr-web
	$(CP) $(PKG_INSTALL_DIR)/usr/share/otbr-web/* $(1)/usr/share/otbr-web/


endef

$(eval $(call BuildPackage,$(PKG_NAME)))
```

Thanks

**Comment by caipiblack** [comment]
Hi,

**For the question about `mDNSResponder`:**

1. You need to set `-DOTBR_MDNS="mDNSResponder"` in `CMAKE_OPTIONS`
2. You need to set `+mdnsresponder` in `DEPENDS`
3. On the target you will need `mdnsd`, `mdns-utils` and `mdnsresponder`

Note that you will have to update the `mdnsresponder` Makefile if you want to use the same version as the version used in `ot-br-posix` ([see the bootstrap script](https://github.com/openthread/ot-br-posix/blob/main/script/bootstrap))

**For the question about `OTBR_WEB`:**

First, when you build for OpenWRT, note that the web interface is integrated into the web interface of OpenWRT.

But if you really want OTBR_WEB you can build it. But when I see all the dependencies required by the dependencies itself I think it's better to use the web integration in OpenWRT interface. 

![image](https://user-images.githubusercontent.com/29680146/173130128-c9c71186-0888-41e6-9e3a-81f6879a21b4.png)

If you really wants OTBR_WEB:

1. You need to set  `-DOTBR_WEB=ON` in `CMAKE_OPTIONS`
2. You need to set  `+jsoncpp +boost-libs` in `DEPENDS`
3. If you have issues like undefined references to boost::filesystem, add this: `TARGET_CFLAGS += -lboost_filesystem` 
4. You need to install npm on your computer (this is used to sync/download js files)  ([see the bootstrap script](https://github.com/openthread/ot-br-posix/blob/main/script/bootstrap))
5. As I think it need a lot of dependencies, I only try to build. So you have to see wich packages you need to install on the target. Just try to install openthread-br and it will tell you..

**Global notes:**

It's possible that you need to install feeds on the SDK:

```
./scripts/feeds install jsoncpp
./scripts/feeds install boost-libs
./scripts/feeds install mdnsresponder
```

**Comment by jwhui** [comment]
Closing stale issue.
