### ISSUE TITLE
On the otbr side, the SRP client registration information was lost after the the otbr-agent restarted.

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/ot-br-posix#1424]
On the otbr side, the SRP client registration information was lost after the the otbr-agent restarted.

There may be two ways to solve this problem:
1 The otbr-agent save the SRP registration information persistently and recover after restart.
2 SRP client is responsible to re-register. SRP client need to know when to re-register. Maybe otbr-agent can use a new port which is diffrent from previous one to servers SRP server and SRP client should re-register if there is a new SRP server.

If there is a mechanism to ensure that the SRP server port must be different from the previous one? If so, I think the second option works.

ot-br-posix git commit id: 5be35949c6f1fd4cc3a8e63169cec6a2211135a4

**Comment by wgtdkp** [comment]
Which address mode is the SRP server running?
```
/**
 * This enumeration represents the address mode used by the SRP server.
 *
 * Address mode specifies how the address and port number are determined by the SRP server and how this info is
 * published in the Thread Network Data.
 *
 */
typedef enum otSrpServerAddressMode
{
    OT_SRP_SERVER_ADDRESS_MODE_UNICAST = 0, ///< Unicast address mode.
    OT_SRP_SERVER_ADDRESS_MODE_ANYCAST = 1, ///< Anycast address mode.
} otSrpServerAddressMode;
```
https://github.com/openthread/openthread/blob/b2132a903162be76eb4ea8a107e82c4e0737525f/include/openthread/srp_server.h#L145-L156

We are already selecting a different port (option 2) under unicast mode:
```
void Server::SelectPort(void)
{
    mPort = kUdpPortMin;

#if OPENTHREAD_CONFIG_SRP_SERVER_PORT_SWITCH_ENABLE
    {
        Settings::SrpServerInfo info;

        if (Get<Settings>().Read(info) == kErrorNone)
        {
            mPort = info.GetPort() + 1;
            if (mPort < kUdpPortMin || mPort > kUdpPortMax)
            {
                mPort = kUdpPortMin;
            }
        }
    }
#endif

    LogInfo("Selected port %u", mPort);
}
```
https://github.com/openthread/openthread/blob/b2132a903162be76eb4ea8a107e82c4e0737525f/src/core/net/srp_server.cpp#L513-L533

------

We can't use a different port in anycast mode since all SRP server need to share the same port.

**Comment by jinpeng1989** [comment]
The address mode of the SRP server is OT_SRP_SERVER_ADDRESS_MODE_UNICAST .
![image](https://user-images.githubusercontent.com/97089879/173277719-4d467688-8ba2-474c-b189-c8fa6e9f562c.png)

In this mode, SRP server select server port between kUdpPortMin(53535) and kUdpPortMax(default 53554). When selecting a new port, next to the current port will be use. My question is , is the current port be saved? Where is it?

Sometimes the SRP server port changes after otbr-agent restart, sometimes id doesn't.

![image](https://user-images.githubusercontent.com/97089879/173282323-9de79fd5-26e8-4a5b-9f65-c9f96c1b2de7.png)

![image](https://user-images.githubusercontent.com/97089879/173282607-18f623ca-1b57-493d-9614-85fd3850e294.png)

**Comment by wgtdkp** [comment]
1. If no SRP service has been registered to the SRP server, the server won't select a new port.
```
#if OPENTHREAD_CONFIG_SRP_SERVER_PORT_SWITCH_ENABLE
        if (!mHasRegisteredAnyService && (mAddressMode == kAddressModeUnicast))
        {
            Settings::SrpServerInfo info;

            mHasRegisteredAnyService = true;
            info.SetPort(GetSocket().mSockName.mPort);
            IgnoreError(Get<Settings>().Save(info));
        }
#endif
```
https://github.com/openthread/openthread/blob/b2132a903162be76eb4ea8a107e82c4e0737525f/src/core/net/srp_server.cpp#L479-L488
2. The server port is saved in settings, keyed by [OT_SETTINGS_KEY_SRP_SERVER_INFO](https://github.com/openthread/openthread/blob/b2132a903162be76eb4ea8a107e82c4e0737525f/include/openthread/platform/settings.h#L73)

// @superwhd

**Comment by jinpeng1989** [comment]
OK. Thank you.
