### ISSUE TITLE
Unable to ping to external IPV6 address and vice versa

### ISSUE THREAD

**Issue by electroshell-asp** [openthread/ot-br-posix#1428]
Hello,

I build the full thread device using Silicon Labs EFR32MG12 as well as OTBR using RPi and EFR32MG12 RCP.
I convert the IPV4 address to IPV6 , prefix it with 64:ff9b and I try to ping form the node and it works well. For Eg 64:ff9b::808:808.
However I try to ping google IPV6 address from the node which is 2404:6800:4007:82a::2004 there is no response. I checked on TCP dump installed on RPi OTBR and monitored wpan0, I get " IP6 fd11:22::8a96:d5dd:27fa:bbaf > bom07s36-in-x04.1e100.net : ICMP6 echo request, id 5, seq 1, length 16". I don't get response on TCP dump as well. I need to get ping working to and from the external IPV6 network in order to work with CoAP from the cloud to the node. I am using eth0.
Kindly advise the configuration of router or node as required.

Thanks

**Comment by jwhui** [comment]
Closing stale issue.
