### ISSUE TITLE
NCP host OS

### ISSUE THREAD

**Issue by jumpingjackgazz** [openthread/ot-br-posix#1445]
Hi all,

I've been thru the documents describing NCP and RCP integration and as far as I understand both model need a Linux Host processor to run : ot-br-posix for RCP or wpantund for NCP.

Can you confirm my understanding ?
Is there any other model available ? Like a RTOS integration available...
Or Linux is a must have on host processor ?

ciao

**Comment by jwhui** [comment]
> Can you confirm my understanding ?

Yes, you are correct.

> Is there any other model available ? Like a RTOS integration available...
> Or Linux is a must have on host processor ?

Espressif ESP32 has an [OTBR with RCP integration using FreeRTOS](https://openthread.io/guides/border-router/espressif-esp32).

**Comment by jumpingjackgazz** [comment]
ok thx Jonathan !
