### ISSUE TITLE
Question: How to disable SLAAC?

### ISSUE THREAD

**Issue by Alex-T-Stark** [openthread/ot-br-posix#1447]
I'd like to disable SLAAC in ot-br-posix.
I'm currently running the latest main commit f8468a2963f9f8bae79d60aa633e953873049f5c

Commit 48e53dfb0e7672978b9209361ecbea1a5c904542 set SLAAC to always enabled.

I've tried flipping the CMake option in `third_party/openthread/CMakeLists.txt`:
`set(OT_SLAAC OFF CACHE BOOL "enable SLAAC" FORCE)` 
The bootstrap/setup scripts suceed in building & installing, but SLAAC remains enabled on reboot.

Hardware: RPi 3B+ & nRF52840 RCP

Is disabling SLAAC supported?

**Comment by abtink** [comment]
Yes. OT core SLAAC support can be enagled/disabled using this config
```
/**
 * @def OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE
 *
 * Define as 1 to enable support for adding of auto-configured SLAAC addresses by OpenThread.
 *
 */
#ifndef OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE
#define OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE 0
#endif
```

**Comment by Alex-T-Stark** [comment]
Great, thank you.

After adding `-DOPENTHREAD_CONFIG_IP6_SLAAC_ENABLE 0` to the openthread CMakeLists.txt targets, I got a build conflict with `OPENTHREAD_CONFIG_BORDER_ROUTING=1`
Setting `OTBR_BORDER_ROUTING=0` in the platform default resolved that, and SLAAC was properly disabled on the rebuild.
