### ISSUE TITLE
Build OTBR agent for Thread 1.2

### ISSUE THREAD

**Issue by OlivierGre** [openthread/ot-br-posix#1449]
I was so far working with a RCP using Thread 1.1.1 and I was building the OTBR agent with:

`INFRA_IF_NAME=wlan0 BACKBONE_ROUTER=0 BORDER_ROUTING=1 OTBR_OPTIONS="-DOT_THREAD_VERSION=1.1" ./script/setup `

I'm now moving to a RCP using Thread 1.2. I'm wondering if I should simply use :
`INFRA_IF_NAME=wlan0 ./script/setup `

or if I still need the other parameters (BACKBONE_ROUTER=0 BORDER_ROUTING=1 OTBR_OPTIONS="-DOT_THREAD_VERSION=1.2"). 

Can you please tell me?

Thank you

**Comment by jwhui** [comment]
It depends what git commit you are using.

The latest OpenThread main branch default for `OT_THREAD_VERSION` is `1.3` - see https://github.com/openthread/openthread/blob/dd631b2a1914b60223d527aafbca50b964cd9b7d/CMakeLists.txt#L105

**Comment by OlivierGre** [comment]
I'm using the latest version of openthread/ot-br-posix's main branch. So if I understand correctly, I should add OTBR_OPTIONS="-DOT_THREAD_VERSION=1.2" to force the usage of 1.2.  

Do I still need BACKBONE_ROUTER=0 BORDER_ROUTING=1  or was it specific to 1.1?

Thanks

**Comment by OlivierGre** [comment]
Ok thanks.
I have looked at examples/platforms/raspbian/default and I can see that BORDER_ROUTING and BACKBONE_ROUTER are enabled so I will build with :

`INFRA_IF_NAME=wlan0 ./script/setup`

**Comment by jwhui** [comment]
Yes, Thread 1.2 includes low-power enhancements that require an update to the RCP. I suggest updating your RCP to match the latest main branch as well.

**Comment by OlivierGre** [comment]
Ok, thank you Jonathan.

**Comment by OlivierGre** [comment]
@jwhui 
Hi Jonathan, 
Our RCP is not yet ready to include the low-power enhancements so I will have to build it with the flags to force the version 1.1 (this is what I was using so far).

A quick question about SRP: Will it work if my OTBR is configured for Thread 1.1?

Thank you
