### ISSUE TITLE
ot-br-posix submodule update

### ISSUE THREAD

**Issue by suveshpratapa** [openthread/ot-br-posix#1452]
Hi, checking to see when the next openthread submodule update can happen on this repo. There are some changes from the openthread repo that we'd like to pull ahead of Monday / next week's Matter SVE; so it would be nice for ot-br-posix to be sync.

**Comment by jwhui** [comment]
Dependabot submits PRs only a daily basis, but we can trigger a manual run at any time.

I just manually triggered it - see #1453.
