### ISSUE TITLE
The compilation in "release" mode fails (with a solution)

### ISSUE THREAD

**Issue by achsoftathome** [openthread/ot-br-posix#1477]
The compilation in "release" mode fails:
> Git commit id: 319e6eb3c1d51d5a0e7f97133a9ea87e0f4404ed
> Error report: At the end.

**To reproduce the problem:**
script/cmake-build \
-DCMAKE_BUILD_TYPE=RELEASE \
...

**A solution:**
A simple solution is to remove the intermediate variable (splitError) used to store the result, as done in the following function "TranslateDomain".

**The patch:**
```
index 6aeccb2823..35df8e4a0e 100644
@@ -259,14 +259,12 @@ void DiscoveryProxy::OnHostDiscovered(const std::string &
         std::string      hostName, domain;
         char             queryName[OT_DNS_MAX_NAME_SIZE];
         otDnssdQueryType type = otDnssdGetQueryTypeAndName(query, &queryName);
-        otbrError        splitError;
 
         if (type != OT_DNSSD_QUERY_TYPE_RESOLVE_HOST)
         {
             continue;
         }
-        splitError = SplitFullHostName(queryName, hostName, domain);
-        assert(splitError == OTBR_ERROR_NONE);
+        assert(SplitFullHostName(queryName, hostName, domain) == OTBR_ERROR_NONE);
 
         if (DnsLabelsEqual(hostName, aHostName))
         {

```

**The error reported by the tool chain :**
[12/54] Building CXX object src/sdp_proxy/CMakeFiles/otbr-sdp-proxy.dir/discovery_proxy.cpp.o
FAILED: src/sdp_proxy/CMakeFiles/otbr-sdp-proxy.dir/discovery_proxy.cpp.o 
/usr/bin/c++ -DHAVE_LIBSYSTEMD=1 -DOTBR_ENABLE_BORDER_AGENT=1 -DOTBR_ENABLE_DBUS_SERVER=1 -DOTBR_ENABLE_DNSSD_DISCOVERY_PROXY=1 -DOTBR_ENABLE_MDNS_MDNSSD=1 -DOTBR_ENABLE_NOTIFY_UPSTART=1 -DOTBR_ENABLE_SRP_ADVERTISING_PROXY=1 -DOTBR_MESHCOP_SERVICE_INSTANCE_NAME="\"OpenThread BorderRouter\"" -DOTBR_PACKAGE_NAME=\"OpenThread_BorderRouter\" -DOTBR_PACKAGE_VERSION=\"0.3.0-319e6eb3c1\" -DOTBR_PRODUCT_NAME=\"BorderRouter\" -DOTBR_SYSLOG_FACILITY_ID=LOG_USER -DOTBR_VENDOR_NAME=\"OpenThread\" -I/home/sah0588/Downloads/matter/ot-br-posix/include -I/home/sah0588/Downloads/matter/ot-br-posix/src -I/home/sah0588/Downloads/matter/ot-br-posix/build/otbr/third_party/openthread/repo/etc/cmake -I/home/sah0588/Downloads/matter/ot-br-posix/third_party/openthread/repo/etc/cmake -I/home/sah0588/Downloads/matter/ot-br-posix/third_party/openthread/repo/include -I/home/sah0588/Downloads/matter/ot-br-posix/third_party/openthread/repo/src/posix/platform/include -I/home/sah0588/Downloads/matter/ot-br-posix/third_party/openthread/repo/src -O3 -DNDEBUG -Wall -Wextra -Werror -Wfatal-errors -Wuninitialized -Wno-missing-braces -std=c++11 -MD -MT src/sdp_proxy/CMakeFiles/otbr-sdp-proxy.dir/discovery_proxy.cpp.o -MF src/sdp_proxy/CMakeFiles/otbr-sdp-proxy.dir/discovery_proxy.cpp.o.d -o src/sdp_proxy/CMakeFiles/otbr-sdp-proxy.dir/discovery_proxy.cpp.o -c /home/sah0588/Downloads/matter/ot-br-posix/src/sdp_proxy/discovery_proxy.cpp
/home/sah0588/Downloads/matter/ot-br-posix/src/sdp_proxy/discovery_proxy.cpp: In member function ‘void otbr::Dnssd::DiscoveryProxy::OnHostDiscovered(const string&, const otbr::Mdns::Publisher::DiscoveredHostInfo&)’:
/home/sah0588/Downloads/matter/ot-br-posix/src/sdp_proxy/discovery_proxy.cpp:262:26: error: variable ‘splitError’ set but not used [-Werror=unused-but-set-variable]
  262 |         otbrError        splitError;
      |                          ^~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors

**Comment by jwhui** [comment]
@achsoftathome , thanks for raising this issue.

I submitted #1482 with a proposed fix. Note that we do not want to move `SplitFullHostName()` into an `assert()` statement, otherwise that method will not be called in release mode.

**Comment by achsoftathome** [comment]
Thanks,
________________________________
