### ISSUE TITLE
State change not working

### ISSUE THREAD

**Issue by vijayrao1988** [openthread/ot-br-posix#1504]
**Describe the bug**
I am using the otbr-posix on Ubuntu 22.04 Server.
I am using the ot-rcp project from the Silicon Labs Simplicity Studio 5 example projects for EFR32.
Everything builds and installs fine.
The RCP gets detected by otbr-agent and I can setup a Thread network properly.
We have other Silicon Labs Thread devices on the network that are on an old stack of Thread. Let's call this 'IOT Network'.
When this OTBR joins the 'IOT Network', the OTBR remains a 'child' forever and does not become a 'router'.

`User@Ubuntu2204-08082022:~$ sudo ot-ctl version`
`OPENTHREAD/0a41196; POSIX; Aug 10 2022 12:54:44`
`Done`

`User@Ubuntu2204-08082022:~$ sudo ot-ctl state`
`child`
`Done`

`User@Ubuntu2204-08082022:~$ sudo ot-ctl state router`
`Error 27: NotCapable`

`User@Ubuntu2204-08082022:~$ sudo ot-ctl routereligible`
`Disabled`
`Done`

`User@Ubuntu2204-08082022:~$ sudo ot-ctl routereligible enable`
`Done`

`User@Ubuntu2204-08082022:~$ sudo ot-ctl routereligible`
`Disabled`
`Done`

`User@Ubuntu2204-08082022:~$ sudo ot-ctl routereligible disable`
`Done`

`User@Ubuntu2204-08082022:~$ sudo ot-ctl routereligible enable`
`Done`

`User@Ubuntu2204-08082022:~$ sudo ot-ctl routereligible`
`Disabled`
`Done`

**To Reproduce**
Information to reproduce the behavior, including:
1. Git commit id - 4659195 https://github.com/openthread/ot-br-posix/commit/4659195ef8faec0ab51120689d4ee759737b574e
2. IEEE 802.15.4 hardware platform - Silicon Labs EFR32 (MGM12P32F1024GE)
3. Build steps - Clone otbr-posix, build and install OpenThread Border Router. Use ot-rcp example project for EFR32 and flash to EFR32 radio board. Connect the RCP to the OTBR and setup a sample network. Use the same network dataset on 2 other EFR32 based nodes.
4. Network topology - 3 devices (1 x OTBR + 2 x Silicon Labs Thread Stack devices)

**Expected behavior** 
In the past versions of OTBR, I have seen the state change as per the sudo ot-ctl state router / sudo ot-ctl state leader command.

**Console/log output**
Outputs attached above in the description.

**Additional context**
1. routereligible remains disabled throughout. How do I enable it?
2. What is Error 27. Not Capable. How do I make it capable of changing states?

**Comment by jwhui** [comment]
The "Not Capable" error indicates that [`MleRouter::IsRouterEligible()`](https://github.com/openthread/openthread/blob/061d22ba8e12342332225ce14199bba73407a112/src/core/thread/mle_router.cpp#L120) is returning `false`.

There are a number of reasons why this may be the case. One reason could be due to how the Active Operational Dataset is configured. Can you provide the output of `dataset active`?

**Comment by vijayrao1988** [comment]
User@Ubuntu2204-08082022:~$ sudo ot-ctl dataset active
Active Timestamp: 1
Channel: 11
Channel Mask: 0x07fff800
Ext PAN ID: 7ec1e5de5fa2e4e6
Mesh Local Prefix: fdaa:4cd3:a4e0:1::/64
Network Key: 2a5345435552452a706173732a484631
Network Name: IOT-Network
PAN ID: 0x5601
PSKc: 12699c676905b6c3576dd1dbe272270a
Security Policy: 672 onrc
Done

**Comment by vijayrao1988** [comment]
Could this be a bug where the RCP is downgrading irreversibly into a End-Device rather than moving to 'child' role reversibly?

**Comment by jwhui** [comment]
> Could this be a bug where the RCP is downgrading irreversibly into a End-Device rather than moving to 'child' role reversibly?

I'm not aware of how this could happen.

Are you able to check what condition is causing [MleRouter::IsRouterEligible()](https://github.com/openthread/openthread/blob/061d22ba8e12342332225ce14199bba73407a112/src/core/thread/mle_router.cpp#L120) to return `false`?

**Comment by jwhui** [comment]
Closing stale issue.
