### ISSUE TITLE
Start a new network with specific channel

### ISSUE THREAD

**Issue by caipiblack** [openthread/ot-br-posix#1525]
**Describe the bug**

We are using `ot-br-posix` on iMX8MN board (Yocto) with EFR32 board to act as a border router for IOT gateway application. The EFR32 board is using a multipan firmware (rcp-uart-802154) for (Zigbee/Thread) application.
 
The particularity of this setup is that Zigbee and Thread **must use the same channel**:

- Currently our strategy is to identify the best channel and then initialize Zigbee and Thread network.
- So when we create a thread network we need to specify the channel.

To do this, we would like to generate the thread network "randomly" (as before (ie: without multipan)) **except for some parameters like the channel**. 

This is how I try to do it:

```
ot-ctl factoryreset
sleep 3

ot-ctl dataset init new
ot-ctl dataset commit active
ot-ctl channel 15
ot-ctl ifconfig up
ot-ctl thread start

# After that, we read the dataset in loop until success or timeout (ot-ctl dataset active -x) to store it in our system
```

**Problem**: 

- When we do it, the command `ot-ctl dataset active -x` fails to execute so we have to retry until success/timeout.

**Notes**:

1. In our application channel monitor and channel manager is disabled (required for multipan, to keep the same channel for zigbee and thread)
2. We are not sure if it's realy good to initialise a random dataset and then fix the channel. Is there a better solution ?
3. We are not sure about where to put `ot-ctl channel 15`. Because if it is before  `dataset commit active` then it will not be used.
4. It's not realy clear to me what `dataset commit active` really does. `Commit new dataset to the Active Operational Dataset in non-volatile storage`. And why the channel cant be set before calling this.
5. Does `dataset init new` execute a network scan before choosing the channel ? Even if channel monitoring is disabled ? Or is the channel selected randomly ?
6. Is there a way to start a channel discovery without starting thread network and without channel monitoring ? 

**To Reproduce**

1. Commit ID: [SiliconLabs repository - Gecko SDK 4.1.1](https://github.com/SiliconLabs/gecko_sdk/tree/799200bb6788939aa0fef97d7fc4ee9aca57148d/util/third_party/ot-br-posix)
3. IEEE 802.15.4 hardware platform: Running on iMX8MN with Yocto using EFR32 board in MultiPAN mode (Zigbee+Thread)
5. Build arguments:

```
EXTRA_OECMAKE = " \
	-DBUILD_TESTING=OFF \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DOT_MULTIPAN_RCP=ON \
	-DOT_POSIX_CONFIG_RCP_BUS=CPC \
	-DOT_BORDER_AGENT=ON \
	-DOT_BORDER_ROUTER=ON \
	-DOT_CHILD_SUPERVISION=ON \
	-DOT_COAP_BLOCK=ON \
	-DOT_COAP_OBSERVE=ON \
	-DOT_COAP=ON \
	-DOT_COAPS=ON \
	-DOT_COMMISSIONER=ON \
	-DOT_COVERAGE=OFF \
	-DOT_DAEMON=ON \
	-DOT_DATASET_UPDATER=ON \
	-DOT_DHCP6_CLIENT=ON \
	-DOT_DHCP6_SERVER=ON \
	-DOT_DIAGNOSTIC=ON \
	-DOT_DNS_CLIENT=ON \
	-DOT_DUA=OFF \
	-DOT_ECDSA=ON \
	-DOT_IP6_FRAGM=ON \
	-DOT_JAM_DETECTION=ON \
	-DOT_JOINER=ON \
	-DOT_LEGACY=ON \
	-DOT_LOG_LEVEL_DYNAMIC=ON \
	-DOT_LOG_OUTPUT=PLATFORM_DEFINED \
	-DOT_MAC_FILTER=ON \
	-DOT_MLR=OFF \
	-DOT_MTD_NETDIAG=ON \
	-DOT_NEIGHBOR_DISCOVERY_AGENT=ON \
	-DOT_PING_SENDER=ON \
	-DOT_PLATFORM=posix \
	-DOT_POSIX_MAX_POWER_TABLE=ON \
	-DOT_POSIX_SETTINGS_PATH=\"/etc/openthread\" \
	-DOT_RCP_RESTORATION_MAX_COUNT=10 \
	-DOT_REFERENCE_DEVICE=ON \
	-DOT_SERVICE=ON \
	-DOT_SLAAC=ON \
	-DOT_SNTP_CLIENT=ON \
	-DOT_SRP_CLIENT=ON \
	-DOT_THREAD_VERSION=1.2 \
	-DOTBR_BACKBONE_ROUTER=OFF \
	-DOTBR_BORDER_AGENT=ON \
	-DOTBR_BORDER_ROUTING=ON \
	-DOTBR_COVERAGE=OFF \
	-DOTBR_DBUS=OFF \
	-DOTBR_DNSSD_DISCOVERY_PROXY=ON \
	-DOTBR_INFRA_IF_NAME=eth0 \
	-DOTBR_MDNS=avahi \
	-DOTBR_MESHCOP_SERVICE_INSTANCE_NAME="OpenThread Border Router" \
	-DOTBR_PRODUCT_NAME="Border Router" \
	-DOTBR_REST=OFF \
	-DOTBR_SRP_ADVERTISING_PROXY=ON \
	-DOTBR_SRP_ADVERTISING_PROXY=ON \
	-DOTBR_VENDOR_NAME="OpenThread" \
	-DOTBR_WEB=ON \
"
```

**Expected behavior**

When I add the channel configuration in my thread initialisation script, I suppose that otbr is not supposed to hang and display `Session socket is ready` during multiples seconds.

**Console/log output**

[otbr-agent.txt](https://github.com/openthread/ot-br-posix/files/9495398/otbr-agent.txt)

**Comment by hemanth-silabs** [comment]
@caipiblack Is there any reason you are not changing the channel in new dataset before committing it? I think the better approach would be:

```
ot-ctl factoryreset
sleep 3

ot-ctl dataset init new
ot-ctl dataset channel 15
ot-ctl dataset commit active
ot-ctl ifconfig up
ot-ctl thread start
```

**Comment by jwhui** [comment]
@caipiblack , I agree with @hemanth-silabs . You should make modifications to the dataset before committing it.

**Comment by caipiblack** [comment]
Thanks for your responses, it works.

Previously I tried to configured the channel before `dataset commit active` but I was using `ot-ctl channel 15` instead of `ot-ctl dataset channel 15`
