### ISSUE TITLE
otbr-web does not start

### ISSUE THREAD

**Issue by jumpingjackgazz** [openthread/ot-br-posix#1527]
Hi all,

I've just cloned a fresh otbr-posix repo to setup a new RPi as border router.
otbr-agent starts correctly and initiates communication with RCP => GOOD
mdns also is started correctly.

The issue is that otbr-web is not installed/started at this end of the setup process: 
for the command: INFRA_IF_NAME=eth0 ./script/setup logs show the following :

...
+ sudo systemctl stop otbr-web
Failed to stop otbr-web.service: Unit otbr-web.service not loaded.
+ true
+ sudo systemctl stop otbr-agent
+ sudo systemctl disable otbr-web
Failed to disable unit: Unit file otbr-web.service does not exist.
+ true
+ sudo systemctl disable otbr-agent
Removed /etc/systemd/system/otbr-agent.service.
Removed /etc/systemd/system/multi-user.target.wants/otbr-agent.service.
+ sudo systemctl is-enabled otbr-web
Failed to get unit file state for otbr-web.service: No such file or directory

I've done this many times and that's the first time I see this issue.
Can you please help ??

ciao
jumpingjackgazz

**Comment by jumpingjackgazz** [comment]
in addition: 
sudo service otbr-web status
Unit otbr-web.service could not be found.

**Comment by jwhui** [comment]
What Linux distribution are you running on your Raspberry Pi?

Did you run `./script/bootstrap` before `./script/setup`?

**Comment by jumpingjackgazz** [comment]
Hi there,

I'm using Raspberry Pi OS with Desktop (64-bit version), from https://www.raspberrypi.com/software/operating-systems/, file : RPI_Image_2022-04-04-raspios-bullseye-arm64.img.xz.

Yes I did run the  ./script/bootstrap before ./script/setup.

Thx for feedback, any other things to check ??

**Comment by jumpingjackgazz** [comment]
Hi there,

WEB_GUI=1 ./script/bootstrap
INFRA_IF_NAME=wlan0 WEB_GUI=1 ./script/setup

fixes the issue !
Thx for concern

ciao

**Comment by jumpingjackgazz** [comment]
you can close the ticket
