### ISSUE TITLE
Ping the external internet does not work

### ISSUE THREAD

**Issue by jumpingjackgazz** [openthread/ot-br-posix#1528]
Hi all,

I have an issue pinging the external internet.
Here what I've done :
1- build up a Rpi image with otbr-posix, otbr-web and mdns services up and running - OK
2- connected my smartphone with Thread commissioning App on my ISP box wifi AP - OK
3- got the otbr Web GUI on smartphone browser and FORM Thread network with it - OK
4- Use the Thread app to commission a joiner node - OK
5- start Openthread on joiner node and get router role - OK
6- Add an external route for the NAT64 Prefix with (sudo ot-ctl route add 64:ff9b::/96 s med  AND sudo ot-ctl netdata register) - OK

**rpi@raspberrypi:~ $ sudo ot-ctl netdata show
Prefixes:
fd11:22:0:0::/64 paros med 6000
Routes:
::/0 s high 6000
2a01:cb08:8192:9e00::/64 s med 6000
64:ff9b:0:0:0:0::/96 s med 6000
Services:
44970 01 68000500000e10 s 6000
44970 5d fd79ff5b32da5b858a4db71f2cac99b4d11f s 6000
Done**

7- ping 64:ff9b::808:808 **- NOT OK**

Weird thing is that I can ping my smartphone (which is on ISP Box Wifi AP).

Can you please help to get the external ping running ?

ciao

PS : Another thing is that I can not do the mDNS discovery setup, it stays stuck on the first command: 
**rpi@raspberrypi:~ $ dns-sd -L "OpenThread BorderRouter" _meshcop._udp local
Lookup OpenThread BorderRouter._meshcop._udp.local
DATE: ---Fri 09 Sep 2022---
10:50:35.729  ...STARTING...
^C**

**Comment by jumpingjackgazz** [comment]
Hi there,

I have tried without Rpi Wifi AP, same issue, external ping from joiner node is not working.
Someone has an idea or things to try ?

ciao

**Comment by jwhui** [comment]
Closing stale issue.
