### ISSUE TITLE
External API (library, dbus, socket, something else)

### ISSUE THREAD

**Issue by caipiblack** [openthread/ot-br-posix#1541]
Hi,

We would like to control the openthread network from our software (connect/create network, execute some diag functions, ...).

Currently we start the network using external script that execute `ot-ctl` commands, we would like to know if there are another API's available. 

We found DBUS API but is there something else ?

- Library ?
- Socket ?
- Something else ?

Do you have any documentation about it ?

Also I would like to know if it is possible to know which devices are connected on the thread network ? (not just the childs of the current router (border router))

- I know that the border router have mDNS feature on ethernet side, but it can't be used for this because it have some cache, so a device can be present in the list without being connected.

Also I have questions about the topology graph:

- How is it possible to generate a topology graph using `ot-ctl` commands ?
- And is it possible to know the child of another router ? How it works ? 
- How the border router know the childs connected to another router ?

I know about `ot-ctl router table` and `ot-ctl child table` commands but for me it's not clear if it display all the childs or only the childs of the current router. And how it realy works "behind".

**Comment by ihidchaos** [comment]
+1

**Comment by caipiblack** [comment]
I found that there is a D-BUS library but currently it is not really documented.

If you need informations about it, see https://github.com/openthread/ot-br-posix/blob/main/src/dbus/server/introspect.xml and all the files in the same folder.

Some examples of commands:

```
dbus-send --system --print-reply --dest=io.openthread.BorderRouter.wpan0 /io/openthread/BorderRouter/wpan0 "io.openthread.BorderRouter.EnergyScan" uint32:200
```

This is easy to code in C.
