### ISSUE TITLE
Why or-br-posix checks my os as debian, on other hand i am using raspbian 

### ISSUE THREAD

**Issue by mark-nirdesh** [openthread/ot-br-posix#1545]
I am not able to ping the ipv6 address from ot-ctl command line.  as I have checked in the code of script/setup my device is raspbian but still its choosing the Debian ,on that note I got output.
 # shellcheck disable=SC2034
NAT64=0
DNS64=0
DHCPV6_PD=0
NETWORK_MANAGER=0
BACKBONE_ROUTER=1
BORDER_ROUTING=1
REST_API=1

instead of getting for  the raspbian 

# shellcheck disable=SC2034
NAT64=1
DNS64=0
DHCPV6_PD=0
NETWORK_MANAGER=0
BACKBONE_ROUTER=1
BORDER_ROUTING=1
WEB_GUI=1
REST_API=1

from the link https://github.com/openthread/ot-br-posix/tree/main/examples/platforms/raspbian

![Untitled](https://user-images.githubusercontent.com/53371402/191890280-99b7c2d5-b5a4-44bc-b3e4-3f9ea68e8b42.png)

I guess this is the reason I am not getting the ping reply.

**Comment by superwhd** [comment]
Could you share the result of `lsb_release -a`? What is the Raspberry Pi image you're using?

Also, apparently the difference between `examples/platforms/raspbian` and `examples/platforms/debian` should not cause connectivity issue (unless you're depending on NAT64).  Could you elaborate on your ping failure?
- What's the network topology?
- What's the type of IP address you're using?

**Comment by THETCR** [comment]
With the migration from `Buster` to `Bullseye` commands like `lsb_release -a` no longer return customised values and return the values from `Debian` instead.

The environment variables still set. The above output is just the default values that are printed for every option.
It does mean the `after_bootstrap` hook doesn't run, but that only contains changes for `Stretch` based releases.

So this is more an issue of unclear/too much output on `stdout`

**Comment by jwhui** [comment]
Closing stale issue.
