### ISSUE TITLE
How to change BR log level ?

### ISSUE THREAD

**Issue by jumpingjackgazz** [openthread/ot-br-posix#1559]
Hi there,

We need to improve our understanding of some issues faced with RPi+RCP implementation and hence we would need
to get extended UART traces on Border Router side.  We need to update trace level from info to debug level on host side.
Could you please detail what has to be done ? Config file to be updated ?

Regards

**Comment by jwhui** [comment]
Add `-DCMAKE_BUILD_TYPE=Debug` to `OTBR_OPTIONS` when building. This will enable debug-level logging in OpenThread core library.

Using `ot-ctl` you should be able to use the [`log level`](https://github.com/openthread/openthread/blob/main/src/cli/README.md#log-level) command to dynamically adjust the log level.
