### ISSUE TITLE
[android] '-std=c99' is valid for C/ObjC but not for C++

### ISSUE THREAD

**Issue by lmnotran** [openthread/ot-br-posix#1571]
**Describe the bug** A clear and concise description of what the bug is.
#1335 is causing a ton of warnings when building for android.

See example: https://github.com/openthread/ot-br-posix/actions/runs/3243645349/jobs/5318661298#step:3:3082

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by lmnotran** [comment]
@jwhui can you take a look please?

**Comment by jwhui** [comment]
@lmnotran , thanks for raising this issue. I'm not sure I have a good answer here. It appears that Android build may automatically apply `LOCAL_CFLAGS` to both C and C++.

@bukepo , thoughts?

**Comment by bukepo** [comment]
If the flag is added only for the new version of mbedtls? Perhaps we can add a flag only for mbedtls souroces.

**Comment by jwhui** [comment]
@lmnotran , can you help review https://github.com/openthread/openthread/pull/8310 and indicate whether it resolves this issue?
