### ISSUE TITLE
REST API should be configurable (e.g. able to listen on IPv6 addresses)

### ISSUE THREAD

**Issue by sgryphon** [openthread/ot-br-posix#1586]
The REST API is hard coded to INADDR_ANY:

https://github.com/openthread/ot-br-posix/blob/92059387fc5bc253cda65a75293d511b58383b38/src/rest/rest_web_server.cpp#L125

This should be configurable, similar to the otbr-web service, with preferably a default of in6addr_any

Note that otbr-web also defaults to IPv4, however it can be easily configured with override "-a ::" to work on IPv6. Some pages work fine using IPv6, however the Topology page in particular is broken (it calls directly to the API).

**Comment by wgtdkp** [comment]
@sgryphon It sounds good to me! Are you willing to submit a PR for this?

**Comment by wgtdkp** [comment]
This is resolved by https://github.com/openthread/ot-br-posix/pull/1670
