### ISSUE TITLE
mDNSResponder-1310.80.1.tar.gz 404 Not Found.

### ISSUE THREAD

**Issue by overheat** [openthread/ot-br-posix#1591]
Looks Apple remove mDNSResponder on their website for opensource.

$ ./script/bootstrap
```
...
wget -4 --no-check-certificate https://opensource.apple.com/tarballs/mDNSResponder/mDNSResponder-1310.80.1.tar.gz
--2022-11-03 15:24:34--  https://opensource.apple.com/tarballs/mDNSResponder/mDNSResponder-1310.80.1.tar.gz
Connecting to 192.168.31.147:7890... connected.
Proxy request sent, awaiting response... 404 Not Found
2022-11-03 15:24:36 ERROR 404: Not Found.
...
```

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by superwhd** [comment]
Thanks for catching this issue. I'm not sure if Apple's website has a temporary issue or they intentionally wants to turn that part down. 

Should we consider fetching mDNSResponder from somewhere else? For example https://github.com/apple-oss-distributions/mDNSResponder/releases/tag/mDNSResponder-1310.80.1 @jwhui @wgtdkp

**Comment by overheat** [comment]
> Thanks for catching this issue. I'm not sure if Apple's website has a temporary issue or they intentionally wants to turn that part down.
> 
> Should we consider fetching mDNSResponder from somewhere else? For example https://github.com/apple-oss-distributions/mDNSResponder/releases/tag/mDNSResponder-1310.80.1 @jwhui @wgtdkp

Good idea! it stuck setting up Raspberry Pi for now.

**Comment by romacdon** [comment]
Is there anyone here from Apple that can comment on if the https://opensource.apple.com/tarballs/ location is permanently disabled or if its a temporary issue?

**Comment by jwhui** [comment]
> Is there anyone here from Apple that can comment on if the https://opensource.apple.com/tarballs/ location is permanently disabled or if its a temporary issue?

@romacdon , the links were changed to what is listed on https://opensource.apple.com/releases/

**Comment by rob-the-dude** [comment]
FWIW, that version of mDNSResponder is fairly old -- it corresponds with macOS 11.2.

They recently provided mDNSResponder-1790.40.31 that is the code from the newly release macOS 13 (Ventura).  Not sure how many bug fixes might be present.
