### ISSUE TITLE
Difference between  ot-rcp.hex and ot-cli.hex?

### ISSUE THREAD

**Issue by sohaibbinaltaf** [openthread/ot-br-posix#1601]
I have on confusion if you could please tell me, there are two kind of hex files, ot-rcp.hex and ot-cli.hex.  Which one is required to be burned for the thread router and which one is required for the end device?

**Comment by jwhui** [comment]
- `ot-rcp` for the border router.
- `ot-cli` for the end device.

The [Thread Border Router codelab](https://openthread.io/codelabs/openthread-border-router#0) provides more details.

**Comment by sohaibbinaltaf** [comment]
thanks a lot.
