### ISSUE TITLE
linkmetrics ot-ctl commands not recognized

### ISSUE THREAD

**Issue by Jakebluhm** [openthread/ot-br-posix#1606]
**Describe the bug**  
I'm trying to use the linkmetrics open thread cli command but it is not working on my Raspberry Pi 4b running OTBR 

**Expected behavior**  
I'm expecting to be able to use all OT Cli commands outlined here -> https://github.com/openthread/openthread/blob/main/src/cli/README.md#radiofilter but I assume I am missing a step that enables linkmetrics commands somewhere.
**Console/log output**
$ sudo ot-ctl linkmetrics query *my_ip_addr* single qmr
Error 35: InvalidCommand

**Additional context**  
This issue has been brought up before on this forum: https://groups.google.com/g/openthread-users/c/LPi4jpH-WLY

Reading the forum, it seems the solution is to to modify the otbr build but it's unclear to me how to do that. The proposed solution:

> To enable it: How did you build OTBR? If you are using cmake, make sure you are using Thread 1.2 and add `-DOT_LINK_METRICS_INITIATOR=ON -DOT_LINK_METRICS_SUBJECT=ON` when building it.

Following the openthread.io tutorial (https://openthread.io/codelabs/openthread-border-router#1) the following commands are used to build the OTBR, do I add the -DOT_LINK_METRICS_INITIATOR=ON -DOT_LINK_METRICS_SUBJECT=ON to .script/bootstrap? or ./script/setup?

**Comment by jwhui** [comment]
@Jakebluhm , you need to enable `OPENTHREAD_CONFIG_MLE_LINK_METRICS_INITIATOR_ENABLE` in the build.

You can try adding the build option here: https://github.com/openthread/ot-br-posix/blob/d893fa58eaff414d13ec0bf70e6771f12ceecca4/third_party/openthread/CMakeLists.txt#L41
Something like:
```
set(LINK_METRICS_INITIATOR ON CACHE BOOL "enable link metrics initiator" FORCE)
```

**Comment by jwhui** [comment]
Closing stale issue.
