### ISSUE TITLE
Add check for having `systemctl` before trying to disable

### ISSUE THREAD

**Issue by a-cinar** [openthread/ot-br-posix#1607]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.
There is no check for `have systemctl` in the[ _disable_services](https://github.com/openthread/ot-br-posix/blob/main/script/_disable_services) script even though this check exists all around the project. This causes the setup to fail if the machine does not have the `systemctl` command.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Add the `if have systemctl; then` line before loop for disabling services that could cause problem to otbr.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
We are using a patch to skip this loop on our circleci builds that uses docker which does not have `systemctl` command installed.

**Comment by jwhui** [comment]
@a-cinar , would you like to submit a PR with the proposed change?

**Comment by a-cinar** [comment]
Sure!

**Comment by a-cinar** [comment]
Created [PR](https://github.com/openthread/ot-br-posix/pull/1610) to fix the issue.
