### ISSUE TITLE
Network Master Key in Web UI

### ISSUE THREAD

**Issue by mateusz-** [openthread/ot-br-posix#164]
Hi,

I added a Network Master Key to the response of `WpanService::HandleStatusRequest` (i.e., `GET /get_properties`) in a [fork](https://github.com/mateusz-/borderrouter).

This helps with OOB commissioning.

Now, the OTBR Web UI loops through all properties and displays them on a status page. This means that the Network Master Key is displayed in plain text.

Does this sound okay? Should the Network Master Key be obtainable via a HTTP(S) request? Should it be displayed in plain text on the status page?

To explain my OOB case a little better, I have a mobile app that establishes a TLS-PSK connection with a border router. TLS is terminated before it reaches the OTBR web service. I then obtain all necessary info, including the Network Master Key, and commission a device using BLE.

**Comment by jwhui** [comment]
@mateusz-, in general, presenting/communicating the Thread Master Key should be done with lots of care. Where possible, the Thread Master Key should only be communicated securely to properly authenticated users. Requiring a TLS-PSK session does help with that. At the same time, the user should take care how the Thread Master Key is communicated and stored after retrieval. Hope that helps.
