### ISSUE TITLE
RadioSpinelNoResponse: OpenThread daemon is not running (nRF52840 DK)

### ISSUE THREAD

**Issue by mmikhan** [openthread/ot-br-posix#1651]
OpenThread daemon fails to run whenever using the nRF 52840 DK development board but works fine when using the nRF 52840 Dongle. I reinstalled it multiple times and started from scratch with so many tweaks but couldn't figure it out.

Default OTBR Agent: `cat /etc/default/otbr-agent`
```
# Default settings for otbr-agent. This file is sourced by systemd

# Options to pass to otbr-agent
OTBR_AGENT_OPTS="-I wpan0 -B wlan0 spinel+hdlc+uart:///dev/ttyACM0 trel://wlan0"
OTBR_NO_AUTO_ATTACH=0
```
I can confirm the development board appears in the same port as shown above.

`ls /dev/ttyA*`
```
/dev/ttyACM0  /dev/ttyACM1  /dev/ttyAMA0
```
I tried manually enabling the OpenThread daemon like the following but no luck.
`sudo otbr-agent -I wpan0 -B wlan0 spinel+hdlc+uart:///dev/ttyACM0 trel://wlan0 -v`
```
otbr-agent[6151]: [NOTE]-AGENT---: Running 0.3.0-6e0cfbceec
otbr-agent[6151]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[6151]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[6151]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
otbr-agent[6151]: [NOTE]-AGENT---: Radio URL: trel://wlan0
otbr-agent[6151]: [NOTE]-ILS-----: Infra link selected: wlan0
otbr-agent[6151]: [INFO]-NCP-----: OpenThread log level changed to 4
otbr-agent[6151]: 49d.17:20:20.325 [W] Platform------: Wait for response timeout
otbr-agent[6151]: 49d.17:20:20.326 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2248: RadioSpinelNoResponse
```

And, here's the `otbr-agent` status: `service otbr-agent status`
```
● otbr-agent.service - OpenThread Border Router Agent
     Loaded: loaded (/lib/systemd/system/otbr-agent.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-12-12 01:10:20 CET; 3s ago
    Process: 5969 ExecStartPre=service mdns start (code=exited, status=0/SUCCESS)
    Process: 5985 ExecStart=/usr/sbin/otbr-agent $OTBR_AGENT_OPTS (code=exited, status=6)
   Main PID: 5985 (code=exited, status=6)
        CPU: 44ms
```

**Hardware**
- Raspberry Pi 4 (4Gb)
- nRF 52840 DK

**Software**
- [nRF Thread Coprocessor sample template](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.2.0/nrf/samples/openthread/coprocessor/README.html)

Does anybody have any idea what's going wrong? It's very odd since nRF 52840 Dongle works fine with the same [sample template](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.2.0/nrf/samples/openthread/coprocessor/README.html) with the following build flag added.
```
-DOVERLAY_CONFIG="overlay-usb.conf" -DDTC_OVERLAY_FILE="usb.overlay"
```

**Comment by jwhui** [comment]
The nRF52840 DK has two USB connectors. Make sure you are connecting to the proper connector for the RCP image you built. The [Set up the RCP Joiner guide](https://openthread.io/codelabs/openthread-hardware#3)](https://openthread.io/codelabs/openthread-hardware#3) provides more details.
