### ISSUE TITLE
Command `nat64` shows InvalidCommand

### ISSUE THREAD

**Issue by mmikhan** [openthread/ot-br-posix#1653]
I want to enable the Nat64 protocol in the Border Router to share internet access to the local Thread network. However, `ot-ctl` doesn't recognize the command `nat64` at all. When I write `sudo ot-ctl nat64 enable`, it shows `InvalidCommand`. It's not only this one but any command with `nat64`. Running `br nat64prefix` even doesn't work.

Not sure what I am missing at this point. Any hint for the right direction is highly appreciated.

**Steps followed**
- Building border router: https://openthread.io/guides/border-router/build with `NAT64=1 NAT64_SERVICE=openthread` flags enabled in the `./script/bootstrap` initial process.
- Flashed nRF52840_Dongle RCP using the steps shown here: https://github.com/openthread/ot-nrf528xx/blob/main/src/nrf52840/README.md

**Comment by jwhui** [comment]
Make sure the `NAT64` and `NAT64_SERVICE` environment variables are also set when running `./script/setup` by using the `export` command. See the [OpenThread NAT64 codelab](https://openthread.io/codelabs/openthread-border-router-nat64#1) for details.

**Comment by mmikhan** [comment]
This is how I did `NAT64=1 NAT64_SERVICE=openthread ./script/bootstrap`. Shall I still need to use `export NAT64=1 NAT64_SERVICE=openthread`?

**Comment by mmikhan** [comment]
Damn, I was pulling my hair. Thanks a million 🙏
