### ISSUE TITLE
Problem with compile on Raspberry Pi on Ubuntu 22.10

### ISSUE THREAD

**Issue by BlackWizard** [openthread/ot-br-posix#1666]
**Describe the bug** 
Compiling of OTBR almost done, but failed in compiling web server code

**To Reproduce** 
main branch commit fbbb62fafce55cdd8c0fa2352b2e27d30c2d2192

**Expected behavior** 
Success compilation

**Console/log output**

[447/451] Building CXX object src/web/CMakeFiles/otbr-web.dir/web-service/web_server.cpp.o
FAILED: src/web/CMakeFiles/otbr-web.dir/web-service/web_server.cpp.o 
/usr/bin/c++ -DMBEDTLS_CONFIG_FILE=\"/home/pi/ot-br-posix/third_party/openthread/mbedtls-config.h\" -DOTBR_ENABLE_BACKBONE_ROUTER=1 -DOTBR_ENABLE_BORDER_AGENT=1 -DOTBR_ENABLE_BORDER_ROUTING=1 -DOTBR_ENABLE_BORDER_ROUTING_COUNTERS=1 -DOTBR_ENABLE_DBUS_SERVER=1 -DOTBR_ENABLE_DNSSD_DISCOVERY_PROXY=1 -DOTBR_ENABLE_FEATURE_FLAGS=1 -DOTBR_ENABLE_NAT64=1 -DOTBR_ENABLE_NOTIFY_UPSTART=1 -DOTBR_ENABLE_REST_SERVER=1 -DOTBR_ENABLE_SRP_ADVERTISING_PROXY=1 -DOTBR_ENABLE_SRP_SERVER_AUTO_ENABLE_MODE=1 -DOTBR_ENABLE_VENDOR_INFRA_LINK_SELECT=0 -DOTBR_MESHCOP_SERVICE_INSTANCE_NAME="\"OpenThread BorderRouter\"" -DOTBR_PACKAGE_NAME=\"OpenThread_BorderRouter\" -DOTBR_PACKAGE_VERSION=\"0.3.0-fbbb62fafc\" -DOTBR_PRODUCT_NAME=\"BorderRouter\" -DOTBR_SYSLOG_FACILITY_ID=LOG_USER -DOTBR_VENDOR_NAME=\"OpenThread\" -DWEB_FILE_PATH=\"/usr/share/otbr-web/frontend\" -I/usr/include/jsoncpp -I/home/pi/ot-br-posix/third_party/Simple-web-server/repo -I/home/pi/ot-br-posix/include -I/home/pi/ot-br-posix/src -I/home/pi/ot-br-posix/build/otbr/third_party/openthread/repo/etc/cmake -I/home/pi/ot-br-posix/third_party/openthread/repo/etc/cmake -I/home/pi/ot-br-posix/third_party/openthread/repo/include -I/home/pi/ot-br-posix/third_party/openthread/repo/src/posix/platform/include -I/home/pi/ot-br-posix/third_party/openthread/repo/src -I/home/pi/ot-br-posix/third_party/openthread/repo/third_party/mbedtls/repo/include -Wall -Wextra -Werror -Wfatal-errors -Wuninitialized -Wno-missing-braces -Wno-deprecated-declarations -Wno-unused-lambda-capture -std=c++11 -MD -MT src/web/CMakeFiles/otbr-web.dir/web-service/web_server.cpp.o -MF src/web/CMakeFiles/otbr-web.dir/web-service/web_server.cpp.o.d -o src/web/CMakeFiles/otbr-web.dir/web-service/web_server.cpp.o -c /home/pi/ot-br-posix/src/web/web-service/web_server.cpp
In file included from /home/pi/ot-br-posix/src/web/web-service/web_server.cpp:42:
/home/pi/ot-br-posix/third_party/Simple-web-server/repo/server_http.hpp: In instantiation of ‘SimpleWeb::ServerBase<socket_type>::Request::Request(const socket_type&) [with socket_type = boost::asio::basic_stream_socket<boost::asio::ip::tcp>]’:
/home/pi/ot-br-posix/third_party/Simple-web-server/repo/server_http.hpp:460:74:   required from here
/home/pi/ot-br-posix/third_party/Simple-web-server/repo/server_http.hpp:117:57: error: member ‘SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::Request::streambuf’ is used uninitialized [-Werror=uninitialized]
  117 |             Request(const socket_type &socket): content(streambuf) {
      |                                                         ^~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
[448/451] Building CXX object src/dbus/server/CMakeFiles/otbr-dbus-server.dir/dbus_thread_object.cpp.o
ninja: build stopped: subcommand failed.

**Additional context** 
gcc version 12.2.0 (Ubuntu 12.2.0-3ubuntu1)

**Comment by jwhui** [comment]
See #1664

**Comment by agners** [comment]
This should be fixed with #1667.

**Comment by jwhui** [comment]
Resolved by #1667.
