### ISSUE TITLE
OT BorderRouter looking for data for thread network

### ISSUE THREAD

**Issue by Simon8890** [openthread/ot-br-posix#1681]
Hi, i was wondering if it could be possible to implement functions into the border router code that permeats to ask data from the thread network and sending them to a firebase project.
thanks

**Comment by wgtdkp** [comment]
Could you provide more information of what you want to achieve? What kind of data do you want from Thread network？

**Comment by Simon8890** [comment]
I want to send data from my personal thread network, composed by nRF5340 devices, to the border router. Data like temperaure.
Is that possible?

**Comment by fgervais** [comment]
Once the nFR53 device are connected to the border router, they have network access so you can have a service like MQTT installed to receive the temperature data and from there, you can use the normal tooling to get that to firebase.

The MQTT service could be installed on another machine on the same border router network or it could be installed directly on the border router machine through a container or not. As you like best.

So to answer the question, I would say that no modification to the border router code is required.

**Comment by jwhui** [comment]
Closing stale issue.
