### ISSUE TITLE
 ot-ctl connect session failed: No such file or directory

### ISSUE THREAD

**Issue by uservipul** [openthread/ot-br-posix#1683]
I've seen multiple threads posted on the same issue, however the solution is still not clear. 

 otbr-agent.service is not running when checking status. 

Please suggest how to fix. I'm running this on Windows 10

**Comment by wgtdkp** [comment]
> otbr-agent.service is not running when checking status.

ot-ctl talks to otbr-agent via unix socket. This error message indicates that the unix socket doesn't exist. You should look into the otbr-agent logs (in syslog) to see why otbr-agent doesn't boot.

Please follow https://openthread.io/guides/border-router/build to set up your Border Router if you are not already doing so.

**Comment by uservipul** [comment]
How do I check syslog? I'm new to this. 

I did follow along the latest guide to build the BR but still didn't work.

**Comment by wgtdkp** [comment]
> Please suggest how to fix. I'm running this on Windows 10

Are you using Windows Subsystem for Linux? If yes, please run command `cat /var/log/syslog | grep otbr-agent` and paste the output here. If no, OTBR doesn't support OS other than posix.

**Comment by uservipul** [comment]
I tried to run the script but now my PuTTY doesn't work, gets shut down and no terminal window opens to login. This could be seperate thread, but can you point me in the right direction?

**Comment by Zepperoni** [comment]
It doesn't work for me either, neither under raspbian nor under ubuntu.
My output to `cat /var/log/syslog | grep otbr-agent`
```
Jan  4 23:55:06 ubuntu otbr-agent: [NOTE]-AGENT---: Backbone interface: eth0
Jan  4 23:55:06 ubuntu otbr-agent[980]: [NOTE]-AGENT---: Running 0.3.0-f87eb3a8df
Jan  4 23:55:06 ubuntu otbr-agent[980]: [NOTE]-AGENT---: Thread version: 1.3.0
Jan  4 23:55:06 ubuntu otbr-agent[980]: [NOTE]-AGENT---: Thread interface: wpan0
Jan  4 23:55:06 ubuntu otbr-agent[980]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Jan  4 23:55:06 ubuntu otbr-agent[980]: [NOTE]-AGENT---: Radio URL: trel://eth0
Jan  4 23:55:06 ubuntu otbr-agent[980]: [NOTE]-ILS-----: Infra link selected: eth0
Jan  4 23:55:06 ubuntu otbr-agent[980]: [INFO]-NCP-----: OpenThread log level changed to 4
Jan  4 23:55:06 ubuntu otbr-agent[980]: 49d.17:03:18.145 [I] Platform------: RCP reset: RESET_POWER_ON
Jan  4 23:55:06 ubuntu otbr-agent[980]: 49d.17:03:18.159 [I] Platform------: RCP reset: RESET_POWER_ON
Jan  4 23:55:06 ubuntu otbr-agent[980]: 49d.17:03:18.163 [C] Platform------: RCP API Version 7 is not in the supported range [4-6]
Jan  4 23:55:06 ubuntu otbr-agent[980]: 49d.17:03:18.163 [C] Platform------: CheckRcpApiVersion() at radio_spinel_impl.hpp:423: RadioSpinelIncompatible
Jan  4 23:55:06 ubuntu systemd[1]: otbr-agent.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jan  4 23:55:06 ubuntu systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jan  4 23:55:12 ubuntu systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 1.
```

**Comment by abtink** [comment]
@Zepperoni regarding your case, I see this error: `RCP API Version 7 is not in the supported range [4-6]`
Need updating the host side (ot-br-posix) to later commit/version.  Your RCP is running later version (can also consider using an older RCP build instead).

**Comment by Zepperoni** [comment]
> @Zepperoni regarding your case, I see this error: `RCP API Version 7 is not in the supported range [4-6]`
> Need updating the host side (ot-br-posix) to later commit/version. Your RCP is running later version (can also consider using an older RCP build instead).

I'm using the latest commit

**Comment by abtink** [comment]
@Zepperoni need latest commit of OT core stack (which I guess is often syned/included in `ot-br-posix` repo and other repos). I guess `ot-br-posix` is still using older OT core version (hence its RCP API version number being at 6)
Quick way around this for now is to use older RCP build (use anything before this commit https://github.com/openthread/openthread/commit/8b59f4d31e86c9808721413c8507c15a51ecd696 to build RCP image).

**Comment by jwhui** [comment]
Closing stale issue.

**Comment by chuckrui** [comment]
@abtink HI,I also meet the same question is that i didn't success to build the thread network.
I used 52840 as the RCP to build the Thread network, but it kept failing, the corresponding path could not be found, I checked the log and the parameter was invalid. What makes me even more confused is why the same hardware can successfully run the Thread network on the Raspberry PI, but not on Ubuntu20.04Pc, as I have looked for many methods online without any success. Can you help me see what the problem is?
Some command line results are provided below.
[1106.txt](https://github.com/openthread/ot-br-posix/files/13274798/1106.txt)

**Comment by jwhui** [comment]
@chuckrui , in your log:
```
Nov  7 02:12:21 chuck-rui otbr-agent[153]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/radio?uart-baudrate=115200
```

`/dev/radio` is not a valid device path.

**Comment by chuckrui** [comment]
@jwhui  Hi,
But on Raspberry 4B,i can't found the /dev/radio the same as Ubuntu PC,
I can see /dev/ttyACM0 on both Ubuntu Pc and Raspberry PI, the only difference is that thread networks can be successfully built on Raspberry PI 4B, but not on Ubuntu Pc.

**Comment by abtink** [comment]
This seems to be related to OS and file/path names you are using and how the UART and other ports are represented.
Basically you are providing a "path" to where the UART is located which does not exist on your machine.
(my guess is on RasperbyPi you probably have symlink for this path so that's why it works).
