### ISSUE TITLE
Unable to run otbr-agent from docker container on MacOS

### ISSUE THREAD

**Issue by AABelkhiria** [openthread/ot-br-posix#1685]
I'm trying to run otbr-agent on MacOS, but I keep getting an Invalid Argument when starting the service.
I'm using macOS Monterey Version 12.6.2 (M1 Pro)

**To Reproduce** Information to reproduce the behavior, including:

1. Board: xGM210P032 Wireless Gecko Module Radio Board (BRD4308A Rev A01) (Target Part: MGM210P032JIA)
2. Serial port: /dev/tty.usbmodem0004402071182

I run the command
```
sudo docker run --rm --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 --dns=127.0.0.1 -it --volume /dev/tty.usbmodem0004402071182:/dev/ttyACM0 --privileged openthread/otbr
```

from the container I edit the `default/otbr-agent` with
```
OTBR_AGENT_OPTS="-I wpan0 spinel+hdlc+uart:///dev/ttyACM0 trel://eth0"
```
then run
```
sudo service otbr-agent start
```
and that's how I get this error
```
otbr-agent[253]: [NOTE]-AGENT---: Running 0.3.0-079bbce
otbr-agent[253]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[253]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[253]: [NOTE]-AGENT---: Backbone interface is not specified
otbr-agent[253]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
otbr-agent[253]: [NOTE]-AGENT---: Radio URL: trel://eth0
otbr-agent[253]: [NOTE]-ILS-----: Infra link selected: 
otbr-agent[253]: [INFO]-NCP-----: OpenThread log level changed to 4
otbr-agent[253]: 49d.22:11:24.825 [C] Platform------: Radio file '/dev/ttyACM0' not supported
otbr-agent[253]: 49d.22:11:24.825 [C] Platform------: Radio file '/dev/ttyACM0' not supported
otbr-agent[253]: 49d.22:11:24.825 [C] Platform------: Init() at radio.cpp:110: InvalidArgument
otbr-agent[253]: 49d.22:11:24.825 [C] Platform------: Radio file '/dev/ttyACM0' not supported
```

**Comment by adminy** [comment]
Unlikely that you'll get this on macos any time soon.
There is an issue on [google threads](https://groups.google.com/g/openthread-users/c/tGodlrI9H7g) open related to this:
But fundamentally its about docker. You can't have macos devices on linux. Linux works with kernel modules that do not transfer over so nicely.

https://github.com/docker/for-mac/issues/900

**Comment by jwhui** [comment]
As @adminy mentioned, I believe exposing a tty device to Docker on macOS is not supported - see [docker/for-mac#900](https://github.com/docker/for-mac/issues/900).

**Comment by jwhui** [comment]
Closing stale issue.
