### ISSUE TITLE
border router tutorial does not work

### ISSUE THREAD

**Issue by jahess** [openthread/ot-br-posix#1687]
I found a raspberrypi 3 that I didn't mind re-imaging with the 2021-05-07-raspios-buster-armhf-lite as recommended at:

    https://openthread.io/codelabs/openthread-border-router#1

The image has a gcc version 8. It did not have git. I tried installing git as shown in the link below but failed. Maybe it is an old apt list that could easily be fixed or maybe the archives have been removed.  Regardless, the directions aren't working very well for a raspberry pi based thread border router.

Having to use an old version of raspios makes me uncomfortable from a security standpoint.  I reported this earlier this morning with:

    https://github.com/openthread/openthread/security/advisories/GHSA-h2xg-7gq5-4546#advisory-comment-77276

And, it is a development hassle.  

Thanks in advance for any suggestions in the mean time.

**Comment by jahess** [comment]
Tried updating buster with...

`
sudo apt update --upgradable
sudo apt full-upgrade
sudo apt install git
`

And gcc is still at 8 so maybe...

**Comment by jahess** [comment]
With 0895ad5 per:

    https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_thread_tools.html#installing-otbr-manually-raspberry-pi

`INFRA_IF_NAME=eth0 ./script/setup`

Got to...

```
+ sudo systemctl enable otbr-firewall
otbr-firewall.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable otbr-firewall
+ sudo systemctl start otbr-firewall
Job for otbr-firewall.service failed because the control process exited with error code.
See "systemctl status otbr-firewall.service" and "journalctl -xe" for details.
+ die 'Failed to start firewall service!'
+ echo ' *** ERROR:  Failed to start firewall service!'
 *** ERROR:  Failed to start firewall service!
+ exit 1
```

Any other suggestions?

**Comment by jahess** [comment]
Same happend with main (079bbce).

**Comment by jahess** [comment]
After attempting to install the pi desktop, rebooting, and trying to build 0895ad5 again... the build looked like it worked.  This is the status I now have...

```
pi@brtr:~/dev/ot-br-posix $ sudo service otbr-agent status
● otbr-agent.service - OpenThread Border Router Agent
   Loaded: loaded (/lib/systemd/system/otbr-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-12-29 17:45:13 MST; 2min 46s ago
  Process: 4332 ExecStartPre=/usr/sbin/service mdns start (code=exited, status=0/SUCCESS)
 Main PID: 4356 (otbr-agent)
    Tasks: 1 (limit: 2059)
   CGroup: /system.slice/otbr-agent.service
           └─4356 /usr/sbin/otbr-agent -I wpan0 -B eth0 spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=1000000 trel://eth0

Dec 29 17:45:13 brtr otbr-agent[4356]: 00:00:00.065 [I] Platform------: Execute command `ipset add otbr-ingress-deny-src-swap fdde:ad00:beef:0::/64 -exist` = 0
Dec 29 17:45:13 brtr otbr-agent[4356]: 00:00:00.074 [I] Platform------: Execute command `ipset swap otbr-ingress-deny-src-swap otbr-ingress-deny-src` = 0
Dec 29 17:45:13 brtr otbr-agent[4356]: 00:00:00.082 [I] Platform------: Execute command `ipset swap otbr-ingress-allow-dst-swap otbr-ingress-allow-dst` = 0
Dec 29 17:45:13 brtr otbr-agent[4356]: 00:00:00.082 [I] Platform------: MulticastRoutingManager: Disable: OK
Dec 29 17:45:13 brtr otbr-agent[4356]: [INFO]-BA------: Publish meshcop service OpenThread BorderRouter #1233._meshcop._udp.local.
Dec 29 17:45:13 brtr otbr-agent[4356]: 00:00:00.085 [I] Platform------: [netif] Host netif is down
Dec 29 17:45:14 brtr otbr-agent[4356]: [INFO]-MDNS----: Received reply for service OpenThread BorderRouter #1233._meshcop._udp., serviceRef = 0x1680410
Dec 29 17:45:14 brtr otbr-agent[4356]: [INFO]-MDNS----: Successfully registered service OpenThread BorderRouter #1233._meshcop._udp.
Dec 29 17:45:14 brtr otbr-agent[4356]: [INFO]-BA------: Result of publish meshcop service OpenThread BorderRouter #1233._meshcop._udp.local: OK
Dec 29 17:45:14 brtr otbr-agent[4356]: [INFO]-BA------: Result of publish meshcop service OpenThread BorderRouter #1233._meshcop._udp.local: OK
```

Still too much of a newbie to know if that is working or not.  The "Host netif down" doesn't sound good.  The pi can ping out to the internet.

**Comment by jwhui** [comment]
Closing stale issue.
