### ISSUE TITLE
Porting otbr to Toradex hardware

### ISSUE THREAD

**Issue by rfabriciors** [openthread/ot-br-posix#1694]
Hello everyone,
I'm porting ot-br to Toradex hardware, Toradex Verdin imx8mp being more exact.
I've been through issues to do this. First I needed put ipset support on Toradex Kernel, ok...But now, when I start the services I'm take the error:

otbr-agent[112]: 00:00:11.314 [C] Platform------: InitMulticastRouterSock() at multicast_routing.cpp:225: Protocol not available
otbr-agent[112]: 00:00:11.314 [C] Platform------: InitMulticastRouterSock() at multicast_routing.cpp:225: Protocol not available

I'm working with Docker containers. Initialy I did use the image openthread/otbr. after I did build my own image, but I do not still sucess. Before I form a thread network the OTBR agent behaviors are normall, but after I form network I receive the above error. I'm using the module NRF52840 (/dev/ttyACM0)

I know this is my lack of understanding, but please help me!

Following the complete error log.
Thank's all

[toradex_error.txt](https://github.com/openthread/ot-br-posix/files/10344907/toradex_error.txt)

**Comment by rfabriciors** [comment]
Guys, I realized that my wpan interface is dying. But I don't know if this is a real reason for last error report in the log showed. I realized too that after the first fail, the interface cannot up again

**Comment by jwhui** [comment]
Closing stale issue.
