### ISSUE TITLE
Version incompatibility RCP & OTBR

### ISSUE THREAD

**Issue by kenvals** [openthread/ot-br-posix#1698]
**Describe the bug** A clear and concise description of what the bug is.
I compiled the latest version of RCP from source (nrf528xx (https://github.com/openthread/ot-nrf528xx ) and commit: 6bb5eb5). Did it according to the instructions.

**To Reproduce** Information to reproduce the behavior, including:

After flashing the stick and installing it in the border...

Jan  6 19:53:39 de3cf91bbfe3 otbr-agent[191]: 51d.16:25:22.453 [I] Platform------: RCP reset: RESET_POWER_ON
Jan  6 19:53:39 de3cf91bbfe3 otbr-agent[191]: 51d.16:25:22.455 [C] Platform------: RCP API Version 7 is not in the supported range [4-6]
Jan  6 19:53:39 de3cf91bbfe3 otbr-agent[191]: 51d.16:25:22.455 [C] Platform------: CheckRcpApiVersion() at radio_spinel_impl.hpp:423: RadioSpinelIncompati

It looks like the RPC has a higher API version than the edge router, although I took the most recent sources. how to deal with it?

1. ot-br-posix commit: [adba2d9](https://github.com/openthread/ot-br-posix/commit/adba2d91d9caaf4eccec2c0b07f06e25202fe26b)

**Comment by abtink** [comment]
@kenvals,
- We have https://github.com/openthread/openthread/pull/8617 in OT core which should help address situations like this.
- In meanwhile, as workaround, you can use an older RCP firmware. You can build RCP before this commit https://github.com/openthread/openthread/commit/8b59f4d31e86c9808721413c8507c15a51ecd696 to build RCP image
