### ISSUE TITLE
Changing the web server port?

### ISSUE THREAD

**Issue by olalonde** [openthread/ot-br-posix#1721]
Is the web server configurable? What if I'd like to change the default port? I couldn't find any documentation on this. Thanks.

**Comment by jwhui** [comment]
Yes, the port is configurable via a command-line option: https://github.com/openthread/ot-br-posix/blob/b22192910dbd091ecd50446bc11c5ff5f1505f24/src/web/main.cpp#L108

**Comment by scyto** [comment]
This is great, how would i pass this into the OTBR docker container?

**Comment by jwhui** [comment]
> This is great, how would i pass this into the OTBR docker container?

Discussion continued here: https://github.com/openthread/ot-br-posix/issues/1916#issuecomment-2143559511
