### ISSUE TITLE
OT-BR on a proxmox container using Debian 11

### ISSUE THREAD

**Issue by agent-purple** [openthread/ot-br-posix#1731]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: latest
2. IEEE 802.15.4 hardware platform: nRF52840 makerdiary dongle
3. Build steps: https://openthread.io/guides/border-router/build
4. Network topology: simple

I tried to install OT-BR in a proxmox container running debian 11.
Added the config below to get the USB mounted into the privileged contaniner
See: https://coldcorner.de/2018/07/12/proxmox-usb-passthrough-fuer-lxc-container-z-wave-uzb1/

/etc/pve/lxc/xxx.conf
lxc.mount.entry: /dev/fuse dev/fuse none bind,create=file 0 0
lxc.cgroup.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/bus/usb/001/005 dev/bus/usb/001/005 none bind,optional,create=file
lxc.cgroup.devices.allow: c 166:* rwm
lxc.mount.entry: /dev/ttyACM0 dev/ttyACM0 none bind,optional,create=file

This works fine and I can see the device as /dev/ttyACM0 within the container.

Installed the software according to build steps (above).
I commented out from /opt/ot-br-posix/script/_rt_tables because it fails on debian.

```
#    if without DOCKER; then
#        sudo sh -c 'echo "" >>/etc/sysctl.conf'
#        sudo sh -c 'echo "# OpenThread configuration" >>/etc/sysctl.conf'
#        sudo sh -c 'echo "net.core.optmem_max=65536" >>/etc/sysctl.conf'
#        sudo sh -c 'sysctl -p /etc/sysctl.conf'
#    fi
```

Installation was successful, but otbr-agent failed to start.

journalctl -xe 
or 
otbr-agent -I wpan0 -B eth0 -v -d 7 spinel+hdlc+uart:///dev/ttyACM0 trel://eth0

Jan 28 23:51:22 thread-border-router otbr-agent[2796]: [NOTE]-AGENT---: Backbone interface: eth0
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: [NOTE]-AGENT---: Running 0.3.0-2f9eeee5b1-dirty
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: [NOTE]-AGENT---: Thread version: 1.3.0
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: [NOTE]-AGENT---: Thread interface: wpan0
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: [NOTE]-AGENT---: Radio URL: trel://eth0
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: [NOTE]-ILS-----: Infra link selected: eth0
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: [INFO]-NCP-----: OpenThread log level changed to 4
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: open uart failed: Operation not permitted
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: open uart failed: Operation not permitted
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: 49d.16:29:49.728 [C] Platform------: Init() at radio.cpp:116: InvalidArgument
Jan 28 23:51:22 thread-border-router otbr-agent[2796]: open uart failed: Operation not permitted
Jan 28 23:51:22 thread-border-router systemd[1]: otbr-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

Please support me to get this error fixed.

**Comment by MonicaisHer** [comment]
I am encountering the same error message 'open UART failed' while running otbr-agent within a container. Have you managed to find a solution for this issue? Thank you.

**Comment by jwhui** [comment]
Closing stale issue.
