### ISSUE TITLE
 Wpan service error: 13 - OpenThread daemon is not running

### ISSUE THREAD

**Issue by mpolinowski** [openthread/ot-br-posix#1749]
## Describe the bug:

I already [posted an issue here](https://github.com/openthread/ot-br-posix/issues/1599#issuecomment-1415812293). But I made a few changes and the Error messages I get changed.

I am starting up the `openthread/otbr:latest` docker container after plugging in the PitayaGo flashed with the [latest fw](https://github.com/makerdiary/pitaya-go/tree/master/firmware/openthread/ncp) and I see the following error messages:

### Firewall

At first I had an firewall error - forgot to run:

```bash
sudo modprobe ip_tables
sudo modprobe ip6table_filter
```

But now it is working:

```bash
ip6tables --help
ip6tables v1.8.2
...
```

And the error message I get changed:

```
+ service otbr-firewall start
+ case "$1" in
+ firewall_start
+ firewall_stop
+ ip6tables -C FORWARD -o wpan0 -j OTBR_FORWARD_INGRESS
ip6tables v1.6.1: Couldn't load target `OTBR_FORWARD_INGRESS':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
+ ip6tables -L OTBR_FORWARD_INGRESS
ip6tables: No chain/target/match by that name.
+ ipset_destroy_if_exist otbr-ingress-deny-src
+ ipset list otbr-ingress-deny-src
ipset v6.34: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6
The set with the given name does not exist
+ ipset_destroy_if_exist otbr-ingress-deny-src-swap
+ ipset list otbr-ingress-deny-src-swap
ipset v6.34: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6
The set with the given name does not exist
+ ipset_destroy_if_exist otbr-ingress-allow-dst
+ ipset list otbr-ingress-allow-dst
ipset v6.34: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6
The set with the given name does not exist
+ ipset_destroy_if_exist otbr-ingress-allow-dst-swap
+ ipset list otbr-ingress-allow-dst-swap
ipset v6.34: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6
The set with the given name does not exist
```

### Radio file

Below I see the following:

```
[NOTE]-AGENT---: Backbone interface: eth0
[NOTE]-AGENT---: Running 0.3.0-a8ba300
[NOTE]-AGENT---: Thread version: 1.3.0
[NOTE]-AGENT---: Thread interface: wpan0
[NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0
[NOTE]-ILS-----: Infra link selected: eth0
[INFO]-NCP-----: OpenThread log level changed to 5
49d.18:29:36.882 [C] Platform------: Radio file '/dev/ttyACM0' not supported
49d.18:29:36.883 [C] Platform------: Radio file '/dev/ttyACM0' not supported
49d.18:29:36.883 [C] Platform------: Init() at radio.cpp:116: InvalidArgument
49d.18:29:36.883 [C] Platform------: Radio file '/dev/ttyACM0' not supported
```

It is not labelled as an error - is this normal?

### Web Frontend

When I open the web front and try to form a network I see:

```
[INFO]-WEB-----: Border router web started on wpan0
[ERR ]-WEB-----: OpenThread daemon is not running.
[ 5215.537512] Voltage normalised (0x00000000)
[ERR ]-WEB-----: OpenThread daemon is not running.
[ERR ]-WEB-----: Wpan service error: 13
```

As described in the [other issue](https://github.com/openthread/ot-br-posix/issues/1599#issuecomment-1415812293) - inside the docker container I only see the web service but not the agent running.

## To Reproduce:

* I am now using a RasPi 3B+ with a fresh and fully updated RaspiOS Buster
* I was getting `under-voltage` and attached an external power supply. It is stable now.
* The Pitaya Go was prepared according to [Maker Diary](https://wiki.makerdiary.com/pitaya-go/openthread/getting-started/)

And I am starting the Container with:

```
docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8888:80 --dns=127.0.0.1 -it --volume /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr:latest --radio-url spinel+hdlc+uart:///dev/ttyACM0
```

### Expected behavior

The agent process should be running, allowing me to form a network through the UI.

### Console/log output

[Complete Log](https://gist.github.com/mpolinowski/6c8e9bfc7e57f4e5263f2f7ae72f2fd5)

**Comment by Majestic7979** [comment]
I have the same issue. Unusable. Using Raspberry Pi OS on a Pi 4.

**Comment by superwhd** [comment]
Sorry I didn't notice this issue previously. 

Regarding this issue, the root cause is your RCP device wasn't found at `/dev/ttyACM0`.
```
49d.18:29:36.882 [C] Platform------: Radio file '/dev/ttyACM0' not supported
```

You mentioned you're using the PitayaGo as the RCP. Not sure if you were following the guide of https://wiki.makerdiary.com/pitaya-go/openthread/openthread-border-router/#flash-the-ncp-firmware. If so, please note that this guide is not maintained by the OpenThread community so it may be outdated or not working any more.

I saw the files in https://github.com/makerdiary/pitaya-go/tree/master/firmware/openthread/ncp hasn't been updated for 5 years. It's normal that the firmware is not compatible with the latest host-side code of OTBR.

**Comment by jwhui** [comment]
Closing stale issue.
