### ISSUE TITLE
Tag new stable release and adopt release schedule

### ISSUE THREAD

**Issue by EwoutH** [openthread/ot-br-posix#1751]
It's been a while since the last stable release of OpenThread Border Router, which was in August 2018. Since then, the project has seen a lot of improvements and bug fixes, but it can be difficult for users to use of these changes without a stable release.

I think it would be really helpful if a new stable release could be created, and consistent release schedule can be created (for example every 2 or 3 months). This way, users would have a clear idea of when they can expect new features and bug fixes, and it would make planning and updating deployments a lot easier.

Also, a new stable release would show that the project is actively maintained and that the development team is dedicated to providing quality updates. This could attract new users and contributors and make existing users more likely to stick with the project.

**Comment by sangsoolee** [comment]
I agree with @EwoutH 
I hope there will be no worries about which commit id to choose when making a product.

**Comment by jwhui** [comment]
@EwoutH @sangsoolee , thanks for raising this suggestion.

Our existing git tags represent commits used to generate OpenThread reference releases used by Thread Group Test Harness releases. These tags allow developers to reference the exact code that was used in the reference test devices and also code is certifiable.

Over the past few years, the burden of certifying specific commits has passed to the OpenThread community, including component vendors and end-product vendors.

Our plan moving forward is to work with the OpenThread community and tag specific commits that have gone through certification. This allows others in the OpenThread community to know which commits are certifiable and indicates what code is being used across the ecosystem.

**Comment by jwhui** [comment]
Closing stale issue.
