### ISSUE TITLE
[Feature request] Implement the multipan stuffs from Silicon Labs into ot-br-posix

### ISSUE THREAD

**Issue by caipiblack** [openthread/ot-br-posix#1779]
We are using EFR32 dongle with multipan firmware (this is a solution from Silicon Labs to use the same dongle for Zigbee, Thread and Bluetooth communication)

Currently we have to use ot-br-posix version from gecko_sdk because they made some modifications in Openthread to support the multipan stuff that is not yet in the official repository

In their implementation, openthread connects to a daemon called cpcd:

![image](https://user-images.githubusercontent.com/29680146/223475069-1c07dba5-e412-44e9-9d97-67bd4a3062a9.png)

So maybe their modifications are around the radio-url and connection stuff 

It should be very good, to merge their stuff in the official ot-br-posix repository, so that the user will be able to use the last versions of openthread instead of versions fixed in the gecko_sdk. [gecko sdk](https://github.com/SiliconLabs/gecko_sdk.git )

**Application note:**

https://www.silabs.com/documents/public/application-notes/an1333-concurrent-protocols-with-802-15-4-rcp.pdf

**Comment by lmnotran** [comment]
Hi @caipiblack,

We're actively working on upstreaming the multipan RCP changes. Stay tuned! 

https://github.com/openthread/openthread/pull/8914

**Comment by lmnotran** [comment]
CC: @parag-silabs @romacdon @bertoldi-silabs @suveshpratapa

**Comment by jwhui** [comment]
Closing stale issue.
