### ISSUE TITLE
Child joins openthread network late

### ISSUE THREAD

**Issue by mbekirtopal** [openthread/ot-br-posix#1797]
Hello everybody .

 I am using openthread in a project. I am creating an openthread network using the stm32wb processor. I install the MTD stack software on the slaves I choose from my cards because I always want them to be child. Everything works fine, but the child device joins the openthrad network late (2 seconds). How can I lower this value?

**Comment by jwhui** [comment]
How much time are you expecting?

It typically takes at least 1 second for a Thread device to join the network. For example, the Thread Specification requires a device to wait 750ms after sending an MLE Parent Request to collect MLE Parent Response messages.

**Comment by jwhui** [comment]
Closing stale issue.
