### ISSUE TITLE
MDNS publish not updating service discovery info

### ISSUE THREAD

**Issue by Thousif-khan** [openthread/ot-br-posix#1805]
Hi,
the SRP server updates client info but sd-dns is not updating the info.
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.235 [I] SrpServer-----: Received DNS update from fde5:e34b:23c0:6932:e080:a511:604c:7318
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.388 [I] SrpServer-----: Processed DNS update info
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.388 [I] SrpServer-----:     Host:ffffffff-ffff-ffff-ffff-ffffffffffff.default.service.arpa.
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.388 [I] SrpServer-----:     Lease:7200, key-lease:1209600, ttl:7200
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.388 [I] SrpServer-----:     1 host address(es):
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.388 [I] SrpServer-----:       fde5:e34b:23c0:6932:e080:a511:604c:7318
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.388 [I] SrpServer-----:     Adding service 'ffffffff-ffff-ffff-ffff-ffffffffffff._elementuredev._udp.default.service.arpa.'
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.388 [I] SrpServer-----: SRP update handler is notified (updatedId = 1255995980)
Mar 28 09:07:55 gateway otbr-agent[1406]: [INFO]-ADPROXY-: Advertise SRP service updates: host=ffffffff-ffff-ffff-ffff-ffffffffffff.default.service.arpa.
Mar 28 09:07:55 gateway otbr-agent[1406]: [INFO]-ADPROXY-: Handle publish SRP service 'ffffffff-ffff-ffff-ffff-ffffffffffff._elementuredev._udp.default.service.arpa.': OK
Mar 28 09:07:55 gateway otbr-agent[1406]: [INFO]-ADPROXY-: Waiting for more publishing callbacks 1
Mar 28 09:07:55 gateway otbr-agent[1406]: [INFO]-ADPROXY-: Handle publish SRP host 'ffffffff-ffff-ffff-ffff-ffffffffffff.default.service.arpa.': OK
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.389 [I] SrpServer-----: Handler result of SRP update (id = 1255995980) is received: OK
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.389 [I] SrpServer-----: Update host ffffffff-ffff-ffff-ffff-ffffffffffff.default.service.arpa.
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.389 [I] SrpServer-----: Update existing service 'ffffffff-ffff-ffff-ffff-ffffffffffff._elementuredev._udp.default.service.arpa.'
Mar 28 09:07:55 gateway otbr-agent[1406]: 00:05:13.389 [I] SrpServer-----: Send success response with granted lease: 7200 and key lease: 680400

avahi-browser gives resolve issue.
Failed to resolve service 'ffffffff-ffff-ffff-ffff-ffffffffffff' of type '_elementuredev._udp' in domain 'local': Timeout reached
Failed to resolve service 'ffffffff-ffff-ffff-ffff-ffffffffffff' of type '_elementuredev._udp' in domain 'local': Timeout reached

**Comment by jwhui** [comment]
Closing stale issue.
