### ISSUE TITLE
Openthread on mt7688 use openwrt

### ISSUE THREAD

**Issue by ngocuong86** [openthread/ot-br-posix#1821]
I tried follow this tutorial: https://github.com/openthread/ot-br-posix/tree/main/etc/openwrt/openthread-br
But when I run: ./scripts/feeds install openthread-br
then have a error : **WARNING: No feed for package 'openthread-br' found**
How to fix it?

**Comment by bukepo** [comment]
could you share your feeds.conf and logs captured when you tried the guide?

**Comment by ngovancuong2735** [comment]
My feeds.conf:
src-git-full packages https://git.openwrt.org/feed/packages.git
src-git-full luci https://git.openwrt.org/project/luci.git
src-git-full routing https://git.openwrt.org/feed/routing.git
src-git-full telephony https://git.openwrt.org/feed/telephony.git
#src-git-full video https://github.com/openwrt/video.git
#src-git-full targets https://github.com/openwrt/targets.git
#src-git-full oldpackages http://git.openwrt.org/packages.git
#src-link custom /usr/src/openwrt/custom-feed
src-link openthread /home/cuong/ot-br-posix/etc/openwrt

**Comment by caipiblack** [comment]
Hello,
Which commit of ot-br-posix is used ?

**Comment by ngovancuong2735** [comment]
I use 19.07 but I tried 22.03 It's success.

**Comment by jwhui** [comment]
Closing stale issue.
