### ISSUE TITLE
Supported CPU architectures

### ISSUE THREAD

**Issue by silabs-PhilippL** [openthread/ot-br-posix#1836]
Hi, 
can the OTBR run on 64bit CPUs, for instance: 

- https://ark.intel.com/content/www/de/de/ark/products/78475/intel-atom-processor-e3845-2m-cache-1-91-ghz.html
- https://ark.intel.com/content/www/de/de/ark/products/93356/intel-xeon-processor-d1567-18m-cache-2-10-ghz.html

or AMD x64 Ryzen CPUs?

Are there any plans to support it on Windows OS?

Thanks

**Comment by jwhui** [comment]
OTBR is generally implemented using standard C/C++, so it should be pretty portable to different CPU architectures. OTBR on Linux on 64-bit CPUs is very common.

I'm not aware of any active efforts to support native Windows.

**Comment by jwhui** [comment]
Closing stale issue.
