### ISSUE TITLE
dbus-daemon leaks memory when OTBR agent exits due to unrecoverable / critical issue 

### ISSUE THREAD

**Issue by AlanLCollins** [openthread/ot-br-posix#1841]
**Describe the bug** 
We found dbus-daemon leaks memory when OTBR agent exits due to unrecoverable / critical issue for e.g  RCP fails to respond within TX_WAIT_US (default = 5s), HandleRcpTimeout() .
https://github.com/openthread/openthread/blob/0ca01ae501e744d9b4ce43c0c92ebfd140d262aa/src/lib/spinel/radio_spinel_impl.hpp#L2301
When OTBR agent exits and restarts, it does not provide any notification to other services connected over dbus which are using libotbr-dbus-client library.

**Potential solution**:

Register a callback method to be called from otbr::DBus::ThreadApiDBus, when otbr-agent restarts/crashes.
For this, ThreadApiDBus needs to filter dbus messages and handle below signals: NameLost, NameOwnerChanged

```
signal time=1682137189.123400 sender=org.freedesktop.DBus -> destination=:1.35 serial=18 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string "io.openthread.BorderRouter.ot0"
signal time=1682137189.123455 sender=org.freedesktop.DBus -> destination=(null destination) serial=9 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "io.openthread.BorderRouter.ot0"
   string ":1.35"
   string ""
```

With this, clients will be able to do cleanup for the dbus connection they have and not leak any memory due to messages being sent to previous dbus connection instance.

![image](https://user-images.githubusercontent.com/93798708/234430396-1e517e2f-9c69-4932-8d2a-1ed2d44a331a.png)

**proposed flow**: 
1. OTBR agent identifies unrecoverable issue, is ready for DieNow(), 
2. It should read all dbus pending messages (to clean the queue) 
3. Then send a notification, and triggers DieNow() 
4. OTBR dbus client catches notification, it should read all dbus pending messages (to clean the queue) 
5. then gives callback to Thread app (host application using dbus library, as shown in image above) 
6. Thread app is responsible to close dbus connection + other vendor-specific clean up

**Comment by bukepo** [comment]
@AlanLCollins thanks for reporting this issue! could you please point to any reference that shows d-bus client must read all pending messages and may otherwise result in memory leak?

**Comment by AlanLCollins** [comment]
Hello @bukepo , these are the references that we found:
https://gitlab.freedesktop.org/dbus/dbus/-/issues/36 
https://gitlab.freedesktop.org/dbus/dbus/-/issues/105 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879898 
You can reproduce by periodically (~10s) & manually killing ot-rcp/otbr-agent. Confirm by monitoring dbus-daemon memory consumption (e.g. procrank / perfdump for Android)

**Comment by AlanLCollins** [comment]
Hello @bukepo , Did you had the chance to look at the references? Does the proposed flow makes sense? 
Cheers! 
Alan

**Comment by jwhui** [comment]
Closing stale issue.
