### ISSUE TITLE
Docker Toolbox is not available anymore

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [openthread/ot-br-posix#1843]
**Describe the bug**

https://openthread.io/guides/border-router/docker#mac_or_windows has a link to Docker Toolbox (https://docs.docker.com/toolbox/) which now redirects users to https://docs.docker.com/desktop/. If the user then installs Docker Desktop and uses it, the RCP dongle mounted into the docker image is only a directory and ot-br-posix does not work.

**Expected behavior**

Either clearly document that Docker Mac and Windows does not work for now and direct users to installing ot-br-posix from source on Mac (Windows?) or find a way how it works with Docker Desktop.

**Comment by markus-becker-tridonic-com** [comment]
Related to https://github.com/openthread/ot-br-posix/issues/1347.

**Comment by jwhui** [comment]
Closing stale issue.
