### ISSUE TITLE
Built-in NAT64 not functional with well-known prefix, external tayga works

### ISSUE THREAD

**Issue by thedevleon** [openthread/ot-br-posix#1858]
**Describe the bug**
We have devices using the Nordic nRF5340 running nRF Connect SDK v2.2.0 and OpenThread 1.2.
For the border router, we are using ot-br-posix running on a Raspberry Pi 4B 4GB. 
The RCP is a nRF52840 Dongle flashed with ot-rcp from https://github.com/openthread/ot-nrf528xx.

The issue that we are experiencing (both with the docker image and the native install), is that the NAT64 translator is not working as we expect it to.
We are using the well-known prefix (64:ff9b::/96) to create IPv6 addresses from IPv4 ones, i.e. `[64:ff9b:XXX.XXX.XXX.XXX]`. Using IPv4 addresses directly in Zephyr doesn't seem to be an option, since the networking layer for thread in zephyr only expects IPv6 addresses. Providing a IPv4 address i.e. to ping or open a socket (as shown the in many of the examples) results in an Invalid argument error.

Checking the nat64 state on the border router, it seems to be active:
```
$ sudo ot-ctl nat64 state
PrefixManager: Active
Translator: Active
Done
```

However, the NAT64 table shown with `ot-ctl nat64 mappings` stays empty and none of our devices are able to reach the internet:
```
$ sudo ot-ctl nat64 mappings
|                  | Address                                                     |        | 4 to 6                  | 6 to 4                  |
+------------------+-------------------------------------------------------------+--------+-------------------------+-------------------------+
| ID               | IPv6                                     | IPv4             | Expiry | Pkts     | Bytes        | Pkts     | Bytes        |
+------------------+------------------------------------------+------------------+--------+----------+--------------+----------+--------------+
Done
```

When we disable the built-in nat64 (by building with `NAT64=0` or `ot-ctl nat64 disable`) and install a third-party NAT64 service (namely tayga) on the RPi instead, our devices can successfully reach IPv4 addresses in the internet using the well-known prefix.

Tayga is configured with the following configs (as outlined in https://blog.djoproject.net/2020/09/13/using-a-raspberry-pi-as-a-nat64-gateway/):
`/etc/tayga.conf`:
```
tun-device nat64
ipv4-addr 192.168.255.1
ipv6-addr 2001:db8::2
prefix 64:ff9b::/96
dynamic-pool 192.168.255.0/24
data-dir /var/spool/tayga
```

`/etc/default/tayga`:
```
CONFIGURE_IFACE="yes"
CONFIGURE_NAT44="no"
IPV4_TUN_ADDR=""
IPV6_TUN_ADDR=""
DAEMON_OPTS=""
```

`/etc/sysctl.conf`:
```
[...]
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
[...]
```

With tayga running, we also get an additional `nat64` interface listed in `ip addr`, which is not present when the ot-br NAT64 is running.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
> master on [ot-br-posix](https://github.com/openthread/ot-br-posix) and [ot-nrf528xx](https://github.com/openthread/ot-nrf528xx).
> OPENTHREAD/d6221f4; POSIX; May 3 2023 11:27:27

2. IEEE 802.15.4 hardware platform
> nRF52840 Dongle flashed with ot-nrf528xx
> OPENTHREAD/thread-reference-20200818-2444-gd6221f4d3; NRF52840; May 3 2023 11:37:07

3. Build steps
>Docker or native install with eth0 as the interface and NAT64=1.

4. Network topology
> 1-5 devices in close proximity to the nRF52840 dongle.

**Expected behavior**
We would expect devices to reach IPv4 addresses easily just by using the well-known prefix. 
Do we need to enable or set the well-known prefix somewhere?

**Comment by jwhui** [comment]
> We would expect devices to reach IPv4 addresses easily just by using the well-known prefix.
> Do we need to enable or set the well-known prefix somewhere?

Because all Thread Border Routers implement the NAT64 function, Thread does not support the NAT64 well-known prefix (`64:ff9b::/96`). Instead, Thread Border Routers dynamically generate their own NAT64 prefixes and publish then as necessary in the Thread Network Data.

Thread End Devices must obtain the NAT64 prefix from the Thread Network Data and synthesize their own IPv6 addresses - see [`otNat64SynthesizeIp6Address()`](https://openthread.io/reference/group/api-nat64#otnat64synthesizeip6address)

You may also find the [Thread Border Router - Provide Internet access via NAT64 codelab](https://openthread.io/codelabs/openthread-border-router-nat64) useful.

**Comment by thedevleon** [comment]
> > We would expect devices to reach IPv4 addresses easily just by using the well-known prefix.
> > Do we need to enable or set the well-known prefix somewhere?
> 
> Because all Thread Border Routers implement the NAT64 function, Thread does not support the NAT64 well-known prefix (`64:ff9b::/96`). Instead, Thread Border Routers dynamically generate their own NAT64 prefixes and publish then as necessary in the Thread Network Data.
> 
> Thread End Devices must obtain the NAT64 prefix from the Thread Network Data and synthesize their own IPv6 addresses - see [`otNat64SynthesizeIp6Address()`](https://openthread.io/reference/group/api-nat64#otnat64synthesizeip6address)
> 
> You may also find the [Thread Border Router - Provide Internet access via NAT64 codelab](https://openthread.io/codelabs/openthread-border-router-nat64) useful.

Thanks for the quick response. After a lot of digging, this is also what I found when looking at the CLI code yesterday evening.

Maybe the documentation / co-labs could be updated to specifically mention that custom implementations (i.e. not the CLI) will need to use the `[otNat64SynthesizeIp6Address()](https://openthread.io/reference/group/api-nat64#otnat64synthesizeip6address)` instead of using the well-known prefix? For example, here it still mentions the well-known prefix (https://openthread.io/guides/border-router/external-commissioning/join#ping_the_external_internet).

**Comment by jwhui** [comment]
> Maybe the documentation / co-labs could be updated to specifically mention that custom implementations (i.e. not the CLI) will need to use the [otNat64SynthesizeIp6Address()](https://openthread.io/reference/group/api-nat64#otnat64synthesizeip6address) instead of using the well-known prefix? For example, here it still mentions the well-known prefix (https://openthread.io/guides/border-router/external-commissioning/join#ping_the_external_internet).

Thanks for pointing this out. We can certainly make updates to the docs. Note that the docs are hosted on GitHub as well, so anyone is able to submit a PR with proposed changes. Are you willing to propose a change?

https://github.com/openthread/ot-docs/blob/main/site/en/guides/border-router/external-commissioning/join.md#ping-the-external-internet

**Comment by thedevleon** [comment]
> > Maybe the documentation / co-labs could be updated to specifically mention that custom implementations (i.e. not the CLI) will need to use the [otNat64SynthesizeIp6Address()](https://openthread.io/reference/group/api-nat64#otnat64synthesizeip6address) instead of using the well-known prefix? For example, here it still mentions the well-known prefix (https://openthread.io/guides/border-router/external-commissioning/join#ping_the_external_internet).
> 
> Thanks for pointing this out. We can certainly make updates to the docs. Note that the docs are hosted on GitHub as well, so anyone is able to submit a PR with proposed changes. Are you willing to propose a change?
> 
> https://github.com/openthread/ot-docs/blob/main/site/en/guides/border-router/external-commissioning/join.md#ping-the-external-internet

Oh, I didn't know the docs were hosted on GitHub. I will make a PR to update the documentation soon. 
On that note, can I also propose changes to the colabs? Specifically for the NAT64 colab (https://openthread.io/codelabs/openthread-border-router-nat64#6), I would like to add the same notice on the final page.

**Comment by jwhui** [comment]
> On that note, can I also propose changes to the colabs? Specifically for the NAT64 colab (https://openthread.io/codelabs/openthread-border-router-nat64#6), I would like to add the same notice on the final page.

Please do! We host the docs on GitHub so that anyone can help contribute. Thanks!
