### ISSUE TITLE
Joining an existing Thread network, i.e. two BRs on the same Thread network

### ISSUE THREAD

**Issue by dtodor** [openthread/ot-br-posix#1878]
We are unable to join an existing Thread network. Here is the setup:
- a Border Router acting as Thread leader
- a second Border Router on the same LAN segment

We've tried initialising the dataset of the second BR with just the network key, but it does not join the Thread network. Is this scenario currently supported? How do we configure the second BR?

**Comment by wgtdkp** [comment]
You should set the same Active Operational Dataset on the 2nd BR.

You can get the dataset HEX string from the 1st BR with CLI command:
```
> dataset active -x
```

And set it to the 2nd BR with CLI command:
```
> dataset set active <THE-DATASET-HEX-STRING>
```

You can find more details of the `dataset` command at https://github.com/openthread/openthread/blob/main/src/cli/README_DATASET.md

If you are initializing the BRs programmatically, you can below APIs to read and write active dataset:
1. https://openthread.io/reference/group/api-operational-dataset#otdatasetgetactivetlvs
2. https://openthread.io/reference/group/api-operational-dataset#otdatasetsetactivetlvs

**Comment by dtodor** [comment]
Thank you, we were able to join the Thread network of the other OTBR. We can also ping between the RCPs using the link-local addresses (e.g. `fe80:0:0:0:c822:19b4:ebe6:7af3`), which I assume requires Thread connectivity.

**Comment by jwhui** [comment]
It should be possible join a new Thread device with just the Thread Network Key - see this [Quick Start](https://github.com/openthread/openthread/blob/main/src/cli/README_DATASET.md#quick-start) guide.

**Comment by dtodor** [comment]
This is what we've tried initially. Unfortunately only using the network key the OTBR was not joining the other Thread network.

**Comment by jwhui** [comment]
> This is what we've tried initially. Unfortunately only using the network key the OTBR was not joining the other Thread network.

I just validated that this works. Can you provide more information about the CLI and/or source code you used? Enough for someone else to reproduce the problem?

**Comment by dtodor** [comment]
I just followed the guide:
```
> dataset networkkey dfd34f0f05cad978ec4e32b0413038ff
Done
> dataset commit active
Done

> ifconfig up
Done
> thread start
Done
```

The only thing that was returned when calling `dataset active` was the previously set network key. We are using a relatively up-to-date commit: `9185bdaaf4396a0b0da3d266862a706a9a03072f`. Before trying to join the network of the first OTBR, the second OTBR was already configured with its one network. Maybe I wasn't resetting the dataset properly?

**Comment by dtodor** [comment]
What would be a properly way to reset the existing dataset and init it with just the network key?

**Comment by abtink** [comment]
You probably need to factory reset device before setting the new dataset? It my have had info from past.
- `factoryreset`  cli command

**Comment by dtodor** [comment]
I'm pretty sure I've tried the factory reset command, but we'll give it a go tomorrow again. Thank you.

**Comment by jwhui** [comment]
@dtodor , can you start with how you configured the first BR and also provide CLI output of `dataset active`?

**Comment by dtodor** [comment]
Yes, will do this tomorrow, don't have access to the devices right now. But generally we do the initialisation like this:

```
ot-ctl dataset init new
ot-ctl dataset commit active
ot-ctl ifconfig up
ot-ctl thread start
ot-ctl dataset active -x
```

**Comment by jwhui** [comment]
@dtodor , it's also worth mentioning that MLE Discovery messages are only sent to the configured PAN ID (you can use `panid` CLI to view the current configuration. If the PAN ID is NOT configured to the broadcast PAN ID (`0xffff`) , then the device will only try to attach to networks matching the configured PAN ID.

The `factoryreset` command should reset PAN ID state back to the broadcast PAN ID.

**Comment by dtodor** [comment]
OK, good to know. We'll test again with the `factoryreset` command.

**Comment by dtodor** [comment]
First OTBR:
```
> ot-ctl dataset active 
Active Timestamp: 1
Channel: 22
Channel Mask: 0x07fff800
Ext PAN ID: 882079ca722b813b
Mesh Local Prefix: fd3f:cb21:ad9c:75a6::/64
Network Key: ce3bee8aeeb29e87d304198c1c6547ea
Network Name: OpenThread-abc0
PAN ID: 0xabc0
PSKc: c9f39390f00a0836c18da55bf9547f4d
Security Policy: 672 onrc
Done
```

Second OTBR after `factoryreset`:
```
> ot-ctl dataset active
Error 23: NotFound
```

Now setting the network key in the second OTBR:
```
> ot-ctl dataset networkkey ce3bee8aeeb29e87d304198c1c6547ea
Done
> ot-ctl dataset commit active
Done
> ot-ctl ifconfig up
Done
> ot-ctl thread start
Done
```

Afterwards the second OTBR successfully connects to the network of the first OTBR:
```
> ot-ctl dataset active
2023:05:23T07:46:15.459Z [I] Platform------: Session socket is ready
Active Timestamp: 1
Channel: 22
Channel Mask: 0x07fff800
Ext PAN ID: 882079ca722b813b
Mesh Local Prefix: fd3f:cb21:ad9c:75a6::/64
Network Key: ce3bee8aeeb29e87d304198c1c6547ea
Network Name: OpenThread-abc0
PAN ID: 0xabc0
PSKc: c9f39390f00a0836c18da55bf9547f4d
Security Policy: 672 onrc
Done
```

So the problem was probably not resetting the second OTBR properly. Thank you for the support!
