### ISSUE TITLE
SRP server is disabled when the OTBR loses WLAN connectivity

### ISSUE THREAD

**Issue by etiennedm** [openthread/ot-br-posix#1955]
**Describe the bug**
SRP server is disabled when the OTBR loses WLAN connectivity.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: 569d0733c6d76d0b55f1db40aabd40eaf7ac4fb0
2. IEEE 802.15.4 hardware platform: Nordic nrf52840
3. OTBR services built with `WEB_GUI=1 NAT64=1 INFRA_IF_NAME=eth0 OTBR_MDNS=avahi ./script/setup`
4. Raspberry Pi (OTBR) is connected to a wifi AP running on my laptop, which allows me to easily turn it on and off. I am logged in on the OTBR through a USB-UART adapter.

**Expected behavior**
The goal was to make sure the Thread devices can communicated with the LwM2M server running on the OTBR, even when it is not connected to the internet or any other network. Following the great advice given [here](https://github.com/openthread/ot-br-posix/issues/1359) I wanted to make the LwM2M server discoverable with SRP on the Thread network, instead of relying on Avahi like I was until now.

When the Wifi AP is up I get the following on the OTBR:
```bash
$ sudo ot-ctl netdata show
Prefixes:
fdfa:f767:79d8:1::/64 paos low 8400
Routes:
fc00::/7 sa med 8400
fdfa:f767:79d8:2:0:0::/96 sn low 8400
Services:
44970 01 67000500000e10 s 8400
44970 5d fd4200bc7d7f4bd4bf8d233440068760d123 s 8400
Contexts:
fdfa:f767:79d8:1::/64 1 c
Done

$ sudo ot-ctl srp server state
running
Done
```

As soon as I bring the Wifi AP down it seems like the SRP server is disabled:
```bash
$ sudo ot-ctl netdata show
Prefixes:
Routes:
Services:
44970 01 67000500000e10 s 8400
Contexts:
fdfa:f767:79d8:1::/64 1 -
Done

$ sudo ot-ctl srp server state
disabled
Done
```

Is this expected? Am I supposed to manually restart the SRP server? What would you recommend to make sure that the services that I want to be advertised by the OTBR's SRP client are persisted through state changes in the otbr-agent, or reboots of the OTBR?

**Comment by abtink** [comment]
This is a feature/behavior of SRP srver (`AutoEnableMode`).
It can be controlled using SPR servers's API: `otSrpServerSetEnabled()` and `otSrpServerSetAutoEnableMode()`:

https://github.com/openthread/openthread/blob/e958f8827ede37d543e962513d332d00dab6b1c3/include/openthread/srp_server.h#L244-L276

```c++
/**
 * Enables/disables the SRP server.
 *
 * On a Border Router, it is recommended to use `otSrpServerSetAutoEnableMode()` instead.
 *
 * @param[in]  aInstance  A pointer to an OpenThread instance.
 * @param[in]  aEnabled   A boolean to enable/disable the SRP server.
 *
 */
void otSrpServerSetEnabled(otInstance *aInstance, bool aEnabled);

/**
 * Enables/disables the auto-enable mode on SRP server.
 *
 * Requires `OPENTHREAD_CONFIG_BORDER_ROUTING_ENABLE` feature.
 *
 * When this mode is enabled, the Border Routing Manager controls if/when to enable or disable the SRP server.
 * SRP sever is auto-enabled if/when Border Routing is started and it is done with the initial prefix and route
 * configurations (when the OMR and on-link prefixes are determined, advertised in emitted Router Advertisement message
 * on infrastructure side and published in the Thread Network Data). The SRP server is auto-disabled if/when BR is
 * stopped (e.g., if the infrastructure network interface is brought down or if BR gets detached).
 *
 * This mode can be disabled by a `otSrpServerSetAutoEnableMode()` call with @p aEnabled set to `false` or if the SRP
 * server is explicitly enabled or disabled by a call to `otSrpServerSetEnabled()` function. Disabling auto-enable mode
 * using `otSrpServerSetAutoEnableMode(false)` will not change the current state of SRP sever (e.g., if it is enabled
 * it stays enabled).
 *
 * @param[in] aInstance   A pointer to an OpenThread instance.
 * @param[in] aEnabled    A boolean to enable/disable the auto-enable mode.
 *
 */
void otSrpServerSetAutoEnableMode(otInstance *aInstance, bool aEnabled);
```

**Comment by etiennedm** [comment]
Well thank you! I should have looked a little deeper into OpenThread's documentation... Do you know why this would be desirable? The SRP server might be used by devices attached to the Thread network to learn about each other, without requiring any off-mesh connectivity.

**Comment by abtink** [comment]
`AutoEnableMode` serves two purposes:

1. It enables the SRP server after the Border Router (BR) has completed the initial prefix and route configuration. This ensures that clients do not need to re-register due to receiving a new OMR prefix and address. It also ensures that services are advertised on the AIL (adjacent infrastructure link) only after the routes are properly set and there is end-to-end reachability between devices on the AIL and Thread mesh. Without this, we could face issues where a service is discoverable on the AIL, but we cannot communicate with it because the routes are not yet advertised and configured.

2. It disables the SRP server when the device is no longer acting as a BR. This is because we want clients that registered with this server to switch to another server/BR that is still acting as a BR and connected to the AIL. This ensures that the clients are still advertised on the AIL (and thus discoverable on the AIL).

**Comment by etiennedm** [comment]
Yes it makes sense! Thanks for the explanation.
