### ISSUE TITLE
There is issue when otbr-agent service stare

### ISSUE THREAD

**Issue by WooshinKang** [openthread/ot-br-posix#1960]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

I am using ubuntu 18.04. 
How can i fix it ?

● otbr-agent.service - OpenThread Border Router Agent
   Loaded: error (Reason: Exec format error)
   Active: inactive (dead)

● otbr-web.service - Border Router Web
   Loaded: loaded (/lib/systemd/system/otbr-web.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2023-08-03 17:06:29 KST; 10min ago
 Main PID: 1100 (otbr-web)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/otbr-web.service
           └─1100 /usr/sbin/otbr-web

charmk@charmk-MINIPC-PN50:/usr/sbin$ file otbr*
otbr-agent: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=4882e5ecfd36998fd529ddf1c944f2a37df8c3fe, not stripped
otbr-web:   ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=1b7cc0ae041ba41925213a500496562a7cd21bd4, not stripped

**Comment by WooshinKang** [comment]
charmk@charmk-MINIPC-PN50:~/Matter/ot-br-posix$ dmesg | grep otbr*
[    2.020561] systemd[1]: /lib/systemd/system/otbr-agent.service:9: Executable path is not absolute: service mdns start
[    2.040468] systemd[1]: otbr-agent.service: Cannot add dependency job, ignoring: Unit otbr-agent.service is not loaded properly: Exec format error.

charmk@charmk-MINIPC-PN50:~/Matter/ot-br-posix$ sudo service otbr-agent status
● otbr-agent.service - OpenThread Border Router Agent
   Loaded: error (Reason: Exec format error)
   Active: inactive (dead)

 8월 03 19:32:09 charmk-MINIPC-PN50 systemd[1]: /lib/systemd/system/otbr-agent.service:9: Executable path is not absolute: service mdns start
 8월 03 19:32:10 charmk-MINIPC-PN50 systemd[1]: /lib/systemd/system/otbr-agent.service:9: Executable path is not absolute: service mdns start
 8월 07 12:59:45 charmk-MINIPC-PN50 systemd[1]: /lib/systemd/system/otbr-agent.service:9: Executable path is not absolute: service mdns start
 8월 07 12:59:45 charmk-MINIPC-PN50 systemd[1]: /lib/systemd/system/otbr-agent.service:9: Executable path is not absolute: service mdns start
 8월 07 12:59:54 charmk-MINIPC-PN50 systemd[1]: /lib/systemd/system/otbr-agent.service:9: Executable path is not absolute: service mdns start
 8월 07 12:59:54 charmk-MINIPC-PN50 systemd[1]: /lib/systemd/system/otbr-agent.service:9: Executable path is not absolute: service mdns start

**Comment by bukepo** [comment]
It seems systemd cannot find the executable. Check the content of `/lib/systemd/system/otbr-agent.service` and make sure the paths are correct.

**Comment by WooshinKang** [comment]
@bukepo   Hi,

File exist in "/lib/systemd/system/"

charmk@charmk-MINIPC-PN50:/lib/systemd/system$ find . -name otbr-agent.service
./otbr-agent.service

**Comment by superwhd** [comment]
Hi @WooshinKang could you also try `service mdns start` and `service mdns status`?

**Comment by WooshinKang** [comment]
charmk@charmk-MINIPC-PN50:/lib/systemd/system$ sudo service mdns status
[sudo] charmk의 암호:
● mdns.service
   Loaded: loaded (/etc/init.d/mdns; generated)
   Active: active (running) since Thu 2023-08-03 17:06:32 KST; 3 days ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/mdns.service
           └─2528 /usr/sbin/mdnsd

 8월 03 17:06:32 charmk-MINIPC-PN50 systemd[1]: Starting mdns.service...
 8월 03 17:06:32 charmk-MINIPC-PN50 mdns[2521]: Starting Apple Darwin Multicast DNS / DNS Service Discovery daemon: mdnsd.
 8월 03 17:06:32 charmk-MINIPC-PN50 systemd[1]: Started mdns.service.
 8월 03 17:06:32 charmk-MINIPC-PN50 mDNSResponder[2528]: Default: mDNSResponder (Engineering Build) (Aug  3 2023 17:03:54) start
 8월 03 17:06:32 charmk-MINIPC-PN50 mDNSResponder[2528]: Default: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentranc
lines 1-13/13 (END)

**Comment by WooshinKang** [comment]
@superwhd 

charmk@charmk-MINIPC-PN50:~/Matter$ cat /lib/systemd/system/otbr-agent.service
[Unit]
Description=OpenThread Border Router Agent
ConditionPathExists=/usr/sbin/otbr-agent
Requires=dbus.socket
After=dbus.socket

[Service]
EnvironmentFile=-/etc/default/otbr-agent
ExecStartPre=service mdns start
ExecStart=/usr/sbin/otbr-agent $OTBR_AGENT_OPTS
KillMode=mixed
Restart=on-failure
RestartSec=5
RestartPreventExitStatus=SIGKILL

[Install]
WantedBy=multi-user.target
Alias=otbr-agent.service

I think it is already absolute path. is it right ?

**Comment by superwhd** [comment]
Try replacing this line:
```ExecStartPre=service mdns start```
with
```ExecStartPre=/usr/sbin/service mdns start```  (depending on where your `service` binary is, check `which service`).

Then run `systemctl daemon-reload` to reload the configuration.

Then `service otbr-agent restart` to see if it helps.

**Comment by WooshinKang** [comment]
@superwhd  

Thanks for your help. 
It is working now.
