### ISSUE TITLE
[openwrt] Fail in "Thread Harness Test" as a Thread Border Router.

### ISSUE THREAD

**Issue by ycc100** [openthread/ot-br-posix#1972]
I built a OpenWRT FW for Qualcomm Maple board and ported the "ot-br-posix" for implementing the Thread Border Router.
- Mother board : Qualcomm Maple board
- RCP board : SiliconLabs MG21

The "Thread Border Router" function seems work well.
But it got a lot of FAIL in "Thread Harness Test".
Attached [C_5_9_1-3.zip](https://github.com/openthread/ot-br-posix/files/12365916/C_5_9_1-3.zip) is the test report of Thread Harness Test Case "BR_1" "C_5_9_1".

Really appreciate if anyone can provide suggestions.

**Comment by jdswensen** [comment]
What configuration options are you compiling `ot-br-posix` with? It might be worth comparing what you are using to the [reference implementation](https://github.com/openthread/ot-reference-release/blob/181f96e403c02fdba58bd7209ba03b2064972c26/script/otbr-setup.bash) that is used for certification. Alternatively, given that you may be porting to a new board, it could be a kernel config issue.

**Comment by ycc100** [comment]
Following are the ot-br-posix Makefile & the kernel config file I used :
- openwrt ot-br-posix Makefile : [openwrt-ot-br-posix-Makefile.zip](https://github.com/openthread/ot-br-posix/files/12374524/openwrt-ot-br-posix-Makefile.zip)
- Kernel .config : [kernel-config.zip](https://github.com/openthread/ot-br-posix/files/12374525/kernel-config.zip)

**Comment by ycc100** [comment]
The file "C_5_9_1_teraterm.log" [in [C_5_9_1-3.zip](https://github.com/openthread/ot-br-posix/files/12365916/C_5_9_1-3.zip)] is otbr-agent log (run in foreground) .

There are several "**Failed to update ipsets**" in the log.

_otbr-agent[26301]: 00:01:47.621 [I] Platform------: Execute command `ipset flush otbr-ingress-allow-dst-swap` = 0
otbr-agent[26301]: 00:01:47.636 [I] Platform------: Execute command `ipset flush otbr-ingress-deny-src-swap` = -1
otbr-agent[26301]: 00:01:47.636 [I] Platform------: Got an error when executing command `ipset flush otbr-ingress-deny-src-swap`: `No child process`
otbr-agent[26301]: 00:01:47.636 [W] Platform------: Failed to update ipsets: `Failed`__

I am not sure why such ipset Failed happen ?
Really appreciate if anyone can provide some suggestions.

**Comment by jwhui** [comment]
Closing stale issue.
