### ISSUE TITLE
OpenThread Border Router not able to join the thread network again after turning it off for around 5 minutes

### ISSUE THREAD

**Issue by gokul-2000** [openthread/ot-br-posix#1976]
**Describe the bug**

I have IoT gateway as OpenThread Border Router with **Leader** role and other 5-10 REED(nxp k32w module) connected on the same OpenThread network as **Router** or **Child** role.

When I turned off the IoT gateway for around 5 minutes then the one of the REED will become **Leader** as per OpenThread feature(Self-healing mesh networking, with no single point of failure).

After that again I turned on the IoT gateway then the state of the Border Router became **Detached** and the Border Router was not able to again join the thread network.

1. Git commit id: 495612f696947fc38dc71e8ee3378477378cf144

**Expected behavior**

OpenThread Border Router should join the existing thread network and should again work normally as **Router** or **Leader**.
What should I need to do to reconnect the OpenThread Border Router to the same thread network?

Let me know in case of more information is required.

Thanks in advance for any support.

**Comment by jwhui** [comment]
@gokul-2000 , can you provide log output from OTBR?

**Comment by gokul-2000** [comment]
Hi @jwhui 

Thanks for the response.

I have attached one log attachment.
**Note: This is the .txt file but you have to change the extension to **.pcapng** because in the attachment pcapng is not supported**

We have registered some devices already.

We have tried below scenario:

- Turned off the Leader device for ~2 minutes and wait for the REED device to become the leader
- After one REED device becomes the leader we turned on the gateway with the RCP module and checked the ot-ctl state and the result is **"detached"**

Expected Result:

- IoT Gateway RCP module will work as a leader or router

We have found some workaround as well and worked around it we have to reboot the system and run it again.

If you want to check sniffer logs you have to use the below configuration for Wireshark.
Please follow this [wireshark configuration link](https://openthread.io/guides/pyspinel/wireshark)

please use this **Decryption key** e765ecb8915a79aef31cd3a1ee5ffcb0 to decode the sniff data.

Please let me know if you need any other data.

[ed_become_leader_try.txt](https://github.com/openthread/ot-br-posix/files/12409458/ed_become_leader_try.txt)

**Comment by gokul-bhalodiya-7** [comment]
Thanks for the response @jwhui 

Will you please explain why the **"ot-ctl state"** of the gateway become **"detached"** when the MLE Frame Counter being reinitialized after restart?

Do we need to implement any extra code in **"otbr-agent"** to save MLE Frame Counter in non-volatile storage?

Please let me know if you need more information.

**Comment by gokul-2000** [comment]
Sorry for the late response from my side.

Thanks for the response @jwhui 

After rechecking the code, I came to know that I had changed **OPENTHREAD_CONFIG_MLE_MAX_ROUTERS** macro value from **32** to **6** to decrease the network congestion.

The problem that I faced is as mentioned below:

- I connect 15 REEDs with the Gateway[Border Router].
- `ot-ctl state` of Gateway[Border Router]: **Leader**
- `ot-ctl state` of max up to 6 REEDs: **Router**
- `ot-ctl state` of other REEDs: **Child**
- Now I power off the Gateway[Border Router] for around 5 minutes.
- As I turned off the gateway for around 5 minutes then one of the REED will become **Leader** as per OpenThread feature(Self-healing mesh networking, with no single point of failure).
- Let's assume that without gateway one of the REED is **Leader**, 6 REEDs are **Router** and others are **Child**.
- Now I turned on the gateway but gateway is not able to rejoin the existing network as the value of **OPENTHREAD_CONFIG_MLE_MAX_ROUTERS** is **6** already.
- So that `ot-ctl state` of Gateway[Border Router]: **Detached**
- Should I change the value of **OPENTHREAD_CONFIG_MLE_MAX_ROUTERS** from **6** to **32**?
- Is there any method to rejoin the thread network as **Leader**?
- Is there any method to rejoin the Border Router in the existing thread network?

Let me know in case of more information is required.

Thanks in advance for any help/support.

**Comment by gokul-bhalodiya-7** [comment]
Thanks for the response @abtink 

> I strongly suggest keeping the `OPENTHREAD_CONFIG_MLE_MAX_ROUTERS` as is (32). Otherwise,you are not compliant with Thread spec and can see unexpected behaviour.

Okay, I will keep the `OPENTHREAD_CONFIG_MLE_MAX_ROUTERS` as is (32).

I have the below-mentioned situation, Please suggest possible solutions.
- Gateway(Border Router) as **Leader** role formed openthread network.
- I connect around 100 REED devices to this openthread network.
- Let's assume 32 REED devices obtain **Router** role in this openthread network.
- Now i turn off the Gateway(Border Router) for around 5 minutes.
- So that one of the REED device will become **Leader** as per OpenThread feature(Self-healing mesh networking, with no single point of failure) and other 32 devices are as **Router** role and remaining devices as **Child** role.
- Now i turn on the Gateway(Border Router), but it fails to rejoin the network as the network already has 1 **Leader** and max number of **Routers(32)**.
- Gateway got **Detached** from openthread network and not able to rejoin the network.
- What should i need to do to rejoin the Gateway(Border Router) to the existing openthread network.

Let me know in case of more information is required.

Thanks in advance for any help/support.

**Comment by abtink** [comment]
> Gateway got Detached from openthread network and not able to rejoin the network.

Even if there are already max number of routers, the new device (gateway in this case) should be able to attach as a REED to the network. An end-device (e.g., REED) can still act as a Border Router for the network, so gateway after attaching as a REED can still function as a Border Router.

If your gateway does not attach as a REED, you may want to invertigate this (check out the logs)?

**Comment by abtink** [comment]
> Now i turn on the Gateway(Border Router), but it fails to rejoin the network as the network already has 1 Leader and max number of Routers(32). So that there are two situations occur, as mentioned below:
> 1. Gateway got Detached from openthread network and not able to rejoin the network.
> 2. Gateway shows Leader role but the other active openthread network with the same dataset credentials has 1 Leader and its Router and Child devices.

Gateway can join the mesh as an end-device (or [REED](https://openthread.io/guides/thread-primer/node-roles-and-types#full_thread_device)) which is perfectly fine. Note that a gateway device can act as a Border Router while being a REED. A Border Router does not need to take a router  role within Thread mesh.

Generally every device first attaches as an end-device and then asks to be promoted to router role.

**Comment by gokul-bhalodiya-7** [comment]
Thanks for the quick response, really appreciated! @abtink 

> Gateway can join the mesh as an end-device (or [REED](https://openthread.io/guides/thread-primer/node-roles-and-types#full_thread_device)) which is perfectly fine. Note that a gateway device can act as a Border Router while being a REED. A Border Router does not need to take a router role within Thread mesh.

I got your point.

> 1. Gateway got Detached from openthread network and not able to rejoin the network.

> 2. Gateway shows Leader role but the other active openthread network with the same dataset credentials has 1 Leader and its Router and Child devices.

Any idea on scenario 1 and scenario 2.

Let me know in case of more information is required.

Thanks in advance for any help/support.

**Comment by abtink** [comment]
Scenario 1 should not be possible:
- If an FTD device (Gateway in your case) has correct Operational Dataset, it cannot stay detached. It will first try to find other nodes and attach to mesh. If it cannot find any other node (after multiple attempts), it will start as leader itself (assuming it is the first/only node in mesh).

Scnario 2: If you see two leaders (for same Operational Dataset), it means the network is partitioned (devices are not within the RF range of each other).

**Comment by jwhui** [comment]
@gokul-bhalodiya-7 , can you validate that the transmitted MAC / MLE Frame Counter values do not go backwards after the reset?

**Comment by gokul-2000** [comment]
Thanks for the response @abtink, @jwhui 

> Gateway shows Leader role but the other active open-thread network with the same dataset credentials has 1 Leader and its Router and Child devices.

Gateway and REED have the same open-thread credentials and are in RF range(both kept at 2 feet distance) still both displayed as a **Leader** role. Logs attached [syslog.txt](https://github.com/openthread/ot-br-posix/files/12594784/syslog.txt).

Please check the Screenshot as well with the dataset and state.
![Leader_End_device_state](https://github.com/openthread/ot-br-posix/assets/138658466/0bd4d6dc-ead2-439e-8137-bf86ac8f6d0d)
![lEADER_rcp_state](https://github.com/openthread/ot-br-posix/assets/138658466/f022d7b3-f739-4dc6-90cf-be2acb606501)

I have attached the wireshark log as well to check sniffer logs.

If you want to check sniffer logs you have to use the below configuration for Wireshark.
Please follow this [wireshark configuration link](https://openthread.io/guides/pyspinel/wireshark)

please use this Decryption key **e765ecb8915a79aef31cd3a1ee5ffcb0** to decode the sniff data.
 Note: This is the .txt file but you have to change the extension to .pcapng because in the attachment pcapng is not supported
[same_nw_two_leader.txt](https://github.com/openthread/ot-br-posix/files/12594809/same_nw_two_leader.txt)

**Comment by gokul-2000** [comment]
Hi @abtink, @jwhui,

Do you guys have any updates on the issue?

Please let me know in case you need more information.

Thanks in advance for any help/support.

**Comment by abtink** [comment]
How do you start your gateway? 
Do you maybe call `state leader` CLI command or the `otThreadBecomeLeader()` API from your application code? These are intended for testing and should not be used. 

Here is filtered logs you posted (all `Mle` message).
- Any device would try 6 attach attempts before assuming it is the only/first device and taking over leader role. This is not what we see in the logs.
- We see in your logs that only one attach attempt (and we see device does indeed find a parent and even sends "Child ID Request" to it) but soon afterwards it show it its role being change to `leader`. This hints at use of the APIs above). 
```
Sep 13 06:24:11 centauri-imx6ull bae-agent[419]: 00:00:00.545 [I] Mle-----------: AttachState Idle -> Start
Sep 13 06:24:14 centauri-imx6ull bae-agent[419]: 00:00:04.411 [N] Mle-----------: Attach attempt 1, AnyPartition reattaching 
with Active Dataset
Sep 13 06:24:14 centauri-imx6ull bae-agent[419]: 00:00:04.411 [I] Mle-----------: AttachState Start -> ParentReq
Sep 13 06:24:14 centauri-imx6ull bae-agent[419]: 00:00:04.411 [I] Mle-----------: Send Parent Request to routers (ff02:0:0:0:
0:0:0:2)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.557 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:3021:9fbc:1c3c:3182,0x2400)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.567 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:605d:c4c6:1df:e96e,0x9800)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.591 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:14e8:e516:8d54:527e,0xe800)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.650 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:1426:1e9:4d6c:e3bd,0xc400)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.666 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:3436:9682:c580:8473,0xf400)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.695 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:d095:8517:4c7f:ca2d,0xa400)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.727 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:78bf:c390:8f40:6384,0x4800)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.735 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:78bf:c390:8f40:6384,0x4800)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.748 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:14ea:fb82:6020:de22,0x7000)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.755 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:14ea:fb82:6020:de22,0x7000)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.756 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:bc83:8f19:b66a:747a,0xc000)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.763 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:c89b:f96c:28a9:909f,0xdc00)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.804 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:fcbf:26b9:1a71:3b4f,0x2000)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.881 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:1057:3e31:30df:bf92,0xac00)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.900 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:4cdc:6748:698e:34c3,0xec00)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:04.999 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:985c:f6fc:9a81:a7a4,0x8000)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:05.025 [I] Mle-----------: Receive Parent Response (fe80:0:0:0:d819:6c8f:a64b:eb7d,0x3c00)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:05.163 [I] Mle-----------: Send Child ID Request (fe80:0:0:0:14e8:e516:8d54:527e)
Sep 13 06:24:15 centauri-imx6ull bae-agent[419]: 00:00:05.174 [I] Mle-----------: AttachState ParentReq -> ChildIdReq
Sep 13 06:24:16 centauri-imx6ull bae-agent[419]: 00:00:06.432 [I] Mle-----------: AttachState ChildIdReq -> Idle
Sep 13 06:24:16 centauri-imx6ull bae-agent[419]: 00:00:06.433 [N] Mle-----------: RLOC16 fffe -> 9c00
Sep 13 06:24:16 centauri-imx6ull bae-agent[419]: 00:00:06.445 [N] Mle-----------: Role detached -> leader

**Comment by abtink** [comment]
Another point that I noticed is `cli` output you posted, says `Master key` instead of `Network key`.
This indicates you are running a rather older commit  of OpenThread before https://github.com/openthread/openthread/pull/6721 (I highly suggest updating to newer version).

**Comment by gokul-bhalodiya-7** [comment]
Thanks for the response @abtink 

> Do you maybe call state leader CLI command or the otThreadBecomeLeader() API from your application code? These are intended for testing and should not be used.

Yes, I used `state leader` CLI command for testing purpose for checking the gateway openthread state. What's the standard practice for knowing the openthread state of the gateway?

> Another point/suggestion: I noticed from cli output you posted, it says Master key instead of Network key.
This indicates you are running a rather older commit of OpenThread before https://github.com/openthread/openthread/pull/6721 (I highly suggest updating to newer version).

The posted logs are of openthread end-device which has an older openthread version. On the gateway side, I have the latest openthread version.

> Any device would try 6 attach attempts before assuming it is the only/first device and taking over leader role. This is not what we see in the logs.
We see in your logs that only one attach attempt (and we see device does indeed find a parent and even sends "Child ID Request" to it) but soon afterwards it show it its role being change to leader. This hints at use of the APIs above).

I got your point, I haven't changed anything related to the attach attempt process in openthread stack. Can you please guide me on how I can verify or make it to do 6 attach attempts?

Also sometimes the gateway gets Detached when we restart it as mentioned in the [previous conversation](https://github.com/openthread/ot-br-posix/issues/1976#issuecomment-1715115323)

Please let me know in case you need more information.

Thanks in advance for any help/support.

**Comment by abtink** [comment]
> Yes, I used `state leader` CLI command for testing purpose for checking the gateway openthread state. What's the standard practice for knowing the openthread state of the gateway?

This is likely the root of the issue you are seeing.

You can use `state` CLI command  (without any additional argument) to check the current state of the device.

If you use `state leader` CLI command, you are forcing device to become leader which explains the behavior you are seeing.  The `state leader` command is only intended for testing and for situation were user intentionally want to test certain behaviors  and know the consequence of calling this API. Calling this API makes your devcie non-coplicant with Thread spec (the [API documentation](https://github.com/openthread/openthread/blob/9b7c78f960b1a4d663a21ea16aa39f63f352aadb/include/openthread/thread_ftd.h#L481-L492))

**Comment by gokul-bhalodiya-7** [comment]
Sorry for the typing mistake, I always use `ot-ctl state` command to check the openthread state of the gateway.

Please consider `ot-ctl state` CLI command instead of `state leader` CLI command in this reply and suggest some solution.

Thanks in advance for any help/support.

**Comment by abtink** [comment]
@gokul-bhalodiya-7 you want to collect logs and debug and understand the issue on your devices. 

Here are some general suggestions. 
- Try to update all devices to later versions of OT.
- Collect logs from "gateway" device that claim is not working correctly and check its logs.
- Collect logs from other devices when you restart your gatway
- Check your application layer code and command that you issue on the gateway and ensure that they are correct.

**Comment by gokul-bhalodiya-7** [comment]
Thanks for the support @abtink and @jwhui 

I will check the logs and do what is needed as you suggested and then I will get back to you after that.

**Comment by jwhui** [comment]
Closing stale issue.
