### ISSUE TITLE
Web-ui topology loads indefinitely

### ISSUE THREAD

**Issue by Peugot206** [openthread/ot-br-posix#1982]
**Describe the bug** The OTBR web ui loads the topology indefinitely. It has worked once but ever since the nodes don't show up anymore. Everything else seems to work perfectly fine. I can see it's active and it's a leader. The 'Status' also works nice on the web-ui (even though sometimes this also doesn't show, but that usually goes away quickly). 
![image](https://github.com/openthread/ot-br-posix/assets/142222422/8bae374b-49ee-4e23-8a87-324e748fd410)

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: 3d7d34b657ebd8e7208db972bb72b55cf7deb0ed
2. Raspberry Pi 4 running Ubuntu 22.04 with an nRF52840 Dongle. Pi connected to WiFi.
3. Open the web-ui and open 'Topology', it doesn't show anything and loads forever.

**Expected behavior** It should show the topology with the nodes (which it once did). 

**Console/log output** I have done some debugging that I found online, even though I'm not sure I understand everything. Here are the logs:
`sudo service otbr-web status`:
```
● otbr-web.service - Border Router Web
     Loaded: loaded (/lib/systemd/system/otbr-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-08-25 08:47:59 CEST; 4 days ago
   Main PID: 1104 (otbr-web)
      Tasks: 1 (limit: 4407)
     Memory: 4.0M
        CPU: 843ms
     CGroup: /system.slice/otbr-web.service
             └─1104 /usr/sbin/otbr-web

Aug 25 08:47:59 nomatterwhat systemd[1]: Started Border Router Web.
Aug 25 08:47:59 nomatterwhat otbr-web[1104]: otbr-web[1104]: [INFO]-WEB-----: Running 0.3.0-thread-reference-20230119-270-g5f5cbb1d7e
Aug 25 08:47:59 nomatterwhat otbr-web[1104]: otbr-web[1104]: [INFO]-WEB-----: Border router web started on wpan0
Aug 25 08:47:59 nomatterwhat otbr-web[1104]: otbr-web[1104]: [ERR ]-WEB-----: OpenThread daemon is not running.
Aug 25 08:47:59 nomatterwhat otbr-web[1104]: [INFO]-WEB-----: Running 0.3.0-thread-reference-20230119-270-g5f5cbb1d7e
Aug 25 08:47:59 nomatterwhat otbr-web[1104]: [INFO]-WEB-----: Border router web started on wpan0
Aug 25 08:47:59 nomatterwhat otbr-web[1104]: [ERR ]-WEB-----: OpenThread daemon is not running.
```

I have tried `sudo service otbr-web restart` but that didn't fix this issue. I checked `sudo systemctl --failed` which returns no services. 

**Additional context** If any is needed, please let me know!

Thanks for any help.

**Comment by chuckrui** [comment]
I'm in the same situation as you.Stick one's eye in.

**Comment by Peugot206** [comment]
@chuckrui hi I found my solution as following. The RPI is connected to Network X, but my PC is connected to Network Y. Network X and Y are both local networks from the same area. Only when I connect to the same network as the Pi this topology loads, even though the web-ui itself works on both networks.

**Comment by jwhui** [comment]
Closing stale issue.
