### ISSUE TITLE
OTBR not able to connect the existing network 

### ISSUE THREAD

**Issue by paTelshREya** [openthread/ot-br-posix#1989]
Hi,

We're working with the nRF52840 Dongles.
We have code based on the nRF Connect SDK using OpenThread on 802.15.4 connecting to an OTBR implemented on docker with an nRF52840 dongle running the RCP firmware. Also, we are creating an OpenThread Network and publishing messages through MQTT-SN from a modified CLI firmware running on nRF52840 Dongles.

**Code is here:** https://github.com/DynamicDevices/openthread-border-router-block

Note: We have enabled auto form thread network with specific network parameters whenever OTBR is up.

- Network Name
- PAN ID: 0x4444
- Network Extended PAN ID: 3333333344444444
- Channel: 15

**Observations:**
If the OTBR comes up BEFORE the other nodes establish a mesh network everything works as expected.

**Issue** starts when the OTBR comes up AFTER the other nodes establish a network.
Case: If there is a network using FTD nodes working as Routers and MTD nodes working as a Child without OTBR, only one of the FTD nodes is working as a Leader. If we turn off the Leader node, one of the FTS nodes will become the Leader of the network. After some time if we turn on OTBR/RCP, it won't connect to the network. If we turn off all FTD nodes one by one (waiting for them to become the Leader and then turning them off) we will left with MTD nodes running as Diteched mode. And within a couple of seconds, OTBR/RCP joins the network as the Leader and all MTD nodes will connect to it as a Child. After that, if we turn on all FTD nodes they will join the network as a Router and work as expected.

**Possible reasons behind this behavior**
- There is already a network with the specific configuration and as we have enabled auto form network in OTBR, it's not forming another network with the same configuration (ideally it should not). However, it should join the existing network by default.

**Questions**
- Is there any configuration we need to enable to make it join the network by default?
- Can we add some checks before forming the network from the OTBR?

Thank you,
Shreya

**Comment by jwhui** [comment]
What do you mean by "auto form"? If you are using `OPENTHREAD_CONFIG_OPERATIONAL_DATASET_AUTO_INIT`, that functionality is deprecated and not recommended.

Thread devices generally need to be configured using the same Operational Dataset. The best way to do this is copying the full Operational Dataset as a hex string from one device to another.

See [README_DATASET.md](https://github.com/openthread/openthread/blob/main/src/cli/README_DATASET.md) for more details.

**Comment by jwhui** [comment]
Closing stale issue.
