### ISSUE TITLE
How to set the OTBR to become the leader state directly after initialization

### ISSUE THREAD

**Issue by song7788** [openthread/ot-br-posix#2003]
hi developer,  I integrated OTBR on the linux device, but when there was a router device nearby, OTBR automatically changed into a child state after startup, and it would continue to change back to a child after setting with the command ot-ctl state leader. This problem bothers me a lot. Can you give me some advice?

**Comment by song7788** [comment]
The chip I used was EFR32MG21, and it was ot-rcp firmware

**Comment by jwhui** [comment]
Thread requires all devices to attach to an existing partition as a child. A router eligible device then attempts to become a router after a random delay of up to 2 minutes.

**Comment by jwhui** [comment]
Closing stale issue.
