### ISSUE TITLE
Crash when discovering more than one service

### ISSUE THREAD

**Issue by gharveymn** [openthread/ot-br-posix#2005]
Hi,

There seems to be an crash which may occur whenever `DiscoveryProxy` is handling more than one query. This is the problem code: 

https://github.com/openthread/ot-br-posix/blob/b4d6f3b43d58902a27976f3700795df61e9e7713/src/sdp_proxy/discovery_proxy.cpp#L186-L227

The issue is that `otDnssdQueryHandleDiscoveredServiceInstance` can free the object invoker for this function (`otbr::Mdns::PublisherAvahi::ServiceSubscription`, for example). When this happens, `aType` is freed, so the program crashes at https://github.com/openthread/ot-br-posix/blob/b4d6f3b43d58902a27976f3700795df61e9e7713/src/sdp_proxy/discovery_proxy.cpp#L215

It just needs to be the case that the matching query is not the last in the current list of queries.

## Reproduction

Perform queries for two different services which are active on the network in rapid succession. You should reproduce this about half the time.

**Comment by abtink** [comment]
Thanks @gharveymn for reporting this.

Not sure how this is happening:
- It is true that `aType` and `aInstanceInfo` are `const &` in the `DiscoveryProxy::OnServiceDiscovered()` method itself
- But this callback should be called from `Publisher::OnServiceResolved()`.
- And `Publisher::OnServiceResolved()` should gets its own copy of `aType` and `aInstanceInfo` as its signature is:
   `void OnServiceResolved(std::string aType, DiscoveredInstanceInfo aInstanceInfo);`
- So even if the original `mType` and `mInstanceInfo` in`Mdns::PublisherAvahi::ServiceSubscription` is freed, the copies  passed to `Publisher::OnServiceResolved()` should stay valid.

**Comment by gharveymn** [comment]
Ah, thanks for the response @abtink. I'm using an older version, and it looks like that signature was changed by https://github.com/openthread/ot-br-posix/pull/1910.

So this has already been fixed; apologies.
