### ISSUE TITLE
OpenWrt build failing with NAT64 enabled

### ISSUE THREAD

**Issue by jwhui** [openthread/ot-br-posix#2033]
The [ot-br-posix/pull/2011](https://github.com/openthread/ot-br-posix/pull/2011) mentioned in [openwrt/pull/11559](https://github.com/openwrt/openwrt/pull/11559) was committed on Dec 19, 2022, and [openwrt#L46](https://github.com/openthread/ot-br-posix/blob/main/tests/scripts/openwrt#L46) depends on The openwrt sdk version is 22.03.3, which does not merge into the above patch.
I think even if it wasn't for this issue, we would need to update the openwrt sdk version, e.g. the latest master to ensure that the two are always compatible.

Nonetheless, I verified locally that compiling with the default 22.03.3 version passes, and switching to master also compiles fine.

I'm not sure if switching to the new openwrt sdk will fix this, or if re-triggering the action run will (I've had CI fail on commits in unrelated code, and a re-run fixed it).
I am testing online by triggering the action after a fork.

_Originally posted by @ihidchaos in https://github.com/openthread/ot-br-posix/issues/2030#issuecomment-1730972956_

**Comment by jwhui** [comment]
> I'm not sure if switching to the new openwrt sdk will fix this, or if re-triggering the action run will (I've had CI fail on commits in unrelated code, and a re-run fixed it).

@ihidchaos compiler errors are deterministic, so re-running the check will not fix it.

**Comment by ihidchaos** [comment]
> > I'm not sure if switching to the new openwrt sdk will fix this, or if re-triggering the action run will (I've had CI fail on commits in unrelated code, and a re-run fixed it).
> 
> @ihidchaos compiler errors are deterministic, so re-running the check will not fix it.

Thanks for the tip, I'm trying to fix it.
The problem I'm having is that this error is hard to reproduce when I manually test it locally, so I'm trying to figure out how to verify it using GitHub Action.
[guoyuchao-vm_2023-09-22_16-18-10.log](https://github.com/openthread/ot-br-posix/files/12702251/guoyuchao-vm_2023-09-22_16-18-10.log)

**Comment by ihidchaos** [comment]
UPDATE: I realized that the `getaddrinfo_a`, `gaicb` and `libnal` don't actually exist in the musl libc. 
I guess I need to find the `gaicb` replacement inside the musl library.

**Comment by ihidchaos** [comment]
I have written code to use c-ares instead of getaddrinfo_a and am testing it on my own fork branch.
However, I'm wondering if introducing c-ares in order to use asynchronous address lookups is necessary.

**Comment by xuyirio** [comment]
There is some platform already adopted the version of using libanl. I'm wondering if we want to keep backward compatibility when switching to c-ares. It might take some time to verify.

As a mitigation of the otbr-posix build CI error, @ihidchaos could you help revert the change introduced by [openthread/pull/9441](https://github.com/openthread/openthread/pull/9441)? It can be changed back again after the solution is finalized.

**Comment by jwhui** [comment]
Closing stale issue.
