### ISSUE TITLE
Thread 1.3 certification on 3.2 fail

### ISSUE THREAD

**Issue by CSS-IanTseng** [openthread/ot-br-posix#2043]
Run on RCP of OTNCS with Thread 1.3 certification BR 3.2 "[DATA] [COMPONENT] Re-register service with active SRP server - Multiple BRs + AIL" will fail on "Check if DUT sends SRP Update : SRP update packet not present [Check if DUT sends SRP update message to BR_1]", the other Thread 1.3 test case with role Router and FED is pass, only FED BR3.2 fail.

I use the raspberrypi and ot-br-posix as OTBR, and 
1. The ot-br-posix git commit id: 89cd39bdc69e4bd52510dbd20e8de381ef3d9ee5
2. OTNCS rcp firmware is ot-rcp-1.3-20230119-ce1647697
3. Build steps was follow the guide of [OpenThread Border Router Build and Configuration](https://github.com/openthread/ot-docs/blob/main/site/en/guides/border-router/build.md#openthread-border-router-build-and-configuration)
4. Network topology is Thread 1.3 certification BR 3.2 use. 
    ● BR_1 – Test bed device operating as a Thread Border Router
    ● BR_2 – Test bed device operating as a Thread Border Router
    ● Router_1 – Test bed device operating as a Thread Router and the Leader
    ● TD_1 (DUT) - Thread End Device or Thread Router, Component DUT
    ● Eth_1 - Test Bed border router device on an Adjacent Infrastructure Link
5. I create our own python script on THCI for RCP test case.

There is find the issue on "dns browse _thread-test._udp.default.service.arpa" command **response time out** when I send command by ot-ctl. But the result should be like setting BR_1, the return results should contain data and not be timed out. Such as,

> [COM98] <<< 'dns browse _thread-test._udp.default.service.arpa'
> [COM98] Expected ['dns browse _thread-test._udp.default.service.arpa']
> [COM98] >>> 'DNS browse response for _thread-test._udp.default.service.arpa.'
> [COM98] >>> 'service-test-1'
> [COM98] >>> '    Port:12345, Priority:0, Weight:0, TTL:7198'
> [COM98] >>> '    Host:host-test-1.default.service.arpa.'
> [COM98] >>> '    HostAddress:fd7b:85ec:f524:1:51d2:f51d:5dd7:dcb2 TTL:7198'
> [COM98] >>> '    TXT:[] TTL:7198'
> [COM98] >>> 'Done'
> fe80::dea6:32ff:fe9f:e5cc > bash('sudo ot-ctl ipaddr mleid',) returns ['fd00:db9:0:0:fc5:bd67:2188:764c', 'Done']

**There is a part of log output and capture information** [fail data.zip](https://github.com/openthread/ot-br-posix/files/12779330/fail.data.zip)
And fail with 'Error 28: ResponseTimeout', like as follow message.

> Status --> BR_2 has been added into the network..  [57]
> Status --> Waiting for 5 seconds .. [Waiting for DUT to register OMR prefix and transmit ICMPv6 Router Advertisements]  [59]
> fe80::dea6:32ff:fe9f:e5cc > bash('sudo ot-ctl ipaddr mleid',) returns ['fd00:db9:0:0:7e11:f3b:5f2:a8eb', 'Done']
> fe80::e65f:1ff:fe69:7daf > bash('sudo ot-ctl srp server disable',) returns ['Done']
> Status --> Waiting for 2 seconds .. [Waiting for 2 seconds]  [61]
> 
> [COM98] <<< 'dns browse _thread-test._udp.default.service.arpa'
> [COM98] Expected ['dns browse _thread-test._udp.default.service.arpa']
> [COM98] >>> 'DNS browse response for _thread-test._udp.default.service.arpa.'
> [COM98] >>> 'Error 28: ResponseTimeout'
> Log -->   [sendCommand() Error: COM98: failed to find end of response]
> 
> COM98: failed to find end of response
> Status --> Err: Error While Running Test Case / COM98: failed to find end of response / Test BR 3 2  [100]

Even if there is a chance to complete subsequent tests, it still fails.

Because of I use ot-br-prosix have chance to pass the BR3.2 test if run more times.
( ot-br-prosix commit 53767f4123dee551229d27cd2b7c0c011e85099f, Wed Aug 30 13:27:51 2023 -0700 )
But latest version is fail, and every time was fail on the same command and return same fail code.

**Comment by jwhui** [comment]
Can you provide the test output from the Test Harness (including packet capture, logs, etc.)?

**Comment by CSS-IanTseng** [comment]
Yes, I modify the description. Thanks for your reminder.

**Comment by CSS-IanTseng** [comment]
OK, Is there have any configuration can disable the SRP server on ot-br-prosix when I build the image?
Because of the RCP setting already disable SRP related function, so about the "dns", "srp" function is runing on ot-br-prosix.

**Comment by jwhui** [comment]
> OK, Is there have any configuration can disable the SRP server on ot-br-prosix when I build the image? Because of the RCP setting already disable SRP related function, so about the "dns", "srp" function is runing on ot-br-prosix.

There is a CMake option here:
https://github.com/openthread/ot-br-posix/blob/e7d42a4f69bfed9b2c1817ca5686dd721abfe1db/etc/cmake/options.cmake#L86

**Comment by EskoDijk** [comment]
Further internal discussion is on: https://threadgroup.atlassian.net/browse/TESTPLAN-590

**Comment by EskoDijk** [comment]
Solution proposed for cert tests: in case the BR DUT is a product that can be tested standalone without THCI, the network interface to the AIL is not connected as per the test topology, and the test should succeed automatically. In case the BR DUT is a Component that's driven by a THCI (so it needs connectivity to the AIL, and so it will auto-enable its SRP server) then an explicit CLI command can be given to the BR DUT to disable its SRP server and then the test can run as usual.

**Comment by EskoDijk** [comment]
One interesting detail: per latest 1.3 test plans, a Border Router component does not have to execute test case 3.2!  (Only test case 3.2b) So if the DUT is a BR Component, the test mentioned here is not intended to be run.

**Comment by jwhui** [comment]
Closing stale issue.
