### ISSUE TITLE
Unexpected Spinel transaction message:1

### ISSUE THREAD

**Issue by chuckrui** [openthread/ot-br-posix#2044]
When i run command on Ubuntu command line and show 
"Unexpected Spinel transaction message:1"
"Error processing response: Drop"

And then, I logined the web to From the Thread Network,it showed failed.

I ran a few commands to make sure there were no OTBR containers running.
"docker stop $(docker ps -a -q)"
"docker network rm otbr"

Here is the full log.
[log1.txt](https://github.com/openthread/ot-br-posix/files/12735547/log1.txt)

**Comment by jwhui** [comment]
Closing stale issue.
