### ISSUE TITLE
wish: Debian packaging

### ISSUE THREAD

**Issue by rzr** [openthread/ot-br-posix#2057]
Hi,

Let me create this ticket to track ongoing efforts to integrate ot-br-posix to debian archive.

Note that effort done for debian will be also useful for other Linux distros, so this will  help for users' adoption of OT/

If any interest please comment, I'll share tips for cooperative maintenance along debian iot team:

https://wiki.debian.org/Teams/pkg-iot

**Comment by jwhui** [comment]
Closing stale issue.
