### ISSUE TITLE
Can `PublishMeshCopService` be an optional KConfig option for TBRs?

### ISSUE THREAD

**Issue by rretanubun** [openthread/ot-br-posix#2067]
**Is your feature request related to a problem? Please describe.**

A customer that wanted to deploy a Thread Border Router wishes to deploy it with external commissioner feature disabled.
i.e. The TBR should not publish a meshcop service to mDNS and not support external commissioner

**Describe the solution you'd like**
A KConfig flag (maybe `OTBR_ENABLE_MESHCOP` ?) to cleanly disable the feature

**Describe alternatives you've considered**

Commenting out or making a custom stub implementation of `BorderAgent::PublishMeshCopService` that does nothing.

**Additional context**

(making sure I am reading this right)

From Thread v1.3.0 Public Spec (27-Feb-2023) Section 9.2.1:

"From a **commissioning** perspective, a Border Router SHALL implement a Mesh Commissioning Protocol **Border Agent** that allows secure, user-initiated joining of new devices to the Thread Network or network management functionality by means of an external Commissioner on an external network."

So **not** supporting External Commissioner for a TBR violates the OpenThread Specification for a SHALL functionality for a TBR and thus will **prevent said device to be Thread Certified, correct**?

**Comment by jwhui** [comment]
A CMake option exists:

https://github.com/openthread/ot-br-posix/blob/14d62f29c25d6a674288cca0faf4ffb7198e55cd/etc/cmake/options.cmake#L34

As you pointed out, not supporting the Border Agent feature will mean that the device cannot be certified as a Thread Border Router. However, it could be certified as a Thread device.
