### ISSUE TITLE
 mdns IPv6 resolve issue on Wlan0 interface

### ISSUE THREAD

**Issue by thousif-e5** [openthread/ot-br-posix#2074]
Hi,
i have an open thread setup with nodes running with SRP client with service name **'_elementuredev._udp'**
in the srp server I can see the client's hostname is registered. 
**SRP Logs:**
```
srp server host
a0624a52-1df2-4d26-bba8-0aa05c27d2b6.default.service.arpa.
    deleted: false
    addresses: [fdcb:67e:9d73:5754:e77:8e63:24ae:3b5f]
5f3feffb-af9f-47ca-9b6c-287199d51312.default.service.arpa.
    deleted: false
    addresses: [fdcb:67e:9d73:5754:dc8f:815e:7f14:6206]
222d9903-7b17-4427-bc93-933f1f790261.default.service.arpa.
    deleted: false
    addresses: [fdcb:67e:9d73:5754:589b:9761:9a38:7970]
7901f953-2bb4-4a90-9a72-c54106fda61e.default.service.arpa.
    deleted: false
    addresses: [fdcb:67e:9d73:5754:8711:36c8:b07:77f1]
175560e5-2391-4633-a5bf-2377711fcce5.default.service.arpa.
    deleted: false
    addresses: [fdcb:67e:9d73:5754:dd6f:e100:a6b4:9ee1]
cd6ccf99-56db-403d-b37c-6eab7729173a.default.service.arpa.
    deleted: false
    addresses: [fdcb:67e:9d73:5754:9db1:945b:6759:9e43]
6ee5d61c-e8a8-4620-8cd1-8d8b08a08a95.default.service.arpa.
    deleted: false
    addresses: [fdcb:67e:9d73:5754:1a83:e6fa:756f:5958]
6bb1e256-6f78-4eb4-94b1-e818711946af.default.service.arpa.
    deleted: false
    addresses: [fdcb:67e:9d73:5754:40f2:43ad:929a:f6c0]
046adab9-1aca-4153-b9b6-7ab406da964d.default.service.arpa.
    deleted: false
    addresses: [fdcb:67e:9d73:5754:a4b1:aebd:1eee:392d]
Done
```
**Problem:** MDNS is not registering the IPv6 address hence IPv6 address resolve issue.
**The attached image shows an error resolving the address.**
![Screenshot from 2023-10-19 22-27-53](https://github.com/openthread/ot-br-posix/assets/138437412/fffa94b8-885f-4369-87e8-b2cf511cbf4b)

**Comment by abtink** [comment]
One suggestion to check:

- What are the address type that clients are registering? (e,g, `fdcb:67e:9d73:5754:40f2:43ad:929a:f6c0 `) 
- If it is a Thread "mesh-loocal" address, it will be not be advertised by adv-proxy as it is not reachable from outside of mesh.

**Comment by thousif-e5** [comment]
hi @abtink,
In earlier commits it used to work and my setup requires the IPv6 to be published in MDNS.
any alternative to that?

thanks

**Comment by abtink** [comment]
Did you check/confirm the mesh-lcoal prefix? My suggestion is to first check this (are these addresses "mesh-local" addresses or not?).

Do you have a BR in your setup?

**Comment by thousif-e5** [comment]
yes, it is the mesh local ipv6 address and I do have a BR setup where you can see the SRP server running.

**Comment by jwhui** [comment]
> yes, it is the mesh local ipv6 address and I do have a BR setup where you can see the SRP server running.

As mentioned in https://github.com/openthread/ot-br-posix/issues/2074#issuecomment-1778889176, mesh-local addresses are intentionally **not** published via mDNS.

**Comment by thousif-e5** [comment]
Any suggestions on polling/events of the **SRP Server** on the client's registration

**Comment by abtink** [comment]
You need devices to provide OMR (off-mesh routable) addresses (other than mesh-local) in their SRP registration.

You can have a BR configured to publish an OMR prefix in Thread network data (which is then used by devices to generate OMR address) and register these addresses with SRP server.

**Comment by jwhui** [comment]
> Any suggestions on polling/events of the **SRP Server** on the client's registration

See [src/cli/README_SRP_SERVER.md](https://github.com/openthread/openthread/blob/main/src/cli/README_SRP_SERVER.md) for the set of available CLI commands.

Note that the reason why mesh-local addresses are not advertised via mDNS is because mesh-local addresses are not useful for hosts on the infrastructure link to communicate with Thread devices.

**Comment by thousif-e5** [comment]
thanks for the info @abtink and  @jwhui.

**Comment by thousif-e5** [comment]
closing
