### ISSUE TITLE
Unable to ping IPV6 computer from Thread device and vice versa

### ISSUE THREAD

**Issue by typepub** [openthread/ot-br-posix#2086]
Hi,

I have this setup:
- OTBR running on Raspberry Pi configured according [https://openthread.io/codelabs/openthread-border-router?hl=en#1]
- Thread device is nrf52840 DK board with OpenThread Cli sample installed
- Computer connected to same Wifi network as OTBR running MacOS Sonoma

From OTBR, I can ping both Computer and Thread device
From Computer, I can ping OTBR but not Thread device
From Thread device, I can ping OTBR but not Computer

So my problem is that the routing between Thread and LAN is not working, both ways.

I checked:
- OTBR service status: up and running
- Firewall: not sure if the configuration is correct

When I try to ping from Computer to Three device, counters for Chain FORWARD and Chain OTBR_FORWARD_INGRESS increase. When I do it the other way (from Thread device) no counter increase.

Here are the rules:
ip6tables -vL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   15   840 OTBR_FORWARD_INGRESS  all  --  any    wpan0   anywhere             anywhere            

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OTBR_FORWARD_INGRESS (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             match-set otbr-ingress-allow-dst dst
   15   840 ACCEPT     all  --  any    any     anywhere             anywhere            
    0     0 ACCEPT     all  --  wpan0  any     anywhere             anywhere             PKTTYPE = unicast

Configurations:
- OTBR:
IP address:
wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fd6d:7be0:2be0:3146:349:d3fd:c2f4:2060  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::6bca:3d3:1024:c035  prefixlen 64  scopeid 0x20<link>
wpan0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet6 fd6d:7be0:2be0:3146:2d17:64a7:d931:66af  prefixlen 64  scopeid 0x0<global>
        inet6 fd6d:7be0:2be0:3146:0:ff:fe00:fc38  prefixlen 64  scopeid 0x0<global>
        inet6 fd6d:7be0:2be0:3146:0:ff:fe00:fc00  prefixlen 64  scopeid 0x0<global>
        inet6 fd6d:7be0:2be0:3146:0:ff:fe00:6c01  prefixlen 64  scopeid 0x0<global>
        inet6 fda1:fbde:3c93:1:1e95:7b14:7087:d544  prefixlen 64  scopeid 0x0<global>
        inet6 fd6d:7be0:2be0:3146:0:ff:fe00:8800  prefixlen 64  scopeid 0x0<global>
        inet6 fd6d:7be0:2be0:3146:0:ff:fe00:fc10  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::403b:31be:3681:6545  prefixlen 64  scopeid 0x20<link>
        inet6 fd6d:7be0:2be0:3146:0:ff:fe00:fc11  prefixlen 64  scopeid 0x0<global>

Routes:
ip -6 route
fd6d:7be0:2be0:3146::/64 dev wpan0 proto kernel metric 256 pref medium
fd6d:7be0:2be0:3146::/64 dev wlan0 proto ra metric 600 pref medium
fda1:fbde:3c93:1::/64 dev wpan0 proto kernel metric 256 pref medium
fe80::/64 dev wpan0 proto kernel metric 256 pref medium
fe80::/64 dev wlan0 proto kernel metric 1024 pref medium
default via fe80::7845:58ff:fee4:4826 dev wlan0 proto ra metric 600 pref high

- Thread device:
IP address:
ot ipaddr
fd6d:7be0:2be0:3146:0:ff:fe00:6c00
fda1:fbde:3c93:1:4252:b261:b9b:b23c
fd6d:7be0:2be0:3146:2cc6:1cc9:3209:142
fe80:0:0:0:6c41:7665:6b0:1851

- Computer:
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 5c:e9:1e:b5:72:4b
	inet6 fe80::c7e:c309:3fa2:718b%en0 prefixlen 64 secured scopeid 0xf 
	inet6 fd6d:7be0:2be0:3146:144e:30e9:6670:be04 prefixlen 64 autoconf secured 

So I suspect that something is going wrong either with the routing configuration or with the firewall configuration, from Thread device to the Computer,  but I don't have the required knowledge to investigate more. Any help will be appreciated. Thanks.

**Comment by typepub** [comment]
Well, I guess it is just a matter of time: after several hours waiting without touching anything, ping works properly.

**Comment by superwhd** [comment]
Hi @typepub, I looked a little bit into the information you provided. 

It seems your on-link prefix of LAN somehow collides with your Thread's mesh-local prefix. They're both `fd6d:7be0:2be0:3146::/64`. That means your Thread network is misconfigured. I'm not sure how you configured the Thread network but reconfiguring it with random credentials (by `dataset init new` and `dataset commit active` ...) should solve the problem.

**Comment by typepub** [comment]
Thanks @superwhd .

You were absolutely right. I can add that this page gave me all information to solve my IP address configuration: [https://github.com/zephyrproject-rtos/zephyr/issues/29567](https://github.com/zephyrproject-rtos/zephyr/issues/29567)
