### ISSUE TITLE
Setup script fails: Removed option OT_EXCLUDE_TCPLP_LIB

### ISSUE THREAD

**Issue by nevi-me** [openthread/ot-br-posix#2096]
**Describe the bug** A clear and concise description of what the bug is.

The setup script at e382c32259b518224314d526a7ef3183ef5f15a8 fails when run, the error comes from a deprecated/removed option on openthread, which causes a build failure.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: e382c32259b518224314d526a7ef3183ef5f15a8
2. IEEE 802.15.4 hardware platform: Raspberry Pi 3B (note, my last successful build was in April 2023, I was updating)
3. Build steps: I ran the bootstrap script, then `INFRA_IF_NAME=wlan0 WEB_GUI=1 BORDER_ROUTING=1  ./script/setup`
5. Network topology: WiFi network, nrf52840 dongle for RCP

**Expected behavior** A clear and concise description of what you expected to happen.

I expected the build to succeed.

**Console/log output** If applicable, add console/log output to help explain your problem.

I didn't attach the full logs because I'm able to reproduce the error with WEB_GUI or BORDER_ROUTING turned off.

```sh
CMake Error at third_party/openthread/repo/etc/cmake/options.cmake:353 (message):
  Removed option OT_EXCLUDE_TCPLP_LIB is set - - Use OT_TCP instead,
  OT_EXCLUDE_TCPLP_LIB is deprecated
Call Stack (most recent call first):
  third_party/openthread/repo/etc/cmake/options.cmake:358 (ot_removed_option)
  third_party/openthread/repo/CMakeLists.txt:65 (include)
```

**Additional context** Add any other context about the problem here.

I was updating an existing build.

**Comment by jwhui** [comment]
I don't see anywhere in `ot-br-posix` where `OT_EXCLUDE_TCPLP_LIB` is being set.

Can you point to where `OT_EXCLUDE_TCPLP_LIB` is being set?

**Comment by nevi-me** [comment]
I also couldn't find where it's being set, however this error was being triggered. I ended up commenting out the 2 checks at the end of the options.cmake file, and everything seems to have built fine (in that I haven't seen issues in my border router so far).

**Comment by jwhui** [comment]
Make sure to clean your build environment. Otherwise the previous build config will remain cached.

**Comment by nevi-me** [comment]
I don't get the error from a clean build
