### ISSUE TITLE
BeagleBone Black not booting after following OTBR guide

### ISSUE THREAD

**Issue by guillermovidalsule** [openthread/ot-br-posix#2121]
Hello!
I'm building an OTBR with my BeagleBone Black and an ESP32-H2.

[**Problem**]
After executing the command `INFRA_IF_NAME=wlan0 ./script/setup` in the OTBR guide (URL: https://openthread.io/guides/border-router/build) and rebooting the board I cannot connect to it. Even if I ping beaglebone.local it does not resolve the name. Notably, the 4 LEDs of the BBB are blinking in the following sequence: D2(0), D2(0), D4(2) D(2). The D4 LED blinks softly, though, and the sequence is a little bit unclear (quite fast and weird).  

[**Important Information**]
- I'm using an 8GB uSD card I flashed with the image `bone-debian-10.3-iot-armhf-2020-04-06-4gb.img.xz` as per the guide with URL https://openthread.io/guides/border-router/beaglebone-black
- The BBB is connected with ETHERNET to the router.
- The BBB is connected to the PC as well.
- The PC I'm using has an UBUNTU 22.04 LTS installed.

[**What I would like**]
To fix this issue, because the alternative is to start all over again by flashing the uSD card and installing everything.

All help is appreciated!

### EDIT ###
Hello again!
I managed to understand what happened and fix it, but I don't now the reason behind it as I'm somewhat new to this.

[**Booting before the problem**]
The times I boot the BBB during the guide I had to press the `BOOT` button to boot from the uSD card or else it would boot from the eMMC.

[**Booting after the problem**]
When I boot the BBB without pressing the `BOOT` button it automatically boots from the uSD (this never happened before and it was not mentioned in the guide, as far as I know). If I boot pressing the `BOOT` button the problem described before happens. This only started after executing `INFRA_IF_NAME=wlan0 ./script/setup` in the guide so I did not expect it (I repeat, I booted many times the same way before this happened)

_Note_: if this is expected behavior (I'm new, so I don't know a lot) you can close this issue

Thank you!

**Comment by guillermovidalsule** [comment]
In the end it was somewhat expected: https://forum.beagleboard.org/t/boot-from-sd-card-emmc/29299

The weird part is that it started happening only after `INFRA_IF_NAME=wlan0 ./script/setup`. It previously never happened...

**Comment by jwhui** [comment]
@guillermovidalsule , glad you figured it out. Thanks for the update.
