### ISSUE TITLE
Use Docker image on bridged or custom docker network

### ISSUE THREAD

**Issue by Cilenco** [openthread/ot-br-posix#2124]
**Describe the bug** 
When running OTBR in a docker container as suggested in the [official guide](https://openthread.io/guides/border-router/docker/run?hl=en) Google Home (and other apps) cannot connect to it.

When starting the docker container with:

```
docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 --dns=127.0.0.1 -it --volume /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr --radio-url spinel+hdlc+uart:///dev/ttyACM0
```
no apps can connect to the border router. However if I execute these command beforehand on the host:

```
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
sudo sysctl -w net.ipv4.conf.all.forwarding=1 
sudo sysctl -w net.ipv6.conf.all.forwarding=1
```
and then start the container like this

```
docker run --net=host --dns=127.0.0.1 -it --volume /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr --radio-url spinel+hdlc+uart:///dev/ttyACM0
```
everything works as expected and apps can connect to the border router. Because I already have a container using port 80 on my host machine I would like to use a custom docker network. I'm not sure how to do that as the Thread communication requires IPv6 and also UDP packets for the DNS discovery.

**To Reproduce**
Follow the Docker tutorial linked above.

**Comment by jwhui** [comment]
Closing stale issue.

**Comment by Majestic7979** [comment]
Why is this a stale issue? Was this resolved? I am in the same situation wondering how to make it work

**Comment by jwhui** [comment]
The key is `--net=host` to bypass its default network isolation and directly connect the container to the host machine's network stack.

**Comment by Majestic7979** [comment]
> The key is `--net=host` to bypass its default network isolation and directly connect the container to the host machine's network stack.

It's not possible, colleague. It's because the same machine runs a reverse proxy (traefik) which means port 80 and 443 is used by Traefik. So I cannot do that, because net=host will try to map port 80 to the OTBR container and it simply won't run, as the port is already mapped to Traefik (which is the priority because I run many services behind the reverse proxy).

If we could use net=host already we would be, trust me. Thanks and hoping someone can explain a solution.

**Comment by jwhui** [comment]
A full Thread Border Router by definition involves a number of network-layer services, including direct manipulation of IPv6 routing tables, publishing services via DNS-SD, etc.

Running Thread Border Router in Docker with network isolation is great for playing around and demos, but won't give you all the features, as you have already discovered.

**Comment by Majestic7979** [comment]
> A full Thread Border Router by definition involves a number of network-layer services, including direct manipulation of IPv6 routing tables, publishing services via DNS-SD, etc.
> 
> Running Thread Border Router in Docker with network isolation is great for playing around and demos, but won't give you all the features, as you have already discovered.

Is this a long way (no disrespect) of saying it's impossible? Or is it possible but complex?

**Comment by Majestic7979** [comment]
Will be praying that someone much smarter than me could donate some of their time for a solution, because I am not the only one and it would be pleasing to the community using this solution in general. Thanks for being honest about it!
