### ISSUE TITLE
 Can the open thread border router be ported to the Android platform?

### ISSUE THREAD

**Issue by koenlee93** [openthread/ot-br-posix#2136]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.

**Describe the solution you'd like** A clear and concise description of what you want to happen.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by jwhui** [comment]
Duplicate of https://github.com/orgs/openthread/discussions/9716
