### ISSUE TITLE
 Best Practices for accessing OpenThread Instance in OT-BR-POSIX project?

### ISSUE THREAD

**Issue by SamsonMMB** [openthread/ot-br-posix#2178]
I am working on creating rest handler extensions to ot-br-posix and wanted to isolate my sources into its own folder for modularity until it is ready for mainlining.
file structure
rest
```
├── CMakeLists.txt
├── ... existing ot-br-posix code
│
├── extensions
│   ├── CMakeLists.txt
│   ├── myFile.cpp
│   ├── myFile.hpp
```
My plan is to develop `'myFile.cpp'` and `'myFile.hpp'`, aiming to integrate C code for invoking OpenThread APIs, for example,
`otThreadGetDeviceRole(otInstance).`

Regarding the implementation in 'myFile.cpp', I am considering the following structure:
```
#include "myFile.hpp"
#ifdef __cplusplus
extern "C" {
#endif
    // C code implementation
    // Question: What is the best practice for accessing an OpenThread instance here?
    otThreadGetDeviceRole(mInstance); // This is what Resource class uses today
    // or
    otThreadGetDeviceRole(gInstance); // Is using the global instance advisable?
#ifdef __cplusplus
}
#endif
```
I found [PR](https://github.com/openthread/ot-br-posix/pull/1658/files) that added new handler, but it extends the exsiting Resource class, I am trying to do something similar but using my own .cpp and .hpp.
From my examination of related files in the rest folder, such as `resource.cpp/resource.hpp`,
I noted that `'otInstance mInstance'` is encapsulated within the private section of the resource class and initialized via` 'ControllerOpenThread *mNcp'`.  `mInstance = mNcp->GetThreadHelper()->GetInstance();`
Intriguingly, I also came across a global instance labeled `'gInstance'` and while that can work, it may not be ideal.
I would be grateful for any pointers on the best-practice methods to integrate OpenThread API calls in my development.

Thank you for everyone's time

**Comment by jwhui** [comment]
Take a look at [src/agent/application.cpp](https://github.com/openthread/ot-br-posix/blob/main/src/agent/application.cpp), where various components are integrated. Note that the component constructors take `mNcp` as an argument. From there, you can access the OpenThread instance.

**Comment by SamsonMMB** [comment]
Thank you @jwhui . With the help of `mNcp` I was able to get hold of instance.
```
 // Initialize the openthread instance
    auto threadHelper = mNcp.GetThreadHelper();
    mInstance         = threadHelper->GetInstance();
```
