### ISSUE TITLE
Compiling Border Router with TCP support

### ISSUE THREAD

**Issue by 10andy0** [openthread/ot-br-posix#2184]
Hi there,

    How to compile border router so that TCP is enabled and TCP cli commands are available in ot-ctl?
I tried to compile it as follows:

                 INFRA_IF_NAME=wlan0  OTBR_OPTIONS="-DOT_TCP=ON"  ./script/setup

    but it doesn't do the thick :(

Couldn't find anywhere how to do it.

Thank you for your help.

Cheers,
Andrii

**Comment by jwhui** [comment]
The `OT_TCP` build option is disabled here:
https://github.com/openthread/ot-br-posix/blob/9326cc38b6b6ce81958a96d7821c4cb21976d636/third_party/openthread/CMakeLists.txt#L69

Note that it is generally preferable to use the host stack's TCP implementation.

**Comment by 10andy0** [comment]
Understood, I just need to enable it so that I could run benchmark test.
I also had to change below to 1 the following line:

`-DOPENTHREAD_CONFIG_TCP_ENABLE=0`

Thank you @jwhui for your help
