### ISSUE TITLE
Border router disappears randomly from home assistant thread network

### ISSUE THREAD

**Issue by paolofaz** [openthread/ot-br-posix#2216]
I'm trying the last official openthread docker image with a sonoff-e  dongle flashed with the last openthread fw (2.4.1)

I've activated the otbr integration in homeassistant (http://my-ip:8081) and it connects well.

The Thread integration is auto discovered from home assistant and it creates a network with a name like "ha-thread-XXXX" as you can see in the image below:

![1](https://github.com/openthread/ot-br-posix/assets/161043675/92a7184e-119b-4bd8-9158-1a6fa57365fe)

After a few minutes (random, about 5), the border router disappears from the thread network with this error "no border routers were found" as you can see in the image below:

![2](https://github.com/openthread/ot-br-posix/assets/161043675/ce036c7b-91a1-442c-86b7-560ffa663fd5)

If i "click" on "reset boarder router", home assistant makes a new thread network with another name (ha-thread-YYYY) and after a few minutes i get the same problem: the border router disappares again etc etc etc

The border router web page is always reachable.

The logs doesnt help beacuse i dont see any error.

this is my compose yaml

`  otbr:
    container_name: otbr
    image: openthread/otbr:latest
    ports:
     - "8086:80"
     - "8081:8081"
    volumes:
     - /dev/ttyACM0:/dev/ttyUSB0
     - /home/paolo/docker/thread:/var/lib/thread
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    command: --radio-url spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=460800
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=0
    - net.ipv4.conf.all.forwarding=1
    - net.ipv6.conf.all.forwarding=1
    dns:
    - 127.0.0.1
    networks:
      - rete_otbr
    ulimits: #THIS IS NECESSARY otherways rsyslog takes a long time to start. with this start in few seconds. bug?
      nofile:
        soft: "65536"
        hard: "65536"  

networks:
  rete_otbr:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.name: "otbr0"
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd11:db8:1::/64
`

**Comment by agners** [comment]
The border router list shown in Home Assistant is based on mDNS/DNS-SD `_meshcop._udp` service. Usually, the timeout is 30 min or so, so if the OTBR/mDNSResponder crashes hard, then it would disappear after that period. But if the border router disappears after a few minutes already, it sounds more it would gracefully announce a service remove.

Anything in the logs of the otbr container (`docker logs otbr`)?

**Comment by paolofaz** [comment]
@agners i copy only the relevants sections of otbr container logs
`
...
++ RESOLV_CONF_HEAD=/etc/resolvconf/resolv.conf.d/head
+ . script/_firewall
++ FIREWALL_SERVICE=/etc/init.d/otbr-firewall
++ sudo modprobe ip6table_filter
**sudo: modprobe: command not found**
++ true
++ FIREWALL=1
+ main
...
...
Mar 14 08:20:41 6cd2c7eaf122 otbr-agent[152]: [INFO]-BA------: Result of publish meshcop service OpenThread BorderRouter #6DC7._meshcop._udp.local: OK
Mar 14 08:20:41 6cd2c7eaf122 otbr-agent[152]: [INFO]-BA------: Result of publish meshcop service OpenThread BorderRouter #6DC7._meshcop._udp.local: OK
Mar 14 08:20:41 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for fd11:db8:1::2 on eth0.
Mar 14 08:20:41 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for ::1 on lo.
Mar 14 08:20:41 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for 127.0.0.1 on lo.
Mar 14 08:20:41 6cd2c7eaf122 avahi-daemon[136]: Host name conflict, retrying with 6cd2c7eaf122-3
Mar 14 08:20:41 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for fd11:db8:1::2 on eth0.*.
Mar 14 08:20:41 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for 172.18.0.2 on eth0.IPv4.
Mar 14 08:20:41 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for ::1 on lo.*.
Mar 14 08:20:41 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for 127.0.0.1 on lo.IPv4.
Mar 14 08:20:42 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for fd11:db8:1::2 on eth0.
Mar 14 08:20:42 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for ::1 on lo.
Mar 14 08:20:42 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for 127.0.0.1 on lo.
Mar 14 08:20:42 6cd2c7eaf122 avahi-daemon[136]: Host name conflict, retrying with 6cd2c7eaf122-4
Mar 14 08:20:42 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for fd11:db8:1::2 on eth0.*.
Mar 14 08:20:42 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for 172.18.0.2 on eth0.IPv4.
Mar 14 08:20:42 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for ::1 on lo.*.
Mar 14 08:20:42 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for 127.0.0.1 on lo.IPv4.
Mar 14 08:20:43 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for fd11:db8:1::2 on eth0.
Mar 14 08:20:43 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for ::1 on lo.
Mar 14 08:20:43 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for 127.0.0.1 on lo.
Mar 14 08:20:43 6cd2c7eaf122 avahi-daemon[136]: Host name conflict, retrying with 6cd2c7eaf122-5
Mar 14 08:20:43 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for fd11:db8:1::2 on eth0.*.
Mar 14 08:20:43 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for 172.18.0.2 on eth0.IPv4.
Mar 14 08:20:43 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for ::1 on lo.*.
Mar 14 08:20:43 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for 127.0.0.1 on lo.IPv4.
Mar 14 08:20:45 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for fd11:db8:1::2 on eth0.
Mar 14 08:20:45 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for ::1 on lo.
Mar 14 08:20:45 6cd2c7eaf122 avahi-daemon[136]: Withdrawing address record for 127.0.0.1 on lo.
Mar 14 08:20:45 6cd2c7eaf122 avahi-daemon[136]: Host name conflict, retrying with 6cd2c7eaf122-6
Mar 14 08:20:45 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for fd11:db8:1::2 on eth0.*.
Mar 14 08:20:45 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for 172.18.0.2 on eth0.IPv4.
Mar 14 08:20:45 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for ::1 on lo.*.
Mar 14 08:20:45 6cd2c7eaf122 avahi-daemon[136]: Registering new address record for 127.0.0.1 on lo.IPv4.
...
...
Mar 14 08:20:46 6cd2c7eaf122 avahi-daemon[136]: Server startup complete. Host name is 6cd2c7eaf122-6.local. Local service cookie is 3781344350.
Mar 14 08:20:46 6cd2c7eaf122 mDNSResponder: Default: mDNSCoreReceiveResponse: Received from 172.18.0.2:5353   22 2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.8.b.d.0.1.1.d.f.ip6.arpa. PTR 6cd2c7eaf122-6.local.
Mar 14 08:20:46 6cd2c7eaf122 mDNSResponder: Default: mDNSCoreReceiveResponse: Unexpected conflict discarding   20 2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.8.B.D.0.1.1.D.F.ip6.arpa. PTR 6cd2c7eaf122.local.
Mar 14 08:20:46 6cd2c7eaf122 mDNSResponder: Default: mDNSCoreReceiveResponse: Received from 172.18.0.2:5353   22 2.0.18.172.in-addr.arpa. PTR 6cd2c7eaf122-6.local.
Mar 14 08:20:46 6cd2c7eaf122 mDNSResponder: Default: mDNSCoreReceiveResponse: Unexpected conflict discarding   20 2.0.18.172.in-addr.arpa. PTR 6cd2c7eaf122.local.
Mar 14 08:21:40 6cd2c7eaf122 otbr-agent[152]: 00:01:00.032 [D] P-RadioSpinel-: Trying to get RCP time offset
Mar 14 08:21:40 6cd2c7eaf122 otbr-agent[152]: 00:01:00.032 [D] P-RadioSpinel-: Sent spinel frame, flg:0x2, iid:0, tid:3, cmd:PROP_VALUE_GET, key:TIMESTAMP
Mar 14 08:21:40 6cd2c7eaf122 otbr-agent[152]: 00:01:00.032 [D] P-RadioSpinel-: Wait response: tid=3 key=2050
Mar 14 08:21:40 6cd2c7eaf122 otbr-agent[152]: 00:01:00.034 [D] P-RadioSpinel-: Received spinel frame, flg:0x2, iid:0, tid:3, cmd:PROP_VALUE_IS, key:TIMESTAMP, timestamp:134738041
Mar 14 08:22:40 6cd2c7eaf122 otbr-agent[152]: 00:02:00.035 [D] P-RadioSpinel-: Trying to get RCP time offset
Mar 14 08:22:40 6cd2c7eaf122 otbr-agent[152]: 00:02:00.035 [D] P-RadioSpinel-: Sent spinel frame, flg:0x2, iid:0, tid:4, cmd:PROP_VALUE_GET, key:TIMESTAMP
...
...
Mar 14 08:25:36 6cd2c7eaf122 mDNSResponder: Default: mDNSCoreReceiveResponse: Unexpected conflict discarding   20 2.0.0.0.2.1.E.F.F.F.C.A.2.4.0.0.1.A.8.B.A.9.6.2.3.4.F.1.4.F.D.F.ip6.arpa. PTR 6cd2c7eaf122.local.
Mar 14 08:25:40 6cd2c7eaf122 otbr-agent[152]: 00:05:00.043 [D] P-RadioSpinel-: Trying to get RCP time offset
Mar 14 08:25:40 6cd2c7eaf122 otbr-agent[152]: 00:05:00.043 [D] P-RadioSpinel-: Sent spinel frame, flg:0x2, iid:0, tid:2, cmd:PROP_VALUE_GET, key:TIMESTAMP
Mar 14 08:25:40 6cd2c7eaf122 otbr-agent[152]: 00:05:00.043 [D] P-RadioSpinel-: Wait response: tid=2 key=2050
Mar 14 08:25:40 6cd2c7eaf122 otbr-agent[152]: 00:05:00.044 [D] P-RadioSpinel-: Received spinel frame, flg:0x2, iid:0, tid:2, cmd:PROP_VALUE_IS, key:TIMESTAMP, timestamp:374754361
Mar 14 08:25:43 6cd2c7eaf122 otbr-agent[152]: 00:05:03.542 [I] Mle-----------: Send Advertisement (ff02:0:0:0:0:0:0:1)
Mar 14 08:25:43 6cd2c7eaf122 otbr-agent[152]: 00:05:03.543 [D] P-RadioSpinel-: Sent spinel frame, flg:0x2, iid:0, tid:3, cmd:PROP_VALUE_SET, key:STREAM_RAW, len:69, channel:15, maxbackoffs:4, maxretries:15 ...
Mar 14 08:25:43 6cd2c7eaf122 otbr-agent[152]: 00:05:03.543 [D] P-RadioSpinel-: ... csmaCaEnabled:1, isHeaderUpdated:0, isARetx:0, skipAes:0, txDelay:0, txDelayBase:0
Mar 14 08:25:43 6cd2c7eaf122 otbr-agent[152]: 00:05:03.551 [D] P-RadioSpinel-: Received spinel frame, flg:0x2, iid:0, tid:3, cmd:PROP_VALUE_IS, key:LAST_STATUS, status:OK
Mar 14 08:25:43 6cd2c7eaf122 otbr-agent[152]: 00:05:03.551 [I] MeshForwarder-: Sent IPv6 UDP msg, len:90, chksum:d053, ecn:no, to:0xffff, sec:no, prio:net
Mar 14 08:25:43 6cd2c7eaf122 otbr-agent[152]: 00:05:03.551 [I] MeshForwarder-:     src:[fe80:0:0:0:b8db:8a8:e4a6:6dc7]:19788
Mar 14 08:25:43 6cd2c7eaf122 otbr-agent[152]: 00:05:03.551 [I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:1]:19788
`
an then... board router get out at 08:25:25, this is logs:
`Mar 14 08:27:14 6cd2c7eaf122 otbr-agent[152]: 00:06:34.595 [D] P-RadioSpinel-: ... csmaCaEnabled:1, isHeaderUpdated:0, isARetx:0, skipAes:0, txDelay:0, txDelayBase:0
Mar 14 08:27:14 6cd2c7eaf122 otbr-agent[152]: 00:06:34.602 [D] P-RadioSpinel-: Received spinel frame, flg:0x2, iid:0, tid:12, cmd:PROP_VALUE_IS, key:LAST_STATUS, status:OK
Mar 14 08:27:14 6cd2c7eaf122 otbr-agent[152]: 00:06:34.602 [I] MeshForwarder-: Sent IPv6 UDP msg, len:90, chksum:cec9, ecn:no, to:0xffff, sec:no, prio:net
Mar 14 08:27:14 6cd2c7eaf122 otbr-agent[152]: 00:06:34.603 [I] MeshForwarder-:     src:[fe80:0:0:0:b8db:8a8:e4a6:6dc7]:19788
Mar 14 08:27:14 6cd2c7eaf122 otbr-agent[152]: 00:06:34.603 [I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:1]:19788
Mar 14 08:27:30 6cd2c7eaf122 otbr-agent[152]: 00:06:50.384 [I] Mle-----------: Send Advertisement (ff02:0:0:0:0:0:0:1)
Mar 14 08:27:30 6cd2c7eaf122 otbr-agent[152]: 00:06:50.384 [D] P-RadioSpinel-: Sent spinel frame, flg:0x2, iid:0, tid:13, cmd:PROP_VALUE_SET, key:STREAM_RAW, len:69, channel:15, maxbackoffs:4, maxretries:15 ...
Mar 14 08:27:30 6cd2c7eaf122 otbr-agent[152]: 00:06:50.384 [D] P-RadioSpinel-: ... csmaCaEnabled:1, isHeaderUpdated:0, isARetx:0, skipAes:0, txDelay:0, txDelayBase:0
Mar 14 08:27:30 6cd2c7eaf122 otbr-agent[152]: 00:06:50.393 [D] P-RadioSpinel-: Received spinel frame, flg:0x2, iid:0, tid:13, cmd:PROP_VALUE_IS, key:LAST_STATUS, status:OK
Mar 14 08:27:30 6cd2c7eaf122 otbr-agent[152]: 00:06:50.393 [I] MeshForwarder-: Sent IPv6 UDP msg, len:90, chksum:db5f, ecn:no, to:0xffff, sec:no, prio:net
Mar 14 08:27:30 6cd2c7eaf122 otbr-agent[152]: 00:06:50.393 [I] MeshForwarder-:     src:[fe80:0:0:0:b8db:8a8:e4a6:6dc7]:19788
Mar 14 08:27:30 6cd2c7eaf122 otbr-agent[152]: 00:06:50.393 [I] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:1]:19788
`

**Comment by agners** [comment]
Uh, I am a bit confused, is that container running `mDNSResponder` and `otbr-agent` at the same time :thinking: 

It does *seem* to me that something with the OTBR container is wrong, as it has this `Withdrawing` messages. Is maybe that bridge configuration causing problems? 

It doesn't look like the [official docs on how to use the Docker container](https://openthread.io/guides/border-router/docker/run) use a bridged setup, maybe the container is not designed to be used that way?

I'd suggest to monitor/track mDNS announcements from the outside to see if there are remove announcements. That would explain the behavior you see in Home Assistant.

Then the question becomes why is the OTBR sending remove announcements?

If you want a easy and just works setup: I can recommend using Home Assistant OS. It offers the OpenThread border router add-on, which is built from upstream OpenThread repositories (see https://github.com/home-assistant/addons/tree/master/openthread_border_router). The whole stack of Home Assistant OS + Home Assistant Core + OTBR add-on is well tested and known to be working well.

**Comment by jwhui** [comment]
Closing stale issue.
