### ISSUE TITLE
NCP commissioning misbehaving.

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#230]
I am using NCP as commissioner. When I run the `joiner add` command, `commissioner joiner-add failed with error 4. InvalidForCurrentState` error occurs. 

PFA screenshot.

<img width="568" alt="screenshot 2018-12-28 at 3 30 28 pm" src="https://user-images.githubusercontent.com/9993036/50511952-9fed5400-0ab5-11e9-920b-07dd516d3d60.png">

**Comment by jwhui** [comment]
When becoming a Commissioner, the device must first confirm its role with the Leader. This involves sending a CoAP message to the Leader and receiving a response. With the current implementation, no Joiners may be added before the Commissioner role is confirmed. Can you try getting the Commissioner state to ensure that it is in `OT_COMMISSIONER_STATE_ACTIVE`?

**Comment by tarunsmalviya** [comment]
How can I get OT_COMMISSIONER_STATE_ACTIVE in RPi, where NCP is configured as commissioner?
Also, when NCP is in leader state, then also I am getting error. Following are the screenshot of end node.

![commissioner issue](https://user-images.githubusercontent.com/9993036/50756095-14c44900-1281-11e9-9b99-b29e04de86d5.png)

**Comment by jwhui** [comment]
The commissioner state is exposed via the wpantund property `Commissioner:State`. You can use the following command to retrieve the current value:
```
wpanctl get Commissioner:State
```

**Comment by tarunsmalviya** [comment]
When NCP is leader, then commissioner start and performs well (as Commissioner:State is active). But when node other than the NCP is leader, and I try to start commissioner, the Commissioner:State is always disable. Below is the Screenshot.

<img width="670" alt="screenshot 2019-01-09 at 2 44 16 pm" src="https://user-images.githubusercontent.com/9993036/50891410-34df3e00-1422-11e9-9e3c-05955cb5c608.png">

**Comment by jwhui** [comment]
@tarunsmalviya, I just tested this on the latest code:
* Border Router: https://github.com/openthread/borderrouter/commit/2e5889a1af55a8e57e0a7525e42c5d9e3c61db49
* NCP: https://github.com/openthread/openthread/commit/b6065c0fc1ef85eaee92ce1da698f34ec143eef3

Unfortunately, I was not able to reproduce your behavior.

I set up a Leader, joined the OTBR to the Leader, then issued the following commands:
```
$ wpanctl commissioner start
Commissioner started
$ wpanctl get commissioner:state
commissioner:state = "active"
```

Can you try entering the above commands manually, where NCP is not the leader?

**Comment by tarunsmalviya** [comment]
@jwhui I had tested on [c32a284](https://github.com/openthread/borderrouter/commit/c32a284e1ba9ec33ee12d215d1662390865a2319)

**Comment by jwhui** [comment]
One thing to note in the original post, the "commissioner start" command succeeded. However, in a subsequent post, "commissioner start" command failed. You may want to update your script to perform "commissioner stop" first to clean up any existing state.

Also, when the NCP is not the leader, the NCP must communicate with the Leader before it can become an active commissioner. Try adding some delay between "commissioner start" and "commissioner joiner-add" commands.

**Comment by tarunsmalviya** [comment]
@jwhui In subsequent post, the commissioner command failed because it was already started(as you can see in screenshot). 

Yes, I waited for more than 10 minutes, but it didn't worked.

**Comment by jwhui** [comment]
To get more visibility into your issue:
1. Can you try to enable logging on the NCP? The logs will be provided to wpantund and inlined in the wpantund logs.
2. Are you able to obtain a packet capture with a sniffer so that we can analyze in wireshark?

**Comment by bukepo** [comment]
@tarunsmalviya could you share the content of your script?

**Comment by tarunsmalviya** [comment]
@bukepo 

```
#!/bin/bash

if [ $# -lt 3 ]
then
	echo "Too few arguments. Expected: 3 | Passed: $#"
	echo "Expected Parameter: <eui64> <timeout> <psk>"
	exit 1
elif [ $# -gt 3 ]
then
	echo "Too many arguments. Expected: 3 | Passed: $#"
	echo "Expected Parameter: <eui64> <timeout> <psk>"
	exit 1
fi

echo "Starting commissioner role..."                                                                                                    │
sudo wpanctl commissioner start

echo "Arguments passed:-"
echo "EUI64   : $1"
echo "Timeout : $2"
echo "PSK     : $3"

sudo wpanctl commissioner joiner-add "$1" $2 $3

echo "\nRun following command on joiner device within $2 seconds:"
echo "factoryreset & ifconfig up & joiner start $3"

exit 0

```

**Comment by tarunsmalviya** [comment]
@jwhui 
Please see the attached screenshot.

I executed following steps:

1. When I ran the **start_commissioner_role.sh** script, output is `commissioner start failed with error 10. Already` for `commissioner start` command.
2. Then I ran `sudo wpanctl get Commissioner:State` command, output is `Commissioner:State = "disabled"`.
3. Then I again ran **start_commissioner_role.sh** script. After 2 minutes, output was `commissioner joiner-add failed with error 4. InvalidForCurrentState`. 

I added a 2 minutes delay as you suggested, but the problem still occurred.

<img width="729" alt="screenshot 2019-02-11 at 12 39 34 pm" src="https://user-images.githubusercontent.com/9993036/52549654-396c8d00-2dfa-11e9-80b0-f02f03aadc2b.png">

**Comment by tarunsmalviya** [comment]
@jwhui Any update?

**Comment by bukepo** [comment]
@tarunsmalviya could you try the fixes in #254 ?

**Comment by jwhui** [comment]
@tarunsmalviya, can you try with the latest master branch to see if the issue still exists?

**Comment by jwhui** [comment]
Closing stale issue.
