### ISSUE TITLE
Cannot disable Spinel debug logging 

### ISSUE THREAD

**Issue by krbvroc1** [openthread/ot-br-posix#2323]
I have built using 
```OTBR_OPTIONS=-DOT_LOG_LEVEL=INFO ...```

However my resultant output still contains a ton of 
```
otbr                 | Jun  7 13:18:18 c66b5ad37c98 otbr-agent[158]: 00:00:44.796 [D] P-RadioSpinel-: Sent spinel frame, flg:0x2, iid:0, tid:13, cmd:PROP_VALUE_SET, key:PHY_CHAN, channel:11
otbr                 | Jun  7 13:18:18 c66b5ad37c98 otbr-agent[158]: 00:00:44.796 [D] P-RadioSpinel-: Wait response: tid=13 key=33

```
Is there a bug in the cmake stuff? I don't know how to fix it but it seems it does not pass the OT_LOG_LEVEL into the third_party openthread build which is where the radio_spinel.cpp code is.

**Comment by Irving-cl** [comment]
Hi @krbvroc1,

I guess `OT_LOG_LEVEL_DYNAMIC` is turned on. Could you run `ot-ctl log level 3`? If the command works, the log level should be changed to "INFO".

**Comment by krbvroc1** [comment]
Hi @Irving-cl,
Yes, you are correct. How would I change this?
- If I leave the dynamic turned on, which is a nice feature, can I set the dynamic default to info at compile time? No end user needs to see these message or fill up log files, but it is nice for a developer when troubleshooting.
- If I turn it off, will the OT_LOG_LEVEL be honored?

**Comment by Irving-cl** [comment]
Hi @krbvroc1,

Yes we can set the dynamic default to info. The macro is [OPENTHREAD_CONFIG_LOG_LEVEL_INIT](https://github.com/openthread/openthread/blob/main/src/core/config/logging.h#L113). And the value is determined by `OPENTHREAD_CONFIG_LOG_LEVEL` as well. So `OT_LOG_LEVEL` should work.

Could you provide the full command to build the otbr-agent?

I built it with:
```
./script/cmake-build -DOT_THREAD_VERSION=1.3 -DOTBR_DBUS=ON -DOT_LOG_LEVEL=INFO
```
And I don't see the RadioSpinel logs.

**Comment by krbvroc1** [comment]
@Irving-cl 
I am building under docker.. I am passing...
``` --build-arg="OTBR_OPTIONS=-DOT_LOG_LEVEL=INFO -DOT_CHANNEL_MONITOR=ON -DOT_CHANNEL_MANAGER=ON -DOT_LINK_METRICS_MANAGER=ON -DOT_LINK_METRICS_SUBJECT=ON"```

And within the script/_otbr is has
https://github.com/openthread/ot-br-posix/blob/32f481b2f7446b4d29ea02f043ae6eadae7bff01/script/_otbr#L70-L82

I will note that my ot-br-posix is from Feb 2024, so it is 4 months out of date. Not sure if that matters.

**Comment by Irving-cl** [comment]
Hi @krbvroc1,

I think the `build-arg` usage should be like:
```
 --build-arg OTBR_OPTIONS='-DOT_LOG_LEVEL=INFO -DOT_CHANNEL_MONITOR=ON -DOT_CHANNEL_MANAGER=ON -DOT_LINK_METRICS_MANAGER=ON -DOT_LINK_METRICS_SUBJECT=ON'
``` 
As an example: https://github.com/openthread/ot-br-posix/blob/32f481b2f7446b4d29ea02f043ae6eadae7bff01/.github/workflows/docker.yml#L91

```

```

**Comment by krbvroc1** [comment]
I don't think it matters. I changed to what you had suggested and I see:
```
#6 0.174 OTBR_OPTIONS=-DOT_LOG_LEVEL=INFO -DOT_CHANNEL_MONITOR=ON -DOT_CHANNEL_MANAGER=ON -DOT_LINK_METRICS_MANAGER=ON -DOT_LINK_METRICS_SUBJECT=ON
```
That is no different than my syntax which according to my log files was identical:
```
#6 0.190 OTBR_OPTIONS=-DOT_LOG_LEVEL=INFO -DOT_CHANNEL_MONITOR=ON -DOT_CHANNEL_MANAGER=ON -DOT_LINK_METRICS_MANAGER=ON -DOT_LINK_METRICS_SUBJECT=ON
```
The radiospinel stuff is part of the small batch of files that are fetched from the openthread repository, not ot-br-posix. 

Looking at the build output I see the following, but I still see debug level messages.

```
#9 96.03 OPENTHREAD_CONFIG_LOG_LEVEL_DYNAMIC_ENABLE=1
...
#9 96.03 OPENTHREAD_CONFIG_LOG_LEVEL=OT_LOG_LEVEL_INFO

```

**Comment by Irving-cl** [comment]
Hi @krbvroc1,

could you update the version of ot-br-posix and openthread? If the issue still exists after that, let's do some debugging. First we can add a `static_assert` [here](https://github.com/openthread/openthread/blob/main/src/core/instance/instance.cpp#L72) to see if `sLogLevel` is set correctly during compiling:
```
#if OPENTHREAD_CONFIG_LOG_LEVEL_DYNAMIC_ENABLE
LogLevel Instance::sLogLevel = static_cast<LogLevel>(OPENTHREAD_CONFIG_LOG_LEVEL_INIT);
static_assert(Instance::sLogLevel == OT_LOG_LEVEL_INFO, "Initial log level incorrect");
#endif
```
If the static_assert failed, we further check the value of `OPENTHREAD_CONFIG_LOG_LEVEL_INIT` and `OPENTHREAD_CONFIG_LOG_LEVEL`. Otherwise, it means `sLogLevel` is somehow changed later.

**Comment by krbvroc1** [comment]
Hi @Irving-cl,
I updated to the latest
```
ot-ctl 
version
OPENTHREAD/32f462f; POSIX; Jun 13 2024 12:32:59
```
Same issue with several debug level items:
```
otbr  | Jun 13 12:40:32 7200f296ca22 otbr-agent[163]: 00:00:43.910 [D] Cli-----------: Output: Done
...
otbr  | Jun 13 12:40:48 7200f296ca22 otbr-agent[163]: 00:01:00.015 [D] P-SpinelDrive-: Received spinel frame, flg:0x2, iid:0, tid:10, cmd:PROP_VALUE_IS, key:TIMESTAMP, timestamp:4068868340
...
otbr  | Jun 13 12:41:17 7200f296ca22 otbr-agent[163]: 00:01:28.917 [D] P-RadioSpinel-: Wait response: tid=7 key=33
...
```
I don't think the static_assert did what we want...
```
#9 140.6 /app/third_party/openthread/repo/src/core/instance/instance.cpp:73:25: error: 'ot::LogLevel ot::Instance::sLogLevel' is private within this context
#9 140.6    73 | static_assert(Instance::sLogLevel == OT_LOG_LEVEL_INFO, "Initial log level incorrect");
#9 140.6       |                         ^~~~~~~~~
#9 140.6 compilation terminated due to -Wfatal-errors.

```

**Comment by Irving-cl** [comment]
Hi @krbvroc1,

No problem... Let's use #if #error then:
```
LogLevel Instance::sLogLevel = static_cast<LogLevel>(OPENTHREAD_CONFIG_LOG_LEVEL_INIT);
#if OPENTHREAD_CONFIG_LOG_LEVEL_INIT == OT_LOG_LEVEL_INFO
#error "INIT is INFO"
#else
#error "INIT is not INFO"
#endif
```

**Comment by krbvroc1** [comment]
Not sure if you saw the edit I made, but it and the assert failed, so something wrong with the makefiles somewhere. Nothing I am doing.
```
static_assert(OPENTHREAD_CONFIG_LOG_LEVEL_INIT == OT_LOG_LEVEL_INFO, "Initial log level incorrect");
```

**Comment by Irving-cl** [comment]
Hi @krbvroc1,

I'm just trying to debug this issue. The intention is to find out if `OPENTHREAD_CONFIG_LOG_LEVEL_INIT` is set to `OT_LOG_LEVEL_INFO` in your case by the error output during compiling. So what is the error during compiling?

**Comment by Irving-cl** [comment]
Oh sorry I just noticed your update in eariler comments. So it's not set to `OT_LOG_LEVEL_INFO`. Then let's futher debug on this. 
Could you use #if #error in https://github.com/openthread/openthread/blob/main/src/core/config/logging.h#L88
to check if `OPENTHREAD_CONFIG_LOG_LEVEL` and `OPENTHREAD_CONFIG_LOG_LEVEL_INIT` have already been defined at this stage. (or they have already been defined by the cmake or other configurations)

**Comment by krbvroc1** [comment]
```OPENTHREAD_CONFIG_LOG_LEVEL``` is already defined at that point, but not ```OPENTHREAD_CONFIG_LOG_LEVEL_INIT```

**Comment by Irving-cl** [comment]
I think we are getting closer to the answer.

Could you check `OPENTHREAD_CONFIG_LOG_LEVEL` is already defined [here](https://github.com/openthread/openthread/blob/main/src/posix/platform/openthread-core-posix-config.h#L56)? Or it's just defined by this statement. Since it's DEBG I guess it's just defined by this statement. If so, that means the cmake doesn't correctly pass `OPENTHREAD_CONFIG_LOG_LEVEL=OT_LOG_LEVEL_INFO` to the source code. We can further check CMake.

**Comment by krbvroc1** [comment]
How do I turn off #warning as errors? It is painful to set #warning and have it abort entire compilation / troubleshooting.

**Comment by Irving-cl** [comment]
You can add `-DOT_COMPILE_WARNING_AS_ERROR=OFF`. But I doubt that somehow the cmake options didn't work now and OT_LOG_LEVEL wasn't set correctly. 

BTW, did you change some source code? Otherwise there shouldn't be any warnings.

**Comment by krbvroc1** [comment]
```
#ifdef OPENTHREAD_CONFIG_LOG_LEVEL
#if OPENTHREAD_CONFIG_LOG_LEVEL == OT_LOG_LEVEL_INFO
#warning "LOG_LEVEL is INFO"
#elif OPENTHREAD_CONFIG_LOG_LEVEL == OT_LOG_LEVEL_DEBG
#warning "LOG_LEVEL is DEBG"
#elif OPENTHREAD_CONFIG_LOG_LEVEL == OT_LOG_LEVEL_CRIT
#warning "LOG_LEVEL is CRIT"
#elif OPENTHREAD_CONFIG_LOG_LEVEL == OT_LOG_LEVEL_WARN
#warning "LOG_LEVEL is WARN"
#elif OPENTHREAD_CONFIG_LOG_LEVEL == OT_LOG_LEVEL_NOTE
#warning "LOG_LEVEL is NOTE"
#elif OPENTHREAD_CONFIG_LOG_LEVEL == OT_LOG_LEVEL_NONE
#warning "LOG_LEVEL is NONE"
#else
#warning "LOG_LEVEL is something else"
#endif
#else
#warning "OPENTHREAD_CONFIG_LOG_LEVEL not defined"
#endif

```
Results in
```
#9 54.10 In file included from /app/third_party/openthread/repo/src/core/openthread-core-config.h:68,
#9 54.10                  from /app/third_party/openthread/repo/src/posix/platform/openthread-posix-config.h:32,
#9 54.10                  from /app/third_party/openthread/repo/src/posix/platform/platform-posix.h:38,
#9 54.10                  from /app/third_party/openthread/repo/src/posix/platform/radio_url.cpp:36:
#9 54.10 /app/third_party/openthread/repo/src/posix/platform/openthread-core-posix-config.h:57:2: error: #warning "LOG_LEVEL is INFO" [-Werror=cpp]
#9 54.10    57 | #warning "LOG_LEVEL is INFO"
#9 54.10       |  ^~~~~~~
#9 54.10 compilation terminated due to -Wfatal-errors.

```

And even though I pass -DOT_COMPILE_WARNING_AS_ERROR=OFF as --build-arg, it still does not disable it. See about -
Wfatal-errors.
```
#9 53.04 ++ OTBR_OPTIONS='-DOT_COMPILE_WARNING_AS_ERROR=OFF -DOT_LOG_LEVEL=INFO -DOT_CHANNEL_MONITOR=ON -DOT_CHANNEL_MANAGER=ON -DOT_LINK_METRICS_MANAGER=ON -DOT_LINK_METRICS_SUBJECT=ON'
```

No I did not change some source code, I was just trying to use multiple #ifdef #warnings but the first one stops compilation.

**Comment by Irving-cl** [comment]
Hi @krbvroc1,

Sorry I forgot that there is an argument of otbr-agent that sets the initial log level: https://github.com/openthread/ot-br-posix/blob/main/src/agent/main.cpp#L90

So we can set the initial logging level by `-d{n}`. `-d7` is debug level. For example, start otbr-agent by `otbr-agent -d7 ...`.
To change it to info level, use `-d6`. How did you start otbr-agent? Could you check the program arguments and set it to `-d6` and try again?

**Comment by Irving-cl** [comment]
ot-br-posix and openthread do have different log util functions. ot-br-posix will set openthread's log level to the same as it by `otLoggingSetLevel`: https://github.com/openthread/ot-br-posix/blob/main/src/ncp/rcp_host.cpp#L184
```
    otLogLevel level = ConvertToOtLogLevel(otbrLogGetLevel());

#if OTBR_ENABLE_FEATURE_FLAGS && OTBR_ENABLE_TREL
    FeatureFlagList featureFlagList;
#endif

    VerifyOrExit(otLoggingSetLevel(level) == OT_ERROR_NONE, error = OTBR_ERROR_OPENTHREAD);
```

When you pass `-d6` what's the output of `ot-ctl log level`?

Could you provide more details of the build and run? I'll try to reproduce it locally and debug.

**Comment by krbvroc1** [comment]
@Irving-cl I figured out the issue and submitted a pull request.
