### ISSUE TITLE
"OpenThread daemon is not running": unable to make OTBR work @Docker

### ISSUE THREAD

**Issue by KC-inDomus** [openthread/ot-br-posix#2390]
Invested a lot of time trying to make OTBR work with Docker both on Raspberry Pi OS and Debian with a Sonoff ZBDongle-E (with [RCP Thread](https://github.com/darkxst/silabs-firmware-builder/tree/main/firmware_builds/zbdonglee) firmware version 2.4.3.0 `ot-rcp-v2.4.3.0-zbdonglee-460800.gbl`) with no success.

On the very same hardware that runs Debian (and the very same sonoff adapter), I tried running Home Assistant OS + OTBR Add-on, and everything **works fine**.

This is the command I tried 
`docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 -dns=127.0.0.1 -it --device /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr --r:testadio-url spinel+hdlc+uart:///dev/ttyACM0`

being sure that:
- /dev/ttyACM0 is correct;
- backbone is fine (tried even specifing `--backbone-interface` parameter);
- openthread/otbr is the image I choosed, but I tried several elses;
- openthread/otbr is [the last version](https://hub.docker.com/layers/openthread/otbr/latest/images/sha256-1c7bbe89a4c662f4b9809a3f5e8884a8ee8d21677cdafaa5487edcdb72ffea46?context=explore);
- tried both wi-fi and eth connections.

Output is always the same:

```
Jul 20 09:57:30 0bce0a258388 kernel: [  201.751479] docker0: port 1(vethf93e1f5) entered disabled state
Jul 20 09:57:30 0bce0a258388 kernel: [  201.751599] device vethf93e1f5 entered promiscuous mode
Jul 20 09:57:30 0bce0a258388 kernel: [  201.751839] docker0: port 1(vethf93e1f5) entered blocking state
Jul 20 09:57:30 0bce0a258388 kernel: [  201.751847] docker0: port 1(vethf93e1f5) entered forwarding state
Jul 20 09:57:30 0bce0a258388 kernel: [  201.752708] docker0: port 1(vethf93e1f5) entered disabled state
Jul 20 09:57:30 0bce0a258388 kernel: [  202.125980] eth0: renamed from vethf2a234c
Jul 20 09:57:30 0bce0a258388 kernel: [  202.142475] IPv6: ADDRCONF(NETDEV_CHANGE): vethf93e1f5: link becomes ready
Jul 20 09:57:30 0bce0a258388 kernel: [  202.142599] docker0: port 1(vethf93e1f5) entered blocking state
Jul 20 09:57:30 0bce0a258388 kernel: [  202.142605] docker0: port 1(vethf93e1f5) entered forwarding state
Jul 20 09:57:30 0bce0a258388 mDNSResponder: Default: mDNSResponder (Engineering Build) (Jul 19 2024 17:58:29) starting
Jul 20 09:57:30 0bce0a258388 otbr-web[172]: [INFO]-WEB-----: Running 0.3.0-3ab211f
Jul 20 09:57:30 0bce0a258388 otbr-web[172]: [INFO]-WEB-----: Border router web started on wpan0
Jul 20 09:57:30 0bce0a258388 otbr-web[172]: [ERR ]-WEB-----: OpenThread daemon is not running.
Jul 20 09:57:30 0bce0a258388 otbr-agent: [NOTE]-AGENT---: Backbone interface: eno0
Jul 20 09:57:30 0bce0a258388 otbr-agent[199]: [NOTE]-AGENT---: Running 0.3.0-3ab211f
Jul 20 09:57:30 0bce0a258388 otbr-agent[199]: [NOTE]-AGENT---: Thread version: 1.3.0
Jul 20 09:57:30 0bce0a258388 otbr-agent[199]: [NOTE]-AGENT---: Thread interface: wpan0
Jul 20 09:57:30 0bce0a258388 otbr-agent[199]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB0
Jul 20 09:57:30 0bce0a258388 otbr-agent[199]: [NOTE]-ILS-----: Infra link selected: eno0
Jul 20 09:57:30 0bce0a258388 otbr-agent[199]: [INFO]-RCP_HOS-: OpenThread log level changed to 5
```
Even if webgui is actually working, no OT daemon is running (as the logs says "**OpenThread daemon is not running.**").

No way to make it work. Anyone?
KC

**Comment by snakuzzo** [comment]
I tried just now on Ubuntu 22.04.4 LTS. Same issue

**Comment by KC-inDomus** [comment]
Solved by myself using this command:

`docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 --dns=127.0.0.1 -it --volume **/dev/ttyACM0:/dev/ttyUSB0** --privileged openthread/otbr --radio-url spinel+hdlc+uart:///**dev/ttyUSB0?uart-baudrate=460800**`

therefore having the foresight to map the local device (`/dev/tty/ACM0`) to the interan expected one (`/dev/ttyUSB0`) and specifying the baud speed of the device (`460800`).
all of this did the magic.

the corresponding docker compose code is:

```
service:
  otbr:
    container_name: "otbr"
    image: openthread/otbr
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1
          net.ipv6.conf.all.forwarding=1
    ports:
        - 8080:80
        - 8081:8081
    dns:
        - 127.0.0.1
    stdin_open: true
    tty: true
    volumes:
        - /dev/ttyACM0:/dev/ttyUSB0
    privileged: true
    command: ["--radio-url", "spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=460800"]
```

Best
KC
