### ISSUE TITLE
The otbr-agent exits abnormally, "Inferior 1 exited with code 01".

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/ot-br-posix#2477]
Describe the bug: The otbr-agent exits abnormally, "Inferior 1 exited with code 01".
The ot-br-posix code used is: https://github.com/SiliconLabs/simplicity_sdk/tree/sisdk-2024.6/util/third_party/ot-br-posix
![85840998e53427321e304ff2cb3e218](https://github.com/user-attachments/assets/4295ac6d-db5c-4041-9f5d-8a42da9e4a3d)

Exit here, please see log.
[SyslogCatchAll-2024-08-28-inferior.txt](https://github.com/user-attachments/files/16888435/SyslogCatchAll-2024-08-28-inferior.txt)
![image](https://github.com/user-attachments/assets/2a84018b-930d-468b-a29a-6412b903ec5e)

**Comment by silabs-sebastien** [comment]
@jinpeng1989 from your discussion in [issue 10673](https://github.com/openthread/openthread/issues/10673), it seems like your otbr-agent might be crashing due to corrupted settings. Is your otbr-agent crashing every time you start it or only sometimes?

**Comment by jinpeng1989** [comment]
It is not clear whether the settings corruption is the root cause of the otbr-agent crash. We just observe that after the otbr-agent crashes, the last syslog print by otbr-agent is always "otPlatSettingsGet() at settings.cpp:259 Failure". Can you help check if the settings file is corrupted?

**Comment by silabs-sebastien** [comment]
@jinpeng1989 Fair point. Could you provide (attach here) a copy of the content of the settings before the crash (i.e.: as close to before the crash as possible; you may want to instrument the code to do so)?

**Comment by jinpeng1989** [comment]
This issue is introduced by the extended ubus interface of the product. The otDatasetGetActive and otDatasetGetActiveTlvs were called incorrectly in UbusGetInformation. https://github.com/openthread/openthread/issues/10673
