### ISSUE TITLE
Unable to receive packet when NCP state is end-device.

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#251]
I noticed that after NCP changed its state from **leader** to **end-device**, packets were not reaching CoAP server.
Below is screenshot of NCP state:
![ncp_as_end_device](https://user-images.githubusercontent.com/9993036/52934163-a2fd1600-337b-11e9-9fa1-a340bd8746b6.png)

**Comment by bukepo** [comment]
could you please give details about this? What CoAP server? How do you test reaching CoAP server?

**Comment by tarunsmalviya** [comment]
@bukepo I am using CoAP Californium server.
I tested by checking logs. When NCP is in end-device state, no packet is received at CoAP server. After some time when state changes to router, then packet are received on CoAP server.

**Comment by jwhui** [comment]
@tarunsmalviya, any chance you can try with a more recent NCP build? You can find pre-built images and instructions to build your own [here](https://openthread.io/guides/ncp/firmware).

**Comment by tarunsmalviya** [comment]
@jwhui Sure. Will update you after that.

**Comment by bukepo** [comment]
@tarunsmalviya any update?

**Comment by tarunsmalviya** [comment]
@bukepo Yes. I tried with flashing latest NCP built, but the problem remains.

**Comment by LuDuda** [comment]
@tarunsmalviya what is the CoAP server address that you use?

**Comment by tarunsmalviya** [comment]
@LuDuda 
IPv6: 2001:db8:1:ffff::a00:1
IPv4: 10.0.0.1

**Comment by bukepo** [comment]
Could you please provide the exact step to reproduce this issue? I am wondering why the node changes from leader to end device. Are you manually setting the role?

**Comment by tarunsmalviya** [comment]
I have built border router(BR) having NCP attached using RPi. In network I had 11 routers(FTD) and 15 end-nodes(SED). Sometime what happens is, NCP degrade from router/leader to end-device and packet does not reach BR. I don't know why BR is being degrade to end-device because as name suggest, it should be either leader or router.

**Comment by librasungirl** [comment]
@tarunsmalviya 
Will the NCP stay in end-device role longer than 2min? Do you have the capture and the wpantund log?

**Comment by tarunsmalviya** [comment]
@librasungirl I have observed maximum of 5 minutes, after that sometimes it goes to router state else I have to reset NCP and recreate network.

Can you let me know where wpantund logs are stored?

**Comment by librasungirl** [comment]
It is in syslog (`/var/log/syslog`) with `wpantund` process name, this log may help to analyze the ncp device behavior.

5 mins seems quite abnormal. If you have the capture, it may help to analyze the network behavior better - as there should be no spontaneous downgrade in your setup theoretically.

**Comment by tarunsmalviya** [comment]
@librasungirl I checked the syslog and discovered that the NCP remains to "end-device" state for max 4 minutes.

```
Mar  2 02:11:31 Spar-01 wpantund[3075]: Node type change: "unknown" -> "end-device"

Mar  2 02:11:31 Spar-01 wpantund[3075]: Pushing a new SLAAC address fddf:dd::447b:7a93:d6c:c008/64 to NCP
Mar  2 02:11:31 Spar-01 wpantund[3075]: Adding address "fddf:dd::447b:7a93:d6c:c008/64" to NCP
Mar  2 02:11:31 Spar-01 wpantund[3075]: Adding on-mesh prefix "fddf:dd::/64" to NCP
Mar  2 02:11:43 Spar-01 wpantund[3075]: wpantund[3075]: SpinelNCPTaskSendCommand.cpp:340: Requirement Failed ((mRetVal) == 0)
Mar  2 02:11:43 Spar-01 wpantund[3075]: wpantund[3075]: SendCommand task encountered an error: 16 (0x00000010)
Mar  2 02:11:43 Spar-01 wpantund[3075]: SpinelNCPTaskSendCommand.cpp:340: Requirement Failed ((mRetVal) == 0)
Mar  2 02:11:43 Spar-01 wpantund[3075]: SendCommand task encountered an error: 16 (0x00000010)
Mar  2 02:14:53 Spar-01 wpantund[3075]: wpantund[3075]: SpinelNCPTaskSendCommand.cpp:340: Requirement Failed ((mRetVal) == 0)
Mar  2 02:14:53 Spar-01 wpantund[3075]: wpantund[3075]: SendCommand task encountered an error: 16 (0x00000010)
Mar  2 02:14:53 Spar-01 wpantund[3075]: SpinelNCPTaskSendCommand.cpp:340: Requirement Failed ((mRetVal) == 0)
Mar  2 02:14:53 Spar-01 wpantund[3075]: SendCommand task encountered an error: 16 (0x00000010)

Mar  2 02:15:30 Spar-01 wpantund[3075]: wpantund[3075]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)**

Mar  2 02:15:30 Spar-01 wpantund[3075]: wpantund[3075]: State change: "associated" -> "uninitialized"
Mar  2 02:15:30 Spar-01 wpantund[3075]: wpantund[3075]: Taking interface(s) down. . .
Mar  2 02:15:30 Spar-01 wpantund[3075]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Mar  2 02:15:30 Spar-01 wpantund[3075]: State change: "associated" -> "uninitialized"
```

Also, is it okay that NCP sometimes transit between "unknown", "end-device" and "router" state. As according to me NCP should be either "router" or "leader".
Check log from **Mar  2 02:11:31** to **Mar  2 06:21:31**

I am attaching syslog. 

[wpantund_Mar_1.txt](https://github.com/openthread/ot-br-posix/files/2945274/wpantund_Mar_1.txt)
[wpantund_Mar_2.txt](https://github.com/openthread/ot-br-posix/files/2945275/wpantund_Mar_2.txt)

**Comment by librasungirl** [comment]
It should be not normal. @abtink , do you have any thoughts why wpantund keep 'Taking interface(s) down' and reset NCP in the attached log?

Noticing you are using quite new NCP fw (795a7e91, Feb 19, 2019) but outdated wpantund (47f3212, Oct 12, 2018), would you mind updating the wpantund (better plus otbr-agent) as well?

**Comment by abtink** [comment]
The logs show it NCP was reset "[-NCP-]: NCP was reset (RESET_POWER_ON, 112)**" that why `wpantund` is correctly bringing the interface down (before reinit the NCP). 

Seems like before this device is trying to add an on-mesh prefix and fails. 
One thing I can suggest to check is if the OPENTHREAD_ENABLE_BORDER_ROUTER is correctly enabled (`--enable-border-router` in configure) on your NCP build.

Note that we need this to be able to add an on-mesh-prefix on NCP (on in general make any changes to network data), and in order to be able use the address wpantund would auto-add an prefix for any added unicast IPv6 address (where none already exist).

Other things I can suggest, increase your log level for both NCP and wpantund. For NCP checkout the `LOG_LEVEL` config options. 
For wpantund, you can add this in your `wpantund.conf` file (can also be changed at run-time using wpantctl and same property name). 
```
Daemon:SyslogMask "all -debug"
```

**Comment by tarunsmalviya** [comment]
@abtink As per your suggestion I have increase log level.

Also, I have noticed that in general there are two type of on mesh prefix, i.e., origin:user and origin:ncp.
If one of them is missing, then packets doesn't reach to border router.

**Comment by jwhui** [comment]
@tarunsmalviya, any further comments on this issue?

**Comment by tarunsmalviya** [comment]
@jwhui After updating border router, only once I faced this issue. I don't have logs due to lack of time of occurence.

**Comment by jwhui** [comment]
@tarunsmalviya, thanks for reporting back. I'll close this issue for now.
