### ISSUE TITLE
External commissioner fails to authenticate

### ISSUE THREAD

**Issue by sathish-indin** [openthread/ot-br-posix#261]
With the latest build, formed a thread network with otbr using otbr-web-gui.
OTBR is deployed in Rpi with kw41x nxp running latest openthread
When External commissioner Thread android app joins the OTBR AP and tries to authenticate itself with passphrase, it fails throwing error "Password is incorrect". But the issue doesnt appear in previous month old builds.

**Comment by bukepo** [comment]
Is otbr the only node or the first node of the Thread network? If not, the password may not be successfully set when you form network in the web gui.

**Comment by sathish-indin** [comment]
Otbr is the only node and he was in leader state when the network is formed.
Tried changing the passprase when the network is formed and could see the PSKc changing accordingly in the wpanctl command.

**Comment by bukepo** [comment]
Thank you, could you please share the command to build NCP?

**Comment by sathish-indin** [comment]
These are the options used when building the otbr NCP. 
BORDER_AGENT=1 BORDER_ROUTER=1 COMMISSIONER=1 UDP_PROXY=1 JOINER=1

**Comment by bukepo** [comment]
Hi, I am not sure if you updated source of OpenThread. If so, you have to update build flag `UDP_PROXY` to `UDP_FORWARD`.

**Comment by bukepo** [comment]
Does it help?

**Comment by sathish-indin** [comment]
No. Still the same issue even with UDP_FORWARD attribute.

**Comment by bukepo** [comment]
Hi @sathish-indin, did you cleaned old build directory? It will not take effect by just modifying the flags. You have to clean the old build directory.

**Comment by jwhui** [comment]
Closing stale issue.

**Comment by NikhilSarnaik** [comment]
Hi @jwhui this issue still persists with the latest ot-br-posix repo. I get the same issue where I see the thread network on the android app but I keep incorrect password error when I try to connect. Is there any workaround this ?
Thanks Nikhil
