### ISSUE TITLE
otbr-agent unable to communicate with RCP

### ISSUE THREAD

**Issue by dakhnod** [openthread/ot-br-posix#2635]
When sending bigger amounts of data (a few KB/s), the Tread stack on my linux machine crashes.
Even worse, sometimes it reaches a state where it is unable to re-establish communication with the RCP.
The only solution we found in such a case is restarting the whole OS.

Is this a known issue?
Is it avoidable for the otbr-agent to crash at all?
What could cause the RCP connection to break so badly?

The is the error I am getting from the otbr-agent:

```
Dez 09 17:25:24 wtc otbr-agent[11862]: 00:00:10.212 [W] P-RadioSpinel-: radio tx timeout
Dez 09 17:25:24 wtc otbr-agent[11862]: 00:00:10.212 [C] P-RadioSpinel-: Failed to communicate with RCP - no response from RCP during initialization
Dez 09 17:25:24 wtc otbr-agent[11862]: 00:00:10.212 [C] P-RadioSpinel-: This is not a bug and typically due a config error (wrong URL parameters) or bad RCP image:
Dez 09 17:25:24 wtc otbr-agent[11862]: 00:00:10.212 [C] P-RadioSpinel-: - Make sure RCP is running the correct firmware
Dez 09 17:25:24 wtc otbr-agent[11862]: 00:00:10.212 [C] P-RadioSpinel-: - Double check the config parameters passed as `RadioURL` input
Dez 09 17:25:24 wtc otbr-agent[11862]: 00:00:10.212 [C] Platform------: HandleRcpTimeout() at radio_spinel.cpp:2011: RadioSpinelNoResponse
```

**Comment by jwhui** [comment]
Such issues are typically very specific to the given RCP implementation and the platform-specific drivers. Have you reached out to the RCP vendor for support?

**Comment by dakhnod** [comment]
You seem to be right, with an nRF52 dongle RCP the connection is way better.
Could have something to do with a proper UART connection somewhere in between...

Thanks!
