### ISSUE TITLE
Border router does not forward CoAP multicast messages

### ISSUE THREAD

**Issue by frif-ch** [openthread/ot-br-posix#264]
### Setup
There is a computer and an OpenThread border router connected to our IPv6 router. (So, they are in the same network). Additionaly, there is a thread device connected to the border router.

### Goal
In the end, I want to discover all CoAP servers in the thread network by sending a CoAP multicast message. (E.g. GET /.well-known/core or CoAP ping)

### Issue
I'm able to send a CoAP GET request from the computer directly to the thread device by using its global IPv6 address. The thread device sends the expected response and everything works fine.

However, when I send a CoAP GET request from the computer to either `ff03::1` or `ff08::1`, the message is not forwarded to the thread network by the border router. I captured the traffic on the border router on eth0 (which is connected to the IPv6 router). There, I can see that the border router receives the CoAP multicast message from the computer. But I cannot see this message beeing forwarded to the thread network (By sniffing the thread traffic).

### Question
Does the openthread border router support multicast messages? If so, do I have to enable it somehow or should it be enabled by default? 

Is my approach even reasonable?

Thanks in advance for any kind of help!

**Comment by librasungirl** [comment]
@frif-ch , multicast routing should be set up to let OTBR  forward multicast traffic into thread network. 
you may want to try the static multicast routing [SMCRoute](https://github.com/troglobit/smcroute/)
and add multicast route either in conf or via command `sudo smcroutectl add eth0 :: ff08::1 wpan0`

**Comment by frif-ch** [comment]
@librasungirl - Thanks a lot for your quick answer. Sorry that I come back to you just now, I had to get started with the SMCRoute tool first. Since I had some troubles with the current version of SMCRoute, I went back to the last offical release (v2.4.4). 

I tried to add the multicast route with your example command `sudo smcroutectl add eth0 :: ff08::1 wpan0` and afterwards I also tried it with the following two lines in the **smcroute.conf** file:
``` 
mgroup from eth0 group ff08::1
mgroup from eth0 group ff08::1 to wpan0
``` 

Still, the border router does not forward CoAP messages with destination ff08::1 to the thread network. I have already tried / checked the following:

- the **smcroute.service** is active and running. 
- I restarted the service several times
- I restarted the border router several times
- kernel configuration requirements for smcroute are met
- direct addressing still works
- CoAP message is received on interface eth0
- eth0 and wpan0 have enabled MULTICAST (checked with `ifconfig` )

Is the following output of  `sudo smcroutectl show` as you would expect? I would have expected something about wpan0 in the outbound column..
```  
ROUTE (S,G)                        INBOUND             PACKETS      BYTES  OUTBOUND
(192.168.2.116, 239.255.255.250)   eth0                     38       6990 
(192.168.2.78, 239.255.255.250)    eth0                     57      10269  
```

Do you have any idea what the problem might be?

**Comment by librasungirl** [comment]
@frif-ch , sorry for late response. It seems ipv6 mutlicast forwarding is not well supported in existing smcroute repo, as well as the `show` command.

Would you please try out [this updated branch](https://github.com/librasungirl/smcroute/tree/ip6_mf)?

**Comment by librasungirl** [comment]
@frif-ch , the update on smcroute is now pushed to the upstream from review (https://github.com/troglobit/smcroute/pull/124).  And it works well on my trial. 
Do you have any update on this?

**Comment by frif-ch** [comment]
@librasungirl , thanks a lot for your effort! I cannot get the v2.5.0-beta1 to work (neither your version nor the official one). Only with the v2.4.4, the smcroute service does not fail to start.

With v2.5.0-beta1, the Static multicast routing daemon fails to start. `sudo journalctl -u smcroute.service ` gives me the following output (which is not very specific):

```
Apr 15 18:57:25 ot-router smcroute[12654]: SMCRoute v2.5.0-beta1
Apr 15 18:57:25 ot-router smcroute[12654]: Ready, waiting for client request or kernel event.
Apr 15 18:58:55 ot-router systemd[1]: smcroute.service: Start operation timed out. Terminating
Apr 15 18:58:55 ot-router systemd[1]: Failed to start Static multicast routing daemon.
Apr 15 18:58:55 ot-router systemd[1]: smcroute.service: Unit entered failed state.
Apr 15 18:58:55 ot-router systemd[1]: smcroute.service: Failed with result 'timeout'.
```

Did you try on an OT border router?

Unfortunately, I will not be able to work on it for the next three weeks. Maybe one of my colleagues will continue in the meantime.

**Comment by librasungirl** [comment]
@frif-ch , the issue you mentioned should have been officially fixed by the maintainer in these two days. (https://github.com/troglobit/smcroute/commit/c7db569b83b188fc0985c165c0eb1cb973713817)

The service type was simply updated from 'notify' to 'simple' as a workaround. However I forced push once when submitting (troglobit/smcroute#124).  Would you please check whether the branch you used has the commit id cf40e9c?

Yes, I tried on OTBR.

**Comment by frif-ch** [comment]
@librasungirl , I finally got the time to try it again. I setup everything from scratch (OTBR and smcroute with commit id cf40e9c) and it works now. Thank you very much! 👍
