### ISSUE TITLE
How to update border router remotely without affecting network configuration?

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#273]
I am trying to update border router remotely, but it fails in between because of wifi disconnection when tends to failure of third_party repo update. 
Running `./script/setup NETWORK_MANAGER=0` does not prevent set up of RPi as AP. 
Also running `./script/update` disconnect RPi from wifi.

**Comment by bukepo** [comment]
Please use `NETWORK_MANAGER=0 ./script/setup` to disable setting up AP.

**Comment by tarunsmalviya** [comment]
@bukepo It worked. Thanks!
