### ISSUE TITLE
How to update OTBR on large scale controllers?

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#278]
I want to update ot-br-posix on multiple controllers which are spread out in different geometrical location. I am using `scripts/update` script to updated ot-br-posix. When updating ot-br-posix remotely, if the power is cut off in between updation, then we have to redo the whole updating process and I will lose data for that particular time. 
Is there any way, I can place precompiled binary and no need to compile in each controller every time I update ot-br-posix.

**Comment by bukepo** [comment]
For now, I would recommend running this project through docker. We will release the latest [otbr](https://cloud.docker.com/u/openthread/repository/docker/openthread/otbr).

**Comment by tarunsmalviya** [comment]
@bukepo Okay
