### ISSUE TITLE
Web GUI functional test

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#28]
I think we should add some basic functional tests for web. To make this happen, I think we should have the following changes,

1. support set listening port at runtime instead of hard coded 80.
2. support set location of front-end files at runtime instead of fixed at compiling time.
3. document HTTP APIs.

**Comment by beriberikix** [comment]
Angular also has a bunch of native constructs for both [Unit](https://docs.angularjs.org/guide/unit-testing) and [e2e](https://docs.angularjs.org/guide/e2e-testing) testing. See also [karma](http://karma-runner.github.io/).

**Comment by LeZhang2016** [comment]
@beriberikix , Thanks a lot for your suggestion, i will investigate the test methods you proposed.:-)

**Comment by jwhui** [comment]
Closing stale issue.
