### ISSUE TITLE
How to change port of otbr-web server?

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#280]

**Comment by bukepo** [comment]
Hi, you may apply PR #281 and create file */etc/default/otbr-web*. e.g.
```bash
OTBR_WEB_OPTS="-p 8080"
```

**Comment by bukepo** [comment]
Does it work?

**Comment by tarunsmalviya** [comment]
@bukepo Apologise for delay. Will update you by the end of week.

**Comment by tarunsmalviya** [comment]
@bukepo It worked.

**Comment by bukepo** [comment]
Thanks for the update!
