### ISSUE TITLE
[docker] Minimize the docker image

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#284]
**Is your feature request related to a problem? Please describe.**
I found the docket image is of size more than 1G

**Describe the solution you'd like**
Remove unnecessary packages and build source. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by librasungirl** [comment]
docker image for raspberry pi is still up to 1.13GB 

> pi@raspberrypi:~ $ docker images
> REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
> openthread/otbr_arm32v7l_raspbian   latest              bdf2891b16fa        36 hours ago        1.13GB
> docker history openthread/otbr_arm32v7l_raspbian:latest
> IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
> bdf2891b16fa        35 hours ago        /bin/sh -c #(nop)  EXPOSE 80                    0B
> <missing>           35 hours ago        /bin/sh -c #(nop)  ENTRYPOINT ["/app/etc/doc…   0B
> <missing>           35 hours ago        /bin/sh -c apt-get autoremove -y -o APT::Aut…   2.68MB
> <missing>           35 hours ago        /bin/sh -c mv /tmp/script . && mv /tmp/etc .    90.5kB
> <missing>           35 hours ago        /bin/sh -c find . -delete && rm -rf /usr/inc…   0B
> <missing>           35 hours ago        /bin/sh -c mv ./script /tmp && mv ./etc /tmp    90.5kB
> <missing>           35 hours ago        /bin/sh -c chmod 644 /etc/bind/named.conf.op…   1.11kB
> <missing>           35 hours ago        /bin/sh -c ./script/bootstrap && ./script/se…   452MB
> <missing>           36 hours ago        /bin/sh -c git reset --hard && git clean -xf…   6MB
> <missing>           36 hours ago        /bin/sh -c apt-get update && apt-get install…   433MB
> <missing>           36 hours ago        /bin/sh -c #(nop) WORKDIR /app                  0B
> <missing>           36 hours ago        /bin/sh -c #(nop) COPY dir:6abacc6a142cd87a8…   168MB
> <missing>           36 hours ago        /bin/sh -c #(nop)  ENV DNS64=1                  0B
> <missing>           36 hours ago        /bin/sh -c #(nop)  ENV NAT64=1                  0B
> <missing>           36 hours ago        /bin/sh -c #(nop)  ENV RELEASE=1                0B
> <missing>           36 hours ago        /bin/sh -c #(nop)  ENV DEBIAN_FRONTEND=nonin…   0B
> <missing>           2 days ago          /bin/sh -c #(nop)  CMD ["/bin/bash"]            0B
> <missing>           2 days ago          /bin/sh -c mkdir -p /run/systemd && echo 'do…   7B
> <missing>           2 days ago          /bin/sh -c rm -rf /var/lib/apt/lists/*          0B
> <missing>           2 days ago          /bin/sh -c set -xe   && echo '#!/bin/sh' > /…   745B
> <missing>           2 days ago          /bin/sh -c #(nop) ADD file:1f4fdc61e133d2f90…   69.9MB

Each instruction in Dockerfile would add one layer, and the sizes of each layer add up to equal the size of the final image.

We should either refine the Dockerfile or use `--squash` option to help to squash newly built layers into a single new layer

**Comment by mchwalisz** [comment]
Instead of trying to reduce size of each layer, it might be easier to use [docker multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/). It will allow to add second stage in which only necessary libraries should be installed and binaries can be copied over from the first stage.

**Comment by librasungirl** [comment]
@mchwalisz , thanks for your suggestions. agree that multi-stage builds have advantages in some use cases. However for OTBR, it has many dependent services, not just one binary. 

I have just updated (#290) to further remove the irrelevant dependent build tools to reduce the image size. Would you please help to take a look? Thanks.

**Comment by mchwalisz** [comment]
Yes, I have already figured out that there are a lot of services started inside docker. Splitting the build tools is a very good start.

I don't know enough (yet) about the OTBR to actually help in review, will try to build it though.

**Comment by jwhui** [comment]
Resolved by #290.
