### ISSUE TITLE
[docker] Docker image could not work well on Raspberry Pi

### ISSUE THREAD

**Issue by librasungirl** [openthread/ot-br-posix#289]
**Describe the bug**
When running openthread/otbr_arm32v7l_raspbian:latest docker image on Raspberry Pi, it will complain

> standard_init_linux.go:190: exec user process caused "exec format error"

**To Reproduce**
docker pull openthread/otbr_arm32v7l_raspbian:latest (https://hub.docker.com/r/openthread/otbr_arm32v7l_raspbian)

Raspberry Pi 3 B+ with latest stretch lite and docker installed

> docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8080:80 --dns=127.0.0.1 -it --volume /dev/ttyACM0:/dev/ttyACM0 --name otbr --privileged openthread/otbr_arm32v7l_raspbian:latest
> WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
> standard_init_linux.go:190: exec user process caused "exec format error"

**Additional context**
A bit dig on the issue, it seems some architecture issue.
https://forums.docker.com/t/standard-init-linux-go-190-exec-user-process-caused-exec-format-error/49368

**Comment by librasungirl** [comment]
@jwhui, It seems that platform is not properly set for otbr_arm32v7l_raspbian 
> // from https://cloud.docker.com/u/openthread/repository/docker/openthread/otbr_arm32v7l_raspbian/timeline
> Arch: amd64
> BuildTime: 2018-08-30T18:42:30.000000000+00:00
> ApiVersion: 1.37
> Platform: {u'Name': u''}
> Version: 18.03.1-ee-3
> MinAPIVersion: 1.12
> GitCommit: b9a5c95
> Os: linux
> GoVersion: go1.10.2
> Starting build of index.docker.io/openthread/otbr_arm32v7l_raspbian:latest...
> Step 1/17 : FROM ubuntu
> ---> 7698f282e524

**Comment by jwhui** [comment]
@librasungirl thanks for raising this.

Yes, we need to cross-compile for arm on Docker Hub.

There is one solution presented here: https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

Other ideas?

**Comment by jwhui** [comment]
I disabled the autobuild on Docker Hub and pushed an image for `openthread/otbr_arm32v7l_raspbian` that should work. We can enable autobuild on Docker Hub when we have this sorted out.

**Comment by jwhui** [comment]
Resolved by #518
