### ISSUE TITLE
Switching to C++11?

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#291]
**Is your feature request related to a problem? Please describe.**
We are integrating some code written in C++11. And otbr-web also requires C++11.

**Describe the solution you'd like**
I'm considering switching to whole source code style of this project to C++11 as well, including otbr-agent, otbr-comimssioner and otbr-web.

**Describe alternatives you've considered**
None

@jwhui Thoughts?

**Comment by jwhui** [comment]
I am OK with moving to C++11 for ot-br-posix.

**Comment by jwhui** [comment]
Resolved by #293.
