### ISSUE TITLE
Script to cross compile. 

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#295]
**Is your feature request related to a problem? Please describe.**
Currently there is no script included for build docker for raspberry pi with cross compile. 

**Describe the solution you'd like**
Provide a unified script to cross compile for different platforms. 

**Describe alternatives you've considered**
Enhance guide to describe how to build docker image with cross compile. 

**Additional context**
It is slow to build natively on raspberry pi.

**Comment by jwhui** [comment]
This should also address #289.

**Comment by jwhui** [comment]
Closing stale issue.
