### ISSUE TITLE
IPv6 incompatibility

### ISSUE THREAD

**Issue by jaimemi** [openthread/ot-br-posix#296]
Hi!

I am trying to configure a Raspberry Pi as a Border Router at my university. I retiently realised that there is not ipv6 support for any of the ethernet ports I can connect there. Is it possible tu use the Border Router with IPv4 only? I was thinking of using the 8.8.8.8 DNS from Google instead of the IPv6 version.

Thank you!

**Comment by jwhui** [comment]
@jaimemi, OTBR supports both NAT64 and DNS64.

Using the OpenThread CLI on a Thread device, you should be able to do something like:
```bash
dns resolve ipv4.google.com 64:ff9b::0808:0808
```

**Comment by jaimemi** [comment]
hi! I tried it but it only work with www.google.com. Indeed, it retursn this address: 2a00:1450:400f:80c:0:0:0:2004, but I can't ping it afterwards.

This is what it says after dns resolve ipv4.google.com 64:ff9b::0808:0808:
![wifi_error](https://user-images.githubusercontent.com/42868962/58249132-57814c00-7d5e-11e9-95e7-c7c82e315dc3.JPG)

**Comment by jwhui** [comment]
Apologies, I had the destination address wrong i my original post. I've edited the post above. Can you see if that helps?

**Comment by jaimemi** [comment]
Hi! 
I'm affraid it did not work. But I found an alterenative and my raspberry pi has already IPv6. My problem now is that I can not ping with any ipv6 address from a second node's CLI. I can not use dns resolve either. However, I can ping the google DNS 2001:4860:4860::8888 from my Raspberry Pi, but as I said not from the node connected to the Border Router by Thread. You know what may happen? Thank you!

**Comment by jaimemi** [comment]
I  give you some more information:
I built the Border Router in Docker
I am connected via VPN to my university's wifi wich supports IPv6 
this is the address of the second node:
`> ipaddr  
fd33:3333:3344:0:0:ff:fe00:6000
fd11:22:0:0:1405:75af:d567:4a77
fd33:3333:3344:0:7edd:d38:805:de77
fe80:0:0:0:98dd:20e:5e7c:8671
Done
`

**Comment by jwhui** [comment]
IPv6 addresses with prefix `fc00::/7` are [Unique Local IPv6 Unicast Addresses](https://tools.ietf.org/html/rfc4193). For global IPv6 connectivity, you should configure globally routable IPv6 addresses.

**Comment by jwhui** [comment]
Closing stale issue.
