### ISSUE TITLE
[commissioner] add mdns discovery support

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#306]
**Is your feature request related to a problem? Please describe.**
currently otbr-commissioner uses IP and Port to connect to Thread border agent. This is not standard behavior.

**Describe the solution you'd like**
define the discovery API in mdns.hpp and implement in supported adapters.

**Describe alternatives you've considered**
None

**Additional context**
commissioner should needs this to discovery Thread networks over Wi-Fi or Ethernet.

**Comment by jwhui** [comment]
Addressed in https://github.com/openthread/ot-commissioner
