### ISSUE TITLE
[commissioner] enhance to use a better CoAP implementation

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#307]
**Is your feature request related to a problem? Please describe.**
current CoAP implementation doesn't support retransmission.

**Describe the solution you'd like**
Find a better one or make one from OpenThread.

**Describe alternatives you've considered**
None

**Additional context**
To make commissioner robust.

**Comment by jwhui** [comment]
Addressed in https://github.com/openthread/ot-commissioner
