### ISSUE TITLE
[discuss] Are STL and virtual not suggested for posix applications

### ISSUE THREAD

**Issue by wgtdkp** [openthread/ot-br-posix#310]
There are good reasons for not using STL and virtual methods for embedded platforms, since STL significantly increase the code size and virtual method introduces performance penalty.

But for posix-aimed applicaitons / libraries, such as ot-br-posix and ot-commissioner, code size and performance penalty are relatively not restricted. In this case, should we still not use STL and virtual? 

Is there still other good reasons that stopping us from using STL and virtual? Even all Nest projects are forced to use "modern C++ " (C++11) now.

**Comment by wgtdkp** [comment]
@jwhui @librasungirl   @bukepo @gjc13

**Comment by bukepo** [comment]
we didn't forbid `stl`. And we are using c++11 now. @wgtdkp

**Comment by wgtdkp** [comment]
@bukepo thanks for reply. I am going to write commissioner 1.2 in a C++11 style, just to make sure if you are okay with that.
