### ISSUE TITLE
NCP state changes to "uninitialized" when running "sudo wpanctl status" command.

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#324]
I have been recently getting an error while executing `sudo wpanctl get` command. PFA for the error and as a result NCP gets reset.

<img width="1680" alt="Screenshot 2019-09-02 at 10 35 27 AM" src="https://user-images.githubusercontent.com/9993036/64096302-ed297000-cd7e-11e9-980f-a3256a9bd0ab.png">

**Comment by gjc13** [comment]
Would you provide the wpantund version and log?
It can be wpanctl querying some outdated fields.

**Comment by tarunsmalviya** [comment]
The wpantund version is `wpantund 0.08.00d (/345bf7d; Jun 27 2019 17:02:59)`.
PFA for system logs.
[syslog.txt](https://github.com/openthread/ot-br-posix/files/3567983/syslog.txt)

**Comment by gjc13** [comment]
If you are using the J-Link embedded serial port on NRF52840, it can be msd causing trash on wire.
Follow the guide here to disable it (search for msddisable):
https://github.com/openthread/openthread/blob/master/src/posix/README.md

**Comment by tarunsmalviya** [comment]
@gjc13 We are using NCP with raspberry pi 3. I didn't understand how it is linked with J-Link.

**Comment by tarunsmalviya** [comment]
@jwhui No.

**Comment by tarunsmalviya** [comment]
This issue is happening again. NCP suddenly goes to uninitialised state in between normal functionality. PFA for reference.
![Screenshot 2019-11-18 at 4 20 31 PM](https://user-images.githubusercontent.com/9993036/69046928-11145d80-0a20-11ea-9f0f-65ee45fb9608.png)

<img width="1914" alt="Screenshot 2019-11-18 at 4 22 02 PM" src="https://user-images.githubusercontent.com/9993036/69046940-17a2d500-0a20-11ea-9eba-5fb45e59b5d1.png">

**Comment by jwhui** [comment]
@tarunsmalviya, what git commit are you using for the NCP firmware? Can you try with the latest master?

**Comment by tarunsmalviya** [comment]
@jwhui I am facing this issue again. 

```
wpan0 => [
	"NCP:State" => "associated"
	"Daemon:Enabled" => true
	"NCP:Version" => "OPENTHREAD/20180926-00632-g2279ef61; NRF52840; May 23 2019 20:44:20"
	"Daemon:Version" => "0.08.00d (/87c90ee; Dec 11 2019 03:46:40)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [F4CE3616BC6AF3E0]
	"NCP:Channel" => 25
	"Network:NodeType" => "router"
	"Network:Name" => "fbceca7b0fe995b3"
	"Network:XPANID" => 0xFBCECA7B0FE995B3
	"Network:PANID" => 0xFBCE
	"IPv6:LinkLocalAddress" => "fe80::3c22:2a04:cb44:d8e1"
	"IPv6:MeshLocalAddress" => "fdfb:ceca:7b0f:0:4ca0:31e0:b5e0:3a5d"
	"IPv6:MeshLocalPrefix" => "fdfb:ceca:7b0f::/64"
	"com.nestlabs.internal:Network:AllowingJoin" => false
]```

There are 23 FTD and 49 SED spread over 42000 sq. ft. area.

**Comment by tarunsmalviya** [comment]
@jwhui Any update?

**Comment by jwhui** [comment]
@tarunsmalviya, can you provide more details about your setup? Including:

- Hardware platform / dev board
- Git commit id
- Command you used to build the NCP image
- Attach full logs from wpantund

**Comment by tarunsmalviya** [comment]
@jwhui Sure. Kindly give me some time.

**Comment by tarunsmalviya** [comment]
@jwhui Following are the details:

- **Hardware platform / dev board**: BT 5.0 Dongle (nRF52840) Raytac
- **Command you used to build the NCP image:** Nordic's SDK inbuilt NCP firmware
```
wpan0 => [
	"NCP:State" => "associated"
	"Daemon:Enabled" => true
	"NCP:Version" => "OPENTHREAD/20180926-00632-g2279ef61; NRF52840; May 23 2019 20:44:20"
	"Daemon:Version" => "0.08.00d (/87c90ee; Dec 11 2019 03:46:40)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [F4CE3603C94DA92B]
	"NCP:Channel" => 25
	"Network:NodeType" => "end-device"
	"Network:Name" => "fbceca7b0fe995b3"
	"Network:XPANID" => 0xFBCECA7B0FE995B3
	"Network:PANID" => 0xFBCE
	"IPv6:LinkLocalAddress" => "fe80::a4ed:b611:cba3:effa"
	"IPv6:MeshLocalAddress" => "fdfb:ceca:7b0f:0:91b9:3125:a185:232f"
	"IPv6:MeshLocalPrefix" => "fdfb:ceca:7b0f::/64"
	"com.nestlabs.internal:Network:AllowingJoin" => false
]
```

<img width="1920" alt="1" src="https://user-images.githubusercontent.com/9993036/80343727-0807a200-8884-11ea-8af4-6266ac3c1eca.png">
<img width="1920" alt="2" src="https://user-images.githubusercontent.com/9993036/80343739-0e961980-8884-11ea-984b-0c2cd526d0ca.png">
[syslog.gz](https://github.com/openthread/ot-br-posix/files/4538001/syslog.gz)

**Comment by rcrouthamel** [comment]
@tarunsmalviya , I too have seen the NCP uninitialized and uninitialized fault when using the nRF52840's native USB port and NCP firmware provided with Nordic SDK for Thread 3.x.x and 4.x.x.  I have been able to reproduce the problem on Nordic EVKs PCA10056 and PCA10059, and Fanstel USB840F, used with RPi3B+ and RPi4 hardware running Raspian Stretch Lite and Buster. The problem coincides with syslog errors: "kernel … failed to set dts/rts"

I resolved the issue by reverting to the precompiled hex file https://openthread.io/platforms/co-processor/ot-ncp-ftd-g5d2e6cd0-nrf52840.tar.gz  After running, wpanctl status reports this NCP:Version as OPENTHREAD/20180926-00531-g5d2e6cd0d; NRF52840; Apr 8 2019 12:14:58, which appears to be very close to the pre-release Thread Reference 2018-09-26.

The SDK 4.x.x. version of NCP/RCP does not show issues when connected via SPI (vs. USB).  This combined with the dts/rts error messages suggests to me a problem with CDC-ACM.

**Comment by jwhui** [comment]
@LuDuda, can you provide thoughts on the above comment from @rcrouthamel ?

**Comment by LuDuda** [comment]
@rcrouthamel @tarunsmalviya can you provide me a step-by-step instruction on how to reproduce this problem on the PCA10056? Did you try to use Ubuntu as a host or only Raspberry Pi?

Not counting our internal tests, I also tried to stress communication on USB by calling `wpanctl get` in a loop constantly, while sending IP data to the NCP as soon as possible. I couldn't observe this problem yet.

Can you run wpantund with verbose logging enabled and observe what kind of errors it reports?

**Comment by jwhui** [comment]
Closing stale issue.
