### ISSUE TITLE
[agent] mojo publishes when Thread is not started

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#328]
**Describe the bug**
mojo publishes when Thread is not started.

**To Reproduce**
1. Stop wpantund or `wpanctl leave`
2. start otbr-agent
3. use `avahi-browse -arp` to check services published by the DUT

**Expected behavior**
No service being published.

**Console/log output**
Thread is published with network empty and extended pan id all zero.

**Additional context**
None

**Comment by jwhui** [comment]
Resolved by #329.
