### ISSUE TITLE
NCP is in end-device state for more than 2 minutes. 

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#332]
I built border router(BR) using RPi. Sometime what happens is, NCP degrade from router/leader to end-device and packet does not reach BR. I don't know why BR is being degrade to end-device because as name suggest, it should be either leader or router.

Also, I created a time series of NCP state as shown in picture below:
<img width="1030" alt="Screenshot 2019-09-18 at 4 52 58 PM" src="https://user-images.githubusercontent.com/9993036/65144964-119b7280-da36-11e9-9c88-c4a4fa0564bc.png">

**Note:-** 1 indicates leader, 2 indicates router and 3 indicates end-device

wpanctl version is `wpanctl 0.08.00d (/345bf7d; Jun 27 2019 16:37:52)`

PFA for [syslog](https://github.com/openthread/ot-br-posix/files/3626142/syslog.txt)

**Comment by jwhui** [comment]
I see quite a few instances of NCP reset occurring in the log (snippet below). Is this expected for your testing?

```
Sep 18 14:43:40 BhumikaRPI wpantund[554]: wpantund[554]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 14:43:40 BhumikaRPI wpantund[554]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 14:44:53 BhumikaRPI wpantund[554]: wpantund[554]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 14:44:53 BhumikaRPI wpantund[554]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 14:44:58 BhumikaRPI wpantund[554]: wpantund[554]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 14:44:59 BhumikaRPI wpantund[554]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 14:45:04 BhumikaRPI wpantund[554]: wpantund[554]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 14:45:04 BhumikaRPI wpantund[554]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 15:29:45 BhumikaRPI wpantund[3346]: wpantund[3346]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 15:29:45 BhumikaRPI wpantund[3346]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 15:29:45 BhumikaRPI wpantund[3346]: wpantund[3346]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 15:29:45 BhumikaRPI wpantund[3346]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 15:32:46 BhumikaRPI wpantund[3346]: wpantund[3346]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Sep 18 15:32:46 BhumikaRPI wpantund[3346]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)

```

**Comment by tarunsmalviya** [comment]
@jwhui No.

**Comment by jwhui** [comment]
@tarunsmalviya, I believe the NCP resets are causing the issues you are seeing.

Can you provide more information about the NCP? Including:

- NCP hardware platform
- How you built the NCP firmware, including commands used to build
- What git commit id are you using for NCP firmware
- Output of `wpanctl status`

**Comment by tarunsmalviya** [comment]
@jwhui 
Hardware used is nrf52840
nRF5 SDK for Thread and Zigbee v2.0.0 (Release Date: Week 39, 2018)
OpenThread libraries projects are based on the following commit of OpenThread: 704511c96e0d093139e4b80ef0739ed2d701afb1

```
wpan0 => [
	"NCP:State" => "associated"
	"Daemon:Enabled" => true
	"NCP:Version" => "OPENTHREAD/g591ec62; NRF52840; Sep 19 2018 11:42:29"
	"Daemon:Version" => "0.08.00d (/345bf7d; Jun 27 2019 17:02:59)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [9F1D6CC6CA7D6DA0]
	"NCP:Channel" => 25
	"Network:NodeType" => "end-device"
	"Network:Name" => "OfficeThread1"
	"Network:XPANID" => 0x1122334455667788
	"Network:PANID" => 0xAB02
	"IPv6:LinkLocalAddress" => "fe80::bcaf:aaca:2765:f52e"
	"IPv6:MeshLocalAddress" => "fd11:2233:4455:0:1c5:fb2c:c2d1:1e50"
	"IPv6:MeshLocalPrefix" => "fd11:2233:4455::/64"
	"com.nestlabs.internal:Network:AllowingJoin" => false
]
```

**Comment by jwhui** [comment]
@tarunsmalviya, thanks for the additional information. Any chance you could try using a more recent version of the nRF5 SDK or at least a more recent version of OpenThread?

For NCP firmware, you could try building straight from GitHub as described in [Pre-Built NCP Firmware](https://openthread.io/guides/ncp/firmware).

**Comment by tarunsmalviya** [comment]
@jwhui I have updated the openthread and NCP version to most recent but still facing the same problem.

```
wpan0 => [
	"NCP:State" => "associated"
	"Daemon:Enabled" => true
	"NCP:Version" => "OPENTHREAD/20180926-00632-g2279ef61; NRF52840; May 23 2019 20:44:20"
	"Daemon:Version" => "0.08.00d (/87c90ee; Dec 11 2019 03:46:40)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [F4CE3616BC6AF3E0]
	"NCP:Channel" => 25
	"Network:NodeType" => "router"
	"Network:Name" => "fbceca7b0fe995b3"
	"Network:XPANID" => 0xFBCECA7B0FE995B3
	"Network:PANID" => 0xFBCE
	"IPv6:LinkLocalAddress" => "fe80::3c22:2a04:cb44:d8e1"
	"IPv6:MeshLocalAddress" => "fdfb:ceca:7b0f:0:4ca0:31e0:b5e0:3a5d"
	"IPv6:MeshLocalPrefix" => "fdfb:ceca:7b0f::/64"
	"com.nestlabs.internal:Network:AllowingJoin" => false
]```

There are 23 FTD and 49 SED spread over 42000 sq. ft. area.

System logs: 
[syslog.1.gz](https://github.com/openthread/ot-br-posix/files/3956005/syslog.1.gz)
[syslog.2.gz](https://github.com/openthread/ot-br-posix/files/3956006/syslog.2.gz)

**Comment by abtink** [comment]
@tarunsmalviya, Jonathan and I looked the logs. NCP resets seems to be all tied to user commands ("reset" or "leave") and expected behavior (from NCP/wpantund point). It may be good to see who/what module is issuing these commands to wpantund:
```
# Filtering NCP resets and issued dbus commands "Reset" and "Leave". 
abtink@abtink ~/Downloads $ cat syslog.2 | grep "wpantund\[8621\]: wpantund\[8621\]" | grep -e "NCP was reset" -e "\"Reset\"" -e "\"Leave\""
Dec 11 05:40:02 Spencers-01 wpantund[8621]: wpantund[8621]: Inbound DBus message for INTERFACE "Reset" from ":1.336"
Dec 11 05:40:02 Spencers-01 wpantund[8621]: wpantund[8621]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Dec 11 05:40:07 Spencers-01 wpantund[8621]: wpantund[8621]: Inbound DBus message for INTERFACE "Leave" from ":1.337"
Dec 11 05:40:07 Spencers-01 wpantund[8621]: wpantund[8621]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
Dec 11 05:40:13 Spencers-01 wpantund[8621]: wpantund[8621]: Inbound DBus message for INTERFACE "Leave" from ":1.11"
Dec 11 05:40:13 Spencers-01 wpantund[8621]: wpantund[8621]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
```

The main issue (from syslog.1) seems to be the network being partitioned a lot. Basically a devcie/router looses connection with others, forms its own partition (which would cause to temporary detach and become a leader). Later device may detect other partition and try to merge the partitions and through  this process device would first attach as child and then become a router again (after some random time interval (order of minutes)).

Some suggestions: 
- Can you increase the number retx in the NCP build `OPENTHREAD_CONFIG_MAC_DEFAULT_MAX_FRAME_RETRIES_DIRECT` and 
`OPENTHREAD_CONFIG_MAC_DEFAULT_MAX_FRAME_RETRIES_INDIRECT`.
- Another config you can enable is the feature `OPENTHREAD_CONFIG_MLE_SEND_LINK_REQUEST_ON_ADV_TIMEOUT`. This will ensure a router to try a unicast "LinkRequest" to a router if it misses "Link Advertisement" form it (before kicking the neighbor/router out of its neighbor table). This can help a lot with avoiding partitions.

**Comment by bhumikaajain** [comment]
@abtink 

We are using nRF5 SDK for Thread and Zigbee v3.2.0 for NCP and router firmware.
Can you help where I can enable this feature in the stack?

**Comment by abtink** [comment]
These are config parameters for OpenThread core itself. I am not familiar how/if nRF5 SDK exposes the OpenThread config option/header file. Maybe others can help you with this.

In general, OpenThread allows users to provide a custom (project specific) config header file through `OPENTHREAD_PROJECT_CORE_CONFIG_FILE`.

**Comment by jwhui** [comment]
Closing stale issue.
