### ISSUE TITLE
Not able to ping though borderrouter to link-local

### ISSUE THREAD

**Issue by embeddedRSA** [openthread/ot-br-posix#334]
Hi, i have set up my border router and i amm able to ping to a global server by using the well-known prefix:
```
> ping 64:ff9b::0808:0808
> 16 bytes from 64:ff9b:0:0:0:0:808:808: icmp_seq=55 hlim=51 time=26ms
```
My problem is pinging link-local addresses such as this one:

```
wlo1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.3.144  netmask 255.255.255.0  broadcast 192.168.3.255
        **inet6 fe80::593d:100:f1d8:44f**  prefixlen 64  scopeid 0x20<link>
        ether ac:b5:7d:26:2f:ba  txqueuelen 1000  (Ethernet)
        RX packets 180966  bytes 161395680 (161.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 117698  bytes 18161299 (18.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
(this is on my border router laptop)
when i try to ping from a node a respond never returns

```
>state
leader
Done
> ping fe80::8817:3ff:fe80:61fa
```
Is what im trying to do possible?

**Comment by jwhui** [comment]
My example were for the network interfaces on the same RPi. If you want to be able to communicate between devices on different subnets, you will need to configure IPv6 routing.

This [email thread on openthread-users](https://groups.google.com/forum/#!msg/openthread-users/38ladIxYDs4/RyiwIO0QDAAJ) may be of help.

**Comment by embeddedRSA** [comment]
yes okay, thanx for the help.
