### ISSUE TITLE
Can i manage 2 Thread networks connecting 2 NCPs to the Raspberry Pi.

### ISSUE THREAD

**Issue by neppi** [openthread/ot-br-posix#346]
Hi anyone,

There should be 2 different thread networks having

- different names
- different master keys
- different PAN IDs
etc.

But both of them should be controlled (managed) by ot-br-posix. Would this be possible?

**Comment by bukepo** [comment]
Yes, this is possible theoretically. But the current code needs enhancements to support it. Mainly, setting different ports for border agents is required.
