### ISSUE TITLE
otbr-web doesn't respect -a

### ISSUE THREAD

**Issue by sjlongland** [openthread/ot-br-posix#352]
**Describe the bug**

`otbr-web` doesn't do authentication, so for security reasons and to prevent tampering, we bind `otbr-web` to the loopback interface so that it can be accessed only over SSH tunnel to protect the confidentiality of the mesh network master key.

In recent builds of `otbr-web`, this does not work.

**To Reproduce**

We're running `ot-br-posix` based on commit https://github.com/openthread/ot-br-posix/commit/72ed754, packaged using https://github.com/vrtsystems/openthread-borderrouter-pkgbuilder to build `.deb` packages for ARMHF and AMD64.

```
root@atrium-br0:~# cat /etc/default/otbr-web 
BR_OPTS="-a 127.0.0.1 -p 8080"
```

I've also tried `-a ::1`.  Same result.

**Expected behavior**

`otbr-web` should be bound to `127.0.0.1` (or `::1`).

**Console/log output**

```
root@atrium-br0:~# ps ax | grep otbr-web
 2123 ?        Ssl    0:00 /usr/sbin/otbr-web -a 127.0.0.1 -p 8080
 2254 pts/2    S+     0:00 grep otbr-web
root@atrium-br0:~# netstat -anlpt
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      2123/otbr-web       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1750/sshd           
tcp        0    196 10.87.144.139:22        10.87.144.172:41558     ESTABLISHED 2081/sshd: root@pts 
tcp6       0      0 :::22                   :::*                    LISTEN      1750/sshd           
```

**Comment by bukepo** [comment]
could you take a look? @gjc13

**Comment by bukepo** [comment]
@sjlongland is this still an issue, I just verified it works as expected:

```bash
➜  sudo ._build/otbr/src/web/otbr-web -a 127.0.0.1 -I wpan0 -p 9912
otWeb[258958]: border router web started on wpan0
^CotWeb[258958]: Stopping web server
➜  netstat -an | grep 9912
tcp        0      0 127.0.0.1:9912          0.0.0.0:*               LISTEN
tcp6       0      0 2401:fa00:41:23:3:59912 2404:6800:4008:c04::443 TIME_WAIT
```

I will close it for now and please feel free to reopen if it's an issue.
