### ISSUE TITLE
[tests] test dbus APIs according to introspection

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#362]
**Is your feature request related to a problem? Please describe.**
We are adding d-bus APIs using standard style. Need design some script to test these d-bus APIs.

**Describe the solution you'd like**
Get introspection and test APIs according to it.

**Describe alternatives you've considered**
dynamically generate introspect xml.

**Additional context**
https://github.com/openthread/ot-br-posix/pull/360

**Comment by bukepo** [comment]
any plan for this?

**Comment by jwhui** [comment]
Closing stale issue.
