### ISSUE TITLE
The lines are too long

### ISSUE THREAD

**Issue by gjc13** [openthread/ot-br-posix#365]
**Is your feature request related to a problem? Please describe.**
Currently we are adopting a 120 column line limit which is too long and the code is hard to read and edit on a laptop, especially when there's a split screen.

**Describe the solution you'd like**
Modify the line limit to 80 columns which is a common standard.

**Additional context**
An concern is the git log.

**Comment by bukepo** [comment]
Sounds good to me!

**Comment by gjc13** [comment]
@bukepo @jwhui The problem is that if we adopt the 80 columns line limit, we need to re-format every file so as to pass the pretty check. The re-format commit will be huge and the `git blame` will all point to this commit afterwards.

We can still track the changes with `git log -p`. If you are fine with such a commit, I'll submit a re-format PR.

**Comment by jwhui** [comment]
Line-width is a controversial topic :)

I personally find 80 columns as too limiting, but I typically develop on a MacBook Pro 15" that has a native display resolution of 2880×1800 or a desktop monitor that supports 3840x2160.

**Comment by abtink** [comment]
I also prefer longer column lines and think 80 columns would be too limiting 
- As Yakun mentioned, we may need to reduce the indention from 4 spaces (to 2 spaces) which in my opinion again makes the code harder to read.
- 80 column will cause many more lines to be wrapped which I think will make code harder to read

I do a lot of coding on MacBook pro 15" and I generally prefer larger fonts (using sublime edit at font size 13 SF Mono). 120 columns fit nicely in full screen window.
