### ISSUE TITLE
[question] non linux based border router

### ISSUE THREAD

**Issue by cfaessler** [openthread/ot-br-posix#366]
I am trying to find out whether it is feasible to develop a thread compatible border router which is not based on a linux system. Reason is to save hw costs. We are evaluation the thread technology for a series of products in the smart home area. We don't consider a raspberry pi solution to be a stable product.
Currently it seems that there are hardly an thread compatible border routers available on the market. I wonder what the reason for this is.

Does anyone know of any available border router devices on the market?
Would it be possible to implement a border router without linux? Basically with a TI-1352 chipset and host controller with eth interface.

**Comment by jwhui** [comment]
See response in https://github.com/openthread/openthread/issues/4550#issuecomment-584761400

Closing this issue to consolidate the discussion.
