### ISSUE TITLE
Fix and refactor the openwrt u-bus agent.

### ISSUE THREAD

**Issue by gjc13** [openthread/ot-br-posix#368]
**Is your feature request related to a problem? Please describe.**
There are memory leaks in the u-bus agent and the thread synchronization mechanism is poorly implemented.
We may need to rewrite the u-bus agent.
Some of the memory issues are handled in https://github.com/openthread/ot-br-posix/pull/345

**Comment by wgtdkp** [comment]
We need to refactor the inheritance to avoid pointer casting.

**Comment by jwhui** [comment]
Closing stale issue.
