### ISSUE TITLE
Use lower cases for namespace names

### ISSUE THREAD

**Issue by gjc13** [openthread/ot-br-posix#374]
**Is your feature request related to a problem? Please describe.**
Currently we are using camel case for inner namespaces. Such style is a little weird since you cannot determine at the first glance whether the `BorderRouter` in `otbr::BorderRouter` is a namespace or a class.

**Describe the solution you'd like**
Use lower case namespace names as suggested by the Google C++ style. The OpenThread code style suggests camel case but lower case is more natrual.

**Comment by gjc13** [comment]
I raised this issue since we are improving the code style in https://github.com/openthread/ot-br-posix/pull/372
@bukepo @jwhui @abtink What's your idea on this renaming?

**Comment by bukepo** [comment]
SGTM. @wgtdkp @librasungirl

**Comment by wgtdkp** [comment]
SGTM

**Comment by abtink** [comment]
I don't have any strong opinion here and fine either way but if asked to choose  would go with the existing (CamelCase) model for all namespaces (after the high level `ot` or `otbr`). The way I see it is that any `class` or `struct` definition is defining a namespace as well so it is fine if we cannot tell the difference and use same naming convention.

**Comment by jwhui** [comment]
What is the benefit of being able to differentiate between namespace and class from the name itself? While the Google C++ style guide provides pros/cons/decision for many of the style choices, it does not provide any such rationale for the namespace naming choice. At the same time, C++ stdlib uses all lower case names for both namespace and class.

The existing [STYLE_GUIDE.md](https://github.com/openthread/ot-br-posix/blob/master/STYLE_GUIDE.md) states:

> All OpenThread class, namespace, structure, method, function, enumeration, and type names in the C/C++ language shall be in upper camel case. Exception: the top level OpenThread namespace 'ot'.

This is generally shared across all OpenThread projects. If there is good reason to change, we should consider making the change uniformly across all OpenThread projects.
