### ISSUE TITLE
no COAP retransmissions for confirmable messages

### ISSUE THREAD

**Issue by mwilniewiec** [openthread/ot-br-posix#396]
We have our own border router implementation which is basing on your ot-br-posix and has multiple additional features.
I observed that there are no retransmitions while sending COAP confirmed messages from border router to nodes inside of thread network.
Is this a bug or expected design?

libcoap server example: coap-server.c in its mainloop has something like:
```
    coap_ticks(&now);
    while (nextpdu && nextpdu->t <= now - ctx->sendqueue_basetime) {
      coap_retransmit( ctx, coap_pop_next( ctx ) );
      nextpdu = coap_peek_next( ctx );
    }
```
I believe this is what is missing to get working retransmitions.

**Comment by bukepo** [comment]
@mwilniewiec We are migrating to the standalone [ot-commissioner](openthread/ot-commissioner). 
Do you encounter this issue in otbr-commissioner? If so, we suggest you migrate to ot-commissioner as well.

**Comment by mwilniewiec** [comment]
Could you please provide me with some motivation overview for a new repo?
Is is just a part of a border router or a new one and this will be deprecated?
Our border router is forming network with dbus, talking with devices using application CoAP and much more, migrating to new repo doesn't look like a trival task :)

**Comment by wgtdkp** [comment]
>Is it just a part of a border router or a new one and this will be deprecated?

Just the builtin commissioner will be deprecated, the border agent will continue. As you pointed out, the otbr-commissioner is some how not very stable and we realized that there needs to be some Commissioner library that enables building Commissioner (mobile) App, so we made the ot-commissioner there.

Conceptually, the commissioner and border router are separate component in a Thread Network. We built otbr-commissioner here for convenience and testing, but binding commissioner and border agent (host) together is not flexible and not recommended.

The CoAP issues you mentioned, I believe is only related with the builtin commissioner. We are going to migrate to use ot-commissioner and not bind them together as we did before. So if you are using otbr-commissioner for commissioning stuffs, please consider [ot-commissioner](https://github.com/openthread/ot-commissioner) (get started [here](https://openthread.io/guides/commissioner)).

**Comment by mwilniewiec** [comment]
Actually it depends on what you need. In our case commissioner is a border router communicating with the cloud server so commissioner could be moved to a different process but it would be still on the host as it is one hardware.
The CoAP I mentioned is actually the problem of all coap messages sent from host (using libcoap) to the Thread network. If commissioner is a separate code with different coap implementation and border router is only a bridge then it is fine for the commissioner.
In our case border router is getting stuff from the cloud and pushing it into the Thread network using libcoap over wpan0. In that case retransmissions are usefull.
I did some investigation, added 
`void AgentLibcoap::Process(timeval &aTimeout)` function called from a main loop at least every second.
With retransmissions  code from libcoap server example:
```
    coap_ticks(&now);
    while (nextpdu && nextpdu->t <= (now - mCoap.sendqueue_basetime)) {
        coap_retransmit( &mCoap, coap_pop_next( &mCoap ) );
        nextpdu = coap_peek_next( &mCoap );
    }
```
With some testing I see that confirmable message retransmissions are working properly.
There is one minor issue with strange timings but actually I see 4 retransmissions with incremental backoff as expected.
