### ISSUE TITLE
ctags not found when building recipe for Yocto Pyro

### ISSUE THREAD

**Issue by paulrox** [openthread/ot-br-posix#398]
Hi,

I've tried to write a simple recipe in order to add the ot-br-posix package to my Yocto image. However, I'm encountering some problems during the `do_configure` task.

I've created the recipe using `recipetool` and passing in the URL to the git repository. The recipe has been successfully created and I added the dependencies to **avahi** and  **ctags**.

The recipe looks like this:

```
LICENSE = "Unknown & MIT & Apache-2.0 & GPLv2"
LIC_FILES_CHKSUM = "file://LICENSE;md5=87109e44b2fda96a8991f27684a7349c \
                    file://third_party/wpantund/repo/third_party/assert-macros/LICENSE;md5=cbf35ecdc8161026afe4da2906fab204 \
                    file://third_party/wpantund/repo/third_party/openthread/LICENSE;md5=543b6fe90ec5901a683320a36390c65f \
                    file://third_party/mdl/repo/LICENSE;md5=6f740e801ce5a08c6c113bf72859bff2 \
                    file://third_party/Simple-web-server/repo/LICENSE;md5=852b3f7f320b19f6431487b8b2fb1d74 \
                    file://third_party/angular-material/repo/LICENSE;md5=3d0c299b7dd4267c3ef21a705cf6a5c6 \
                    file://third_party/angular/repo/LICENSE.md;md5=0d83982330e37f011a2cef9b15cb43aa \
                    file://third_party/openthread/repo/LICENSE;md5=543b6fe90ec5901a683320a36390c65f \
                    file://third_party/openthread/repo/third_party/jlink/SEGGER_RTT_V640/License.txt;md5=162718c5643c4224b32b1e5a959b03fb \
                    file://third_party/openthread/repo/third_party/Qorvo/LICENSE.txt;md5=48978fe3da0e36bbeaa441890e01382c \
                    file://third_party/openthread/repo/third_party/mbedtls/repo/LICENSE;md5=302d50a6369f5f22efdb674db908167a \
                    file://third_party/openthread/repo/third_party/nlbuild-autotools/repo/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57 \
                    file://third_party/openthread/repo/third_party/silabs/LICENSE.txt;md5=2bff89602d6e66a300ed41a5ba0dd701 \
                    file://third_party/openthread/repo/third_party/NordicSemiconductor/libraries/utf_converter/LICENSE;md5=67c501b46a86f1f4e16d826332a28d3e \
                    file://third_party/openthread/repo/third_party/NordicSemiconductor/nrfx/LICENSE;md5=57eb7f5661b47a82547f91a4a948f64b \
                    file://third_party/openthread/repo/third_party/openthread-test-driver/LICENSE;md5=751419260aa954499f7abaabaa882bbe \
                    file://third_party/libcoap/repo/LICENSE.BSD;md5=a59366bd7eaa8a42f7b79a94a467538f \
                    file://third_party/libcoap/repo/COPYING;md5=d68ef62852d5333e5361065f066d62f8"

SRC_URI = "gitsm://github.com/openthread/ot-br-posix.git;protocol=https"

# Modify these as desired
PV = "1.0+git${SRCPV}"
SRCREV = "7cc2e97aa896c06a95f2086a47999d51119d2b77"

S = "${WORKDIR}/git"

# NOTE: the following prog dependencies are unknown, ignoring: cmp
DEPENDS = "dbus avahi ctags"

# NOTE: if this software is not capable of being built in a separate build directory
# from the source, you should replace autotools with autotools-brokensep in the
# inherit line
inherit pkgconfig perlnative autotools

# Specify any options you want to pass to the configure script using EXTRA_OECONF:
EXTRA_OECONF = "--prefix=/usr --sysconfdir=/etc --enable-commissioner=yes"
```
The recipe is not complete because the handle of the `do_install` task is not there but this is not an issue.

If I try to build the recipe as it is using the bitbake command it always fails during the `do_configure` task with the following error:

`checking checking if Exuberant Ctags is available... configure: error: could not find ctags`

The recipe for the `ctags` package (which is already included in the meta-oe layer) uses the latest release (5.8). I've also tried to write my own recipe for ctags in order to use the lastest commit available on the Sourceforge svn but the result is the same.

Of course, if I use the `--enable-commissioner=no` and `--enable-web-service=no` options the package can be built without any issue (If I disable only the commissioner it fails during the build because it still looks for its Makefile).

**Comment by bukepo** [comment]
@paulrox sorry for the late reply.

I'm not sure what's the root cause, but ctags are required to be install as a host tool. So I think you should install it out side of the yocto build process.

Besides, we are doing some cleaning up including replacing otbr-commissioner with openthread/ot-commissioner and removing wpantund mode support, after which the libcoap library is not necessary anymore and will be removed from dependencies as well.

**Comment by paulrox** [comment]
Hi,

Thanks for the response. I already tried to install ctags as host tool but this didn't resolve the issue. 

Anyway, if you planned to remove wpantund support, how the BR will interact with the NCP?

**Comment by gabekassel** [comment]
I'm also trying to build in Yocto and figure out the right components. It looks like wpantund will no longer be necessary and border-agent is moving into OT core. Can anyone suggest the right mixture of components for a posix BR at this point?

**Comment by gabekassel** [comment]
Looks like ot-daemon is overtaking wpantund. Is that correct?

**Comment by jwhui** [comment]
> Looks like ot-daemon is overtaking wpantund. Is that correct?

Yes, that is the plan. See #403 for the start of that effort.

**Comment by gabekassel** [comment]
Thanks @jwhui - is otbr-agent still needed for off network commissioning or is that also in core+commissioning daemon?

**Comment by jwhui** [comment]
> Thanks @jwhui - is otbr-agent still needed for off network commissioning or is that also in core+commissioning daemon?

@gabekassel, otbr-agent is still required. #417 has a rough list of changes we are planning.

**Comment by paulrox** [comment]
Hi,

I tried to install from the 171f0eb483a1fd7cb99d6cfa96dc095e375a7c9e commit (after the cleanup that you mentioned earlier) and now it works like a charm!
Thank you!

Note: In order to use it with the `pyro` branch of Yocto, I had to update the `cmake` recipe because the stock one was too old.

**Comment by bukepo** [comment]
Glad to hear you made progress!
