### ISSUE TITLE
Discovering IP addresses of all nodes in a Thread network?

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#413]
### **Setup**

- I am using RaspberryPi 3B+, in which OTBR service is running. 
- A dummy interface in RPi with IPv4 address **10.0.0.1**.
- A CoAP server listening at **10.0.0.1:5683**.

### **Problem Statement**
I have created a Thread network in which one FTD and one SED are there. SED is sending a packet after every 30 seconds to the CoAP server listening at **10.0.0.1:5683**. 
Now, I want to sent a packet from CoAP server to SED and in order to do so, I need to know IPv6 address of the SED. So I do I get IPv6 address of SED or FTD?

### **Solution**
I tried following approach which works:
Initially, SED is sending its IPv6 address in CoAP packet and CoAP server stores it. Now whenever CoAP server need to send a packet to SED, then it make use of previously stored IPv6 address of SED. This is explained in [this](https://github.com/openthread/ot-br-posix/issues/315) issue.

### **Queries**

- **Is there any other way through which I can get IP address of all nodes with EUI64(in order to uniquely identify them) in Thread network in RPi?**

- **Is there any way to assign DNS to Thread node?**

**Comment by jwhui** [comment]
@tarunsmalviya , IP address discovery is a common problem in any IP network. There are a number of solutions including DNS and application-specific, both of which you've already identified.

> Is there any other way through which I can get IP address of all nodes with EUI64(in order to uniquely identify them) in Thread network in RPi?

To list all IPv6 addresses and associated IEEE EUI-64, your best bet is to use an application-specific mechanism.

> Is there any way to assign DNS to Thread node?

You could certainly implement Dynamic DNS (DDNS) [RFC 2136](https://tools.ietf.org/html/rfc2136). OpenThread does not currently provide a DDNS implementation.

**Comment by tarunsmalviya** [comment]
@jwhui Thank you for validating the approaches.

Is there any cli command through which I can retrieve IP address list of Thread network?

**Comment by jwhui** [comment]
> @jwhui Thank you for validating the approaches.
> 
> Is there any cli command through which I can retrieve IP address list of Thread network?

There are cli commands to retrieve state about directly attached children. However, there are no CLI commands to retrieve IPv6 addresses for all devices in a Thread network. Thread intentionally does not require any device in the network to maintain state about all other devices for scalability.

**Comment by tarunsmalviya** [comment]
@jwhui Okay. Thanks for clarification.

**Comment by vijayrao1988** [comment]
If all you are looking for is a terminal command (this is possible on an Ubuntu machine on the Thread network through a RCP), you could try:
``ping -r -I wpan0 -t 16 -c 2 ff03::1``

This should gather 1 set of responses from all the devices on the network and then you can use that point of contact to gather a confirmation by communicating to some sort of server on them.
You will need to substitute wpan0 with the interface name you have on your system.
ff03::1 might need to be added to the router table.

**Comment by ksathara** [comment]
@jwhui, you have mentioned that for we can get IPV6 address  for MTD devices. Could you please elaborate on that?

Thanks,
Kaushalya

**Comment by abtink** [comment]
> @jwhui, you have mentioned that for we can get IPV6 address for MTD devices. Could you please elaborate on that?
> 
> Thanks, Kaushalya

Check [`otThreadGetChildNextIp6Address()`](https://github.com/openthread/openthread/blob/70adcabca6270eead21f126533c697d4d1637b77/include/openthread/thread_ftd.h#L577-L597)
