### ISSUE TITLE
Unable to receive acknowledgement of CoAP CON message in NCP firmware.

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#415]
I am trying to sending CoAP CON message (resource `dfu/`) from NCP and FTD firmware to CoAP server running on RPi.

When I send CON message from FTD to CoAP server, the acknowledgement is received but not when sending CON message from NCP to CoAP server.

The address of NCP is `feef:ee::87b1:5246:674d:326e`, of FTD is `feef:ee::f639:87f2:2f77:b48d` and of CoAP server is `2001:db8:1:ffff::a00:1`.

I tried debugging using tcpdump logs and discovered that CoAP server is sending acknowledgement message (which can be seen in _**nat.pcap**_) but there is no trace of that acknowledgement message at `wpan0` in interface (which can be seen in _**wpan.pcap**_).

Can anyone help why is that so?

PFA for tcpdump logs.

[tcpdump.zip](https://github.com/openthread/ot-br-posix/files/4550225/tcpdump.zip)

**Comment by jwhui** [comment]
@tarunsmalviya , this traffic pattern is not supported. The challenge is that the NCP and wpan0 interface on host side are both part of the same IPv6 interface. When the CoAP response is sent from the RPi host, the destination will match an IPv6 address assigned to its wpan0 interface. As a result, the Linux kernel will attempt to service the packet directly rather than passing it to the NCP.

**Comment by tarunsmalviya** [comment]
@jwhui Is there any other approach to achieve this because resolving is problem will enable us to perform DFU in NCP.

**Comment by jwhui** [comment]
@tarunsmalviya , as for other alternatives, how about utilizing a bootloader that supports DFU in the NCP?

**Comment by tarunsmalviya** [comment]
@jwhui We are using Nordic's OTA DFU example, in which we first add mbr file, then bootloader and then application on NRF52840 chip. In application, we enable the DFU when new firmware version is available at the server.

But in this case CoAP response are not being received.

**Comment by jwhui** [comment]
Closing stale issue.
