### ISSUE TITLE
[mdns] wrong encoding of extended PAN ID in mDNS response

### ISSUE THREAD

**Issue by wgtdkp** [openthread/ot-br-posix#419]
**Describe the bug** A clear and concise description of what the bug is.
ot-br-posix encodes extended PAN ID as HEX string in mDNS response, while Thread specification defines it to be binary data.

https://github.com/openthread/ot-br-posix/blob/699aa6a59308f6e913e3efbe57099113c8aaf744/src/agent/border_agent.cpp#L300-L316

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.
The value of extended PAN ID is encoded as binary data.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by bukepo** [comment]
The official Thread commissioner also recognize the extended pan id as hex. So I think we should be discuss this in Thread group to make it clear about the encoding.

**Comment by wgtdkp** [comment]
I have created a [JIRA issue](https://threadgroup.atlassian.net/browse/SPEC-936?atlOrigin=eyJpIjoiYWM0NzYzY2M1NGU5NGZhZGEwODI5ZmE0MjVlMTQ1YjIiLCJwIjoiaiJ9) for this but later closed it when found out that it is legal to have binary data.

FYI, [related issue](https://github.com/openthread/ot-commissioner/issues/92) on ot-commissioner.
