### ISSUE TITLE
Unable to access 'https://github.com/openthread/wpantund.git/': Couldn't connect to server.

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#421]
I am trying to install `ot-br-posix` in Raspberry Pi 3B. I am encountering an issue regarding cloning of `wpantund` repository. PFA for reference.

Version which I am trying to build:
```
commit 699aa6a59308f6e913e3efbe57099113c8aaf744
Author: Yakun Xu <xyk@google.com>
Date:   Wed Apr 29 14:07:51 2020 +0800
```

I checked following:
- Internet is working fine.
- When I try to clone `wpantund` repository manually by executing `git clone https://github.com/openthread/wpantund.git` command, it gets cloned successfully.

<img width="1201" alt="Screenshot 2020-05-08 at 2 22 22 PM" src="https://user-images.githubusercontent.com/9993036/81389550-a5da5700-9137-11ea-8321-a880e02855e5.png">

**Comment by bukepo** [comment]
What is the raspbian version?

**Comment by tarunsmalviya** [comment]
@bukepo 
```
Linux 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by bukepo** [comment]
@tarunsmalviya we just removed wpantund support in this project, could you try the latest code?

**Comment by tarunsmalviya** [comment]
@bukepo You mean to say stretch version is not supported. Right?

**Comment by jwhui** [comment]
@tarunsmalviya , with #424, wpantund is no longer used in master branch. As a result, the wpantund issue you are facing should no longer exist. As @bukepo suggested, can you try installing with the latest master branch? Note that the [Border Router Setup Guide](https://openthread.io/guides/border-router/build) has been updated to reflect master's migration to using RCP mode.

**Comment by tarunsmalviya** [comment]
@jwhui [#424](https://github.com/openthread/ot-br-posix/pull/424) was merged 12 days ago and I was facing this issue before that.
Also, as per @bukepo's suggestion, I tried installing with latest master branch. I discovered that there are many changes done in the new version. 

I have following queries:
- Also, in the [Border Router Setup Guide](https://openthread.io/guides/border-router/build), there is no mention of NCP. Is this because it does not exists now? RCP came into picture now?

- Until now, I was using `0.08.00d (/0.07.01-341-g1f65656; May 11 2020 21:06:03)` version of **ot-br-posix**. When I updated **ot-br** service, `wpanctl` was miss behaving even when the `wpantund` still exists. Sometimes, the output of `sudo wpanctl status` command shows `offline` state and sometimes `uninitialized` state. Also, NCP was attached but thread network was not coming up in RPi.

- Is it so that earlier version is now not deprecated and migration from older to newer version is not handled? We will be needing RCP instead of NCP.

**Comment by gjc13** [comment]
‘’‘Also, in the Border Router Setup Guide, there is no mention of NCP. Is this because it does not exists now? RCP came into picture now?

Yes, RCP is now the recommended radio peripheral rather than NCP.

```Sometimes, the output of sudo wpanctl status command shows offline state and sometimes uninitialized state. Also, NCP was attached but thread network was not coming up in RPi.

In the wpantund solution otbr shouldn't interfere with Thread network creation. You need to check the wpantund log to identify the error.

```Is it so that earlier version is now deprecated and migration from older to newer version is not handled? We will be needing RCP instead of NCP.

There is a feature to migrate ncp network data to rcp in OpenThread. You can find how to use it [here](https://github.com/openthread/openthread/blob/master/script/check-ncp-rcp-migrate).
After you've acquired the network data on the host machine, you can form the Thread network with this data and the network shall be migrated.

**Comment by jwhui** [comment]
Closing stale issue.
