### ISSUE TITLE
[openwrt] add mdns support

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#426]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.
The current OpenWRT build doesn't publish Thread mDNS.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Integrate with mdnsd

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
Integrate with umdns

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by mrninhvn** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. The current OpenWRT build doesn't publish Thread mDNS.
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen. Integrate with mdnsd
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered. Integrate with umdns
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Hi, do i need any more configuration after installing umdns?
Thank you.

**Comment by wgtdkp** [comment]
@mrninhvn  mdns support on OpenWRT platform is missing, it will be great if you could contribute!

**Comment by mrninhvn** [comment]
> @mrninhvn mdns support on OpenWRT platform is missing, it will be great if you could contribute!

I still don't quite understand, How will the lack of mdns affect?
I have 2 border routers, 1 running on openwrt and 1 running on raspberry, openwrt border router cannot run alone without the raspberry router.

**Comment by wgtdkp** [comment]
@mrninhvn 
> I have 2 border routers, 1 running on openwrt and 1 running on raspberry, openwrt border router cannot run alone without the raspberry router.

What do you mean openwrt border router cannot not run? What's the phenomenon? What's you detail setup?

@caipiblack you need to provide an implementation of the [mdns.hpp](https://github.com/openthread/ot-br-posix/blob/main/src/mdns/mdns.hpp) interface for openWRT. Just as [mdns_avahi.cpp](https://github.com/openthread/ot-br-posix/blob/main/src/mdns/mdns_avahi.cpp) for Linux/Raspberry Pi and [mdns_mdnssd.cpp](https://github.com/openthread/ot-br-posix/blob/main/src/mdns/mdns_mdnssd.cpp) for Mac OS. You should use `OTBR_MDNS` to specify which mDNS implementation should be used for your platform when building OTBR.

**Comment by wgtdkp** [comment]
@caipiblack For why we need a mDNS implementation:

0. The Thread interface doesn't process multicast packets to handle mDNS queries.
1. In Thread network, we use the unicast [SRP](https://datatracker.ietf.org/doc/html/draft-ietf-dnssd-srp-12) protocol to register services to the Border Router. This is for avoiding multicast packets in Thread network as it will exhaust battery of end devices.
2. End devices' SRP services are registered to a SRP server running on the Border Router.
3. There is an [Advertising Proxy](https://github.com/openthread/ot-br-posix/blob/main/src/sdp_proxy/discovery_proxy.hpp) which helps publish the SRP services on the infrastructure link (e.g. WiFi and Ethernet) as mDNS services.
4. Hosts (or mobile devices) on the infrastructure link uses mDNS queries to discover the services registered by end devices.

**Comment by mrninhvn** [comment]
> 
> What do you mean openwrt border router cannot not run? What's the phenomenon? What's you detail setup?
> 

I got same problem with @caipiblack, thread device can ping to router, but can't ping to wifi device and vice versa.

**Comment by caipiblack** [comment]
**Update:**

Since [this pull-request](https://github.com/openthread/ot-br-posix/pull/1673) ot-br-posix works with avahi backend for mDNS stuffs.

We can also discover thread devices using avahi-browse from the router or the LAN network of the router.

Is there anything else to check ?
Is there still something to do ?

**Comment by jwhui** [comment]
@caipiblack , thanks for helping to address this issue.

> We can also discover thread devices using avahi-browse from the router or the LAN network of the router.

This validates the Advertising Proxy, where Thread devices can publish services and devices on the LAN can discover those services.

> Is there anything else to check ?

We should also validate the other direction - Discovery Proxy, where Thread devices can discover services on published by devices on the LAN.

**Comment by jwhui** [comment]
Closing stale issue.
