### ISSUE TITLE
[openwrt] unable to send network diagnostic to realm-local multicast addresses

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#427]
**Describe the bug** A clear and concise description of what the bug is.
We use network diagnostic protocol to build topology of the Thread network, however for unknown reason, the realm-local multicast address `ff03::2` cannot be sent out if the socket is not bound to the Thread interface. This is currently only found in my gl-inet 750m. OpenWRT on x86 doesn't have this issue.

I guess the root cause is inside the kernel(4.9.120).

**To Reproduce** Information to reproduce the behavior, including:

1. Create Thread network with CLI by ot-ctl
2. tcpdump -i wpan0 to monitor packets
3. ot-ctl networkdiagnostic get ff03::2 0 1

**Expected behavior** A clear and concise description of what you expected to happen.
The tcpdump should capture a packet to [ff03::2]:63631
**Console/log output** If applicable, add console/log output to help explain your problem.
No such packets are found.

**Additional context** Add any other context about the problem here.

**Comment by jwhui** [comment]
Closing stale issue.
