### ISSUE TITLE
Installation isn't working anymore on both Stretch and Buster

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#431]
**Describe the bug** A clear and concise description of what the bug is.

1. Installation on Stretch Lite no longer works due to CMake errors (even with apt-get update and apt-get upgrade):
CMake Error at CMakeLists.txt:29 (cmake_minimum_required):
  CMake 3.11.4 or higher is required.  You are running version 3.7.2

2. Installation on Buster is able to get past the CMake issue but fails to install all of the needed software, particularly otbr-web, otbr-agent and wpantund.

3. Installation on Stretch with a miraculously updated CMake still fails because needed software fails to install (see Buster install).

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
> commit 11b3fdde2a8ba83063e1d51be85db128e8e96083 (HEAD -> master, origin/master, origin/HEAD)

2. IEEE 802.15.4 hardware platform
> nothing yet

3. Build steps
> etch raspi micro sd card with stretch lite or buster lite (I tried both, neither work)
> sudo apt-get update
> sudo apt-get install git
> git clone https://github.com/openthread/ot-br-posix
> cd ot-br-posix
> sudo ./script/bootstrap
> sudo NETWORK_MANAGER=0 ./script/setup (or sudo ./script/setup, I tried both)
> sudo reboot

4. Network topology
> Just a lonely raspi.

**Expected behavior** A clear and concise description of what you expected to happen.

I expected to have what I used to have: a working host OTBR.  I expected to have items detailed in the openthread.io documentation (https://openthread.io/guides/border-router/build) such as wpantund.conf, otbr-agent, otbr-web.

**Console/log output** If applicable, add console/log output to help explain your problem.

I had the otbr installation previously working for both NCP and RCP.  When this worked, I was using hash commit a39d800e464582cc07414ea76603ee5442ff8f89 and had followed the instructions on the web pages.  These web pages claim that this installation should operate on stretch lite, however it no longer seems to function on hash commit 11b3fdde2a8ba83063e1d51be85db128e8e96083.  The current installation will no longer install on stretch lite, even when updated and upgraded.  It fails with this error:
CMake Error at CMakeLists.txt:29 (cmake_minimum_required):
  CMake 3.11.4 or higher is required.  You are running version 3.7.2

On Buster, the CMake version isn't an issue, so the installation process gets farther along.  However, much of the OTBR software is no longer installing.  There is no /etc/wpantund.conf.  I have no running otbr-agent nor otbr-web in systemctl status.  Generally, I first install without network manager.  The installation appeared to complete:
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  libjsoncpp-dev
0 upgraded, 1 newly installed, 0 to remove and 43 not upgraded.
Need to get 78.6 kB of archives.
After this operation, 380 kB of additional disk space will be used.
Get:1 http://raspbian.mirror.constant.com/raspbian buster/main armhf libjsoncpp-dev armhf 1.7.4-3 [78.6 kB]
Fetched 78.6 kB in 1s (145 kB/s)
Selecting previously unselected package libjsoncpp-dev:armhf.
(Reading database ... 58738 files and directories currently installed.)
Preparing to unpack .../libjsoncpp-dev_1.7.4-3_armhf.deb ...
Unpacking libjsoncpp-dev:armhf (1.7.4-3) ...
Setting up libjsoncpp-dev:armhf (1.7.4-3) ...
pi@raspberrypi:~/ot-br-posix $ cd /etc
pi@raspberrypi:/etc $ ls wpantund.conf
ls: cannot access 'wpantund.conf': No such file or directory

However, there was no wpantund.conf file created and systemctl status showed only the avahi-daemon and tayga services running while otbr-web and otbr-agent were not present in the list.  Nothing shows as degraded, it appears that the otbr software no longer is installing.  When I ran ./script/server, I got this:
Current platform is raspbian
* Applying /etc/sysctl.d/98-rpi.conf ...
kernel.printk = 3 4 1 3
vm.min_free_kbytes = 16384
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /etc/sysctl.d/protect-links.conf ...
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /etc/sysctl.conf ...
Failed to start otbr-nat44.service: Unit otbr-nat44.service not found.
 *** ERROR:  Failed to start NAT44!

Then I attempted the installation with the network manager piece installing.   That install terminated with:
Connection 'BorderRouter-Eth' (9de41adb-626d-49f9-a15e-121c2c9e0d65) successfully added.
Error: Connection activation failed: IP configuration could not be reserved (no available address, timeout, etc.)
pi@raspberrypi:~/ot-br-posix $
When I run ./script/server, I get:
pi@raspberrypi:~/ot-br-posix $ ./script/server
Current platform is raspbian
* Applying /etc/sysctl.d/60-otbr-ip-forward.conf ...
net.ipv6.conf.all.forwarding = 1
net.ipv4.ip_forward = 1
* Applying /etc/sysctl.d/98-rpi.conf ...
kernel.printk = 3 4 1 3
vm.min_free_kbytes = 16384
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /etc/sysctl.d/protect-links.conf ...
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /etc/sysctl.conf ...
active
active
active
inactive
Failed to start otbr-web.service: Unit otbr-web.service not found.
 *** ERROR:  Failed to start otbr-web!

**Additional context** Add any other context about the problem here.

I can't tell if the intent is to move to Buster or not but the CMake requirements are not working on Stretch and even if I try to get past that, there is still an issue with pieces of the BR no longer installing (even on Stretch).  The fact that the OTBR pieces are no longer installing may have something to do with recent changes to support MacOS?  But even if that is the case, I expect the installation documentation to match with the installation process.  Right now that isn't working for me.  Am I doing something incorrectly here?  My process worked previously but appears to no longer work.

**Comment by bukepo** [comment]
Thanks for reporting this issue. We recently remove wpantund support from this project, and the [openthread.io](https://openthread.io/guides/border-router/build) is also updated. You'll only see otbr-agent and otbr-web. Please reference the latest document.

---

For stretch, you can get a newer cmake by `sudo apt-get install -y python3-pip && sudo pip3 install -U cmake`, and then you can continue using stretch. I'll submit a PR to upgrade cmake.

---

I also encountered the following issue once, but after a second ./script/setup, the issue goes away. We'll enhance this later if this occurs repeatedly.

> Connection 'BorderRouter-Eth' (9de41adb-626d-49f9-a15e-121c2c9e0d65) successfully added.
> Error: Connection activation failed: IP configuration could not be reserved (no available address, timeout, etc.)

**Comment by JaneFromSilabs** [comment]
Hi and thank you for your response.  

The CMake command does allow me to get past the first problem.  I had tried that previous to this post but I wasn't sure this was still the supported OS at the time.  So, the clarification around the proper OS is helpful also.  I'll continue to use Stretch.  Cheers!

**Comment by bukepo** [comment]
@JaneFromSilabs could you point out what update you expect in that readme?

**Comment by JaneFromSilabs** [comment]
In my previous post, I pointed to a specific wpantund command.  I wasn't sure if that information was still accurate given that the NCP installation no longer has references to wpantund.

**Comment by JaneFromSilabs** [comment]
Additionally, setting up using the NCP installation documentation requests that we configure the file /etc/default/otbr-agent with the following (edited with my tty port):
`
# Default settings for otbr-agent. This file is sourced by systemd

# Options to pass to otbr-agent
OTBR_AGENT_OPTS="-I wpan0 /dev/ttyACM0 115200"
`
However, when I configure as above, I'm getting these error messages:
`May 21 18:06:23 raspberrypi ModemManager[417]: <info>  Creating modem with plugin 'Generic' and '1' ports
May 21 18:06:23 raspberrypi ModemManager[417]: <warn>  Could not grab port (tty/ttyACM0): 'Cannot add port 'tty/ttyACM0', unhandled serial type'
May 21 18:06:23 raspberrypi ModemManager[417]: <warn>  Couldn't create modem for device at '/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2': Failed to find primary AT port
May 21 18:06:26 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
May 21 18:06:26 raspberrypi systemd[1]: Stopped Border Router Agent.`

tty/ttyACM0 is not the path I have configured.  I'm also seeing a lot of these:
`May 21 18:15:29 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
May 21 18:15:29 raspberrypi systemd[1]: Stopped Border Router Agent.
May 21 18:15:29 raspberrypi systemd[1]: Started Border Router Agent.
May 21 18:15:29 raspberrypi otbr-agent[1278]: Thread interface wpan0
May 21 18:15:30 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=1/FAILURE
May 21 18:15:30 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
May 21 18:15:30 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
`
I think something is still not working with this installation.

**Comment by gabekassel** [comment]
I'm seeing something potentially similar and was about to post separately, but will post here. I've built ot-daemon/ot-ctl in our posix OS as well as otbr-agent. ot-daemon works great but whenever I launch otbr-agent, ot-daemon exits. i get no output from otbr-agent when running it (even with verbose). curious how to debug and if this matches this post.

```
May 21 21:55:50 eero daemon.info ntpd[2360]: 21 May 21:55:50 ntpd[2360]: Soliciting pool server 198.74.51.125
May 21 21:56:38 eero daemon.info ntpd[2360]: 163.237.218.19 local addr 10.0.4.1 -> <null>
May 21 21:56:38 eero daemon.info ntpd[2360]: 21 May 21:56:38 ntpd[2360]: 163.237.218.19 local addr 10.0.4.1 -> <null>
May 21 22:06:39 eero user.info otbr-agent[3296]: Thread interface tun0
May 21 22:06:45 eero user.info otbr-agent[3310]: Thread interface tun0
May 21 22:06:45 eero daemon.info ot-daemon[2349]: /usr/sbin/ot-daemon[2349]: [CRIT]-PLAT----: HandleValueIs() at /usr/src/debug/openthread-core/git+AUTOINC+883d32356f-r0/git/src/lib/spinel/radio_spinel_impl.hpp:760: RadioSpinelReset
May 21 22:06:45 eero daemon.info ot-daemon[2349]: OPENTHREAD/20191113-00566-g3c83428b-dirty; EFR32; May 21 2020 11:47:44
May 21 22:06:45 eero daemon.crit /usr/sbin/ot-daemon[2349]: [CRIT]-PLAT----: HandleValueIs() at /usr/src/debug/openthread-core/git+AUTOINC+883d32356f-r0/git/src/lib/spinel/radio_spinel_impl.hpp:760: RadioSpinelReset
May 21 22:06:45 eero daemon.notice systemd[1]: ot-daemon.service: Main process exited, code=exited, status=4/NOPERMISSION
May 21 22:06:45 eero daemon.warn systemd[1]: ot-daemon.service: Failed with result 'exit-code'.

```

**Comment by bukepo** [comment]
@JaneFromSilabs the path is the serial device path of the RCP(not NCP). Could you confirm the device path is correct and the serial port configuration is right? For example, some device may require flow control rts/cts, and the baudrate may be different from 115200.

---

@gabekassel Now otbr-agent already manages the the tun device and OpenThread daemon is running inside this otbr-agent. So I think you should remove ot-daemon from your setup.

**Comment by JaneFromSilabs** [comment]
@bukepo Thank you, yes, this is working with the RCP now.  I was trying to still use the NCP.  Is NCP still supported with the OTBR?  It is listed here: https://openthread.io/platforms, so I am assuming it is still supported.  Are there instructions for setting that up since it no longer seems to be the main configuration?

**Comment by jwhui** [comment]
@JaneFromSilabs, we have transitioned OTBR to using RCP and that is reflected in our [Border Router Build and Configuration guide](https://openthread.io/guides/border-router/build).

We have moved wpantund support to the [wpantund/master](https://github.com/openthread/ot-br-posix/tree/wpantund/master) branch for historical reasons. However, we would prefer new work going forward to use the RCP model.

Can you use RCP moving forward? Or is there a reason why you might prefer NCP?

**Comment by JaneFromSilabs** [comment]
Hi @jwhui ,

Thank you for the response on this.  We are currently investigating whether or not this will be an issue for us.  

Can you please tell me if this move away from the NCP Border Router specific or is this a general architecture decision affecting any host application?

Cheers,
Jane

**Comment by gabekassel** [comment]
> @JaneFromSilabs the path is the serial device path of the RCP(not NCP). Could you confirm the device path is correct and the serial port configuration is right? For example, some device may require flow control rts/cts, and the baudrate may be different from 115200.
> 
> @gabekassel Now otbr-agent already manages the the tun device and OpenThread daemon is running inside this otbr-agent. So I think you should remove ot-daemon from your setup.

Thanks @bukepo - this resolved a lot for me. That being the case, should I change anything about how I'm building openthread core for posix, now? Currently I'm building with daemon mode enabled. Do I even need to build openthread posix separate from otbr agent now?

**Comment by jwhui** [comment]
> Can you please tell me if this move away from the NCP is Border Router specific or is this a general architecture decision affecting any host application?

@JaneFromSilabs , we have decided to move the ot-br-posix project to use the RCP model moving forward. RCP allows OpenThread core to run on the host side, which provides a number of benefits. Including but not limited to:

1. OpenThread can utilize the significant resources of Linux host.

1. Simplify networking interactions by centralizing all IP-based protocol logic on the host.

1. Simplify debugging by allowing direct use of all tools typically available for Linux processes.

The OpenThread core project continues to support [SoC, RCP, and NCP platform designs](https://openthread.io/platforms#platform_designs).

**Comment by jwhui** [comment]
> Thanks @bukepo - this resolved a lot for me. That being the case, should I change anything about how I'm building openthread core for posix, now? Currently I'm building with daemon mode enabled. Do I even need to build openthread posix separate from otbr agent now?

@gabekassel , building otbr-agent should be sufficient, as that links directly to the OpenThread library.

**Comment by JaneFromSilabs** [comment]
Thank you, @jwhui and @bukepo, I have the RCP working and have confirmed that the lack of NCP support is not an issue for us going forward.  Have a great weekend!
