### ISSUE TITLE
[tests] add fuzzer test for dbus client

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#433]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.

fuzzer test is missing in this project.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
add a fuzzer test for dbus interface.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
add a fuzzer test for the dbus client library as well.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by jwhui** [comment]
Closing stale issue.
