### ISSUE TITLE
ot-ctl fails to add on-mesh prefix for global routing

### ISSUE THREAD

**Issue by nealjack** [openthread/ot-br-posix#439]
**Describe the bug**
Using the new command line interface `ot-ctl`, it is possible to form a network on the border router using the steps listed [here](https://openthread.io/guides/border-router/external-commissioning#manual). However, the command to add a prefix is not successful, and my devices never get a new address with this prefix and are unable to send packets outside the thread network. The only way to successfully form a network with a proper on-mesh prefix is to use the "form" page on the border router web interface.

**To Reproduce**
As per the [documentation](https://openthread.io/guides/border-router/external-commissioning#manual) to manually form a network on the border router:
```
sudo ot-ctl factoryreset
sudo ot-ctl panid 0xface
sudo ot-ctl extpanid dead00beef00cafe
sudo ot-ctl masterkey 00112233445566778899aabbccddeeff
sudo ot-ctl channel 25
sudo ot-ctl networkname OpenThread
sudo ot-ctl ifconfig up
sudo ot-ctl thread start
sudo ot-ctl prefix add fd11:22::/64 pasor
```
*Note: The documentation erroneously lists `xpanid` as the command instead of extpanid*

I was unable to find any documentation on ot-ctl, and what `pasor` indicates. I can actually pass any sort of string to `ot-ctl prefix add` and get "Done" as a result. It seems like it's failing silently, if failing at all.

I can form the network successfully without the prefix command, and using the "settings" on the web interface to add the prefix also does not work.

1. Git commit id: fdba1c7
2. IEEE 802.15.4 hardware platform: nrf52840 dongle
3. Build steps: Built from source on Raspberry Pi 4 according to [these directions](https://openthread.io/guides/border-router/build#set-up-the-border-router). I set `NETWORK_MANAGER=0` during the build to prevent the creation of a WiFi AP.
4. Network topology: Currently just one border router and one thread end device.

**Expected behavior** 
I expected this series of commands would have the same result as forming the network from the web interface. The [underlying backend](https://github.com/openthread/ot-br-posix/blob/171f0eb483a1fd7cb99d6cfa96dc095e375a7c9e/src/web/web-service/wpan_service.cpp#L76) for the web interface seems to be making the same commands.

**Console/log output** 
I ran the commands listed above on the border router, including the prefix command.

On the end device, it joins the network but never gets a global prefix:
```
<info> app: State changed! Flags: 0x0117D33D Current role: 1
<info> app: State changed! Flags: 0x000000E4 Current role: 2
<info> app: State changed! Flags: 0x00000200 Current role: 2
```
Should have also seen:
```
<info> app: State changed! Flags: 0x00000001 Current role: 2
```

**Comment by jwhui** [comment]
@nealjack , we recently updated master branch to use the [RCP model](https://openthread.io/platforms#radio-co-processor-rcp) on ot-br-posix.

By moving OpenThread core from the 15.4 SoC to Linux host, we are able to remove wpantund and utilize the existing [OpenThread CLI](https://github.com/openthread/openthread/tree/master/src/cli).

After making updates to the network data locally, try issuing the [`netdataregister`](https://github.com/openthread/openthread/tree/master/src/cli#netdataregister) command to cause the device to register its network data on the Leader.

Hope that helps. Let us know.

**Comment by nealjack** [comment]
Thanks for the quick response. Yes, it looks like that was the step I was missing. I can confirm that the prefix is added, my device gets an address, and can send messages externally.

I realize these are pretty recent architectural changes, and that documentation is pretty sparse right now, so thank you for the clarity.

To reiterate some changes to documentation that I noticed need to be made:
It's obvious now that you mention it that `ot-ctl` is using the OpenThread CLI, but I didn't find any mention or links to this in the border router documentation. I would add the `netdataregister` command to the guide I [linked](https://openthread.io/guides/border-router/external-commissioning#manual), as well as fix the typo with `extpanid`.

**Comment by jwhui** [comment]
@nealjack , thanks for identifying these issues. We'll work to update the Border Router guide.

**Comment by Vyrastas** [comment]
@bukepo Is sorting this out.

**Comment by bukepo** [comment]
@nealjack Could you help check the latest guide?

**Comment by nealjack** [comment]
@bukepo It looks like the documentation has been fixed! Thanks!
