### ISSUE TITLE
ot-ctl commands hang indefinitely

### ISSUE THREAD

**Issue by nealjack** [openthread/ot-br-posix#440]
**Describe the bug**
I have noticed that some `ot-ctl` commands do not exit cleanly, and seem to stay in the OpenThread CLI indefinitely. This makes it hard to write startup services that automatically set up the network and add a prefix.

Notably, `ot-ctl reset` hangs at the CLI:
```
$ sudo ot-ctl reset
>
```
I have noticed this behavior with `channel` and `factoryreset` commands as well.

1. Git commit id: fdba1c7
2. IEEE 802.15.4 hardware platform: nrf52840 dongle
3. Build steps: Build steps in the documentation with NETWORK_MANAGER=0
4. Network topology: one border router and one end device

**Expected behavior**
I would expect `ot-ctl` commands to exit immediately

**Comment by gjc13** [comment]
When `ot-ctl` hang, is `otbr-agent` still running or it crashes?

**Comment by bukepo** [comment]
submitted: https://github.com/openthread/openthread/pull/5011
