### ISSUE TITLE
ot-ctl commands hang indefinitely

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#443]
**Describe the bug** A clear and concise description of what the bug is.
Similar/same issue as ot-ctl commands hang indefinitely #440: I stop getting proper responses and the CLI hangs forever.

`Last login: Fri May 29 17:45:00 2020 from 172.16.1.171

pi@rpi2:~ $

pi@rpi2:~ $ sudo ot-ctl state

disabled

Done

\> pi@rpi2:~ $ sudo ot-ctl panid 0xface

Done

pi@rpi2:~ $ sudo ot-ctl extpanid dead00beef00cafe

\> Done

\>

`
(edited to escape the '>' character and add line feeds)

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: commit 0a18ff04240020f2cfc9cb776bd3162ddb40c8d8

2. IEEE 802.15.4 hardware platform
Silicon Labs brd4161a

3. Build steps
git clone https://github.com/openthread/ot-br-posix
./script/bootstrap
NETWORK_MANAGER=0 ./script/setup
Verified my device was using ttyACM0
Configured /etc/default/otbr-agent with OTBR_AGENT_OPTS="-I wpan0 /dev/ttyACM0 115200"
Built an RCP for my device from the tip of master

4. Network topology
Just the lone OTBR at the moment

**Expected behavior** A clear and concise description of what you expected to happen.
I expected the raspi prompt to return to me.

**Console/log output** If applicable, add console/log output to help explain your problem.
Console output is above.  Here is the syslog tail:
May 29 17:54:08 rpi2 systemd[776]: Listening on GnuPG cryptographic agent (access for web browsers).
May 29 17:54:08 rpi2 systemd[776]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
May 29 17:54:08 rpi2 systemd[776]: Reached target Paths.
May 29 17:54:08 rpi2 systemd[776]: Reached target Timers.
May 29 17:54:08 rpi2 systemd[776]: Reached target Sockets.
May 29 17:54:08 rpi2 systemd[776]: Reached target Basic System.
May 29 17:54:08 rpi2 systemd[776]: Reached target Default.
May 29 17:54:08 rpi2 systemd[776]: Startup finished in 215ms.
May 29 17:54:08 rpi2 systemd[1]: Started User Manager for UID 1000.
May 29 17:54:15 rpi2 systemd[1]: Started Session c2 of user pi.
May 29 17:56:07 rpi2 otbr-agent[403]: [INFO]-PLAT----: Session socket is ready
May 29 17:56:07 rpi2 otbr-agent[403]: [INFO]-CLI-----: execute command: state
May 29 17:56:21 rpi2 otbr-agent[403]: [INFO]-PLAT----: Session socket is ready
May 29 17:56:21 rpi2 otbr-agent[403]: [INFO]-CLI-----: execute command: panid 0xface
May 29 17:56:21 rpi2 otbr-agent[403]: [INFO]-CORE----: Notifier: StateChanged (0x00008000) [PanId]
May 29 17:56:37 rpi2 otbr-agent[403]: [INFO]-PLAT----: Session socket is ready
May 29 17:56:37 rpi2 otbr-agent[403]: [INFO]-CLI-----: execute command: extpanid dead00beef00cafe
May 29 17:56:37 rpi2 otbr-agent[403]: [INFO]-CORE----: Notifier: StateChanged (0x00000010) [MLAddr]
May 29 17:58:21 rpi2 otbr-agent[403]: [INFO]-MAC-----: Received IPv6 UDP msg, len:83, chksum:5a5a, from:662b0d87546edeec, sec:yes, prio:net, rss:-92.0
May 29 17:58:21 rpi2 otbr-agent[403]: [INFO]-MAC-----:     src:[fe80:0:0:0:642b:d87:546e:deec]:19788
May 29 17:58:21 rpi2 otbr-agent[403]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:1]:19788
May 29 17:58:21 rpi2 otbr-agent[403]: [INFO]-PLAT----: processReceive: OK
May 29 17:58:21 rpi2 otbr-agent[403]: [NOTE]-MLE-----: Failed to process UDP: InvalidState
May 29 18:01:26 rpi2 systemd[1]: Started Session c3 of user pi.
May 29 18:07:18 rpi2 systemd[1]: Starting Cleanup of Temporary Directories...
May 29 18:07:18 rpi2 systemd[1]: Started Cleanup of Temporary Directories.
May 29 18:08:24 rpi2 otbr-agent[403]: [INFO]-MAC-----: Received IPv6 UDP msg, len:83, chksum:8853, from:662b0d87546edeec, sec:yes, prio:net, rss:-90.0
May 29 18:08:24 rpi2 otbr-agent[403]: [INFO]-MAC-----:     src:[fe80:0:0:0:642b:d87:546e:deec]:19788
May 29 18:08:24 rpi2 otbr-agent[403]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:1]:19788
May 29 18:08:24 rpi2 otbr-agent[403]: [INFO]-PLAT----: processReceive: OK
May 29 18:08:24 rpi2 otbr-agent[403]: [NOTE]-MLE-----: Failed to process UDP: InvalidState

**Additional context** Add any other context about the problem here.

**Comment by bukepo** [comment]
@JaneFromSilabs  I cannot reproduce this issue, could you please try if cherry-pick https://github.com/openthread/openthread/pull/5026 fixes the issue you ran into?

**Comment by bukepo** [comment]
Is this still an issue? @JaneFromSilabs

**Comment by JaneFromSilabs** [comment]
Hi @bukepo , 

Sorry for the delay in my response.  I have been out of the office for a few days.  I am back in the office as of this morning.  I was able to test with commit c14ef63c07a788708f135cf5392854b4bc4d5e31 and the problem is no longer reproducible!  I am able to form a Thread network now.  Thank you!

Cheers,
Jane
