### ISSUE TITLE
[web]  otbr-web binary command option require unwanted argument

### ISSUE THREAD

**Issue by tttttangTH** [openthread/ot-br-posix#450]
After setting up ot-br-posix in Docker and start otbr-web, it will give an `option require an arrgument `  error when checking version number.

```
./build/src/web/otbr-web -v
## ./build/src/web/otbr-web: option requires an argument -- 'v'
## Usage: ./build/src/web/otbr-web [-d DEBUG_LEVEL] [-I interfaceName] [-p port] [-a 
listenAddress] [-v]
```

We know `-v` option is generally used to print version number which does not need an argument.
So the expected output should be like:

```
./build/src/web/otbr-web -v
#0.2.0-6413bac-dirty
```

**Comment by bukepo** [comment]
I think there is a typo. In this project, we use `-v` for verbose, and `-V` for print version. Would you like to submit a PR to fix this issue?

**Comment by tttttangTH** [comment]
Yeah, will fix it. Do I need to change the behavior in another issue/PR?

**Comment by bukepo** [comment]
Either way works for me.

**Comment by wgtdkp** [comment]
@tttttangTH Let's just fix the wrong output of `-v` option of in **`otbr-web`**. We can change `-v` / '-V' of **`otbr-agent`** in another PR.
