### ISSUE TITLE
openthread/otbr docker image on docker hub is outdated

### ISSUE THREAD

**Issue by gjc13** [openthread/ot-br-posix#452]
**Describe the bug** 
The docker image `otbr` on github is outdated and still uses wpantund.

**To Reproduce** 

```
docker pull openthread/otbr:latest
docker run -it --entrypoint bash openthread/otbr
```
The image is outdated.

**Expected behavior** 
The image should be linked to `otbr_amd64_linux`.

**Comment by Vyrastas** [comment]
Maybe OTBR needs to be uploading a new Docker image with each new merge, similar to what OpenThread does.  Can you set it up that way?  I think we didn't do it originally to provide a stable image.

**Comment by jwhui** [comment]
I agree that we should push a new image with each merge. Maybe we can use a GitHub Action (see [Multi-arch build and images, the simple way](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)).

**Comment by Vyrastas** [comment]
I would like to try and implement this, but I have so much else going on that I don't know when I'd be able to get to it.  Someone else might have to take this on if it's a priority.
