### ISSUE TITLE
Unable to commission node for some random duration.

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#466]
I have setup OTBR in Raspberry Pi 3B+. I have been using OpenThread for around 21 months now. There is an issue I face many times, i.e., commissioning of node does not happen for few random hours and then all of sudden it works. Since last two weeks, it is happening every so often.

Following are the details:
1. OS version is stretch
2. `"NCP:Version" => "OPENTHREAD/20180926-01143-g8a1992e2; NRF52840; Dec 10 2019 22:48:00"`
3. `Daemon:Version" => "0.08.00d (/0.07.01-341-g1f65656; May 11 2020 21:06:03)"`
4. Firmware is build on Nordic SDK 4.0.0

Following are the observations:
1. When I tried to commission node burned with our firmware, I faced this issue.
2. When I tried to commission node burned with CLI firmware shipped with SDK, I did't faced this issue.
3. When I changed the daemon version to `"Daemon:Version" => "0.08.00d (/345bf7d; Jun 27 2019 17:02:59)"`, I did't faced this issue (with both firmwares).

I don't know how to debug this problem.
Kindly help me with this.

Thanks in advance.

**Comment by jwhui** [comment]
@tarunsmalviya , can you try with a more recent build of NCP?

**Comment by tarunsmalviya** [comment]
@jwhui Okay. Will get back to you once done.

**Comment by jwhui** [comment]
Closing stale issue.
