### ISSUE TITLE
Ping responses are not reported back in the CLI

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#471]
### **Describe the bug** A clear and concise description of what the bug is.

I am able to ping from my ftd soc to the OTBR, but when I try to ping the ftd soc from the OTBR, the packet is never reported as received.  I believe the OTBR is receiving the ping because it showed up in the trace of the wpan0 interface, but the CLI is not reporting the command success.

I send a ping to my soc from the OTBR as follows:
```
pi@rpi1:~ $ sudo ot-ctl ping fe80:0:0:0:1c98:b036:cad1:ed49 8 1 1000
Done
pi@rpi1:~ $
```

That is all of the information I ever receive back in the CLI.

But I do see the ping reply in both of my trace applications (tcpdump and simplicity studio):
```
pi@rpi1:~ $ sudo tcpdump -vv -XX -i wpan0 ip6
tcpdump: listening on wpan0, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
15:33:33.224740 IP6 (hlim 64, next-header ICMPv6 (58) payload length: 16) fe80::1c98:b036:cad1:ed49 > fe80::c873:ac98:f181:6b2: [icmp6 sum ok] ICMP6, echo reply, seq 7
        0x0000:  0000 ffff 0000 0000 0000 0000 0000 86dd  ................
        0x0010:  6000 0000 0010 3a40 fe80 0000 0000 0000  `.....:@........
        0x0020:  1c98 b036 cad1 ed49 fe80 0000 0000 0000  ...6...I........
        0x0030:  c873 ac98 f181 06b2 8100 bf62 0007 0007  .s.........b....
        0x0040:  1eac b16b 0000 0000                      ...k....
```
![image](https://user-images.githubusercontent.com/58004715/84400920-a485c980-abd0-11ea-8c1d-a6cbe24aefb8.png)

### **To Reproduce** Information to reproduce the behavior, including:

I formed a thread network (of just the 2 nodes) using:
> ot-ctl channel 11
> ot-ctl networkname SilabsOpenThread
> ot-ctl panid 0xABCD
> ot-ctl extpanid DEAD00BEEF00CAFE
> ot-ctl masterkey 00112233445566778899AABBCCDDEEEE
> ot-ctl ifconfig up
> ot-ctl thread start
> I verified the OTBR was in state "leader"
> I set the same information on the soc for panid, masterkey and channel, and then brought up the interface and started thread
> I verified the device joined as a child node
> I waited 120 seconds for the joiner node (soc) to become a router and made sure upgraded
> I made sure I could ping from the soc to the link local of the otbr wpan0, but the reverse direction did not report the reply was received

### 1. Git commit id 
> commit c14ef63c07a788708f135cf5392854b4bc4d5e31

### 2. IEEE 802.15.4 hardware platform 
> Silabs BRD4161A

### 3. Build steps
> git clone https://github.com/openthread/ot-br-posix
> ./script/bootstrap
> NETWORK_MANAGER=0 ./script/setup
> Verified my device was using ttyACM0
> Configured /etc/default/otbr-agent with OTBR_AGENT_OPTS="-I wpan0 spinel+hdlc+uart:///dev/ttyACM0"
> Built an RCP for my device

### 4. Network topology
> Just the 2 devices on the same mesh

### **Expected behavior** A clear and concise description of what you expected to happen.
> I would like to see the ping replies represented in the UI

### **Console/log output** If applicable, add console/log output to help explain your problem.
> See above

**Comment by jwhui** [comment]
@JaneFromSilabs , thanks for raising this issue.

This is currently expected behavior. `ot-ctl` is exiting before the ICMPv6 Echo Reply is received.

Can you try running `ot-ctl` in interactive mode by invoking `ot-ctl` without any arguments?

For example:
```
$ sudo ot-ctl
> ping fe80:0:0:0:4813:3001:fe36:5367
Done
16 bytes from fe80:0:0:0:4813:3001:fe36:5367: icmp_seq=1 hlim=64 time=6ms
```

**Comment by JaneFromSilabs** [comment]
Hi @jwhui , 

Thank you for letting me know that this is intended.  It does work fine in the interactive mode.  Since this is intended behavior, this issue is closed.

Cheers,
Jane
