### ISSUE TITLE
ot-ctl (interactive mode) exits when executing factoryreset

### ISSUE THREAD

**Issue by simonlingoogle** [openthread/ot-br-posix#474]
**Describe the bug**
ot-ctl (interactive mode) exits when executing CLI command: factoryreset

**Expected behavior**
It should not exit.

**Comment by romacdon** [comment]
What would be the fix here?  Would it be to have ot-ctl automatically reconnect to the otbr-agent after sending a "factoryreset" or "reset" command to the otbr-agent when running in interactive mode?

**Comment by simonlingoogle** [comment]
> What would be the fix here? Would it be to have ot-ctl automatically reconnect to the otbr-agent after sending a "factoryreset" or "reset" command to the otbr-agent when running in interactive mode?

Automatically reconnecting sounds promising to me. I will submit a fix lately to address this issue. 

Besides, `ot-ctl` exits automatically if `otbr-agent` has exited. From a larger perspective, do you think we should keep `ot-ctl` running despite the status of `otbr-agent` service is a good idea? @bukepo @gjc13 @jwhui

**Comment by romacdon** [comment]
My thought is that if otbr-agent exists then it doesn't really make sense to keep ot-ctl running however in the factoryreset and reset cases otbr-agent isn't really exiting.

**Comment by simonlingoogle** [comment]
> My thought is that if otbr-agent exists then it doesn't really make sense to keep ot-ctl running however in the factoryreset and reset cases otbr-agent isn't really exiting.

It's difficult for `ot-ctl` to determine why the session was closed. That's why I used a reconnecting timeout in https://github.com/openthread/openthread/pull/5466 and expects ot-daemon to recover before timeout expires if it's `factoryreset` or `reset`.

**Comment by romacdon** [comment]
> > My thought is that if otbr-agent exists then it doesn't really make sense to keep ot-ctl running however in the factoryreset and reset cases otbr-agent isn't really exiting.
> 
> It's difficult for `ot-ctl` to determine why the session was closed. That's why I used a reconnecting timeout in [openthread/openthread#5466](https://github.com/openthread/openthread/pull/5466) and expects ot-daemon to recover before timeout expires if it's `factoryreset` or `reset`.

I agree and I like your solution.

**Comment by JaneFromSilabs** [comment]
I have one question about this.  Right now, factoryreset and reset seem to be the only clean ways of exiting the interactive mode.  The 'exit' command seems to exit the otbr-agent all together.  Control-c seems to exit but this is not obvious to the user and it seems to mess up the terminal window (at least in putty).  I can end the entire telnet session, I suppose.  Is there a good way to exit the interactive mode that I'm not finding?

**Comment by simonlingoogle** [comment]
> I have one question about this. Right now, factoryreset and reset seem to be the only clean ways of exiting the interactive mode. The 'exit' command seems to exit the otbr-agent all together. Control-c seems to exit but this is not obvious to the user and it seems to mess up the terminal window (at least in putty). I can end the entire telnet session, I suppose. Is there a good way to exit the interactive mode that I'm not finding?

Agree with you. I actually think we should not exit `ot-daemon` when we issue the `exit` command on `ot-ctl`, but only exit `ot-ctl`. Currently, the only thing `ot-ctl` does is passing the commands to `ot-daemon`. Maybe we need to enhance `ot-ctl` upon that.

**Comment by romacdon** [comment]
Maybe `exit` in interactive mode exits `ot-ctl` but in non interactive mode sends it to `ot-daemon`?
