### ISSUE TITLE
Set up the Border Router failed

### ISSUE THREAD

**Issue by grja** [openthread/ot-br-posix#478]
Setting up the Border Router failed on Pi3B 2019-04-08-raspbian-stretch-lite.

**To Reproduce** 
- Download and install the 2019-04-08-raspbian-stretch-lite on SD card, insert the SD card into the Raspberry Pi and power it up.
- install git
- git clone https://github.com/openthread/ot-br-posix
- cd ot-br-posix
- ./script/bootstrap
- ./script/setup
  It fails with message :
  Connection 'BorderRouter-Eth' (301e760d-abf9-46d1-a828-49a5fb3a5f78) successfully added.
Error: Connection activation failed.

 Git commit id
I used latest commit
commit 55021269c7c461c4afb4c8a29a39c0fb4c7b8759

Configuration: 
Pi3B V1.2 + nRF52840-Dongle

Log attached:
[setup.log](https://github.com/openthread/ot-br-posix/files/4784702/setup.log)

**Comment by bukepo** [comment]
There is a known unstable issue for setup, could you try run the script again and see if the issue goes away?

**Comment by hao-gao** [comment]
@grja @bukepo 
`sudo apt install dnsmasq` before ./script/setup fixes this.
because we can see following in syslog:
` <error> [1592383199.9311] device (wlan0): share: (wlan0) failed to start dnsmasq: Could not find "dnsmasq" binary`
seems we need to install dnsmasq for recent versions of nm in /script/bootstrap?

**Comment by grja** [comment]
`sudo apt install dnsmasq` before ./script/setup fixed this issue.
Than you for your help.

**Comment by mhallam281** [comment]
We had this same issue, and sudo apt install dnsmasq before ./script/setup fixed it foe us as well. Thanks for digging into this.

**Comment by simonlingoogle** [comment]
@grja @hao-gao 
Do you mind propose a PR for this fix?
