### ISSUE TITLE
Upgrade and Downgrade Procedures

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#482]
Is your feature request related to a problem? Please describe.
I need to use an older RCP build, so I am attempting to downgrade to an older version of the OTBR right now and having trouble doing so. Here are the steps I am taking:

```
git checkout <commit hash> (I am using 591cfebbe1a337f84bc2549505e2fc42886ab4a6)
git submodule update --recursive --init
sudo ./script/update
```
After a reboot, I cannot talk to the RCP so I suspect I am either not doing this correctly or perhaps downgrade is not supported and I need to reflash the raspi.

Describe the solution you'd like
Is there documentation on how to go about this? Additionally, is there documentation of the supported update process? I just want to make sure I'm doing this correctly. For updating, I would expect the same process (checkout, update submodules, update script). Is that sequence the best practice?

**Comment by brianljt** [comment]
Recently, there is a change which changes Spinel protocol (https://github.com/openthread/openthread/commit/201b7b1a3d337bd1afaa97880f32c3cca77cf283). So a newer host driver requires a newer RCP build. If you are using an older RCP build, you might need to try with some older host driver.

For commit 591cfebbe1a337f84bc2549505e2fc42886ab4a6, its submodule openthread is using b28d7c4a.

**Comment by JaneFromSilabs** [comment]
I guess I was looking for more procedural information.  I want to make sure that when I upgrade/downgrade that I do things the correct way and that we tell our customers the correct information about how to go about this.  

Generally speaking, how do you recommend going about updating the border router?  Is there also a downgrade procedure?

**Comment by brianljt** [comment]
I think the steps you mentioned is fine for upgrading and downgrading. In general I would suggest to use same OpenThread commit ID for RCP and OTBR. I.E. commit id for repo bt-br-posix/third_party/openthread/repo should be same as the one for RCP image. Each commit to OpenThread repo will trigger github action to do some simulation tests thus ensure a matching host driver and RCP firmware can function as expected.

**Comment by JaneFromSilabs** [comment]
If the downgrading should work, I believe there may be an issue.  When I downgraded, despite having those exact pointers you specified checked out, I could not connect to an older RCP.  I could only connect to a current RCP build.  When I re-etched my raspi, I was able to use those same hash commits for the ot-br-posix and the ot-br-posix/thirdparty/openthread/repo repositories and connect to my older RCP.  It seems somehow the spinal change isn't getting downgraded with my above noted process.  I don't know whether or not this is worth supporting, but I thought I should mention that I was unable to get that to work despite following what I believe the process should be.

**Comment by brianljt** [comment]
I had a tried on RaspberryPi and found you might be missing one step when using older ot-br-posix. Please check step 5 in https://openthread.io/guides/border-router/build . If the RCP device is not specified, host cannot talk to it. You can have a try on host with command "sudo ot-ctl" and see if command prompt is shown.

BTW, In a recent commit (https://github.com/openthread/ot-br-posix/commit/55021269c7c461c4afb4c8a29a39c0fb4c7b8759), the default device is specified.

**Comment by JaneFromSilabs** [comment]
Thanks for the information!  I was able to get this working in the end, and it does work fine, it just wasn't matching up with the OpenThread running on my other devices anymore.

**Comment by brianljt** [comment]
Glad to hear that it is working for you now @JaneFromSilabs . BTW, I've committed one PR to make newer host driver compatible with older RCP firmware. Once this commit is included in ot-br-posix submodule, the new host driver can talk to old RCP firmware without the need to downgrade it. https://github.com/openthread/openthread/pull/5139

Although it is done, I would still suggest to use matching OpenThread commit for host side and RCP side for stability consideration.

**Comment by JaneFromSilabs** [comment]
Yes, I tried using that today and it seemed to work for me (I was using it with an RCP built from f411a412).  I was able to bring up connections and ping the interfaces on the BR as well as through the BR using NAT64.  I have not seen any instability yet but I haven't done anything all that stressful with it yet either.  Thanks for this update!
