### ISSUE TITLE
[commissioner] missing on-mesh commissioner d-bus API

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#483]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.
on-mesh commissioner is available on border router, but currently no d-bus API exposed.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
export commissioner functionality through d-bus.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
none

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by jwhui** [comment]
Closing stale issue.
