### ISSUE TITLE
OpenThread daemon is not running

### ISSUE THREAD

**Issue by iDarshan** [openthread/ot-br-posix#486]
I am trying to run OpenThread Border Router on Ubuntu 18.04. I cloned latest master branch of ot-br-posix. Followed steps given on https://openthread.io/guides/border-router/build. Installation is successful and I can see otbr-web and otbr-agent services running. Still, when I give `ot-ctl state` command, it says "OpenThread daemon is not running". Guide says that use adapter instead of USB port, but I am running it on a PC, so the workaround given is not applicable. Searched Google group and StackOverflow but didn't find anything related to this issue. Please provide some information to resolve this issue.

**Comment by bukepo** [comment]
Did you run ot-ctl with sudo?

**Comment by iDarshan** [comment]
Yes.

**Comment by iDarshan** [comment]
I just tried the same steps on Rasperry Pi 4 with Raspbian OS. In that too it gives same error. OpenThread daemon is not running. Something is wrong. Please help here.

**Comment by bukepo** [comment]
Could you double check if the `otbr-agent` is running? If not, maybe you have to check what's happening by manually run the command:

```bash
service otbr-agent stop
# Note: /dev/ttyUSB0 should be the path to the serial device of the RCP dongle
otbr-agent -I wpan0 -d7 -v spinel+hdlc+uart:///dev/ttyUSB0
```

**Comment by iDarshan** [comment]
```
darshan@Ubuntu18:~$ sudo service otbr-agent status
[sudo] password for darshan: 
● otbr-agent.service - Border Router Agent
   Loaded: loaded (/lib/systemd/system/otbr-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-06-20 12:53:03 CDT; 25s ago
 Main PID: 6391 (otbr-agent)
    Tasks: 1 (limit: 4666)
   CGroup: /system.slice/otbr-agent.service
           └─6391 /usr/sbin/otbr-agent -I wpan0 spinel+hdlc+uart:///dev/ttyACM0

Jun 20 12:53:04 Ubuntu18 otbr-agent[6391]: Thread is down
Jun 20 12:53:04 Ubuntu18 otbr-agent[6391]: Check if Thread is up: OK
Jun 20 12:53:04 Ubuntu18 otbr-agent[6391]: Stop publishing service
Jun 20 12:53:04 Ubuntu18 otbr-agent[6391]: PSKc is not initialized
Jun 20 12:53:04 Ubuntu18 otbr-agent[6391]: Check if PSKc is initialized: OK
Jun 20 12:53:04 Ubuntu18 otbr-agent[6391]: Initialize OpenThread Border Router Agent: OK
Jun 20 12:53:04 Ubuntu18 otbr-agent[6391]: Border router agent started.
Jun 20 12:53:04 Ubuntu18 otbr-agent[6391]: [INFO]-CORE----: Notifier: StateChanged (0x00038200) [NetData PanId NetName ExtPanId]
Jun 20 12:53:04 Ubuntu18 otbr-agent[6391]: [INFO]-PLAT----: processNetifLinkEvent: OK
Jun 20 12:53:07 Ubuntu18 otbr-agent[6391]: [WARN]-PLAT----: Error decoding hdlc frame: Parse
darshan@Ubuntu18:~$ 
```
Note that NCP device is at /dev/ttyACM0 and not at ttyUSB0.
After that running it manually:
```

darshan@Ubuntu18:~$ otbr-agent -I wpan0 -d7 -v spinel+hdlc+uart:///dev/ttyACM0
otbr-agent[6810]: Running 0.2.0-a9acf4a-dirty
otbr-agent[6810]: Thread interface wpan0
darshan@Ubuntu18:~$ 
```
Still `sudo ot-ctl state` gives "OpenThread daemon is not running"

**Comment by iDarshan** [comment]
Looked at detailed logs of the otbr-agent service. It seems like its failing and keep restarting.
```

Jun 17 15:19:40 Ubuntu18 systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Jun 17 15:19:40 Ubuntu18 systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 26.
Jun 17 15:19:40 Ubuntu18 systemd[1]: Stopped Border Router Agent.
Jun 17 15:19:40 Ubuntu18 systemd[1]: Started Border Router Agent.
Jun 17 15:19:40 Ubuntu18 otbr-agent[2305]: Running 0.2.0-c111798
Jun 17 15:19:40 Ubuntu18 otbr-agent[2305]: Thread interface wpan0
Jun 17 15:19:42 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Jun 17 15:19:42 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jun 17 15:19:47 Ubuntu18 systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Jun 17 15:19:47 Ubuntu18 systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 27.
Jun 17 15:19:47 Ubuntu18 systemd[1]: Stopped Border Router Agent.
Jun 17 15:19:47 Ubuntu18 systemd[1]: Started Border Router Agent.
Jun 17 15:19:47 Ubuntu18 otbr-agent[2306]: Running 0.2.0-c111798
Jun 17 15:19:47 Ubuntu18 otbr-agent[2306]: Thread interface wpan0
Jun 17 15:19:49 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Jun 17 15:19:49 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jun 17 15:19:54 Ubuntu18 systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Jun 17 15:19:54 Ubuntu18 systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 28.
```

**Comment by bukepo** [comment]
It seems the RCP is not compatible with the daemon. Could you try building the RCP from the latest code?

**Comment by iDarshan** [comment]
RCP Firmware for nrf52840 is built from latest master branch. I also tried Firmware provided by Nordic SDK. No luck so far. Please try OTBR on Ubuntu 18.04 (64 bit) and nrf52840. You will observe the problem.

**Comment by TaTiTuTeKo** [comment]
@iDarshan, please make sure you are connecting to J3 connector of the PCA10056 board to your Ubuntu, and the SW9 switch is switched to 'USB', but not 'Li-Po or VDD'. That means, you need to use the 'Native' USB port of 52840, but not the USB port of the segger interface MCU at J2.

**Comment by iDarshan** [comment]
@TaTiTuTeKo I am following the guide in which the information you gave is there. So I am using the right connector.

**Comment by iDarshan** [comment]
I am observing that after build and install I don't see wpantund service running. I see otbr-agent, otbr-web and avadhi daemon running. Is that a cause of failure?
I also saw another issue filed for this problem at https://github.com/openthread/ot-br-posix/issues/214
Point 3 in that issue.

Please let me know what needs to be done here to make this work.

**Comment by iDarshan** [comment]
@bukepo Do you need more information or logs for this issue?

**Comment by bukepo** [comment]
From the logs you provided, the root cause is RCP is incompatible with otbr-agent. We just added backward compatibility to it. Could you try rebuild otbr-agent:

git pull origin master
git submodule update --init

**Comment by iDarshan** [comment]
@bukepo Just rebuilt the ot-br-posix after updating and installed. Rebooted the system. Still the same error. Following is the log of otbr-agent service:

```
darshan@Ubuntu18:~$ journalctl -u otbr-agent.service -n 20
-- Logs begin at Wed 2020-04-08 15:16:21 CDT, end at Wed 2020-06-24 23:01:06 CDT. --
Jun 24 23:00:49 Ubuntu18 otbr-agent[3009]: Running 0.2.0-f93719a
Jun 24 23:00:49 Ubuntu18 otbr-agent[3009]: Thread interface wpan0
Jun 24 23:00:51 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Jun 24 23:00:51 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jun 24 23:00:56 Ubuntu18 systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Jun 24 23:00:56 Ubuntu18 systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 25.
Jun 24 23:00:56 Ubuntu18 systemd[1]: Stopped Border Router Agent.
Jun 24 23:00:56 Ubuntu18 systemd[1]: Started Border Router Agent.
Jun 24 23:00:56 Ubuntu18 otbr-agent[3033]: Running 0.2.0-f93719a
Jun 24 23:00:56 Ubuntu18 otbr-agent[3033]: Thread interface wpan0
Jun 24 23:00:58 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Jun 24 23:00:58 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jun 24 23:01:03 Ubuntu18 systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Jun 24 23:01:03 Ubuntu18 systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 26.
Jun 24 23:01:03 Ubuntu18 systemd[1]: Stopped Border Router Agent.
Jun 24 23:01:03 Ubuntu18 systemd[1]: Started Border Router Agent.
Jun 24 23:01:04 Ubuntu18 otbr-agent[3057]: Running 0.2.0-f93719a
Jun 24 23:01:04 Ubuntu18 otbr-agent[3057]: Thread interface wpan0
Jun 24 23:01:06 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Jun 24 23:01:06 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
darshan@Ubuntu18:~$
```

 I also pulled openthread repo master branch to the latest and built nrf52840 firmware with the following command:
```
make -f examples/Makefile-nrf52840 BORDER_AGENT=1 BORDER_ROUTER=1 COMMISSIONER=1 \
  DHCP6_CLIENT=1 DHCP6_SERVER=1 JOINER=1 MAC_FILTER=1 REFERENCE_DEVICE=1 \
  UDP_FORWARD=1 USB=1
```

**Comment by bukepo** [comment]
> @bukepo Just rebuilt the ot-br-posix after updating and installed. Rebooted the system. Still the same error. Following is the log of otbr-agent service:
> 
> 
> 
> ```
> 
> darshan@Ubuntu18:~$ journalctl -u otbr-agent.service -n 20
> 
> -- Logs begin at Wed 2020-04-08 15:16:21 CDT, end at Wed 2020-06-24 23:01:06 CDT. --
> 
> Jun 24 23:00:49 Ubuntu18 otbr-agent[3009]: Running 0.2.0-f93719a
> 
> Jun 24 23:00:49 Ubuntu18 otbr-agent[3009]: Thread interface wpan0
> 
> Jun 24 23:00:51 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
> 
> Jun 24 23:00:51 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
> 
> Jun 24 23:00:56 Ubuntu18 systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
> 
> Jun 24 23:00:56 Ubuntu18 systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 25.
> 
> Jun 24 23:00:56 Ubuntu18 systemd[1]: Stopped Border Router Agent.
> 
> Jun 24 23:00:56 Ubuntu18 systemd[1]: Started Border Router Agent.
> 
> Jun 24 23:00:56 Ubuntu18 otbr-agent[3033]: Running 0.2.0-f93719a
> 
> Jun 24 23:00:56 Ubuntu18 otbr-agent[3033]: Thread interface wpan0
> 
> Jun 24 23:00:58 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
> 
> Jun 24 23:00:58 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
> 
> Jun 24 23:01:03 Ubuntu18 systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
> 
> Jun 24 23:01:03 Ubuntu18 systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 26.
> 
> Jun 24 23:01:03 Ubuntu18 systemd[1]: Stopped Border Router Agent.
> 
> Jun 24 23:01:03 Ubuntu18 systemd[1]: Started Border Router Agent.
> 
> Jun 24 23:01:04 Ubuntu18 otbr-agent[3057]: Running 0.2.0-f93719a
> 
> Jun 24 23:01:04 Ubuntu18 otbr-agent[3057]: Thread interface wpan0
> 
> Jun 24 23:01:06 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
> 
> Jun 24 23:01:06 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
> 
> darshan@Ubuntu18:~$
> 
> ```
> 
> 
> 
>  I also pulled openthread repo master branch to the latest and built nrf52840 firmware with the following command:
> 
> ```
> 
> make -f examples/Makefile-nrf52840 BORDER_AGENT=1 BORDER_ROUTER=1 COMMISSIONER=1 \
> 
>   DHCP6_CLIENT=1 DHCP6_SERVER=1 JOINER=1 MAC_FILTER=1 REFERENCE_DEVICE=1 \
> 
>   UDP_FORWARD=1 USB=1
> 
> ```

Did you flashed RCP or NCP? The otbr-agent only works with RCP. The binary file is ot-rcp. Besides, since you built it with USB=1, you should connect the USB port instead of the jlink port. If it still not working, could you try building with USB=0 and use the jlink port instead?

**Comment by iDarshan** [comment]
@bukepo I cloned the ot-br-posix repo again. Seems like submodule update didn't work. And yes I am using RCP firmware as mentioned in the guide. After new repo build of ot-br-posix, otbr-agent worked for a while and crashed again. Here is the log:
```

darshan@Ubuntu18:~$ journalctl -u otbr-agent.service -n 20
-- Logs begin at Wed 2020-04-08 15:16:21 CDT, end at Thu 2020-06-25 11:25:26 CDT. --
Jun 25 11:25:16 Ubuntu18 otbr-agent[1745]: [INFO]-MAC-----: Sending Beacon Request
Jun 25 11:25:16 Ubuntu18 otbr-agent[1745]: [CRIT]-PLAT----: Write() at ../../third_party/openthread/repo/src/posix/platform/hdlc_interface.cpp:247: Inp
Jun 25 11:25:16 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=5/NOTINSTALLED
Jun 25 11:25:16 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jun 25 11:25:21 Ubuntu18 systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Jun 25 11:25:21 Ubuntu18 systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 3.
Jun 25 11:25:21 Ubuntu18 systemd[1]: Stopped Border Router Agent.
Jun 25 11:25:21 Ubuntu18 systemd[1]: Started Border Router Agent.
Jun 25 11:25:21 Ubuntu18 otbr-agent[4717]: Running 0.2.0-f93719a
Jun 25 11:25:21 Ubuntu18 otbr-agent[4717]: Thread interface wpan0
Jun 25 11:25:21 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 25 11:25:21 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jun 25 11:25:26 Ubuntu18 systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Jun 25 11:25:26 Ubuntu18 systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 4.
Jun 25 11:25:26 Ubuntu18 systemd[1]: Stopped Border Router Agent.
Jun 25 11:25:26 Ubuntu18 systemd[1]: Started Border Router Agent.
Jun 25 11:25:26 Ubuntu18 otbr-agent[4737]: Running 0.2.0-f93719a
Jun 25 11:25:26 Ubuntu18 otbr-agent[4737]: Thread interface wpan0
Jun 25 11:25:26 Ubuntu18 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 25 11:25:26 Ubuntu18 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
lines 1-21/21 (END)
```

**Comment by G-Pereira** [comment]
I am having the same issue and I would like to share te build switches I am using. Maybe that's the culprit.

`make -f examples/Makefile-nrf52840 BORDER_AGENT=1 BORDER_ROUTER=1 COMMISSIONER=1 UDP_FORWARD=1 USB=1 BOOTLOADER=USB LINK_RAW=1`

Is this ok?

**Comment by G-Pereira** [comment]
By the way I am running the otbr on a orangePi running Armbian Buster (Debian Buster) and the problem is the same

**Comment by G-Pereira** [comment]
I'm trying to gather as much information as I can, here is a list: 
- nrf52840 (E73 module from ebyte) connected via USB and powered by OrangePi Zero LTS pins
- Permissions: `crw-rw---- 1 root dialout 166, 0 Jun 25 22:23 /dev/ttyACM0`
- groups user belongs to: `tty disk dialout sudo audio video plugdev games users systemd-journal input netdev ssh`
- ot-br-posix commit: f93719a08c9ff2aee7295c6297c8d54b525656ca
- openthread commit: 2ebdf874eb874ccb2d30c96c171878f1ce607c17
- flashed nrf52840 with RCP with the following switches `BORDER_AGENT=1 BORDER_ROUTER=1 COMMISSIONER=1 UDP_FORWARD=1 USB=1` (different than earlier post)
- script used to configure OrangePi -> [setup-otbr.txt](https://github.com/openthread/ot-br-posix/files/4834156/setup-otbr.txt)

**Comment by bukepo** [comment]
From the logs, It seems the RCP crashed. I remember there are some unstable issue in USB=1 mode. Could you try build the RCP according to the link?
https://github.com/openthread/openthread/tree/master/src/posix#nrf52840

Please use USB=0 mode, only connect the jlink port. And could you share the hardware version of your nrf52840?

**Comment by G-Pereira** [comment]
Thank you for the suggestion. What are the default UART pins in the Px.xx format?

**Comment by G-Pereira** [comment]
@iDarshan I don't know the board you're using but maybe you can do the same as me and use a USB to serial converter. It seems that USB as a serial transport is being dropped support... Even in Nordic's Infocenter, they mention that it's preferable to use either UART or SPI.

**Comment by G-Pereira** [comment]
Well, I am getting exactly the same issue and the exit code is: `(code=exited, status=6)`

**Comment by jwhui** [comment]
> Well, I am getting exactly the same issue when using UART and the exit code is: `(code=exited, status=6)`

@G-Pereira , are you able to test with a Raspberry Pi 3B+ running Raspbian Stretch Lite and an [nRF52840 USB Dongle](https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52840-Dongle)? That configuration seems to work for me. It would be useful to see if some difference in environment is contributing to the issue.

**Comment by jwhui** [comment]
> @bukepo I cloned the ot-br-posix repo again. Seems like submodule update didn't work. And yes I am using RCP firmware as mentioned in the guide. After new repo build of ot-br-posix, otbr-agent worked for a while and crashed again.

@iDarshan , can you provide more detail on how you are exercising the Thread network? That would help us reproduce the issue.

**Comment by G-Pereira** [comment]
> > Well, I am getting exactly the same issue when using UART and the exit code is: `(code=exited, status=6)`
> 
> @G-Pereira , are you able to test with a Raspberry Pi 3B+ running Raspbian Stretch Lite and an [nRF52840 USB Dongle](https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52840-Dongle)? That configuration seems to work for me. It would be useful to see if some difference in environment is contributing to the issue.

I don't have a Raspberry for the time being.



> > @bukepo I cloned the ot-br-posix repo again. Seems like submodule update didn't work. And yes I am using RCP firmware as mentioned in the guide. After new repo build of ot-br-posix, otbr-agent worked for a while and crashed again.
> 
> @iDarshan , can you provide more detail on how you are exercising the Thread network? That would help us reproduce the issue.

I am trying to configure the border router as the first node on my network so no more devices are involved

**Comment by G-Pereira** [comment]
> > Well, I am getting exactly the same issue when using UART and the exit code is: `(code=exited, status=6)`
> 
> @G-Pereira , are you able to test with a Raspberry Pi 3B+ running Raspbian Stretch Lite and an [nRF52840 USB Dongle](https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52840-Dongle)? That configuration seems to work for me. It would be useful to see if some difference in environment is contributing to the issue.

What a second @bukepo just said here that USB is unstable at the moment, how come?

**Comment by jwhui** [comment]
> > @G-Pereira , are you able to test with a Raspberry Pi 3B+ running Raspbian Stretch Lite and an [nRF52840 USB Dongle](https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52840-Dongle)? That configuration seems to work for me. It would be useful to see if some difference in environment is contributing to the issue.
> 
> What a second @bukepo just said here that USB is unstable at the moment, how come?

@G-Pereira , FWIW, the nRF52840 USB Dongle seems to work well enough for me for testing. I agree that in a production system, SPI would be preferred.

**Comment by G-Pereira** [comment]
> > > @G-Pereira , are you able to test with a Raspberry Pi 3B+ running Raspbian Stretch Lite and an [nRF52840 USB Dongle](https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52840-Dongle)? That configuration seems to work for me. It would be useful to see if some difference in environment is contributing to the issue.
> > 
> > 
> > What a second @bukepo just said here that USB is unstable at the moment, how come?
> 
> @G-Pereira , FWIW, the nRF52840 USB Dongle seems to work well enough for me for testing. I agree that in a production system, SPI would be preferred.

That's nice to know! At the moment I've trashed my custom board because of a design issue I've made. So I will gather what I've learned to the second iteration and will have your SPI suggestion in mind. Thanks for the support.
To sum it up, I would like to ask you to disregard the issues I've reported since I've noticed that I had other problems with my board.
Thank you all for the support!

**Comment by iDarshan** [comment]
> > @bukepo I cloned the ot-br-posix repo again. Seems like submodule update didn't work. And yes I am using RCP firmware as mentioned in the guide. After new repo build of ot-br-posix, otbr-agent worked for a while and crashed again.
> 
> @iDarshan , can you provide more detail on how you are exercising the Thread network? That would help us reproduce the issue.

@jwhui The only difference in standard setup mentioned on openthread.io and mine is that I am using a PC running Ubuntu 18.04 (64 bit) instead of RPi3. I have also tried the same steps with RPi4 instead of RPi3. Same results. otbr-agent is starting for some time and then crashes, maybe because PC goes to sleep. Please let me know if you need more information.

**Comment by rcrouthamel** [comment]
> > Well, I am getting exactly the same issue when using UART and the exit code is: `(code=exited, status=6)`
> 
> @G-Pereira , are you able to test with a Raspberry Pi 3B+ running Raspbian Stretch Lite and an [nRF52840 USB Dongle](https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52840-Dongle)? That configuration seems to work for me. It would be useful to see if some difference in environment is contributing to the issue.

FWIW, I successfully built a fresh system today RPi3B+ Raspbian Buster with an nRF52840 Dongle (v1.2.0). https://github.com/openthread/ot-br-posix/commit/ad268823f2f5a019b93741da462fa74beabea21f 
Below is the step-by-step (sorry) written like a hardware engineer.  I used much fewer switches:

@jwhui I couldn't build the latest ot-br-posix on Raspbian Stretch Lite anymore

I second the use of SPI in production, having seen too many spurious disconnects with cdc-acm.  I build this system to kick the tires on otbr-agent while I figure out how to get SPI working correctly with this version.

> ***Prepared new v1.2.0 nRF52840 Dongle using Ubuntu 16.04 on WSL***
git clone https://github.com/openthread/openthread
cd openthread
./script/bootstrap
./bootstrap
make -f examples/Makefile-nrf52840 USB=1 BOOTLOADER=USB
copied file to Windows and programmed with nRF Connect programmer
Do not plug the dongle into the RPI yet
***SD Card - Fresh Raspbian Buster***
change pw
setup wifi country
change locale,keyboard,timezone to US Eastern
enable ssh
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git
git clone https://github.com/openthread/ot-br-posix
cd ot-br-posix
./script/bootstrap
./script/setup
ls /dev/tty*
(plugged in dongle)
ls /dev/tty*
(new device is at /dev/ttyACM0)
sudo nano /etc/default/otbr-agent
(confirmed path is correct already)
sudo reboot
login
(confirmed services are running:  avahi-daemon.service, otbr-agent.service, otbr-web.service)
sudo ot-ctl state returns:
	disabled
	Done
Connect laptop wifi to SSID = BorderRouter-AP; Password = 12345678
Operate the border router using the web GUI
-done-

**Comment by jwhui** [comment]
> @jwhui I couldn't build the latest ot-br-posix on Raspbian Stretch Lite anymore

@rcrouthamel , interesting. I just tried building on Raspbian Stretch Lite on latest master (ad26882) and everything worked as expected.

My steps on a fresh Raspbian Stretch Lite image:
```
sudo apt-get update
sudo apt-get install git
git clone https://github.com/openthread/ot-br-posix
cd ot-br-posix
./script/bootstrap
./script/setup
sudo reboot
```

Can you provide any details on what failed for you?

**Comment by rcrouthamel** [comment]
@jwhui Hmm, I'll try again first thing tomorrow.  Come to think of it, I did run the installation for our cellular manager before ot-br-posix, but I can't see how that would be a problem.  Should I be planning to stick with Stretch for Thread Group compliance reasons?

**Comment by jwhui** [comment]
> Should I be planning to stick with Stretch for Thread Group compliance reasons?

@rcrouthamel , Stretch is simply our reference platform and what we have tested in the past and is what we recommend in the Border Router Setup Guide, but there is reason otherwise to stick with Stretch. If something else works for you, feel free to use that.

**Comment by rcrouthamel** [comment]
> @jwhui Hmm, I'll try again first thing tomorrow. Come to think of it, I did run the installation for our cellular manager before ot-br-posix, but I can't see how that would be a problem. Should I be planning to stick with Stretch for Thread Group compliance reasons?

@jwhui Sorry, my bad.  I built https://github.com/openthread/ot-br-posix/commit/ad268823f2f5a019b93741da462fa74beabea21f today on Stretch Lite with no issues. I'll stick with Stretch while I work out my SPI issues (at least).

**Comment by iDarshan** [comment]
> > Should I be planning to stick with Stretch for Thread Group compliance reasons?
> 
> @rcrouthamel , Stretch is simply our reference platform and what we have tested in the past and is what we recommend in the Border Router Setup Guide, but there is reason otherwise to stick with Stretch. If something else works for you, feel free to use that.

@jwhui Raspbian stretch is old. Not getting newer releases of it. Also its not supported on RPi4. So why to stick with old platform and not support the latest one? For broader use of this border router code, it should support various new platforms and build systems. Should be able to build on a custom Linux distro using Yocto as a build system, just an example. That will make porting of this border router on newer platform much easier.

**Comment by jwhui** [comment]
> @jwhui Raspbian stretch is old. Not getting newer releases of it. Also its not supported on RPi4. So why to stick with old platform and not support the latest one? For broader use of this border router code, it should support various new platforms and build systems. Should be able to build on a custom Linux distro using Yocto as a build system, just an example. That will make porting of this border router on newer platform much easier.

@iDarshan , the latest versions of Raspbian or Raspberry Pi OS are not stable. One example is the [USB problems on Raspberry Pi 4](https://groups.google.com/d/msg/openthread-users/zXiIQnIZ4Ys/ggTpf2yXCgAJ). Another example is when Buster first came out, there were some incompatibilities between network manager and the Wi-Fi driver.

Like I said in https://github.com/openthread/ot-br-posix/issues/486#issuecomment-652210022, Stretch is simply something we've tested and is known to work, which serves as a useful reference for those trying to debug issues. If other (newer) distributions work for you, go ahead and use that. We can look into updating the Border Router Setup Guide once we've validated a given reference platform.

**Comment by iDarshan** [comment]
@jwhui So how to use this border router on Linux machine which does not use aptutils or brew for dependency package installation? In the guide it is said that it can be used on any Linux machine.

**Comment by jwhui** [comment]
> @jwhui So how to use this border router on Linux machine which does not use aptutils or brew for dependency package installation? In the guide it is said that it can be used on any Linux machine.

@iDarshan , an arbitrary Linux-based platform has far too much variability. A "getting started" guide needs to rely on some kine of reference platform. For us, that is currently Raspberry Pi 3B+ and Docker. Where the guide mentions "any Linux-based machine" that was in reference to Docker.

That said, this is an open-source, community-based project. We welcome all contributions! If there is a reference platform you are passionate about, please feel free to contribute it. For example, the BeagleBone platform support in OTBR was a community contribution.

**Comment by jwhui** [comment]
Closing stale issue.
