### ISSUE TITLE
OTBR is broadcasting MLDv2 messags in the Thread network

### ISSUE THREAD

**Issue by simonlingoogle** [openthread/ot-br-posix#488]
**Describe the bug** 
OTBR is broadcasting MLDv2 messags in the Thread network. (see the pcap)

**To Reproduce**

1. Git commit id: master (8a7c53b9faeeef96a8a7c4fb1de364cf00acf365)
2. IEEE 802.15.4 hardware platform: Raspberry Pi3 (otbr-agent) + OT RCP

**Expected behavior**
OTBR should **NOT** broadcast MLDv2 messages in the Thread network.

**Console/log output**

[Pass_OpenThread_9.2.1_Commissioner_R2.0.0_2020_06_22-16_01_06_Ch-23.pcapng.zip](https://github.com/openthread/ot-br-posix/files/4812100/Pass_OpenThread_9.2.1_Commissioner_R2.0.0_2020_06_22-16_01_06_Ch-23.pcapng.zip) 
**MasterKey: aabbccddeeff00112233445566778899**

**Comment by jwhui** [comment]
Resolved by https://github.com/openthread/openthread/pull/7343
