### ISSUE TITLE
[build] builds failing on master as of bd8b7fc

### ISSUE THREAD

**Issue by jwhui** [openthread/ot-br-posix#493]
**Describe the bug** A clear and concise description of what the bug is.

Travis and Docker Hub builds are failing as of bd8b7fc.

**Comment by bukepo** [comment]
The problem is USER is not set on docker hub. And I didn't find the issue trying to address in #489 on my raspberry PI. I'm going to revert the change.

**Comment by simonlingoogle** [comment]
> The problem is USER is not set on docker hub. And I didn't find the issue trying to address in #489 on my raspberry PI. I'm going to revert the change.


It's actually a known issue of ninja: https://github.com/ninja-build/ninja/issues/1302
I will seek for a better fix if necessary.
