### ISSUE TITLE
Installation of OTBR using AP/WiFi setup does not create required files in /usr/sbin

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#496]
**Describe the bug** A clear and concise description of what the bug is.
Executable files in /usr/sbin do not exist after a clean (fresh etch of the OS) raspi installed with the OTBR if the installation is run using the command "sudo ./script/setup".  

However, "sudo NETWORK_MANAGER=0 ./script/setup" does install everything properly.

**To Reproduce** Information to reproduce the behavior, including:
Create a clean etch of a raspi with Stretch.  Install with the WiFi AP.

1. Git commit id
pi@rpi2:~/ot-br-posix $ git show
commit f93719a08c9ff2aee7295c6297c8d54b525656ca
Author: Yakun Xu <xyk@google.com>
Date:   Wed Jun 24 13:28:11 2020 +0800

    [ot] update OpenThread to support older RCP (#495)

2. IEEE 802.15.4 hardware platform
Not relevant

3. Build steps
Etch raspibian Stretch OS
sudo apt-get update
sudo apt-get install git
git clone https://github.com/openthread/ot-br-posix
sudo ./script/bootstrap
sudo ./script/setup

4. Network topology
Not relevant

**Expected behavior** A clear and concise description of what you expected to happen.
ot-ctl should exist in /usr/sbin (also otbr-agent and otbr-web, I'm not finding any of them post install)

**Console/log output** If applicable, add console/log output to help explain your problem.
pi@rpi2:~/ot-br-posix $ which ot-ctl
pi@rpi2:~/ot-br-posix $ sudo ot-ctl state
sudo: ot-ctl: command not found
pi@rpi2:~/ot-br-posix $ ls /usr/sbin/o*
ls: cannot access '/usr/sbin/o*': No such file or directory

**Additional context** Add any other context about the problem here.

**Comment by bukepo** [comment]
Could you try cleaning very thing and run scripts **without sudo**? The scripts calls sudo when necessary. Run the whole script with sudo can be problematic. If it still fails, could you paste the output of those scripts?

**Comment by JaneFromSilabs** [comment]
Sure.  Here is that output.  It behaved the same way for me.  

[output.txt](https://github.com/openthread/ot-br-posix/files/4839174/output.txt)

**Comment by jwhui** [comment]
> Sure. Here is that output. It behaved the same way for me.
> 
> [output.txt](https://github.com/openthread/ot-br-posix/files/4839174/output.txt)

@JaneFromSilabs , from the log, it appears that the process is failing in [`network_manager_install`](https://github.com/openthread/ot-br-posix/blob/f93719a08c9ff2aee7295c6297c8d54b525656ca/script/setup#L60) and not actually progressing to `otbr_install`.

Can you confirm that you are using:

1. Raspberry Pi 3B+ (not 3B or any other version)?

1. The Raspberry Pi is connected via Ethernet and you are connected via Ethernet? In other words, you should not be using the Wi-Fi interface.

1. Distribution is Raspbian Stretch Lite (not Raspbian Stretch Desktop)?

Thanks.

**Comment by jwhui** [comment]
@JaneFromSilabs , for what it's worth, I just tested clean OTBR install with latest master (f93719a) and it worked as expected for me.

**Comment by JaneFromSilabs** [comment]
1.  I am using a Raspberry Pi 3+ v1.2
2.  I am using Ethernet
3.  I am using Stretch Lite

This device that is failing claims a 2014 copyright.  Maybe this is just a simple hardware failure?  I'll try to set up another Pi to test.  I'm thinking that maybe something is going wrong with the WiFi interface itself since the NETWORK_MANAGER=0 installation works just fine on this device.

**Comment by JaneFromSilabs** [comment]
Here is the device information:
![IMG_3084](https://user-images.githubusercontent.com/58004715/86034525-c07acf00-ba08-11ea-8459-92f1988c4912.jpg)

**Comment by jwhui** [comment]
@JaneFromSilabs , you are running "Raspberry Pi B+" not "Raspberry Pi 3 B+". Because "Raspberry Pi B+" does not have Wi-Fi, the current Network Manager install will fail.

See https://en.wikipedia.org/wiki/Raspberry_Pi for more information on different Raspberry Pi versions.

**Comment by JaneFromSilabs** [comment]
Oh, sorry about that.  I guess I just assumed it was a 3.  I can't believe we have any hardware this old to be honest.  I'll swap that out. 

The good news is that the regular install worked on this old B+!
