### ISSUE TITLE
otbr-agent won't start with SPI RCP

### ISSUE THREAD

**Issue by rcrouthamel** [openthread/ot-br-posix#502]
**Describe the bug** A clear and concise description of what the bug is.
otbr-agent.service exits with "status=2/INVALIDARGUMENT" when built and configured for SPI

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
https://github.com/openthread/ot-br-posix/commit/ad268823f2f5a019b93741da462fa74beabea21f
2. IEEE 802.15.4 hardware platform
> Nordic nRF52840 DK (PCA10056v1.0.0), prepared as follows:
> git clone https://github.com/openthread/openthread
> cd openthread
> ./script/bootstrap
> ./bootstrap
> make -f examples/Makefile-nrf52840 NCP_SPI=1
> arm-none-eabi-objcopy -O ihex output/nrf52840/bin/ot-rcp ot-rcp.hex
> copied file ot-rcp.hex to Windows and programmed board using nRF Connect programmer
> Connected DK to rPi 3B+ as follows (reference https://github.com/openthread/openthread/blob/master/examples/platforms/nrf528xx/nrf52840/transport-config.h)
> nRF VDD to rPi.1 (3.3V)
> nRF GND to rPi.9 (GND)
> (MOSI) nRF_P0.4 to rPi.19 (SPI0.MOSI)
> (MISO) nRF_P0.28 to rPi.21 (SPI0.MISO)
> (SCK) nRF_P0.3 to rPi.23 (SPI0.SCLK)
> (CSN) nRF_P0.29 to rPI.26 (SPI0.CE1)
> (IRQ) nRF_P0.30 to rPi.40 (GPIO21)
> nRF nRESET to rPI.38 (GPIO20)

3. Build steps
> SD Card - Fresh Raspbian 9 Stretch Lite, installed in RPI 3B+
> change pw, setup wifi country, change locale,keyboard,timezone, etc using raspi-config
> enable spi
> enable ssh
> sudo apt-get update
> sudo apt-get upgrade
> sudo apt-get install git
> git clone https://github.com/openthread/ot-br-posix
> cd ot-br-posix
> git checkout ad26882
> export OTBR_OPTIONS="-DOT_POSIX_CONFIG_RCP_BUS=SPI"
> mkdir /home/pi/logs
> touch /home/pi/logs/setup.log
> echo "setup on 1Jul2020 with Raspbian Stretch and SPI RCP" &? /home/pi/logs/setup.log
> ./script/bootstrap 2>&1 | tee /home/pi/logs/setup.log
> ./script/setup 2>&1 | tee /home/pi/logs/setup.log
> sudo nano /etc/default/otbr-agent
> (replace line with:
> OTBR_AGENT_OPTS="-I wpan0 spinel+spi:///dev/spidev0.1?gpio-int-device=/dev/gpiochip0&gpio-int-line=21&gpio-reset-dev=/dev/gpiochip0&gpio-reset-line=20&no-reset=1&spi-speed=1000000"
> )
NOTE:  see bootstrap and build output in file setup.log, attached.
4. Network topology
Border Router with SPI RCP only.

**Expected behavior** A clear and concise description of what you expected to happen.
'sudo ot-ctl state' should output: " idle, Done" and otbr-agent.service should be running.
**Console/log output** If applicable, add console/log output to help explain your problem.
sudo ot-ctl state' outputs: "OpenThread daemon is not running."
journalctl -u otbr-agent.service -n 20
-- Logs begin at Thu 2016-11-03 13:16:43 EDT, end at Wed 2020-07-01 16:32:00 EDT. --
Jul 01 16:28:04 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jul 01 16:28:09 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Jul 01 16:28:09 raspberrypi systemd[1]: Stopped Border Router Agent.
Jul 01 16:28:09 raspberrypi systemd[1]: Started Border Router Agent.
Jul 01 16:28:09 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 01 16:28:09 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Jul 01 16:28:09 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jul 01 16:28:14 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Jul 01 16:28:14 raspberrypi systemd[1]: Stopped Border Router Agent.
Jul 01 16:28:14 raspberrypi systemd[1]: Started Border Router Agent.
Jul 01 16:28:14 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 01 16:28:14 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Jul 01 16:28:14 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jul 01 16:28:19 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Jul 01 16:28:19 raspberrypi systemd[1]: Stopped Border Router Agent.
Jul 01 16:28:19 raspberrypi systemd[1]: Started Border Router Agent.
Jul 01 16:28:19 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 01 16:28:19 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Jul 01 16:28:19 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Jul 01 16:28:21 raspberrypi systemd[1]: Stopped Border Router Agent.
**Additional context** Add any other context about the problem here.
[setup.log](https://github.com/openthread/ot-br-posix/files/4860829/setup.log)

**Comment by bukepo** [comment]
@rcrouthamel I'm trying locally, could you upload otbr-agent logs?

otbr-agent -d7 -v -I wpan0 'spinel+spi:///dev/spidev0.1?gpio-int-device=/dev/gpiochip0&gpio-int-line=21&gpio-reset-dev=/dev/gpiochip0&gpio-reset-line=20&no-reset=1&spi-speed=1000000'

**Comment by rcrouthamel** [comment]
Yes!  Editing `gpio-reset-dev` to `gpio-reset-device` per @bukepo changed exit code from 2/INVALIDARGUMENT to 6/NOTCONFIGURED when used with an nRF52840 DK programmed connected as described above.   When same is used on a custom board (Pi HAT) used previously as an RCP with wpantund, otbr-agent starts successfully and Thread is operational.

I must have done something wrong in configuring or connecting the nRF52840 DK.  I will return to that setup, enable logs and report back here,

Did I miss any build flags for the RCP on the nRF52840 DK?  I only used "NCP_SPI=1".

**Comment by rcrouthamel** [comment]
I re-flashed the nRF52840 DK with the same hex I thought I used before and it is working now (I am chalking this up to user error).  It appears the only real problem was with the gpio-reset-device parameter typo.

Suggest the output from '$ sudo otbr-agent --help' should be corrected, both for the parameter typo above and to update the comments related to 'sysfx-exported GPIO' so they refer to chardev kernel GPIO instead.

**Comment by rcrouthamel** [comment]
Issue resolved by passing correct parameters into otbr-agent at start-up.
