### ISSUE TITLE
[route] advertisement Thread on-mesh prefixes

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-br-posix#504]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.
External network doesn't know Thread's on-mesh prefix.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Use radvd to advertise Thread's on-mesh prefix to external network.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
* Manually configure, this is not user friendly.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by jwhui** [comment]
Closing stale issue.
