### ISSUE TITLE
Multicast pings to ff03 receive response from OTBR ALOC rather than OTBR RLOC.  Is this intended?

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#527]
**Describe the bug** A clear and concise description of what the bug is.
Multicast pings to ff03 receive response from OTBR ALOC rather than OTBR RLOC.  Is this intended behavior for some reason?  I expected the BR to use the RLOC as it's source address.

**To Reproduce** Information to reproduce the behavior, including:
Send a ping to ff03::1 where a BR might respond.  Check the source address of the response.

1. Git commit id - commit a69a9d5c82d25b6d3c6ddd5ac29d80676b34465f
2. IEEE 802.15.4 hardware platform - BRD4161A (Silabs)
3. Build steps - As documented
4. Network topology - 2 node network with OTBR and SoC running ot-cli-ftd

**Expected behavior** A clear and concise description of what you expected to happen.
I expected to receive a ping response sourced from the RLOC, but I am getting them from the ALOC instead.  This seems odd to me and I wanted to know if this is intended behavior.

**Console/log output** If applicable, add console/log output to help explain your problem.
From the OTBR -
> ipaddr
2001:22:0:0:a215:6044:acc9:2a02
fdde:ad03:0:0:c7ed:e129:1bf1:1eb4
fdde:ad00:dead:beef:1b89:882c:1450:b79b
fd00:df4:6000:0:0:ff:fe00:fc34
fd00:df4:6000:0:0:ff:fe00:fc00
fd00:df4:6000:0:0:ff:fe00:1800
fd00:df4:6000:0:e4f1:f97f:ef39:9382
fe80:0:0:0:7003:587c:5fca:11af
Done
> ipaddr rloc
fd00:df4:6000:0:0:ff:fe00:1800
Done

From the soc - 
ping ff03::1 16 2 3
Done
24 bytes from fd00:df4:6000:0:0:ff:fe00:fc34: icmp_seq=86 hlim=64 time=39ms

**Additional context** Add any other context about the problem here.

**Comment by jwhui** [comment]
@JaneFromSilabs , thanks for raising this issue.

ICMPv6 Echo processing is implemented by the Linux kernel. To avoid using the IPv6 anycast address as an IPv6 source address, I think we need to do some extra configuration to tell the Linux kernel as such.

@bukepo , thoughts on marking the address as an anycast address when configuring on Linux network interface?

**Comment by bukepo** [comment]
This needs rewrite the mapping address code in netif.cpp with the netlink API. I'll submit PR soon.

**Comment by JaneFromSilabs** [comment]
Thank you all very much!

**Comment by bukepo** [comment]
I couldn't add anycast address to an interface. `sudo strace ip addr add anycast fdde:ad00:beef::ff:fe00:fc11 dev wpan0` gives invalid argument error. I didn't find anycast examples on Linux. I need more time to investigate the support of anycast on Linux.

**Comment by romacdon** [comment]
Hi @bukepo, just curious, any progress on this issue?

**Comment by bukepo** [comment]
Sorry to update. This issue was fixed. Could you try it out?

**Comment by romacdon** [comment]
@JaneFromSilabs is going to try this out an let you know @bukepo

**Comment by bukepo** [comment]
any update?

**Comment by JaneFromSilabs** [comment]
@bukepo Yep, this works fine now.  Thank you!
