### ISSUE TITLE
Partial table of ot-ctl commands with bigger results

### ISSUE THREAD

**Issue by d1ee** [openthread/ot-br-posix#529]
**Describe the bug** A clear and concise description of what the bug is.
`sudo ot-ctl neighbor table` returns a partial table and the command hangs.
`sudo ot-ctl router table` has the same issue.

```
$ sudo ot-ctl neighbor table
| Role | RLOC16 | Age | Avg RSSI | Last RSSI |R|S|D|N| Extended MAC     |
+------+--------+-----+----------+-----------+-+-+-+-+------------------+
|   C  | 0x8805 |  78 |      -68 |       -68 |1|1|1|1| 769ddd4f9f25dee8 |
|   C  | 0x8806 |  72 |      -65 |       -65 |1|1|1|1| 9a3ec4b893b1d77e |
|   R  | 0x0400 |   3 |      -58 |       -59 |1|0|1|1| 265edb578a0f00eb |
|   R  | 0x1c00 |  13 |      -61 |       -60 |1|0|1|1| 72ce3d47688ef0a5 |
|   R  | 0x2000 |  12 |      -76 |       -76 |1|0|1|1| 5e161d5df4fc10c9 |
|   R  | 0x3c00 |  37 |      -66 |       -64 |1|0|1|1| 524055cd1e0fae34 |
|   R  | 0x4000 |  15 |      -68 |       -69 |1|0|1|1| b627fb5a69290c07 |
|   R  | 0x6000 |   9 |      -69 |       -72 |1|0|1|1| 46cd2da769eafa55 |
|   R  | 0x6c00 |  22 |      -66 |       -70 |1|0|1|1| 7e8eb39980012592 |
|   R  | 0x7400 |  13 |      -78 |       -78 |1|0|1|1| de653b7f48fb4b20 |
|   R  | 0x8000 |  11 |      -54 |       -51 |1|0|1|1| 762dff83bb803860 |
|   R  | 0x8400 |  36 |      -57 |       -56 |1|0
```

```
$ sudo ot-ctl router table
| ID | RLOC16 | Next Hop | Path Cost | LQ In | LQ Out | Age | Extended MAC     |
+----+--------+----------+-----------+-------+--------+-----+------------------+
|  1 | 0x0400 |       15 |         1 |     3 |      3 |   8 | 265edb578a0f00eb |
|  7 | 0x1c00 |       27 |         1 |     3 |      3 |  18 | 72ce3d47688ef0a5 |
|  8 | 0x2000 |       59 |         1 |     3 |      3 |  17 | 5e161d5df4fc10c9 |
| 15 | 0x3c00 |       59 |         1 |     3 |      3 |   4 | 524055cd1e0fae34 |
| 16 | 0x4000 |        1 |         1 |     3 |      3 |  19 | b627fb5a69290c07 |
| 24 | 0x6000 |        7 |         1 |     3 |      3 |  14 | 46cd2da769eafa55 |
| 27 | 0x6c00 |       15 |         1 |     3 |      3 |  26 | 7e8eb39980012592 |
| 29 | 0x7400 |       61 |         1 |     3 |      3 |  17 | de653b7f48fb4b20 |
| 32 | 0x8000 |       47 |         1 |     3 |      3 |   1 | 762dff83bb803860 |
| 33 | 0x8400 |       16 |         1 |     3 |      3 |  40 | 5afc85db77daf3b8 |
| 34 | 0x8800 |       63 |         0 |  
```

I had to break the commands with ctrl-c.

Maybe it's just a buffer problem.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
a69a9d5c82d25b6d3c6ddd5ac29d80676b34465f without any modification

2. IEEE 802.15.4 hardware platform
- RaspberryPi 3B 
- RCP nrf52840 dongle

3. Build steps
I followed the usual build steps described in documentation.

4. Network topology
I have 18 devices including border router.
Border router is the leader.
There are 15 router.
There are 3 child devices, 2 are attached to the leader/border router and another child device to a router device.

**Expected behavior** A clear and concise description of what you expected to happen.
I expect to see all routers/children in the list.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by bukepo** [comment]
Hi @d1ee could you try if https://github.com/openthread/openthread/pull/5134 fixes the issue?

**Comment by d1ee** [comment]
> Hi @d1ee could you try if [openthread/openthread#5134](https://github.com/openthread/openthread/pull/5134) fixes the issue?

Hi, yes I can test it.

**Comment by d1ee** [comment]
@bukepo Maybe it's a stupid question, but what does the openthread project have to do with this issue? I mean, this is a border router project and I don't seen any direct connection to the openthread project, so I am clueless how to try out that branch.

**Comment by bukepo** [comment]
Hi @d1ee openthread is located at `third_party/openthread/repo`. You may cherry-pick that PR into your local openthread source at that path.

**Comment by d1ee** [comment]
@bukepo Thanks for your help.

It has an effect, but doesn't fix the problem. It prints only 10 devices, but I have more, and it also hangs.

```
$ sudo ot-ctl router table| ID | RLOC16 | Next Hop | Path Cost | LQ In | LQ Out | Age | Extended MAC     |
+----+--------+----------+-----------+-------+--------+-----+------------------+
|  1 | 0x0400 |       63 |         0 |     0 |      0 |  30 | 0000000000000000 |
|  7 | 0x1c00 |       63 |         0 |     0 |      0 |   4 | 0000000000000000 |
|  8 | 0x2000 |       63 |         0 |     3 |      3 |  29 | 5e161d5df4fc10c9 |
| 15 | 0x3c00 |       63 |         0 |     0 |      0 |  40 | 0000000000000000 |
| 16 | 0x4000 |       16 |         1 |     0 |      0 |   1 | 0000000000000000 |
| 24 | 0x6000 |       63 |         0 |     0 |      0 |  30 | 0000000000000000 |
| 27 | 0x6c00 |       63 |         0 |     0 |      0 |  31 | 0000000000000000 |
| 29 | 0x7400 |       63 |         0 |     0 |      0 |  27 | 0000000000000000 |
| 33 | 0x8400 |       63 |         0 |     0 |      0 |   3 | 0000000000000000 |
| 37 | 0x9400 |       63 |         0 |     0 |      0 |  31 | 0000000000000000 |
^C
```

I think the application stops when the output exceeds 1024 bytes. The first two examples was exactly 1024 bytes when I redirected the output to a file. The third one was 984 bytes, but it would have been exceeded 1024 bytes in the next line.

Maybe there is a internal buffer of size 1024 bytes used?

**Comment by jwhui** [comment]
@d1ee , the CLI output buffer is specified using [OPENTHREAD_CONFIG_CLI_UART_TX_BUFFER_SIZE](https://github.com/openthread/openthread/blob/b49ee0879ac1c264d947f2dc8c3bbc276f58f868/src/cli/cli_config.h#L65). Can you try increasing that value?

**Comment by d1ee** [comment]
@jwhui I tried, and it works after increasing the buffer size to 2048. Thanks :+1: 

```
$ sudo ot-ctl router table
| ID | RLOC16 | Next Hop | Path Cost | LQ In | LQ Out | Age | Extended MAC     |
+----+--------+----------+-----------+-------+--------+-----+------------------+
|  1 | 0x0400 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
|  7 | 0x1c00 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
|  8 | 0x2000 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 15 | 0x3c00 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 16 | 0x4000 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 24 | 0x6000 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 27 | 0x6c00 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 29 | 0x7400 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 33 | 0x8400 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 37 | 0x9400 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 40 | 0xa000 |       63 |         0 |     3 |      3 |   2 | 56150c452bd8dbd1 |
| 45 | 0xb400 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 47 | 0xbc00 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 54 | 0xd800 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |
| 59 | 0xec00 |       63 |         0 |     3 |      3 |   1 | 127de904c247299c |
| 61 | 0xf400 |       63 |         0 |     0 |      0 |  16 | 0000000000000000 |

Done
```

Thanks for your help @bukepo and @jwhui . I would like to contribute back, but I am not sure whether just increasing the buffer size should be enough.

**Comment by jwhui** [comment]
@d1ee , great to hear it is working now.

We also welcome your contributions! You can look to adding `OPENTHREAD_CONFIG_CLI_UART_TX_BUFFER_SIZE` to [src/posix/platform/openthread-core-posix-config.h](https://github.com/openthread/openthread/blob/master/src/posix/platform/openthread-core-posix-config.h) with a larger value (maybe even up to 8192 bytes). I think that should be sufficient.

**Comment by d1ee** [comment]
@jwhui Of course, I'll do it.

**Comment by d1ee** [comment]
Fixed by https://github.com/openthread/openthread/pull/5312
