### ISSUE TITLE
Attempts to bind a udp port to a multicast address results in the termination of the interactive CLI

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#538]
**Describe the bug** A clear and concise description of what the bug is.
Attempts to bind a udp port to a multicast address results in the termination of the interactive CLI.

**To Reproduce** Information to reproduce the behavior, including:
Attempt to bind a port using the udp cli command:
> sudo ot-ctl
> udp bind ff02::1 4242
pi@rpi1:~ $
(but the rest of the cli is working fine)

If I open first, I get further, but its still not working:
> udp open
Done
> udp bind ff02::1 4242
Error 1: Failed

1. Git commit id - ecc25701117fc99c6630584dc98294527a145f7d
2. IEEE 802.15.4 hardware platform - Silabs BRD4161A
3. Build steps - As documented on openthread.io
4. Network topology - [soc] ))  <thread/802.15.4> (( [otbr]

**Expected behavior** A clear and concise description of what you expected to happen.
I expected to bind that multicast address to the port.  This command functions as expected on the soc, just not on the otbr.  (Or if I need to use raspbian for these bindings then probably the command should not be accessible.)

**Console/log output** If applicable, add console/log output to help explain your problem.
> sudo ot-ctl
> udp bind ff02::1 4242
pi@rpi1:~ $

> udp open
Done
> udp bind ff02::1 4242
Error 1: Failed

**Additional context** Add any other context about the problem here.

**Comment by bukepo** [comment]
I don't think `bind()` supports binding to a multicast address. You should firstly subscribe to the multicast address and then bind to the special any address. I think the following commands should work(`ff02::1` is already subscribed by default):
```bash
> udp bind :: 4242
```

**Comment by jwhui** [comment]
@bukepo , should we simply return an error here rather than terminating the interactive CLI?

**Comment by bukepo** [comment]
I tried, but unable to reproduce the crash of interactive CLI. @JaneFromSilabs could you share a full procedure to reproduce the issue?

**Comment by JaneFromSilabs** [comment]
If there is anything I can do to help find this, please let me know.  This exiting behavior is still happening to me on the latest code, at least on these 2:
```> factoryreset
pi@rpi1:~ $ sudo ot-ctl
> udp bind ff02::1 4242
pi@rpi1:~ $
```
```
pi@rpi2:~ $ sudo ot-ctl
>
>
> udp bind ff02::1 4242
pi@rpi2:~ $
```
```
pi@rpi1:~/ot-br-posix $ git show
commit 274c11a371df6ffe0f7562359f31dd43af0fe871
Author: Jiacheng Guo <gjc@google.com>
Date:   Fri Sep 11 23:45:04 2020 +0800
```
```
pi@rpi2:~/ot-br-posix $ git show
commit 274c11a371df6ffe0f7562359f31dd43af0fe871
Author: Jiacheng Guo <gjc@google.com>
Date:   Fri Sep 11 23:45:04 2020 +0800
```

**Comment by JaneFromSilabs** [comment]
This doesn't seem to be a problem anymore.  I can no longer reproduce this on recent code.
