### ISSUE TITLE
coap documentation seems to be out of date

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#539]
**Describe the bug** A clear and concise description of what the bug is.
I'm trying to get coap/coaps wotking with the otbr.  Since the CLI commands weren't there like they are in ot-cli-ftd, I went looking for information.  I located this document:
https://openthread.io/guides/border-router/tools#coap-client

However, the link to configure.ac leads to a 404 error.  So, I went fishing for configure.ac files and found 2:
pi@rpi1:~/ot-br-posix $ find . -name configure.ac -print
./third_party/openthread/repo/configure.ac
./third_party/openthread/repo/third_party/nlbuild-autotools/repo/examples/config                                                                                                             ure.ac

Neither has a reference to --disable-examples as the document suggests.  Is this document out of date and if so, how should I be going about this?  Is there another document I should instead be following?  Thanks!

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id ecc25701117fc99c6630584dc98294527a145f7d
2. IEEE 802.15.4 hardware platform Silabs BRD4161A
3. Build steps - as documented
4. Network topology NA

**Expected behavior** A clear and concise description of what you expected to happen.
I'm just trying to find out how I should go about getting a little coap working.

**Console/log output** If applicable, add console/log output to help explain your problem.
pi@rpi1:~/ot-br-posix $ find . -name configure.ac -print
./third_party/openthread/repo/configure.ac
./third_party/openthread/repo/third_party/nlbuild-autotools/repo/examples/config                                                                                                             ure.ac

pi@rpi1:~/ot-br-posix $ find . -name configure.ac -print
./third_party/openthread/repo/configure.ac
./third_party/openthread/repo/third_party/nlbuild-autotools/repo/examples/config                                                                                                             ure.ac

pi@rpi1:~/ot-br-posix/third_party/openthread/repo $ grep disable-example configure.ac
pi@rpi1:~/ot-br-posix/third_party/openthread/repo $ 

**Additional context** Add any other context about the problem here.

**Comment by bukepo** [comment]
Thank you for pointing out this issue. This project doesn't use libcoap any more. I will update the document.

**Comment by bukepo** [comment]
Removed the outdate document.
