### ISSUE TITLE
ff32…::1 and ff33…::1 are working, but not ff32…::2 and ff33…::2

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#540]
**Describe the bug** A clear and concise description of what the bug is.
ping to FF32:40:<mesh local prefix>::2 gets no response from OTBR, but ::1 responds	

**To Reproduce** Information to reproduce the behavior, including:
From the soc (expecting the otbr to respond) -
> ipaddr
fd00:df4:6000:0:0:ff:fe00:d800
2001:22:0:0:7fd6:4697:b366:73f
fdde:ad03:0:0:c282:7967:95a:7ab9
fdde:ad00:dead:beef:ceb9:c649:2cc4:8757
fd00:df4:6000:0:1164:73e3:493d:a60b
fe80:0:0:0:7025:4a21:ee23:631
Done
>
> ping ff32:40:fd00:df4:6000:0::2 8 1 1000
Done
>
>
> ping ff32:40:fd00:df4:6000:0::1 8 1 1000
Done
>
> 16 bytes from fe80:0:0:0:6cb5:3884:acfc:8190: icmp_seq=42 hlim=64 time=36ms
>

1. Git commit id - ecc25701117fc99c6630584dc98294527a145f7d
2. IEEE 802.15.4 hardware platform - Silabs BRD4161A
3. Build steps - as documented
4. Network topology - [soc] ))  {802.15.4/thread}  (( [otbr]

**Expected behavior** A clear and concise description of what you expected to happen.
I expected a ping response on all routers as well as all devices for ff32 and ff33.

**Console/log output** If applicable, add console/log output to help explain your problem.
see above

**Additional context** Add any other context about the problem here.

**Comment by jwhui** [comment]
I believe this is expected behavior.

The Thread Specification defines an All Thread Nodes multicast address that has group id 1. However, the Thread Specification does not define an All Thread Routers multicast address that has group id 2. To ready all routers, you can try using the realm-local all routers multicast address `ff03::2`.

Hope that helps.

**Comment by JaneFromSilabs** [comment]
@jwhui Right you are.  We used to support this in our old thread stack but it isn't mandated.  Thanks!
