### ISSUE TITLE
Package could avoid a useless dependency if ot-ctl not linked against libncurses/libtinfo

### ISSUE THREAD

**Issue by sjlongland** [openthread/ot-br-posix#548]
Saw this comment from Debian's build system whilst building OpenThread Border Router (as a `.deb` package):

```
24-Aug-2020 15:56:51 | dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/openthread-border-router/usr/sbin/ot-ctl was not linked against libncurses.so.5 (it uses none of the library's symbols)
-- | --
24-Aug-2020 15:56:51 | dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/openthread-border-router/usr/sbin/ot-ctl was not linked against libtinfo.so.5 (it uses none of the library's symbols)
```

Apparently the `ot-ctl` command links against these two libraries, but doesn't use any functions from it.  `-Wl,--as-needed` in `LDFLAGS` can sometimes help with this sort of problem on `binutils`-based platforms (a flag that [Gentoo implemented system-wide](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed) some time back to great effect).

Low priority of course, since OpenThread Border Router works fine regardless of this problem and the libraries are likely to be needed by other installed programs anyway.  Of course, if there are plans to fully utilise `ncurses` in `ot-ctl`, then feel free to close this issue as a `wontfix`.

**Comment by jwhui** [comment]
Closing stale issue.
