### ISSUE TITLE
Configuring network outside of the interactive mode causes `commissioner start` command to exit interactive mode

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#560]
**Describe the bug** A clear and concise description of what the bug is.
If I configure everything  for this thread mesh in the same interactive session, I have no problem.  However, if I configure mostly command line and then enter the interactive mode just to start the commissioner, I exit the interactive mode and I'm returned to the raspi unix prompt.

**To Reproduce** Information to reproduce the behavior, including:
```sudo ot-ctl factoryreset
sudo ot-ctl channel 11
Done
sudo ot-ctl panid 0xabcd
Done
sudo ot-ctl networkname S1LABS7
Done
sudo ot-ctl masterkey 00112233445566778899aabbccddeeff
Done
sudo ot-ctl extpanid 000abcd000000000
Done
sudo ot-ctl pskc 67c0c203aa0b042bfb5381c47aef4d9e
Done
sudo ot-ctl prefix add 2001:1212::/96 paros med
Done
sudo ot-ctl ifconfig up
Done
sudo ot-ctl thread start
Done
sudo ot-ctl
>
> state
leader
Done
> commissioner start
Commissioner: petitioning
Done
> pi@rpi2:~ $ 
```
1. Git commit id
```pi@rpi1:~/ot-br-posix $ git show
commit 274c11a371df6ffe0f7562359f31dd43af0fe871
Author: Jiacheng Guo <gjc@google.com>
Date:   Fri Sep 11 23:45:04 2020 +0800
```
2. IEEE 802.15.4 hardware platform
Silabs 4161a

**Comment by gjc13** [comment]
The header file `include/openthread/ip6.h` says:

```
 55 #define OT_IP6_PREFIX_SIZE 8                           ///< Size of an IPv6 prefix (bytes)
 56 #define OT_IP6_PREFIX_BITSIZE (OT_IP6_PREFIX_SIZE * 8) ///< Size of an IPv6 prefix (bits)
```

Which means we do not support IP prefix longer than `xxx::/64`. This in turn leads to ioctl error when trying to update the address on the interface.

Modifying `2001:1212::/96` to `2001:1212::/64` resolves the issue. I'll also update the cli interface to reject such prefixes.

**Comment by JaneFromSilabs** [comment]
@gjc13 Thank you!  

You may want to close this as a duplicate of:
https://github.com/openthread/openthread/issues/5527
