### ISSUE TITLE
dbus-client test failed frequently

### ISSUE THREAD

**Issue by simonlingoogle** [openthread/ot-br-posix#569]
**Describe the bug** 
dbus-client test failed frequently in Github Actions. 

**Expected behavior**

dbus-client test passes. 

**Console/log output**

[logs_1429.zip](https://github.com/openthread/ot-br-posix/files/5287708/logs_1429.zip)

**Comment by gjc13** [comment]
From the log it looks like the `sleep` command is not correctly run. Still investigating what caused this.
