### ISSUE TITLE
Docker install does not work

### ISSUE THREAD

**Issue by krbvroc1** [openthread/ot-br-posix#570]
Not really a docker expert, but running

```
docker build --no-cache -t openthread/otbr -f etc/docker/Dockerfile .
```
fails with error messages about 

```
fatal: unable to access 'https://gitlab.com/xyz.git/': Problem with the SSL CA cert (path? access rights?)
```

Maybe certificates have been updated recently? My solution was to add 'ca-certificates' to the Dockerfile as follows and the build completed. Otherwise, none of the github repos  are downloaded and nothing builds.
 
```
# Required during build, could be removed
ENV OTBR_DOCKER_DEPS git ca-certificates
```

**Comment by gjc13** [comment]
Thanks for pointing out. PR submitted in https://github.com/openthread/ot-br-posix/pull/572 .
