### ISSUE TITLE
source ipv6 to send a Coap command not correct from BR

### ISSUE THREAD

**Issue by nicho2** [openthread/ot-br-posix#589]
I send a get coap to a product and the destination address of answer is not with the ipv6 address of sender

I have a border router with this ipv6:
        inet6 fd11:22::bf58:afb5:d0ad:fece  prefixlen 64  scopeid 0x0<global>
        inet6 **fdbb:ddbd:7576:8ac9:3d9a:4e09:9924:d8ea**  prefixlen 64  scopeid 0x0<global>
        inet6 **fdbb:ddbd:7576:8ac9:0:ff:fe00:5800**  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::ec6b:a474:33d7:a5  prefixlen 64  scopeid 0x20<link>

and a product with:
      **fdbb:ddbd:7576:8ac9:0:ff:fe00:b400**
      fd11:22:0:0:6da3:1b77:caf2:209a
      **fdbb:ddbd:7576:8ac9:e9ce:3e37:385e:923e**
      fe80:0:0:0:1c52:147b:5695:3bc5

from Border Router, i send a get Coap command to my product with host address :fdbb:ddbd:7576:8ac9:e9ce:3e37:385e:923e 
the BR uses its source address  : fdbb:ddbd:7576:8ac9:0:ff:fe00:5800
and the product answers with 
source address :  fdbb:ddbd:7576:8ac9:0:ff:fe00:b400
and destination address : fdbb:ddbd:7576:8ac9:0:ff:fe00:5800
so my client coap says:
( WARNING - Un-Matched incoming response message fdbb:ddbd:7576:8ac9:0:ff:fe00:b400:5683)

![image](https://user-images.githubusercontent.com/11471811/95968003-3fa3df80-0e0d-11eb-954a-45db320ea83c.png)

I think the BR don't choose the good IPv6, but also there's two address in the same subnet

Is someone can help me to resolve this issue or is it a bug?

Thanks

**Comment by jwhui** [comment]
@nicho2 , how are you generating the CoAP ACK/Response? The APIs allow passing a `otMessageInfo` struct that should specify both socket and peer addresses. In most cases, this should be the same `otMessageInfo` struct that was received as part of the request.

**Comment by nicho2** [comment]
For the coap client, I am using CoapThon library.
But indeed, on the product side when creating the response message, the local address is not filled with the address of the sender so the product decides on the source address itself.
Thanks
