### ISSUE TITLE
Persist ccathreshold after daemon restart

### ISSUE THREAD

**Issue by rodrigobrochado** [openthread/ot-br-posix#609]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.
Sometimes when the ot-br container restart, I need to manually restart the dbus and otbr-agente services. In doing so, the ccathreshold comes back to the default (-74). 

**Describe the solution you'd like** A clear and concise description of what you want to happen.
The ccathreshold could be persisted like the ot-br network dataset, for example.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
Don't know

**Additional context** Add any other context or screenshots about the feature request here.
I've build the docker imaged based on 6f0c8036.

**Comment by bukepo** [comment]
Does a startup option work for you? We just added an option to set fem-lnagain, we can do the similar for cca threshold. See https://github.com/openthread/openthread/pull/5788

**Comment by rodrigobrochado** [comment]
Do you mean adding an argument like the typical  "--radio-url" that is passed to docker? That would be helpful!
