### ISSUE TITLE
Topology cannot show childdata

### ISSUE THREAD

**Issue by IHIDCHAOS** [openthread/ot-br-posix#610]
**Describe the bug**

We have a border router and three devices (2X FTD and 1X MTD). After we connect the three devices to OTBR, we find that the Thread topology diagram can only show the topological relationship between Leader (OTBR) and Router (FTD), which doesn't display any Child (MTD) information.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id : ea8fe65f28cd9262ff1a83d015b6e4dcc38efbd4
2. IEEE 802.15.4 hardware platform : nRF52840DK + OpenWrt 19.07
3. Build steps : follow the offical openwrt guide and otbr official compilation guidance documents
4. Network topology : OTBR + 2X FTD + 1X MTD

**Expected behavior** A clear and concise description of what you expected to happen.

Topology graph should show childdata as well.

**Console/log output** If applicable, add console/log output to help explain your problem.
![image](https://user-images.githubusercontent.com/20263334/98920280-e3ff6b80-250a-11eb-90d1-975353d3931b.png)
![image](https://user-images.githubusercontent.com/20263334/98920302-e82b8900-250a-11eb-9677-4a1a6c109841.png)
![image](https://user-images.githubusercontent.com/20263334/98920315-ec57a680-250a-11eb-8f96-bd67f1b33a3e.png)

```
root@OpenWrt:~# ubus call otbr networkdata
{
	"networkdata0": {
		"rloc": "0x003c",
		"routedata": [
			{
				"routerid": 12,
				"rloc": "0x3000"
			},
			{
				"routerid": 17,
				"rloc": "0x4400"
			}
		],
		"childdata": [
			
		]
	},
	"networkdata1": {
		"rloc": "0x0030",
		"routedata": [
			{
				"routerid": 15,
				"rloc": "0x3c00"
			},
			{
				"routerid": 17,
				"rloc": "0x4400"
			}
		],
		"childdata": [
			
		]
	}
}

```

**Additional context** Add any other context about the problem here.

At the same time, we noticed that there is a data mismatch between networkdata and rloc16 in the topology. For example, rloc16 of FTD 1 is 0x3c00, but in networkdata and topology, there is a conflict between 0x3c00 and 0x003c. We want to know if this is a feature of thread or a bug within this version?

**Comment by bukepo** [comment]
just submitted fix to the mismatch issue. Need more time for child table issue. @wgtdkp not sure if you have any idea about this issue.

**Comment by bukepo** [comment]
This issue was introduced by openthread/openthread#5660. @simonlingoogle why is disabling multicast loop necessary for backbone router?

**Comment by simonlingoogle** [comment]
> This issue was introduced by [openthread/openthread#5660](https://github.com/openthread/openthread/pull/5660). @simonlingoogle why is disabling multicast loop necessary for backbone router?

We turned `IPV6_MULTICAST_LOOP` off so that a node does not need to receive and handle backbone link-local multicast messages it has sent. For example, a node does not receive and handle Backbone Query it sent for DAD process. 

Another consideration is that a node does not send multicast messages to the itself on the Thread stack. So, I intended to keep the behavior consistent on the Backbone link too.

**Comment by bukepo** [comment]
@IHIDCHAOS could you try whether the issue still exists in the latest OpenThread?

**Comment by IHIDCHAOS** [comment]
Hi, bukepo, the latest version shows nothing.
```
root@OpenWrt:~# ubus call otbr networkdata
{
}
```
The OTBR WEB GUI Topology(not luci web) can show childdata, but no routerdata.
I will pull more logs here later.

**Comment by IHIDCHAOS** [comment]
Hi @bukepo,
Here are the details.
**MTD and FTD in thread network:**
![image](https://user-images.githubusercontent.com/20263334/101301853-0455e800-3875-11eb-9cf9-bc3f57f7df60.png)
**Ubus shows nothing:**
![image](https://user-images.githubusercontent.com/20263334/101301876-10da4080-3875-11eb-9770-8a7ccfcac50c.png)
**OTBR WEB GUI Topology:**
just childdata
![image](https://user-images.githubusercontent.com/20263334/101302000-6b739c80-3875-11eb-8c73-fa5f55109314.png)
