### ISSUE TITLE
OpenWrt OTBR ping no response

### ISSUE THREAD

**Issue by IHIDCHAOS** [openthread/ot-br-posix#612]
**Describe the bug** A clear and concise description of what the bug is.

I use openwrt 19.07 as my otbr. I use Tayga with the following configuration to do NAT64.

/etc/config/network
```
......
config globals 'globals'
	option ula_prefix 'ddbe:48ec:56c6::/48'
config interface 'nat64'
	option proto 'tayga'
	option ipv4_addr '192.168.64.1'
	option ipv6_addr '2001:db8:1::1'
	option prefix '64:ff9b::/96'
	option dynamic_pool '192.168.64.0/24'
......
```
 /etc/config/firewall
```
......
config zone
	option name 'lan'
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'ACCEPT'
	option network 'lan nat64'
......
```
and then I run command to apply that.
```
/etc/init.d/firewall restart
/etc/init.d/network restart
```
then ping the google dns ip.
```
[root@OpenWrt:/root]#ping 64:ff9b::8.8.8.8
PING 64:ff9b::8.8.8.8 (64:ff9b::808:808): 56 data bytes
64 bytes from 64:ff9b::808:808: seq=1 ttl=111 time=152.386 ms
64 bytes from 64:ff9b::808:808: seq=2 ttl=111 time=140.731 ms
64 bytes from 64:ff9b::808:808: seq=3 ttl=111 time=141.900 ms
^C
```
it seems ok.
but when i use **ot-ctl** ping this ip,i can not see the output,and no packet found at interface tayga-nat64.
```
[root@OpenWrt:/root]#ot-ctl ipaddr
fd11:22:0:0:3abb:cae8:b5bc:8852
fd06:2e0b:361b:8cde:0:ff:fe00:fc00
fd06:2e0b:361b:8cde:0:ff:fe00:b800
fd06:2e0b:361b:8cde:8b6e:f902:b158:3445
fe80:0:0:0:4c9b:518b:3a94:d235
Done
```
```
[root@OpenWrt:/root]#ot-ctl ping 64:ff9b::8.8.8.8
Done
```
following the openthread.io guide i set `ot-ctl prefix add fd11:22::/64 pasor` and `ot-ctl netdata register` but useless.
and I test it with nRF52840dk as thread FTD,after join thread network, I get the same issue.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id 39ccbb438c17ae964081313caa64ed3e2b89e114
2. IEEE 802.15.4 hardware platform nRF52840 DK
3. Build steps
4. Network topology OTBR+FTD

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by IHIDCHAOS** [comment]
packet on **wpan0** shows no response:
![image](https://user-images.githubusercontent.com/20263334/99389520-158f8280-28cf-11eb-9df9-c6db09da3d15.png)
no packet on **tayga-nat64**:
![image](https://user-images.githubusercontent.com/20263334/99389708-5a1b1e00-28cf-11eb-90ca-f46ba4ff1208.png)

**Comment by bukepo** [comment]
@IHIDCHAOS have you enabled IPv6 forwarding on wpan0 interface? I think you can verify this by the following command:

```bash
cat /proc/sys/net/ipv6/conf/wpan0/forwarding
```

If it outputs 1, then the forwarding is on, if not, could you try enable it by echo `1` to that file?

**Comment by IHIDCHAOS** [comment]
> @IHIDCHAOS have you enabled IPv6 forwarding on wpan0 interface? I think you can verify this by the following command:
> 
> ```shell
> cat /proc/sys/net/ipv6/conf/wpan0/forwarding
> ```
> 
> If it outputs 1, then the forwarding is on, if not, could you try enable it by echo `1` to that file?

I will check it on weekdays, thx!

**Comment by IHIDCHAOS** [comment]
Hi,I created a network using Luci.
![image](https://user-images.githubusercontent.com/20263334/99923967-32b2ce00-2d73-11eb-82da-9b0edb2d5d72.png)
And test result:
![image](https://user-images.githubusercontent.com/20263334/99923962-2b8bc000-2d73-11eb-8521-27a5a36a0baa.png)
Forwarding is turned on automatically.

**Comment by IHIDCHAOS** [comment]
Hi bukepo, 

I upload this Raspberry Pi 3B openwrt firmware at [google drive](https://drive.google.com/drive/folders/1l_YCz5UbiafaOsCTmsWYh_gV-Ou1lra1?usp=sharing). 

Could you please help me locate the reason of this "no response" problem?

Thanks in advance!

Best,
Guo

**Comment by bukepo** [comment]
@IHIDCHAOS After another look at this issue, I think this is an expected behavior. The echo-request seen in wireshark is actually a packet comes into openwrt from OpenThread's IP stack. I guess the packet is correctly forward to the nat64 interface and the echo-response may also reached its destination, the IP stack of OpenWRT's linux kernel. The response is not delivered to OpenThread's IP stack because the `fd11:22:0:0:3abb:cae8:b5bc:8852` also exists in wpan0 interface. You can only use `ot-ctl ping` to reach nodes inside of Thread network.

**Comment by IHIDCHAOS** [comment]
@bukepo Thanks! It seems true. When I use zephyr client with openthread, I can ping with `net ping 64:ff9b::8.8.8.8` and get network response, while `ot ping 64:ff9b::8.8.8.8` just shows `Done`. 
So 

> You can only use ot-ctl ping to reach nodes inside of Thread network.

is Right.
