### ISSUE TITLE
otbr-agent not present in latest armv7 docker image

### ISSUE THREAD

**Issue by rodrigobrochado** [openthread/ot-br-posix#616]
**Describe the bug** A clear and concise description of what the bug is.

The latest openthread/otbr image for armv7 doesn't have otbr-agent service installed.  
It's a bug, right? Or the latest ot-br-posix is not stable-likely?

**To Reproduce** Information to reproduce the behavior, including:
```bash
# on a raspberrypi 3
docker pull openthread/otbr@sha256:5823f09f9863fb1d80a5c445beb4d65484d81b1bd315701e3817530178c7239e

docker run --rm --name openthread_otbr -d --sysctl "net.ipv6.conf.all.disable_ipv6=0 \
        net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" \
        -p 8080:80 --dns=127.0.0.1 -it --volume \
        /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr \
        --radio-url spinel+hdlc+uart:///dev/ttyACM0

sudo docker exec openthread_otbr service --status-all
 [ + ]  avahi-daemon
 [ + ]  dbus
 [ ? ]  hwclock.sh
 [ + ]  named
 [ - ]  otbr-nat44
 [ - ]  procps
 [ + ]  rsyslog
 [ + ]  tayga


```
1. Git commit id  39ccbb43
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.
It works in amd64. We have also built the image out of our fork and the last one that worked was merged from commit 6f0c80367. Didn't test the ones between 6f0c80367...39ccbb43 yet.

**Comment by jwhui** [comment]
@rodrigobrochado , thank you for raising this issue. This is a duplicate of #613.

We have submitted #614 to address this issue and is under review.

**Comment by rodrigobrochado** [comment]
OMG. I have't refreshed the issues page, sorry.

**Comment by jwhui** [comment]
@rodrigobrochado , #614 has been merged and new docker images pushed. Thanks again for raising this issue.

**Comment by rodrigobrochado** [comment]
Thanks!!!
