### ISSUE TITLE
The tayga service does not start automatically

### ISSUE THREAD

**Issue by IHIDCHAOS** [openthread/ot-br-posix#636]
**Describe the bug** A clear and concise description of what the bug is.
The tayga service does not start automatically, so NAT64 is not available by default.
**To Reproduce** Information to reproduce the behavior, including:
follow [OpenThread Border Router Build and Configuration](https://openthread.io/guides/border-router/build?hl=en)
1. Git commit id 089271cbf530239072fa426af9896efd21019b73
2. IEEE 802.15.4 hardware platform nRF52840
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.
The tayga service should start automatically.
**Console/log output** If applicable, add console/log output to help explain your problem.
```
pi@raspberrypi:~ $ sudo systemctl status tayga
¡ñ tayga.service - LSB: userspace NAT64
   Loaded: loaded (/etc/init.d/tayga; generated)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)
pi@raspberrypi:~ $ ping 64:ff9b::8.8.8.8
connect: Network is unreachable
pi@raspberrypi:~ $ sudo systemctl start tayga
pi@raspberrypi:~ $ ping 64:ff9b::8.8.8.8
PING 64:ff9b::8.8.8.8(64:ff9b::808:808) 56 data bytes
64 bytes from 64:ff9b::808:808: icmp_seq=2 ttl=112 time=140 ms
64 bytes from 64:ff9b::808:808: icmp_seq=3 ttl=112 time=140 ms
^C
--- 64:ff9b::8.8.8.8 ping statistics ---
3 packets transmitted, 2 received, 33.3333% packet loss, time 45ms
rtt min/avg/max/mdev = 140.046/140.211/140.376/0.165 ms

```
**Additional context** Add any other context about the problem here.

**Comment by bukepo** [comment]
It seems this is an intended behavior. `nat64_start` is only called in `script/server`.
