### ISSUE TITLE
BorderRouter-AP unable to connect

### ISSUE THREAD

**Issue by IHIDCHAOS** [openthread/ot-br-posix#637]
**Describe the bug** A clear and concise description of what the bug is.
pc cannot connect to RPI3 BorderRouter-AP with default password 12345678
**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id https://github.com/openthread/ot-br-posix/commit/089271cbf530239072fa426af9896efd21019b73
2. IEEE 802.15.4 hardware platform nRF52840
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.
![image](https://user-images.githubusercontent.com/20263334/100821994-6df87f80-348c-11eb-8a27-8d08f8e7a95c.png)
![image](https://user-images.githubusercontent.com/20263334/100822125-ad26d080-348c-11eb-9500-bb23724e48fa.png)

**Additional context** Add any other context about the problem here.

**Comment by bukepo** [comment]
@IHIDCHAOS Could you provide logs on RPI3? Also could you make sure the RPI's Wi-Fi is set to China's regulatory domain?

**Comment by IHIDCHAOS** [comment]
Hi @bukepo 
I clean build the otbr with fresh install 2020-08-20-raspios-buster-armhf-lite.img.
```
git clone https://github.com/openthread/ot-br-posix
cd ot-br-posix
./script/bootstrap
NETWORK_MANAGER=0 ./script/setup
```
and then [set up AP manually](https://openthread.io/guides/border-router/access-point?hl=en), without changing the Wi-Fi region, it works.
So I guess the NETWORK_MANAGER script has something not work properly.

To automatically set up the Wi-Fi AP using Network Manager:
[setup.log](https://github.com/openthread/ot-br-posix/files/5650732/setup.log)
