### ISSUE TITLE
OTBR sends Multicast Listener Report Message V2 to the Thread network

### ISSUE THREAD

**Issue by simonlingoogle** [openthread/ot-br-posix#641]
**Describe the bug**

OTBR sends `Multicast Listener Report Message V2` multicast to the Thread network when it attaches, bringing significant and unnecessary network traffic.

**To Reproduce**

It happens when a OTBR device joins a Thread network.

**Expected behavior**

OTBR should not send this message to the Thread network

**Console/log output** 

Packet frame:

```
Frame 88: 94 bytes on wire (752 bits), 94 bytes captured (752 bits) on interface 0
Ethernet II, Src: 22:22:22:22:22:22 (22:22:22:22:22:22), Dst: Broadcast (ff:ff:ff:ff:ff:ff)
IEEE 802.15.4 Data, Dst: 0x0400, Src: 16:6e:0a:00:00:00:00:1d
6LoWPAN
    Fragmentation Header
    [2 Message fragments (176 bytes): #86(128), #88(48)]
Internet Protocol Version 6, Src: fe80::146e:a00:0:1d, Dst: ff02::16
    0110 .... = Version: 6
    .... 0000 0000 .... .... .... .... .... = Traffic Class: 0x00 (DSCP: CS0, ECN: Not-ECT)
    .... .... .... 0000 0000 0000 0000 0000 = Flow Label: 0x00000
    Payload Length: 136
    Next Header: IPv6 Hop-by-Hop Option (0)
    Hop Limit: 1
    Source: fe80::146e:a00:0:1d
    Destination: ff02::16
    IPv6 Hop-by-Hop Option
Internet Control Message Protocol v6
    Type: Multicast Listener Report Message v2 (143)
    Code: 0
    Checksum: 0x2a9c [correct]
    [Checksum Status: Good]
    Reserved: 0000
    Number of Multicast Address Records: 6
    Multicast Address Record Changed to exclude: ff33:40:fd00:db8::1
    Multicast Address Record Changed to exclude: ff32:40:fd00:db8::1
    Multicast Address Record Changed to exclude: ff03::fc
    Multicast Address Record Changed to exclude: ff03::1
    Multicast Address Record Changed to exclude: ff02::16
    Multicast Address Record Changed to exclude: ff02::2

```

Some other packets to `ff02::16` that wireshark can not dissect. 

![image](https://user-images.githubusercontent.com/52448427/100956477-7e276200-3553-11eb-8ec5-c6a721f62974.png)

**Comment by simonlingoogle** [comment]
I think we can fix it by one these solutions:

1. Parse the IP6 header in `processTransmit` of `posix/platform/netif.cpp` and skip such messages
2. Ip6::SendRaw drop multicast packets with link local scope (very simple to implement, but not sure if it's proper)
3. Use ip6tables rules to drop such packets in the wpan0 interface.

Thoughts? @librasungirl @bukepo @jwhui

**Comment by bukepo** [comment]
Yes, I prefer filtering unsupported packets inside OpenThread's IPv6 stack(src/core/ip6.cpp), which helps all platforms.

**Comment by jwhui** [comment]
Closing stale issue.
