### ISSUE TITLE
otbr-agent erroneously reports RadioSpinelIncompatible

### ISSUE THREAD

**Issue by msandstedt** [openthread/ot-br-posix#642]
Confirmed both RCP and otbr are using spinel version 4.3, but otbr-agent erroneously reports a mismatch:

```
Dec 02 23:29:25 pavillion otbr-agent[116645]: Running 0.2.0-9ef7480
Dec 02 23:29:25 pavillion otbr-agent[116645]: Thread interface wpan0
Dec 02 23:29:25 pavillion otbr-agent[116645]: Backbone interface
Dec 02 23:29:26 pavillion otbr-agent[116645]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Dec 02 23:29:26 pavillion otbr-agent[116645]: [CRIT]-PLAT----: Init() at ../../third_party/openthread/repo/src/lib/spinel/radio_spinel_impl.hpp:233: RadioSpinelIncompatible
```

This appears to be a regression with at this recent commit:

```
commit 9ef7480b90e135137a38eb9ca2f0d3ad8ff24e8f
Author: Simon Lin <simonlin@google.com>
Date:   Wed Nov 25 00:59:53 2020 +0800

    [backbone-router] remove MLR multicast routing using smcroute (#604)
```

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: 9ef7480b90e135137a38eb9ca2f0d3ad8ff24e8f
2. RCP hardware: nrf52840
3. otbr build: ./script/bootstrap; ./script/setup

**Comment by jwhui** [comment]
@msandstedt , the error indicates that your nRF52840 is not running RCP firmware.

Can you provide details on how you built and setup your nRF52840 RCP?

**Comment by msandstedt** [comment]
> @msandstedt , the error indicates that your nRF52840 is not running RCP firmware.
> 
> Can you provide details on how you built and setup your nRF52840 RCP?

This is how I'm building firmware for the nRF52840:

```
git clone https://github.com/openthread/openthread
cd openthread
git checkout 0b0d6eef1d569c77a6cc08c3d4a39b76ea3e33c0
git log -n1
commit 0b0d6eef1d569c77a6cc08c3d4a39b76ea3e33c0 (HEAD)
Author: Mason Tran <mason@lmnotran.com>
Date:   Mon Nov 2 12:57:57 2020 -0500

    [efr32] use -mfpu=fpv4-sp-d16 for efr32mg1x chips (#5760)
./bootstrap
make -f examples/Makefile-nrf52840 clean
make -f examples/Makefile-nrf52840 BORDER_AGENT=1 BORDER_ROUTER=1 COMMISSIONER=1 UDP_FORWARD=1 USB=1 LINK_RAW=1 BOOTLOADER=USB
arm-none-eabi-objcopy -O ihex output/nrf52840/bin/ot-ncp-ftd output/nrf52840/bin/ot-ncp-ftd.hex
```

All revs of ot-br-posix at and after 9ef7480 exhibited the problem.  All revs I've tried at and before 9ef7480^ did not show the problem.  That is, the RCP flashed with openthread at the above works for me with ot-br-posix 9ef7480^ and before, and does not work with ot-br-posix 9ef7480 and after.

**Comment by jwhui** [comment]
> ```
> arm-none-eabi-objcopy -O ihex output/nrf52840/bin/ot-ncp-ftd output/nrf52840/bin/ot-ncp-ftd.hex
> ```

@msandstedt , it appears you are flashing the NCP image. You should be using the RCP image (`output/nrf52840/bin/ot-rcp`). We recently fixed a bug that did not properly check for the RCP image in https://github.com/openthread/openthread/pull/5822. Now that the bug is fixed, you are now properly seeing this error.

**Comment by msandstedt** [comment]
Ah, I see.  Thank you!
