### ISSUE TITLE
OTBR add "On-Mesh Prefix" on OpenWRT Luci

### ISSUE THREAD

**Issue by ihidchaos** [openthread/ot-br-posix#643]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.
The Form function of the native OT Border Router WEB GUI can directly set the default ON-Mesh Prefix, while OpenWrt's Luci Form does not have this option.
This results in devices connected to the OpenWrt Thread network being unable to get the Mesh Local IP from the OTBR.
![image](https://user-images.githubusercontent.com/20263334/100977767-6b755300-357c-11eb-9481-02cd2e4c72a0.png)
![image](https://user-images.githubusercontent.com/20263334/100978105-e0488d00-357c-11eb-9d28-cdae08cacfa0.png)
**Luci form: no fd11:22 ip**
![image](https://user-images.githubusercontent.com/20263334/100979098-500b4780-357e-11eb-815c-f82bd11809d1.png)
![image](https://user-images.githubusercontent.com/20263334/100979071-44b81c00-357e-11eb-8cd2-7f935170e290.png)

**OTBR WEB form: ok**
![image](https://user-images.githubusercontent.com/20263334/100980085-acbb3200-357f-11eb-82c7-caf2eae7daf0.png)
![image](https://user-images.githubusercontent.com/20263334/100980242-e8ee9280-357f-11eb-9ab9-d75acc29c4dd.png)

 
**Describe the solution you'd like** A clear and concise description of what you want to happen.
a. Add the setonmeshprefix(to set) and onmeshprefix(to get) functions to the Ubus, then call the ubus command on the Luci Web.
b. Add the setonMeshPrefix and onmeshPrefix functions to ot-ctl, then Call the ot-ctl command on the Luci Web.
**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by bukepo** [comment]
@IHIDCHAOS In fact, Thread can have multiple prefixes. Instead of adding setonmeshprefix, I think it better to add UI support full functionality of https://github.com/openthread/openthread/tree/master/src/cli#prefix. That is, OpenWRT should be able to manage multiple prefixes with different flags. Thoughts?

**Comment by ethanlyc** [comment]
Hi @bukepo,

Thanks for your reply. 

I noticed that in your link there are some Prefix flag features only work on Thread 1.2. But right now on the official OTBR Web GUI there is only one box for setonmeshprefix. I wonder is this a preparation for the new Thread version? If so, may be it would be better to start with Raspberry Pi? If not, then add setonmeshprefix input box on OpenWrt platform is great complement for now.

In addition, are there any cases where multiple prefixes need to be added to one end device? Any example links are much appreciated!

Best,
Yicong

**Comment by jwhui** [comment]
I agree that Raspberry Pi should also allow configuration of multiple on-mesh prefixes.

**Comment by jwhui** [comment]
Closing stale issue.
