### ISSUE TITLE
Setting up a RCP Borderrouter via ot-ctl: No such file or directory

### ISSUE THREAD

**Issue by MarcelloDavis** [openthread/ot-br-posix#644]
**Describe the bug** As I am quite new to openthread and setting up thread-mesh-networks, I thought you might help me on an issue I just ran into. I tried to set up a Openthread Borderrouter via Raspberry Pi3B and a nrf52840 USB Dongle as RCP. I essentially followed this tutorial https://github.com/openthread/openthread/issues/5311 and came to the point where the three services

- `avahi-daemon.service`
- `otbr-agent.service`
- `otbr-web.service`

are running when typing `sudo systemctl status`. Till this point I got no issues, which indicates I set up the Borderrouter correctly.

However, typing `sudo ot-ctl dataset init new` leads to an error which says "connect session failed: No such file or directory".

This step (`sudo ot-ctl dataset init new`) is also listed on the official openthread site (https://openthread.io/guides/border-router/external-commissioning?hl=en&comm=ot-commissioner), where it says that you need to form the network on the command line of OpenThread POSIX.
Current working directory was `~/ot-br-posix`, maybe the chosen directory was not correct?
I found the root directory of `ot-ctl` on the Raspberry Pi under: `~/ot-br-posix/build/otbr/third_party/openthread/repo/src/posix`, but even if changing the working directory to this path, the above shown command (`sudo ot-ctl dataset init new`) leads to the same issue (connect session failed: No such file or directory).

At this point I am not sure whether ot-ctl was installed correctly..

I hope that you can help me :)

**EDIT**: The command `sudo nrfutil dfu usb-serial -pkg out.zip -p /dev/ttyACM0 -b 115200` led to an error that says: "No trigger interface found for device with serial number: C8A8AA709BED, Product ID: 0xCAFE and Vendor ID..."
I just copied the command above, perhaps perhaps the hex-file flashed to the Dongle is not correct?

**Comment by jwhui** [comment]
@MarcelloDavis , the "connect session failed: No such file or directory" error indicates that otbr-agent process is not actually running. You can validate whether the otbr-agent process is running by doing something like this:
```
$ ps -ax | grep otbr-agent
 1874 ?        Ss     0:00 /usr/sbin/otbr-agent -I wpan0 spinel+hdlc+uart:///dev/ttyACM0
 2043 pts/0    S+     0:00 grep --color=auto otbr-agent
```

The most common reason why otbr-agent is not running is because the RCP is not configured with the correct firmware image.

You can find otbr-agent logs in `/var/log/messages`, can you provide those logs?

**Comment by jwhui** [comment]
Closing stale issue.

**Comment by sohaibbinaltaf** [comment]
Hello, 

I have successfully developed the RCP border router. Now I am trying to connect a thread node which consists of Raspberry pi with nRF52840 dongle with ot-cli-ftd.hex file flashed over it. 

But no CLI commands run over it, and I cant connect it with the border router. How can i setup this thread node . Do I need to install the openthread or ot-br-posix on the pi, or any other package

**Comment by jwhui** [comment]
> Hello,
> 
> I have successfully developed the RCP border router. Now I am trying to connect a thread node which consists of Raspberry pi with nRF52840 dongle with ot-cli-ftd.hex file flashed over it.
> 
> But no CLI commands run over it, and I cant connect it with the border router. How can i setup this thread node . Do I need to install the openthread or ot-br-posix on the pi, or any other package

@sohaibbinaltaf , you may find the [Thread Border Router codelab](https://openthread.io/codelabs/openthread-border-router) helpful.

BTW, please open a new issue for new questions.

**Comment by sohaibbinaltaf** [comment]
@jwhui Thank you
