### ISSUE TITLE
RCP / ot-ctl crashes frequently and ot-ctl returns "OpenThread daemon not working"

### ISSUE THREAD

**Issue by vijayrao1988** [openthread/ot-br-posix#647]
**Description of the bug**
Background - On an ubuntu-20.04 based Border Router, we have a Silabs MGM12P32 based RCP. The setup works fine on booting up, connects well as the wpan0 interface with the Thread network and we are able to get stable operation for days together.
Bug - Occasionally, the OpenThread daemon stops running resulting in the wpan0 interface dropping off. All commands to ot-ctl then result in "OpenThread daemon not running".

**To Reproduce** I haven't noticed any particular event leading up to this crash but we have observed the crash often for it to be noted as a bug.

1. Git commit id : 38e91052d1fb12a55c4e34073f9e399471650b4b
2. IEEE 802.15.4 hardware platform: Silicon Labs EFR32MG12 (Module: MGM12P32GE)
3. Build steps: The RCP application is built with the following options BOARD=BRD4304A BORDER_AGENT=1 BORDER_ROUTER=1 UDP_FORWARD=1 COMMISSIONER=1 JOINER=1 COAP=1 DHCP6_CLIENT=1 DHCP6_SERVER=1 USB=1
4. Network topology: Typically a chain with the RCP/BorderRouter at one extreme end

**Expected behavior** No crashes, stable operation

I would like to know if there is a log I could check when the otbr-agent crashes or if it is held even after reboots. Any pointers would be helpful to resolve the situation.

We are currently using an older commit of ot-br-posix as we found it to be stable. We found stability issues with some of the later commits.

**Comment by jwhui** [comment]
> I would like to know if there is a log I could check when the otbr-agent crashes or if it is held even after reboots. Any pointers would be helpful to resolve the situation.

The logs are sent to syslog (i.e. `/var/log/messages`). Can you provide those logs?

> We are currently using an older commit of ot-br-posix as we found it to be stable. We found stability issues with some of the later commits.

Are you using the same firmware image for the RCP? In other words, is the only change the commit of ot-br-posix you are using? Can you provide which commit of ot-br-posix provides better stability?

**Comment by jwhui** [comment]
Closing stale issue.
