### ISSUE TITLE
Can OTBR Web Agent Port Number be Modifiable?

### ISSUE THREAD

**Issue by vijayrao1988** [openthread/ot-br-posix#648]
**Is your feature request related to a problem? Please describe.**
I have some other web services running on a ubuntu based gateway (border router). The 2nd web service seems to take precedence over the OTBR Web Agent, but any links from the home page seem to get redirected to unavailable resources - which is a clear indication of a conflict.

**Describe the solution you'd like**
I would like to modify the port number of the OTBR web service. If the port number can be specified at the time of the build it will allow integrating with other functionalities conveniently.

**Comment by bukepo** [comment]
You may try starting `otbr-web -p PORT`.

**Comment by jwhui** [comment]
Closing stale issue.
