### ISSUE TITLE
Unable to receive packet when NCP state is end-device.

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#655]
Continuation of #251 issue.

I am using RaspberryPi 3B as border router. Around 88 nodes are there in the OpenThread network spread across 42000 sq ft. I have noticed that when NCP enters into `end-device` state, no packet reaches at `wpan0` interface of border router. The NCP stays in `end-state` for more than 30 minutes.

I have reported this issue earlier whose link is mentioned above. Because of lack of logs, the issue was closed. I started facing this issue again.

Following are the details of NCP:
```
wpan0 => [
	"NCP:State" => "associated"
	"Daemon:Enabled" => true
	"NCP:Version" => "OPENTHREAD/20191113-00092-g8a1992e2; NRF52840; Apr  6 2020 22:33:55"
	"Daemon:Version" => "0.08.00d (/87c90ee; Dec 11 2019 03:46:40)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [03C94DA92B366938]
	"NCP:Channel" => 25
	"Network:NodeType" => "end-device"
	"Network:Name" => "fbceca7b0fe995b3"
	"Network:XPANID" => 0xFBCECA7B0FE995B3
	"Network:PANID" => 0xFBCE
	"IPv6:LinkLocalAddress" => "fe80::280d:b488:b42a:722b"
	"IPv6:MeshLocalAddress" => "fdfb:ceca:7b0f:0:bade:e4fe:c48b:8175"
	"IPv6:MeshLocalPrefix" => "fdfb:ceca:7b0f::/64"
	"com.nestlabs.internal:Network:AllowingJoin" => false
]
```

I have published the `NCPNodeType` and `NoOfNode` parameter onto the cloud. Below is the screenshot of the graph.
As you can see in the graph, whenever `NCPNodeType` value is 3, `NoOfNode` becomes 0 because no packet is being received at `wpan0` interface (I checked using tcpdump tool).

(In `NCPNodeType`, 1 means `leader`, 2 means `router` and 3 means `end-device`) 

<img width="1139" alt="Screenshot 2020-12-18 at 1 36 20 PM" src="https://user-images.githubusercontent.com/9993036/102590095-0bfb7380-4136-11eb-8611-4cb3d86a1409.png">

PFA for syslog. (Time: 12:40 pm to 1:30 pm)
[syslog.log](https://github.com/openthread/ot-br-posix/files/5714427/syslog.log)

**Comment by jwhui** [comment]
@tarunsmalviya , thanks for raising this issue.

It appears you are using a commit that's just over a year old: https://github.com/openthread/openthread/commit/8a1992e2

Is it possible for you to test with a newer version of OpenThread on the NCP? For example, I'm thinking (https://github.com/openthread/openthread/pull/4783) may help address this situation.

**Comment by tarunsmalviya** [comment]
@jwhui Okay. Give me some time.

**Comment by jwhui** [comment]
Closing stale issue.
