### ISSUE TITLE
ot-ctl don't retrieve networkdiagnostic get response

### ISSUE THREAD

**Issue by mmcharfi-bluegriot** [openthread/ot-br-posix#689]
**Describe the bug** 
I try to get some information about the network topology by sending the standard Thread diagnostic messages with ot-ctl command networkdiagnostic. I see with the log of otbr-agent that I receive a response from my router but nothing appear in ot-ctl "interface". (the command work with CLI but i need it with ot-ctl).

**To Reproduce** 
Start a network.  With ot-ctl send:
 networkdiagnostic get fdde:ad00:beef:0:0:ff:fe00:_rloc16_ 16

1. Git commit id
c80e888ae60c939789fc31de36e1621655f7101b
2. IEEE 802.15.4 hardware platform
NRF52840
4. Network topology
1 Border router, 1 router, 4 child.

**Expected behavior** 
Want to receive a response like: 
> DIAG_GET.rsp/ans: 1000

**Console/log output** 
Log of otbr-agent:

> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-CLI-----: execute command: networkdiagnostic get 
> fdde:ad00:beef:0:0:ff:fe00:c400 16
> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-DIAG----: Sent diagnostic get
> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-PLAT----: processTransmit: OK
> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-MAC-----: Sent IPv6 UDP msg, len:63, chksum:e392, to:0xc400, sec:yes, prio:normal
> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-MAC-----:     src:[fdde:ad00:beef:0:0:ff:fe00:5400]:61631
> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-MAC-----:     dst:[fdde:ad00:beef:0:0:ff:fe00:c400]:61631
> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-MAC-----: Received IPv6 UDP msg, len:60, chksum:f3c2, from:0xc400, sec:yes, prio:net, rss:-62.0
> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-MAC-----:     src:[fdde:ad00:beef:0:0:ff:fe00:c400]:61631
> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-MAC-----:     dst:[fdde:ad00:beef:0:0:ff:fe00:5400]:61631
> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-PLAT----: processReceive: OK
> Jan 28 15:53:17 raspberrypi otbr-agent[4727]: [INFO]-DIAG----: Received diagnostic get response

**Comment by bukepo** [comment]
Could you try the latest build? I think we fixed this issue before.

**Comment by mmcharfi-bluegriot** [comment]
I try the latest build. Is look to have the same behaviour. Do i need to update the RCP firmware as well ? 
I communicate with the RCP with SPI.

**Comment by martinzi** [comment]
I have similar observations with missing networkdiagnostic responses while using the topology view of otbr-web or the diagnostics REST interface. After some unknown time or events network topology view tends to degrade and remains incomplete. 
A reset helps to receive networkdiagnostic get responses as expected with ot-ctl - not on the web interfaces though.
```
sudo ot-ctl
> reset
> networkdiagnostic get ff02::2 0 1 16
```

**Comment by mmcharfi-bluegriot** [comment]
I update the rcp software with the latest build and also the ot-br-posix:
`> rcp version
OPENTHREAD/20191113-01682-gad91ac3b9; NRF52840; Feb  3 2021 16:37:13
> version
OPENTHREAD/0.01.00; POSIX; Jan 29 2021 10:12:30
`
 But i have nearly the same behaviour. The difference is that now in the log of otbr-agent i didnt see the "processReceive: OK".
I communicate with my  rcp true SPI maybe this feature is not enable when using SPI communiation ?

**Comment by wgtdkp** [comment]
@mmcharfi-bluegriot I tried the latest otbr with both simulation and UART+nordic devices, both are working for me. Is it possible for you to try simulation or UART devices? So that we can be sure if it is issue with SPI or not.

**Comment by bukepo** [comment]
@mmcharfi-bluegriot What's the platform your otbr-agent running on?

**Comment by mmcharfi-bluegriot** [comment]
@bukepo I a run on Raspberry pi 3b+, and my rcp is a nrf52840 package in a fanstel module (bt840X). @wgtdkp Thanks, i will try with uart rcp later in the day and keep you in touch.

**Comment by wgtdkp** [comment]
@mmcharfi-bluegriot Are you building with `OTBR_REST`?

**Comment by mmcharfi-bluegriot** [comment]
@wgtdkp ha ok, I didnt build with OTBR_REST isn't set to 1 by default ? there is my compilation step:
```
export OTBR_OPTIONS="-DOT_POSIX_CONFIG_RCP_BUS=SPI"
NETWORK_MANAGER=0 ./script/setup
```

**Comment by wgtdkp** [comment]
@mmcharfi-bluegriot 
> I will try to compile with the OTBR_REST flag today

You should not use `OTBR_REST` and CLI at the same time, it is expected that the CLI will not receive diagnostic response if OTBR_REST is enabled.

**Comment by wgtdkp** [comment]
@mmcharfi-bluegriot Any updates?

**Comment by IHIDCHAOS** [comment]
Hi @wgtdkp 
I have the same prbolem.
I am running a OTBR on the OpenWrt platform, and I have an nRF52840DK board as a thread end device.
![image](https://user-images.githubusercontent.com/20263334/108672610-5ece1e80-751d-11eb-8aa7-f7129c08fee6.png)
As the picture shows, I can get **child table** and **router table** from ot-ctl,and also I can get **TLV_CHILD_TABLE** and **TLV_NETWORK_DATA** from networkdiagnostic, but I can not get **networkdata** from ubus.

Here are my versions:
RCP Version:
OPENTHREAD/0.01.00; POSIX; Feb 20 2021 09:57:43

CLI Version:
OPENTHREAD/20191113-01728-g14ef4e4; NRF52840; Feb 21 2021 23:05:16

**Comment by wgtdkp** [comment]
@IHIDCHAOS
I think this is because `ubus` and `OT CLI` are both setting the network diagnostic callback and `OT CLI` wins:
```c++
// OT CLI sets network diagnostic callback.
#if OPENTHREAD_FTD || OPENTHREAD_CONFIG_TMF_NETWORK_DIAG_MTD_ENABLE
    otThreadSetReceiveDiagnosticGetCallback(mInstance, &Interpreter::HandleDiagnosticGetResponse, this);
#endif
```

I will create a quick fix that sets the callback every time the `otThreadSendDiagnosticGet` is called.

**Comment by mmcharfi-bluegriot** [comment]
Hi @wgtdkp,
Sorry for the late response. I try with uart devices (NRF52840DK) + RPi but I have the same issues. There is my step:
```
git clone https://github.com/openthread/ot-br-posix 
cd ot-br-posix
./script/bootstrap
NETWORK_MANAGER=0 OTBR_REST=0 ./script/setup
```
Did i set the flag wrong ? I also test without OTBR_REST=0 option but nothing change. I will try with the simulation device, but I am not sure that I am compiling in the good.

**Comment by wgtdkp** [comment]
@mmcharfi-bluegriot Sorry I didn't make this clear. the options to disable `OTBR_REST` should be:
```shell
NETWORK_MANAGER=0 OTBR_OPTIONS="-DOTBR_REST=OFF" ./script/setup
```

**Comment by wgtdkp** [comment]
@IHIDCHAOS @mmcharfi-bluegriot @martinzi 
I submitted two PRs (#707 and https://github.com/openthread/openthread/pull/6192) for this issue, please let me know if this works for you.

**Comment by IHIDCHAOS** [comment]
It solves my problem. 
I can get data from both **ubus** and **OTBR-REST** now. 
Thanks!
![image](https://user-images.githubusercontent.com/20263334/108789473-4c9fbf00-75b5-11eb-924b-e6252a8bf667.png)

**Comment by mmcharfi-bluegriot** [comment]
working for me too. Thanks
