### ISSUE TITLE
nat64 setup script broken on Raspberry Pi OS

### ISSUE THREAD

**Issue by neye-zhaw** [openthread/ot-br-posix#694]
The automatic setup of tayga did not work for me.

The tayga initscript that comes with the current tayga package (Version: 0.9.2-8) looks like this:

```
$ cat /etc/default/tayga
# Defaults for tayga initscript
# sourced by /etc/init.d/tayga
# installed at /etc/default/tayga by the maintainer scripts

# Configure interface and set the routes up
CONFIGURE_IFACE="yes"

# Configure NAT44 for the private IPv4 range
CONFIGURE_NAT44="yes"

# Additional options that are passed to the Daemon.
DAEMON_OPTS=""

# IPv4 address to assign to the NAT64 tunnel device
IPV4_TUN_ADDR=""

# IPv6 address to assign to the NAT64 tunnel device
IPV6_TUN_ADDR=""
```

Which means at least [script/_nat64#L50](https://github.com/openthread/ot-br-posix/blob/83babaf236cad8471be28185d8d4351d37564919/script/_nat64#L50) has no effect. I did not check the other lines.

**Comment by jwhui** [comment]
Resolved by #782
