### ISSUE TITLE
Default ot-ctl not equivalent to wpanctl

### ISSUE THREAD

**Issue by krbvroc1** [openthread/ot-br-posix#696]
I built the latest OTBR to run on a RaspPi and I was previously using the deprecated wpanctl. wpanctl allowed me to add-service and remove-service which is not available on the default OTBR build.

1) It would be nice if the same behavior was supported with a default build.

2) Regardless, what is the proper way to enable this. I am lost on all the cmake files and scripts. Looking at the source code, I think I need to enable OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE. But I am at a loss of how to 'properly' do that with the installation/build scripts provided.

**Comment by jwhui** [comment]
@krbvroc1 , you can enable ability to add service entries into the Thread Network Data using the [`OT_SERVICE`](https://github.com/openthread/openthread/blob/31746000e85cc733f5c0627a4332244e992192ad/etc/cmake/options.cmake#L270) CMake build option.

You can add the build option to one of the following flies:
- [script/_otbr](https://github.com/openthread/ot-br-posix/blob/master/script/_otbr)
- [third_party/openthread/CMakeLists.txt](https://github.com/openthread/ot-br-posix/blob/master/third_party/openthread/CMakeLists.txt)

You can find documentation on the OpenThread build options in https://github.com/openthread/openthread/blob/master/examples/README.md

Hope that helps.

**Comment by krbvroc1** [comment]
@jwhui Thank you very much for the help...  I was close...

I had tried setting SERVICE=1 in  ./third_party/openthread/repo/examples/common-switches.mk 
And I tried executing NETWORK_MANAGER=0 SERVICE=1 ./script/setup

I had looked the openthread build page https://openthread.io/guides/build, but it seems your suggestion prefixes the option with OT_ - using the OT_SERVICE version does work.

One other question for you...
I had manually created a network using ot-ctl dataset commands (not the webpage FORM network button) and then...

```
ot-ctl dataset commit active
ot-ctl prefix add fd11:22::/64 pasor
ot-ctl ifconfig up
ot-ctl thread start
ot-ctl netdata register
```

However, when I reboot the border router, there is no fd11:22 being configured / restored. Is that supposed to be in some config file located somewhere?  If I manually rerun the 
```
ot-ctl prefix add fd11:22::/64 pasor
ot-ctl netdata register
```
the route returns.

**Comment by jwhui** [comment]
Currently, OTBR does not provide a mechanism to statically configure the on-mesh prefix. One thing you could do is configure the on-mesh prefix as part of a startup script.

Going forward, OTBR needs to provide a mechanism to automatically configure the on-mesh prefix. Note that this does not imply the prefix should be statically configured. There is existing work to enable this:
- openthread/openthread#5856
- openthread/openthread#6008

There is still some more work to do to enable this by default.
