### ISSUE TITLE
mDNS announce is missing necessary fields

### ISSUE THREAD

**Issue by mikhail-pridushchenko** [openthread/ot-br-posix#702]
**Description:**
otbr-agent doesn't announce on mDNS the information required by the Thread 1.2 specification.
Particular fields missing:
* rv - record format.
* sb - state bitmap.

Fields missing in case of BBR function enabled (not required in non-CCM case, though looking sane):
* dn -Thread Domain Name.
* sq - BBR sequence number.
* bb - BBR port.

**To Reproduce:**

1. Git commit id: 35e9327b8e6c2dc2b9d0efbc3b64ea23d5db9894
2. IEEE 802.15.4 hardware platform: nRF52840.
3. Build steps
    a. Build OTBR with script parameters: `NETWORK_MANAGER=0 BACKBONE_ROUTER=1`
    b. Build RCP as: `make -f examples/Makefile-nrf52840 USB=1 BOOTLOADER=1 THREAD_VERSION=1.2`
4. Network topology
    OTBR running with BBR function enabled, right after network formation.

**Steps to check:**
In the OTBR shell:
```
# Install avahi-browse
$ sudo apt-get install avahi-utils
# The test itself
$ avahi-browse --cache --resolve _meshcop._udp
```

**Expected behavior:**
As mentioned in the 'To Reproduce' section, the TXT Answer Record from mDNS should contain the following fields (in addition to the present 'tv', 'xp', and 'nn' ones): 'rv', 'sb', 'dn', 'sq', 'bb'. As result the `avahi-browse` output should look like (main attention to the last line):
```
$ avahi-browse --cache --resolve _meshcop._udp
+   eth0 IPv6 OpenThreadDemo                                _meshcop._udp        local
+   eth0 IPv4 OpenThreadDemo                                _meshcop._udp        local
=   eth0 IPv6 OpenThreadDemo                                _meshcop._udp        local
   hostname = [otc-otbr-05.local]
   address = [fdaa:bb::ba27:ebff:fe58:9fa2]
   port = [49191]
   txt = ["tv=1.2.0" "xp=""""" "nn=OpenThreadDemo"]
=   eth0 IPv4 OpenThreadDemo                                _meshcop._udp        local
   hostname = [otc-otbr-05.local]
   address = [172.16.1.5]
   port = [49191]
   **txt = ["rv=1" "tv=1.2.0" "sb=""""" "xp=""""" "nn=OpenThreadDemo" "dn=Thread" "sq=""""" "bb="""""]**
```

**Console/log output:** If applicable, add console/log output to help explain your problem.
In the current state the mDNS announce looks like (main attention to the last line):
```
$ avahi-browse --cache --resolve _meshcop._udp
+   eth0 IPv6 OpenThreadDemo                                _meshcop._udp        local
+   eth0 IPv4 OpenThreadDemo                                _meshcop._udp        local
=   eth0 IPv6 OpenThreadDemo                                _meshcop._udp        local
   hostname = [otc-otbr-05.local]
   address = [fdaa:bb::ba27:ebff:fe58:9fa2]
   port = [49191]
   txt = ["tv=1.2.0" "xp=""""" "nn=OpenThreadDemo"]
=   eth0 IPv4 OpenThreadDemo                                _meshcop._udp        local
   hostname = [otc-otbr-05.local]
   address = [172.16.1.5]
   port = [49191]
   **txt = ["tv=1.2.0" "xp=""""" "nn=OpenThreadDemo"]**
```

**Comment by wgtdkp** [comment]
I can confirm this is a known issue.

**Comment by wgtdkp** [comment]
@mikhail-pridushchenko created PR https://github.com/openthread/ot-br-posix/pull/721 for this issue.
