### ISSUE TITLE
Anything Needed in addition to a Raspberry Pi 3B?

### ISSUE THREAD

**Issue by mberg22** [openthread/ot-br-posix#705]
I've compiled both ot-br-posix and the example for nrf52840 with no errors.  I've also been all over the openthread.io site and can't seem to find a statement on this.  Does the Pi 3B have everything it needs to run this?  I see a reference to hooking up a serial cable, which I assume is to an additional board, as It wasn't clear just what or how to "flash" the nrf52840. Again, perhaps in error I assumed that was a chipset on the PI.

Id like to replace my Google wifi devices with Raspberry Pi's. I was assuming, perhaps incorrectly that the bootstrap scripts would pretty much do that.

Those bootstrap script are very nice, thanks for the hard work in creating them.
I can see the PI with my cellphone wifi, but I never get an IP address assigned and I get the following lines in my /var/log/syslog file over and over. 

Feb 21 23:30:58 mesh01 systemd[1]: otbr-agent.service: Service RestartSec=5s expired, scheduling restart.
Feb 21 23:30:58 mesh01 systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 689.
Feb 21 23:30:58 mesh01 systemd[1]: Stopped Border Router Agent.
Feb 21 23:30:58 mesh01 systemd[1]: Started Border Router Agent.
Feb 21 23:30:58 mesh01 otbr-agent[15467]: Running 0.2.0-f6404ab5-dirty
Feb 21 23:30:58 mesh01 otbr-agent[15467]: Thread interface wpan0
Feb 21 23:30:58 mesh01 systemd[1]: otbr-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 21 23:30:58 mesh01 otbr-agent[15467]: Backbone interface 
Feb 21 23:30:58 mesh01 systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Feb 21 23:30:58 mesh01 otbr-agent[15467]: [CRIT]-PLAT----: Init() at /home/pi/ot-br-posix/third_party/openthread/repo/src/posix/platform/hdlc_interface.cpp:150: InvalidArgument

**Comment by bukepo** [comment]
You need an 802.15.4 dongle which supports OpenThread. You may find many them in https://openthread.io/vendors.
