### ISSUE TITLE
Thread 1.2 non-CCM OTBR must report 2 bytes of operational dataset security policy flags

### ISSUE THREAD

**Issue by mikhail-pridushchenko** [openthread/ot-br-posix#714]
**Describe the bug** In Thread 1.2 non-CCM case OT BR reports security policy flags as defined by Thread 1.1 specification.

**To Reproduce** Information to reproduce the behavior, including:

1. OT BR commit: 3d6ce344a73f58d8dcec2caefa07c205f1484a01
    `openthread` module commit: e49d20ff02aa85a11f3a15d34a7a389516b79472
2. IEEE 802.15.4 hardware platform: nRF52840 dongle
3. Build steps:
    OTBR: with environment variables `NETWORK_MANAGER=0 BACKBONE_ROUTER=1`
    nRF52840 FW: `USB=1 BOOTLOADER=1 THREAD_VERSION=1.2`
4. Network topology: 1 OT BR, network formation just finished. Commissioner application able to detect and petition.

**Expected behavior**.
On commissioner command `opdataset get active` OT BR is to provide MGMT_ACTIVE_GET.rsp with 2 bytes of security policy flags (as defined in the Thread 1.2 specification pt. 8.10.1.15 Security Policy TLV (12)).
Output of the `ot-ctl dataset active` command is to be changed correspondingly.

**Console/log output** If applicable, add console/log output to help explain your problem.
1. Check on the OT BR side: in the shell issue `ot-ctl dataset active` command. The output will be:
```
$ sudo ot-ctl dataset active
...
Security Policy: 672, onrcb
Done
```
As per Thread 1.1 specification operational dataset security policy has 1 byte of flags with 5 flag bits. These flags symbolically shown inthe `Security Policy` line after the comma.

2. Check on the commissioner side:
```
> start fd01:1234:5678:0:ee08:fec4:de7f:625d 49191
[done]
> opdataset get active
{
...
    "SecurityPolicy": {
        "Flags": "ff",
        "RotationTime": 672
    }
}
[done]
```
`Flags` field is 1 byte long (as per Thread 1.1 specification).

**Additional context** Add any other context about the problem here.

**Comment by EskoDijk** [comment]
Yes, it needs to be 2 bytes of flags.  I did not build this OT BR yet so cannot comment if the build steps / commands are okay or not.

**Comment by jwhui** [comment]
Resolved by https://github.com/openthread/openthread/pull/6320
