### ISSUE TITLE
DHCPCD breaks OTBR IPv6 connectivity via Ethernet

### ISSUE THREAD

**Issue by mikhail-pridushchenko** [openthread/ot-br-posix#737]
**Describe the bug**
OTBR is inaccessible via IPv6 with `dhcpcd.conf` installed by setup script.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: 083fb6921903441bf44f46c263c123eb4af6e4a9
2. IEEE 802.15.4 hardware platform: nRF52840 (formal, unrelated)
3. Build steps:
```
$ NETWORK_MANAGER=0 BACKBONE_ROUTER=1 ./script/bootstrap
$ NETWORK_MANAGER=0 BACKBONE_ROUTER=1 ./script/setup
```
4. Network topology:
OTBR and PC connected to the ethernet switch. Both of them obtain IPv4 addresses from DHCP4 server, and IPv6 addresses by means of radvd daemon running on the separate Raspberry Pi connected to the same switch. The address information follows.
    4.1. OTBR:
```
$ ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:54:12:28 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.7/24 brd 172.16.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd01:1234:5678:0:ba27:ebff:fe54:1228/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 86399sec preferred_lft 14399sec
    inet6 fe80::ba27:ebff:fe54:1228/64 scope link 
       valid_lft forever preferred_lft forever
```
    4.2. PC:
```
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:b3:be:dd brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.250/24 brd 172.16.1.255 scope global dynamic noprefixroute enp0s3
       valid_lft 307sec preferred_lft 307sec
    inet6 fd01:1234:5678:0:584c:6db4:56ce:fd61/64 scope global temporary dynamic 
       valid_lft 86364sec preferred_lft 14364sec
    inet6 fd01:1234:5678:0:ca3e:ec4a:1c58:aa93/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 86364sec preferred_lft 14364sec
    inet6 fe80::ba49:b6dc:eb0c:ecb3/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

**Expected behavior** A clear and concise description of what you expected to happen.
OTBR must be accessible via IPv6 address. Particularly ICMP echo requests must be served and replied.

**Console/log output** If applicable, add console/log output to help explain your problem.
At the PC:
```
$ ping fd01:1234:5678:0:ba27:ebff:fe54:1228
PING fd01:1234:5678:0:ba27:ebff:fe54:1228(fd01:1234:5678:0:ba27:ebff:fe54:1228) 56 data bytes
^C
--- fd01:1234:5678:0:ba27:ebff:fe54:1228 ping statistics ---
491 packets transmitted, 0 received, 100% packet loss, time 501750ms
```
At the OTBR:
```
$ ping fd01:1234:5678:0:584c:6db4:56ce:fd61
connect: Network is unreachable
```

**Additional context** Add any other context about the problem here.
1. IPv4 networking has no issue.
2. When original `dhcpcd.conf` restored, IPv6 connectivity recovers:
OTBR addresses after restore:
```
$ ip a s eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:54:12:28 brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.7/24 brd 172.16.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd01:1234:5678:0:4629:94de:28b6:df8c/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 86351sec preferred_lft 14351sec
    inet6 fe80::4912:5494:aef3:492/64 scope link 
       valid_lft forever preferred_lft forever
```
Ping from PC:
```
$ ping fd01:1234:5678:0:4629:94de:28b6:df8c
PING fd01:1234:5678:0:4629:94de:28b6:df8c(fd01:1234:5678:0:4629:94de:28b6:df8c) 56 data bytes
64 bytes from fd01:1234:5678:0:4629:94de:28b6:df8c: icmp_seq=1 ttl=64 time=1.92 ms
64 bytes from fd01:1234:5678:0:4629:94de:28b6:df8c: icmp_seq=2 ttl=64 time=1.19 ms
^C
--- fd01:1234:5678:0:4629:94de:28b6:df8c ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 1.198/1.560/1.923/0.364 ms
```
3. OTBR works fine with original `dhcpcd.conf`.

**Comment by mikhail-pridushchenko** [comment]
`dhcpcd.conf` variants attached in the archive: [dhcp-ip6-no-ping.tar.gz](https://github.com/openthread/ot-br-posix/files/6148543/dhcp-ip6-no-ping.tar.gz)

* `dhcpcd.conf.orig` - original file.
* `dhcpcd.conf.otbr` - the one installed by setup script.

**Comment by wgtdkp** [comment]
@mikhail-pridushchenko Can you try with:
```shell
$ DHCPV6_PD=0 NETWORK_MANAGER=0 BACKBONE_ROUTER=1 ./script/bootstrap
$ DHCPV6_PD=0 NETWORK_MANAGER=0 BACKBONE_ROUTER=1 ./script/setup
```

The `DHCPV6_PD` option will change `dhcpcd.conf`.

Another option is to work on the latest OTBR master commit (2f566d8f2b7335a58c05e9616e40fcf3fc1cc919):
```shell
$ ./script/bootstrap
$ INFRA_IF_NAME=eth0 ./script/setup
```

(you will still need to restore the original dhcpcd.conf first because the changes by `DHCPv6_PD` is not easy to be undo.)

This commit has `NETWORK_MANAGER` and `DHCPV6_PD` disabled by default but enables `BACKBONE_ROUTER`. In addition, you don't need the `radvd` service any more because the new OTBR will advertise the prefix by itself.

**Comment by mikhail-pridushchenko** [comment]
Thank you for the instruction. Everything works fine with the latest comment.
