### ISSUE TITLE
OTBR-Agent doesn't start up

### ISSUE THREAD

**Issue by jensstruemper** [openthread/ot-br-posix#742]
**Describe the bug** A clear and concise description of what the bug is.
I've installed the most recent version of OTBR on a fresh RPI3b debian buster but otbr-agent fails starting

**To Reproduce** Information to reproduce the behavior, including:
./script/bootstrap
INFRA_IF_NAME=eth0 ./script/setup 

1. Git commit id
cf3a67383e9e25ca89208234d8efd8bee6b92f25

2. IEEE 802.15.4 hardware platform
nrf52840 USB dongle RCP 

3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

Mar 18 10:02:48 raspberrypi systemd[1]: Started Border Router Agent.
Mar 18 10:02:48 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Mar 18 10:02:48 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Mar 18 10:02:53 raspberrypi systemd[1]: otbr-agent.service: Service RestartSec=5s expired, scheduling restart.
Mar 18 10:02:53 raspberrypi systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 249.
Mar 18 10:02:53 raspberrypi systemd[1]: Stopped Border Router Agent.

**Additional context** Add any other context about the problem here.

**Comment by wgtdkp** [comment]
@jensstruemper Thanks for raising this issue, can you help provide the otbr-agent log? you can get the log with:
```shell
cat /var/log/syslog | grep otbr-agent
```

**Comment by jensstruemper** [comment]
Of course! 

This is repeatedly showing up in syslog:

Mar 18 12:22:08 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Mar 18 12:22:08 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Mar 18 12:22:13 raspberrypi systemd[1]: otbr-agent.service: Service RestartSec=5s expired, scheduling restart.
Mar 18 12:22:13 raspberrypi systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 1769.
Mar 18 12:22:13 raspberrypi otbr-agent[7790]: Running 0.3.0-cf3a6738
Mar 18 12:22:13 raspberrypi otbr-agent[7790]: Thread interface wpan0
Mar 18 12:22:13 raspberrypi otbr-agent[7790]: Backbone interface eth0
Mar 18 12:22:14 raspberrypi otbr-agent[7790]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Mar 18 12:22:14 raspberrypi otbr-agent[7790]: [NOTE]-PLAT----: RCP API Version: 3
Mar 18 12:22:14 raspberrypi otbr-agent[7790]: [CRIT]-PLAT----: RCP is missing required capabilities: tx-security tx-timing
Mar 18 12:22:14 raspberrypi otbr-agent[7790]: [CRIT]-PLAT----: CheckRadioCapabilities() at ../../third_party/openthread/repo/src/lib/spinel/radio_spinel_impl.hpp:380: RadioSpinelIncompatible

**Comment by wgtdkp** [comment]
@jensstruemper You need to rebuild your RCP firmware with one additional option:
1. `THREAD_VERSION=1.2` for automake
2. `-DOT_THREAD_VERSION=1.2` for CMake.

Better to clear the build directory and starts a fresh build.

**Comment by jwhui** [comment]
@jensstruemper , in openthread/openthread, we just switched the default Thread Version to 1.2 - see https://github.com/openthread/openthread/pull/6281. So if you use the latest from openthread/openthread, you should be able to build an RCP without needing to specify Thread Version 1.2 explicitly.

**Comment by jensstruemper** [comment]
Thanks @wgtdkp & @jwhui I was indeed using an outdated RCP firmware. I realized it when I copied the syslog.

**Comment by jensstruemper** [comment]
mhhh, I just tried to build the RPC but it failed:

 make -f examples/Makefile-nrf52840 USB=1 BOOTLOADER=USB
  MKDIR    build/nrf52840
  CONFIG   nrf52840...
(cd build/nrf52840 && /Users/jens/Development/openthread/examples/../configure INSTALL="/usr/bin/install -p" CPP="arm-none-eabi-cpp" CC=" arm-none-eabi-gcc" CXX=" arm-none-eabi-g++" CCAS=" arm-none-eabi-gcc" OBJC="" OBJCXX="" AR="arm-none-eabi-ar" RANLIB="arm-none-eabi-ranlib" NM="arm-none-eabi-nm" STRIP="arm-none-eabi-strip" CPPFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-nrf52840-config.h\"' -DOPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE='\"openthread-core-nrf52840-config-check.h\"' -I/Users/jens/Development/openthread/examples/../examples/platforms/nrf528xx/nrf52840  -DOPENTHREAD_CONFIG_CLI_TRANSPORT=OT_CLI_TRANSPORT_UART -DOPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1 -DOPENTHREAD_CONFIG_THREAD_VERSION=3 -DOPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT=0 -DMBEDTLS_USER_CONFIG_FILE='\"nrf52840-mbedtls-config.h\"' -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/mbedtls_plat_config -DMBEDTLS_CONFIG_FILE='\"nrf-config.h\"' -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/include -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/config -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/nrf_cc310_plat/include -DAPP_USBD_NRF_DFU_TRIGGER_ENABLED=1 -DOPENTHREAD_CONFIG_NCP_UART_ENABLE=1 -DUSB_CDC_AS_SERIAL_TRANSPORT=1 -Wno-expansion-to-defined -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mabi=aapcs " CFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-nrf52840-config.h\"' -DOPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE='\"openthread-core-nrf52840-config-check.h\"' -I/Users/jens/Development/openthread/examples/../examples/platforms/nrf528xx/nrf52840  -DOPENTHREAD_CONFIG_CLI_TRANSPORT=OT_CLI_TRANSPORT_UART -DOPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1 -DOPENTHREAD_CONFIG_THREAD_VERSION=3 -DOPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT=0 -DMBEDTLS_USER_CONFIG_FILE='\"nrf52840-mbedtls-config.h\"' -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/mbedtls_plat_config -DMBEDTLS_CONFIG_FILE='\"nrf-config.h\"' -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/include -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/config -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/nrf_cc310_plat/include -DAPP_USBD_NRF_DFU_TRIGGER_ENABLED=1 -DOPENTHREAD_CONFIG_NCP_UART_ENABLE=1 -DUSB_CDC_AS_SERIAL_TRANSPORT=1 -Wno-expansion-to-defined -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mabi=aapcs " CXXFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-nrf52840-config.h\"' -DOPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE='\"openthread-core-nrf52840-config-check.h\"' -I/Users/jens/Development/openthread/examples/../examples/platforms/nrf528xx/nrf52840  -DOPENTHREAD_CONFIG_CLI_TRANSPORT=OT_CLI_TRANSPORT_UART -DOPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1 -DOPENTHREAD_CONFIG_THREAD_VERSION=3 -DOPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT=0 -DMBEDTLS_USER_CONFIG_FILE='\"nrf52840-mbedtls-config.h\"' -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/mbedtls_plat_config -DMBEDTLS_CONFIG_FILE='\"nrf-config.h\"' -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/include -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/config -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/nrf_cc310_plat/include -DAPP_USBD_NRF_DFU_TRIGGER_ENABLED=1 -DOPENTHREAD_CONFIG_NCP_UART_ENABLE=1 -DUSB_CDC_AS_SERIAL_TRANSPORT=1 -Wno-expansion-to-defined -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mabi=aapcs -fno-exceptions -fno-rtti " CCASFLAGS="  -x assembler-with-cpp " LDFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-nrf52840-config.h\"' -DOPENTHREAD_CORE_CONFIG_PLATFORM_CHECK_FILE='\"openthread-core-nrf52840-config-check.h\"' -I/Users/jens/Development/openthread/examples/../examples/platforms/nrf528xx/nrf52840  -DOPENTHREAD_CONFIG_CLI_TRANSPORT=OT_CLI_TRANSPORT_UART -DOPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1 -DOPENTHREAD_CONFIG_THREAD_VERSION=3 -DOPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT=0 -DMBEDTLS_USER_CONFIG_FILE='\"nrf52840-mbedtls-config.h\"' -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/mbedtls_plat_config -DMBEDTLS_CONFIG_FILE='\"nrf-config.h\"' -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/include -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/config -I/Users/jens/Development/openthread/examples/../third_party/NordicSemiconductor/libraries/nrf_security/nrf_cc310_plat/include -DAPP_USBD_NRF_DFU_TRIGGER_ENABLED=1 -DOPENTHREAD_CONFIG_NCP_UART_ENABLE=1 -DUSB_CDC_AS_SERIAL_TRANSPORT=1 -Wno-expansion-to-defined -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mabi=aapcs -specs=nano.specs -specs=nosys.specs -Wl,--gc-sections " --host=arm-none-eabi --prefix=/ --exec-prefix=/nrf52840 --enable-ftd --enable-mtd --enable-linker-map --with-examples=nrf52840  --disable-builtin-mbedtls --with-custom-linker-file=/Users/jens/Development/openthread/examples/../examples/platforms/nrf528xx/nrf52840/nrf52840_bootloader_usb.ld --enable-ncp --enable-radio-only --enable-cli)
/bin/sh: /Users/jens/Development/openthread/examples/../configure: No such file or directory
make: *** [build/nrf52840/config.status] Error 127

**Comment by jwhui** [comment]
Did you run `./bootstrap` first?

**Comment by jensstruemper** [comment]
Argh. Yes, but the one in /script. Working fine now.
Thanks!
