### ISSUE TITLE
Unable to connect to BorderRouter-AP

### ISSUE THREAD

**Issue by 99002507** [openthread/ot-br-posix#759]
Hi,
**I have a problem where I'm able to see BorderRouter-AP SSID and when I tried to connect through my mobile it is not connecting, but just showing as saved.**

I'm using Raspberry Pi 3B with nrf52840 dongle for  BorderRouter setup in NCP design and did all the configuration correctly and could able to see the required services running, but facing issue on connecting to Wi-Fi AP. Tried with different mobiles but couldn't see any change.

Used ot-br-posix repo and Wpantund/master branch for configuration in Pi 3B.
Followed Nordic Semiconductor Infocenter instructions to program dongle with the supported firmware. 

**Commands used**: cd ot-br-posix 
git checkout wpandunt/master
./script/bootstrap
./script/setup
for wpanutund : /etc/wpantund.conf.
Config:NCP:SocketPath "/dev/ttyACM0"

**12345678** is the password that I tried to connect.
Checked in the network manger file in ot-br-posix repo, and can see the same password written there.

I would be very thankful if I get any solution or suggestion to resolve this issue.
Thank you.

**Comment by jwhui** [comment]
There seems to be a regression with the latest Raspberry Pi OS image.

Can you try using a separate Wi-Fi AP? You can try building with:

```
NETWORK_MANAGER=0 ./script/bootstrap
NETWORK_MANAGER=0 ./script/setup
```

Then use raspi-config to connect the RPi to your Wi-Fi AP.

**Comment by jwhui** [comment]
Closing stale issue.
