### ISSUE TITLE
otbr-agent init failure when increasing rx frame buffer size in OpenThread POSIX

### ISSUE THREAD

**Issue by paulrox** [openthread/ot-br-posix#771]
Hi,

I was facing the "NoBufs" problem when running my border router with OpenThread in RCP configuration and I've tried to increase the OPENTHREAD_CONFIG_PLATFORM_RADIO_SPINEL_RX_FRAME_BUFFER_SIZE value as suggested [here](https://github.com/openthread/openthread/issues/5678).
However, when I increase this value (I've tried 16384 and 32768) I'm no more able to launch the otbr-agent daemon because it fails on the `Init()` function.

This is the log:

```
Apr  2 11:31:23 glbr-2367010-ull user.info otbr-agent[1399]: Running 0.3.0-d7475e4
Apr  2 11:31:23 glbr-2367010-ull user.info otbr-agent[1399]: Thread version: 1.2.0
Apr  2 11:31:23 glbr-2367010-ull user.info otbr-agent[1399]: Thread interface: wpan0
Apr  2 11:31:23 glbr-2367010-ull user.info otbr-agent[1399]: Backbone interface:
Apr  2 11:31:23 glbr-2367010-ull user.crit otbr-agent[1399]: [CRIT]-PLAT----: Init() at /usr/src/debug/ot-br-posix/1.0+gitAUTOINC+d7475e4ae3-r0/git/third_party/openthread/repo/src/lib/spinel/radio_spinel_impl.hpp:270: Failure
```

I'm working with a fork of this project but my modifications involve just the Web Server side and the specific commit of the OpenThread library. In particular, I've recently updated the main repo on branch `main` with commit `4b6d3b86` and the OpenThread submodule on branch `main` with commit `eda95b04`. 

At this moment I've been able to solve the issue by increasing the UART baud rate to 460800 and by enabling the HW flow control but I would like to also increase the buffer size just to be sure.

**Comment by jwhui** [comment]
Failing in `RadioSpinel::Init()` typically indicates something even more fundamental than not having enough buffers. If you want to root cause this issue, I suggest trying to determine where `error` is being set to something other than `OT_ERROR_NONE` in `RadioSpinel::Init()`.

**Comment by jwhui** [comment]
Closing stale issue.
