### ISSUE TITLE
Binary build question

### ISSUE THREAD

**Issue by krbvroc1** [openthread/ot-br-posix#778]
Is there a process or some suggestions on how to build the ot-br-posix (for RaspPi) from source and create some sort of package of installable files or a debian package? I am a novice with CMake.

I'd like to build on either a RaspPi or perhaps docker (assuming it produces ARM executables) and be able to install on another RaspPi without having to repeat the lengthy process or duplicating SD cards.

I do see that there is an 'install_manifest.txt' generated in the build/otbr. I am not sure if that is a complete list and it doesn't really tell me the source location of those files, just the destination. Maybe I could just 'tar' those files up after installation, but I thought I'd ask the team here. You all probably do this a lot.

**Comment by bukepo** [comment]
you may build a package through `script/test clean package`.

**Comment by jwhui** [comment]
Closing stale issue.
