### ISSUE TITLE
commissioner in the web ui doesn't work

### ISSUE THREAD

**Issue by cahty82008** [openthread/ot-br-posix#780]
**Describe the bug**
**Border router:**
I set up a border router on Raspberry Pi 3B, in the Border Router web UI "Commission" page, i set up two parameters and start the commissioner, and got the information "Commission operation is success":
_Network Passphrase: 12345678
Joiner Pskd: J01NMM_
![image](https://user-images.githubusercontent.com/24818980/114027422-9ef02300-9877-11eb-8ddd-1b2caefee92a.png)

**Joiner**
then I tried to start the joiner, but it failed to join:
```
> factoryreset
> ifconfig up
Done
> panid 0xffff
Done
> scan
| J | Network Name     | Extended PAN     | PAN  | MAC Address      | Ch | dBm | LQI |
+---+------------------+------------------+------+------------------+----+-----+-----+
> | 0 | OpenThreadDemo   | 1111111122222222 | 1234 | 2e4f28c66b2de83e | 15 | -45 | 192 |
Done
> joiner start J01NMM
Done
> Join failed [NotFound]
> 
```

I also have a question, what is the "Network Passphrase"?  Where do i need this ? Seems that i only need the "Pskd" when i start a joiner.

**Comment by themzlab** [comment]
I have the same question.  Network Passphrase is a confusing term and I didn't see a related term in the command line instructions.

**Comment by jwhui** [comment]
@cahty82008 , thanks for raising this issue.

"Network Passphrase" should be removed from the Commission page.

I have submitted #780 to fix the issues you have raised.
