### ISSUE TITLE
Compile Ot-br-posix and RCP image

### ISSUE THREAD

**Issue by ChauhanPD** [openthread/ot-br-posix#787]
My Query is about guide to compile ot-br-posix with web-service and to compile RCP image to which ot-ctl can communicate.

I have taken ot-br-posix and openthread of below commit ids:
ot-br-posix:
#Master branch Commits till Apr 06, 2021
SRCREV = "b9565b4c44c9ccb413748d82905c8ef741768f57"

openthread:
#Apr 7, 2021
OPEN_THREAD_COMMIT_HASH="83cecbb8e3f9418e3953e3ce65c269561b3f947b"

I have compiled ot-br-posix, but it seems that web-service is not included by default. I have tried to make OTBR_WEB in main CMakeLists.txt along with other flags as below:

_set(OTBR_WEB ON)
set(OTBR_MDNS ON)
set(OTBR_WEB_DATADIR ${CMAKE_INSTALL_FULL_DATADIR}/otbr-web)
set(OTBR_BACKBONE_ROUTER ON)_

But, with the above flags, I observed errors for json/json.h file. I have resolved by applying below patch:

------------------------------------------------------------------------------------------------------------------------------------
diff --git a/src/web/web-service/wpan_service.hpp b/src/web/web-service/wpan_service.hpp
index 54a86a74..85c264d2 100644
--- a/src/web/web-service/wpan_service.hpp
+++ b/src/web/web-service/wpan_service.hpp
@@ -42,8 +42,8 @@
 #include <stdlib.h>
 #include <string.h>
 
-#include <json/json.h>
-#include <json/writer.h>
+#include <jsoncpp/json/json.h>
+#include <jsoncpp/json/writer.h>
 
 #include "common/logging.hpp"
 #include "utils/hex.hpp"

------------------------------------------------------------------------------------------------------------------------------------

But after that, there are many other errors observed.

Kindly guide me for the successful compilation of ot-br-posix with web-service.

Also, which flags should be included in the compilation of openthread source code for RCP image to which ot-ctl, from the host processor, can communicate?

**Comment by jwhui** [comment]
@ChauhanPD , have you taken a look at:

1. [Border Router Build and Configuration Guide](https://openthread.io/guides/border-router/build)
2. [Border Router Codelab](https://openthread.io/codelabs/openthread-border-router#0)

**Comment by krbvroc1** [comment]
@jwhui Those guides lack reproducibility. I am struggling with this myself (once again).

For example, if I want to create an OTBR using docker, how do I specify which git commit to use so I can create the same version next week as now? The docker process just fetches the latest, builds, and then deletes/uninstalls all the source tree it used! So how to even change build options?

And since someone would want a RCP that is compatible with the OTBR, how is that built? For example, I just followed the docker OTBR install and after it launched, it complained that my RCP was of the wrong version. It was probably from a hex file I had 2 months ago. Again, how would I separately build openthread with a *specific git commit* to I can create the same version next week as now?

**Comment by jwhui** [comment]
The Border Router Build and Configuration Guide includes a section on how to build the Docker image [Build the Dockerfile](https://openthread.io/guides/border-router/docker#build_the_dockerfile).

To build using a specific commit, just use:
```
```

1. `git checkout <commit>`
2. `git submodule

**Comment by krbvroc1** [comment]
But where to issue those commands? I used the Dockerfile and I am confused if it actually builds based on the git tree it is run from, or it actually downloads the otbr-latest docker image from dockerhub and uses that. I have a feeling it does the later which means it is not reproducible.

**Comment by jwhui** [comment]
> But where to issue those commands? I used the Dockerfile and I am confused if it actually builds based on the git tree it is run from, or it actually downloads the otbr-latest docker image from dockerhub and uses that. I have a feeling it does the later which means it is not reproducible. And since it deletes the source tree after the build, how do you pass options to it such as enabling 'OT_SERVICE' or some other feature?

Dockerfile builds directly from the local source tree - see [etc/docker/Dockerfile](https://github.com/openthread/ot-br-posix/blob/main/etc/docker/Dockerfile).

So just make sure your source tree is checked out to the commit you want (including submodules) before calling `docker build`.

**Comment by krbvroc1** [comment]
Ok, pardon my ignorance then, I thought I had to build with the Dockerfile, get a bash shell and rebuild inside the container. I was ignorant of the fact that it uses the source tree. So I guess I just modify the source tree locally (such as script/_otbr) to enable features. I thought I had to pass them as environment variables or something.

And if I look at the OTBR git history...
submodule: bump third_party/openthread/repo from `f7802d6` to `62ae1a1` 

Does that mean it is a good idea to fetch that openthread commit to use to build the RCP, so they match?

**Comment by jwhui** [comment]
> Does that mean it is a good idea to fetch that openthread commit to use to build the RCP, so they match?

While the serial interface between RCP and `ot-daemon` is relatively stable, it does change on occasion - like the recent switch to Thread 1.2.

Probably a good idea to stay in sync between the repos. `git submodule update` should do that for you. You can even go `third_party/openthread/repo` and build from there.

**Comment by krbvroc1** [comment]
> You can even go `third_party/openthread/repo` and build from there.

That sounds convenient, but doesn't the Dockerfile delete that directory? Or there something obvious I am missing on how to do that?

Also, rather than modify source code, I tried `docker build --build-arg OTBR_OPTIONS="-DOT_SERVICE=ON"`, but it doesn't appear that enables the SERVICE option. Is there some other magic to do this via the command line?

**Comment by jwhui** [comment]
> That sounds convenient, but doesn't the Dockerfile delete that directory? Or there something obvious I am missing on how to do that?

Dockerfile doesn't touch your local source tree. When building Docker, your local source tree is copied into Docker.

When building the RCP, just stay in your local source tree.

> Also, rather than modify source code, I tried `docker build --build-arg OTBR_OPTIONS="-DOT_SERVICE=ON"`, but it doesn't appear that enables the SERVICE option. Is there some other magic to do this via the command line?

That should enable the SERVICE build feature.  How did you determine that the SERVICE feature is not enabled?

**Comment by krbvroc1** [comment]
> When building the RCP, just stay in your local source tree.

What I think is confusing the issue here is that I also used Docker to build the RCP, so I wasn't clear on how to reuse that local source tree. I guess it doesn't apply since I am not cross compiling on the native host.

> That should enable the SERVICE build feature. How did you determine that the SERVICE feature is not enabled?

You are correct, after finally getting things running, the service commands are present. I was looking at the build process which was scrolling by and I did not see the '-DOT_SERVICE=ON' flag or what appeared to be the appropriate flag printed when it summarized the build options.

I am really struggling to get a working OTBR especially datasets failing to propagate and routing issues. When following these 'guides' to build the latest OTBR and RCP, I assume those are now THREAD 1.2. Is that somehow incompatible with the Router / End Devices that I am using that uses Nordic Connect SDK / Zeyphr / and its Openthread version (OPENTHREAD/gaad6518ee)?

**Comment by jwhui** [comment]
> I am really struggling to get a working OTBR especially datasets failing to propagate and routing issues. When following these 'guides' to build the latest OTBR and RCP, I assume those are now THREAD 1.2. Is that somehow incompatible with the Router / End Devices that I am using that uses Nordic Connect SDK / Zeyphr / and its Openthread version (OPENTHREAD/gaad6518ee)?

I cannot locate commit `aad6518ee`, but Thread 1.2 should be fully backward compatible with Thread 1.1.

Can you provide the steps/commands you are using so that we can reproduce the issues you are seeing?

**Comment by krbvroc1** [comment]
I have tried so many things that I have forgotten what/where I am to be honest... Thinking about reverting to the OTBR commit on my RaspPi from Feb 2 and reverting the RCP that same date.

Just as an example, 
Docker OTBR:
```
root@531a734e601a:/app# ot-ctl dataset active
Active Timestamp: 2
Channel: 26
Channel Mask: 0x07fff800
Ext PAN ID: babe1111babe2222
Mesh Local Prefix: fd42:b90b:4391:1c92::/64
Master Key: cafe2233445566778899babe9999babe
Network Name: Thread
PAN ID: 0x4638
PSKc: e887b3aa2e115e509688ad15a6579e49
Security Policy: 672, onrcb
Done
root@531a734e601a:/app# ot-ctl neighbor table
| Role | RLOC16 | Age | Avg RSSI | Last RSSI |R|D|N| Extended MAC     |
+------+--------+-----+----------+-----------+-+-+-+------------------+
|   R  | 0x7c00 |   0 |      -60 |       -59 |1|1|1| 3e56f5e088fd225c |
root@531a734e601a:/app# ot-ctl leaderdata
Partition ID: 1275277943
Weighting: 64
Data Version: 177
Stable Data Version: 242
Leader Router ID: 31
Done
root@531a734e601a:/app# ot-ctl netdata show
Prefixes:
fd7b:6c27:c742:5007::/64 paos med 9c00
Routes:
fd4d:6c4d:ef44:0::/64 s med 9c00
Services:
44970 5d c000 s 9c00
44970 01 4e04b000000e10 s 9c00
Done

```
And on the single FTD:
```
uart:~$ ot dataset active
Active Timestamp: 1
Channel: 26
Channel Mask: 0x07fff800
Ext PAN ID: babe1111babe2222
Mesh Local Prefix: fd78:5bd:40c2:3bb2::/64
Master Key: cafe2233445566778899babe9999babe
Network Name: Thread
PAN ID: 0x4638
PSKc: e887b3aa2e115e509688ad15a6579e49
Security Policy: 672, onrcb
Done
uart:~$ ot neighbor table
| Role | RLOC16 | Age | Avg RSSI | Last RSSI |R|D|N| Extended MAC     |
+------+--------+-----+----------+-----------+-+-+-+------------------+
|   R  | 0x9c00 |  22 |      -62 |       -63 |1|1|1| aaf59be3e145b34c |
uart:~$ ot leaderdata
Partition ID: 1275277943
Weighting: 64
Data Version: 177
Stable Data Version: 242
Leader Router ID: 31
Done
uart:~$ ot netdata show
Prefixes:
fd7b:6c27:c742:5007::/64 paos med 9c00
Routes:
fd4d:6c4d:ef44:0::/64 s med 9c00
Services:
44970 5d c000 s 9c00
44970 01 4e04b000000e10 s 9c00
Done
```
I don't understand it, the OTBR has a higher activetimestamp yet they do not sync up and they have different Mesh Local Prefix. It has been sitting like that for at least 30 minutes.

**Comment by jwhui** [comment]
@krbvroc1 , thanks for sharing more details. Unfortunately, I am not yet able to reproduce this behavior locally.

Can you also provide the output of `ipaddr` command on both devices?

If there's any chance you can share steps/commands to reproduce this behavior, that would help a lot.

**Comment by krbvroc1** [comment]
> Can you also provide the output of `ipaddr` command on both devices?

I went back to an earlier version of OTBR (running on RaspPi instead of Docker) and RCP and factory reset everything so both BR and FTD had the same dataset. What I have found so far is that even though I set a prefix and netdata register it, while the prefix does make it to the FTD, it does not show up under ipaddr on the FTD. The FTD is not adding/create a ip addr based on  the prefix. I am starting to wander if this is an issue with openthread under zephyr (or at least the version I am using -- official NCS 1.5.0). When I add the prefix I do not see the 'IP6_ADDRESS_ADDED' flag being set in the state change callback, only THREAD_NETDATA. Something just isn't correct.

Here you can see the FTD has the prefix, but no associated address.
```
uart:~$ ot netdata show
Prefixes:
2001:db8:1:0::/64 paros med 5400
Routes:
Services:
Done
uart:~$ ot ipaddr
fd03:b099:34cc:6d32:0:ff:fe00:fc00
fd03:b099:34cc:6d32:0:ff:fe00:9000
fd03:b099:34cc:6d32:c4bf:f257:a393:1aa6
fe80:0:0:0:c161:96f8:758f:ec37
Done
```

**Comment by jwhui** [comment]
> What I have found so far is that even though I set a prefix and netdata register it, while the prefix does make it to the FTD, it does not show up under ipaddr on the FTD. The FTD is not adding/create a ip addr based on the prefix.

Can you tell whether the Zephyr build enables OpenThread's `SLAAC` feature? OpenThread requires this feature to autoconfigure an IPv6 address.

Otherwise, this might be something specific to Zephyr. Maybe @LuDuda can provide some input.

**Comment by krbvroc1** [comment]
> Can you tell whether the Zephyr build enables OpenThread's `SLAAC` feature? OpenThread requires this feature to autoconfigure an IPv6 address.

I spent so many hours trying to figure this out and trace where the problems were among so many things... Why in the world would Nordic not set this option in their coap_client sample (or any sample for that matter). Enabling it has gotten routing working on the RaspPi. Now, I will try Docker again.

**Comment by ChauhanPD** [comment]
One more query:
script/setup modifies and/or adds files to the file-system along with compilation. Right? So, in my case of Yocto compilation, it actually modifies files of my PC and compiles code of the yocto build folder.
Is it okay to set up after compilation? Is there any dependency of set-up before compilation? Can we do only compilation and then set-up? If yes, kindly guide me to do the only compilation.

**Comment by ChauhanPD** [comment]
https://openthread.io/platforms/co-processor/ot-daemon
is it necessary to run ot-daemon before ot-ctl?

git clone --recursive https://github.com/openthread/ot-nrf528xx.git
$ cd ot-nrf528xx
$ script/build nrf52840 USB_trans

Is this the correct source? or https://github.com/openthread/openthread is correct? for RCP image

**Comment by jwhui** [comment]
> https://openthread.io/platforms/co-processor/ot-daemon
> is it necessary to run ot-daemon before ot-ctl?
> 
> git clone --recursive https://github.com/openthread/ot-nrf528xx.git
> $ cd ot-nrf528xx
> $ script/build nrf52840 USB_trans
> 
> Is this the correct source? or https://github.com/openthread/openthread is correct? for RCP image

We are currently transitioning platform-specific code from https://github.com/openthread/openthread to https://github.com/openthread/ot-nrf528xx
