### ISSUE TITLE
otbr-agent can not running

### ISSUE THREAD

**Issue by luyou-tuya** [openthread/ot-br-posix#790]
**Describe the bug** A clear and concise description of what the bug is.
  I git clone https://github.com/openthread/ot-br-posix.git  Latest code 
The compilation steps are as follows：
cd ot-br-posix
./script/bootstrap
INFRA_IF_NAME=eth0 ./script/setup
After the compilation is successful, restart the device, but otbr does not run
~# ot-ctl
connect session failed: No such file or directory
I manually execute the following commands：
root@chengqiang-desktop:~# otbr-agent -d 7 -v -I wpan0 spinel+hdlc+uart:///dev/ttyACM0
otbr-agent[6491]: Running 0.3.0-75ef16d5
otbr-agent[6491]: Thread version: 1.2.0
otbr-agent[6491]: Thread interface: wpan0
otbr-agent[6491]: Backbone interface:
otbr-agent[6491]: [INFO]-PLAT----: RCP reset: RESET_SOFTWARE
otbr-agent[6491]: [NOTE]-PLAT----: RCP API Version: 1
otbr-agent[6491]: [CRIT]-PLAT----: RCP is missing required capabilities: tx-security tx-timing
otbr-agent[6491]: [CRIT]-PLAT----: CheckRadioCapabilities() at ../../third_party/openthread/repo/src/lib/spinel/radio_spinel_impl.hpp:380: RadioSpinelIncompatible

but ootbr-agent still cannot run, what is the reason？

**Comment by wgtdkp** [comment]
Upgrade your RCP firmware to Thread 1.2. You can rebuild it with the `THREAD_VERSION=1.2` option for makefile or `OT_THREAD_VERSION=1.2` option for CMake (remember to clean the build directory before rebuilding). Another option is to update the RCP to the latest openthread main branch.

**Comment by luyou-tuya** [comment]
> Upgrade your RCP firmware to Thread 1.2. You can rebuild it with the `THREAD_VERSION=1.2` option for makefile or `OT_THREAD_VERSION=1.2` option for CMake (remember to clean the build directory before rebuilding). Another option is to update the RCP to the latest openthread main branch.
Thank you！
