### ISSUE TITLE
OTBR must announce non-local IPv6 address if available

### ISSUE THREAD

**Issue by mikhail-pridushchenko** [openthread/ot-br-posix#809]
**Describe the bug**
Under some circumstances the OTBR creates mDNS announce with link-local IPv6 address. As result commissioner is unable to connect to the BR with discovered address. The issue has stochastic nature. That is: only one of 3 BRs with same software reproduces the issue.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id a362436119261c7ea8f74a778b0d2a1236579b4f
2. IEEE 802.15.4 hardware platform: nRF52840 dongle
3. Build steps
```
$ git clone --recurse-submodules git@github.com:openthread/ot-br-posix.git
$ cd ot-br-posix
$ INFRA_IF_NAME=eth0 ./script/bootstrap
$ INFRA_IF_NAME=eth0 ./script/setup
```
4. Network topology: trivial (one OTBR).

**Expected behavior** OTBR must analyze all addresses on the interface passed as `-B` parameter to the otbr-agent and prefer any routable address.

**Comment by wgtdkp** [comment]
@mikhail-pridushchenko Thanks for the issue!
We are using `mDNSResponder` for advertising the `_meshcop._udp` service and
it is the mdns deamon that decides not preferring addresses with larger scope. I didn't find a to control this
behavior.

The OTBR is advertising in both IPv4 and IPv6 address spaces and the commissioner is discovering in only IPv4
space. I submitted https://github.com/openthread/ot-commissioner/pull/198 to reject any IPv6 addresses. Please
confirm if the PR works for you. (please directly comment in that PR if you find problems with, thanks!)

**Comment by wgtdkp** [comment]
@mikhail-pridushchenko can you help confirm if the PR resolves your issue?

**Comment by mikhail-pridushchenko** [comment]
I confirm it solves the issue. Thanks for the fix.

**Comment by jwhui** [comment]
Resolved by https://github.com/openthread/ot-commissioner/pull/198
