### ISSUE TITLE
Compile ot-br-posix for i.mx6ull in Yocto build system.

### ISSUE THREAD

**Issue by ChauhanPD** [openthread/ot-br-posix#818]
I need to compile the ot-br-posix source code for i.mx6ull processor as host and in yocto build system in my PC having Ubuntu 18.04 OS.
I am using ot-br-posix code of below commit id
#Master branch Commits till Apr 06, 2021
SRCREV = "b9565b4c44c9ccb413748d82905c8ef741768f57"

Kindly have an answer to each query

1. in my recipe file (.bb), I have called script/setup file.
This script/setup modifies and/or adds files to the file-system along with compilation. Right? So, in my case of Yocto compilation, it actually modifies files of my PC and compiles code of the yocto build folder.
Is it okay to set up after compilation? Is there any dependency of set-up before compilation? Can we do only compilation and then set-up? If yes, kindly guide me to do the only compilation of ot-br-posix code.

2. During compilation, I have an error related to "Boost" folder (posted on 16-Apr-2021 https://github.com/openthread/openthread/issues/6283):

I have updated _otbr script as below:
otbr_install ()
"-DCMAKE_INSTALL_PREFIX=/usr" is updated with
"-DCMAKE_INSTALL_PREFIX=/home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot/usr".

With above change, error related to "Boost" folder is resolved, but now struggling with new error:

| [1/342] Linking CXX executable third_party/openthread/repo/src/posix/ot-ctl
| FAILED: third_party/openthread/repo/src/posix/ot-ctl
| : && /home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++ -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0=/usr/src/debug/otbr/git-r0 -fdebug-prefix-map=/home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0=/usr/src/debug/otbr/git-r0 -fdebug-prefix-map=/home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot= -fdebug-prefix-map=/home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot-native= -fvisibility-inlines-hidden -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed third_party/openthread/repo/src/posix/CMakeFiles/ot-ctl.dir/client.cpp.o -o third_party/openthread/repo/src/posix/ot-ctl -L/home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot-native/usr/lib -Wl,-rpath,/home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot-native/usr/lib: /home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot/usr/lib/libreadline.so -lncurses && :
| /home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot-native/usr/lib/libncurses.so.5: file not recognized: file format not recognized
| collect2: error: ld returned 1 exit status

Kindly help me resolve the above error.

3. During build, I have seen below line:
build/otbr/build.ninja:6039: COMMAND = cd /home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/git/build/otbr/third_party/openthread/repo/third_party/mbedtls/repo && /home/pandurang/projects/git/Gateway/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/otbr/git-r0/recipe-sysroot-native/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.

I need to know from where this is generated? I want to replace "**recipe-sysroot-native**" with "**recipe-sysroot**"

4. https://openthread.io/platforms/co-processor/ot-daemon
is it necessary to run ot-daemon before ot-ctl?

5
git clone --recursive https://github.com/openthread/ot-nrf528xx.git
$ cd ot-nrf528xx
$ script/build nrf52840 USB_trans
Is this the correct source? or https://github.com/openthread/openthread is correct? for RCP image

Regards.

**Comment by ChauhanPD** [comment]
hello All,

Kindly give your valuable inputs.

Regards.

**Comment by ChauhanPD** [comment]
Hello @jwhui @abtink @wgtdkp 

Do you have any suggestions?

**Comment by ChauhanPD** [comment]
Hello @jwhui @abtink @wgtdkp 

https://openthread.io/platforms/co-processor
As per the above link:
"Radio Co-Processor (RCP) — Application layer and OpenThread core on the host processor, minimal OpenThread MAC on the 802.15.4 SoC. Communication between the RCP and the host processor is managed by OpenThread Daemon through an **SPI interface** over the Spinel protocol."

So, where do we give the information about SPI interface (socket path) as we do for UART like /dev/ttyUSB0 in wpantund?
Waiting for your reply to this and my previous queries.

Regards.

**Comment by abtink** [comment]
> So, where do we give the information about SPI interface (socket path) as we do for UART like /dev/ttyUSB0 in wpantund?

@ChauhanPD , 

 - RCP requires a OpenThread POSIX app (see [link](https://github.com/openthread/openthread/tree/main/src/posix) process to run on host (which implements the Thread protocol)
   - When running posix app, you specify the radio as radio URL link.
   - You can see all options (which include SPI) here: https://github.com/openthread/openthread/blob/main/src/posix/platform/radio_url.cpp#L38-L64

**Comment by gabekassel** [comment]
Here is a sample of a known working Yocto recipe for otbr-agent. As @abtink notes, you'll need an RCP/NCP running OT firmware. I would recommend invoking otbr-agent using whatever system manager in your system (example shown packages a systemd service that itself calls otbr-agent with the radio URL as specified when running otbr-agent --help). 

ot-ctl is the interface to ot-daemon and otbr-agent. The daemon must be running before ot-ctl is useful. 

```
DESCRIPTION = "OpenThread Border Router Agent"
HOMEPAGE = "https://github.com/openthread/ot-br-posix"

LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://LICENSE;md5=87109e44b2fda96a8991f27684a7349c"

SRCBRANCH ?= "main"
SRC_URI  += "gitsm://git@github.com/openthread/ot-br-posix.git;branch=${SRCBRANCH};protocol=ssh"

S = "${WORKDIR}/git"
SRCREV = "${AUTOREV}"
PV_append = "+${SRCPV}"

SRC_URI  += " \
    file://otbr-agent.service \
"

RDEPENDS_${PN} += "avahi-daemon"

DEPENDS += "avahi boost dbus iproute2 jsoncpp ncurses readline wget"

inherit cmake systemd

EXTRA_OECMAKE += " \
    -GNinja \
    -DCMAKE_BUILD_TYPE="Release" \
    -DOTBR_BORDER_ROUTING=ON \
    -DOTBR_COVERAGE=OFF \
    -DBUILD_TESTING=OFF \
    -DOTBR_MDNS=avahi \
    -DOTBR_BACKBONE_ROUTER=OFF \
    -DOTBR_SRP_ADVERTISING_PROXY=ON \
    -DOT_DUA=OFF \
    -DOT_MLR=OFF \
"

do_install_append() {
    install -d ${D}${systemd_system_unitdir}
    install -m 0644 ${WORKDIR}/otbr-agent.service ${D}${systemd_system_unitdir}
}

FILES_${PN} += "${systemd_system_unitdir}/otbr-agent.service"

SYSTEMD_SERVICE_${PN} = "otbr-agent.service"

SYSTEMD_AUTO_ENABLE_${PN} = "disable"
```

here's a sample of a systemd service/unit to invoke otbr-agent. your specific radio URL will depend on your RCP and platform. 
```
[Unit]
Description=OpenThread Border Router service
Wants=avahi-daemon.service
Wants=dbus.service

[Service]
Type=simple
ExecStart=otbr-agent -d7 -I wpan0 -B br-lan 'spinel+hdlc+uart:///dev/ttyQHS0?uart-baudrate=115200&uart-flow-control'
Restart=on-failure
RestartSec=5
```

building and running ot-daemon is very similar to above. it depends on your specific requirements which version you build. also note that the example above assumes Avahi as your mDNS resolver.

**Comment by jwhui** [comment]
Closing stale issue.
