### ISSUE TITLE
Building DBus client separately (as a library)

### ISSUE THREAD

**Issue by LanderN** [openthread/ot-br-posix#823]
**Is your feature request related to a problem? Please describe.**
For our C++ application, we need to issue commands to the running otbr-agent instance. The DBus API seems like a good way (the only way?) to do this. The provided DBus client code is easy-to-use and can save a lot of time writing our own wrapper. Unfortunately, it doesn't seem possible to build the dbus client for use by our application without also building a significant part of the remainder of the ot-br-posix and openthread code. This complicates the build process and pulls in dependencies (like mbedtls) which our application doesn't use.

**Describe the solution you'd like**
It would be useful to have the DBus client as a standalone library which applications can use to easily control the otbr-agent from another process.

**Describe alternatives you've considered**
We could use a general C++ DBus wrapper like the ones mentioned [here](https://www.freedesktop.org/wiki/Software/DBusBindings/), but they seem outdated and/or have significant dependencies we would like to avoid, while being more complicated to use than the provided DBus client.

**Comment by wgtdkp** [comment]
@LanderN Are there still such requirements? Have you already been able to build the d-bus client separately?

**Comment by jwhui** [comment]
Closing stale issue.
