### ISSUE TITLE
otbr hw is raspberrypi+rcp(nrf52840 USB). bind9.service, logrotate.service and man-db.service didn't work usually, when they work with several hours.

### ISSUE THREAD

**Issue by Vandoul** [openthread/ot-br-posix#835]
**Describe the bug** A clear and concise description of what the bug is.
The wpan0 interface disappeared when bind9, logrotate and man-db service run error. End devices can not work with otbr.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id : 
    master branch
2. IEEE 802.15.4 hardware platform : 
    NRF52840
3. Build steps
`
./script/bootstrap
INFRA_IF_NAME=eth0 ./script/setup
`
4. Network topology
    otbr is also a leader, connected by several end devices (sed, number of device is 10).
    32KB of data every 5 minutes.
    No other router role.

**Expected behavior** A clear and concise description of what you expected to happen.
    otbr runs the mqttSN gateway app, transpond data from end device to cloud server.

**Console/log output** If applicable, add console/log output to help explain your problem.
```
pi@raspberrypi:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        <...>

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        <...>

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        <...>

pi@raspberrypi:~ $ sudo systemctl --failed
  UNIT              LOAD    ACTIVE    SUB      DESCRIPTION
● bind9.service     loaded  failed    failed   BIND Domain Name Server
● logrotate.service loaded  failed    failed   Rotate log files
● man-db.service    loaded  failed    failed   Daily man-db regeneration

pi@raspberrypi:~ $ sudo systemctl status otbr-agent.service
● otbr-agent.service - Border Router Agent
   Loaded: loaded (/lib/systemd/system/otbr-agent.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Mon 2021-05-10 07:54:02 BST; 1s ago
  Process: 9730 ExecStart=/usr/sbin/otbr-agent $OTBR_AGENT_OPTS (code=killed, signal=ABRT)
 Main PID: 9730 (code=killed, signal=ABRT)

```

**Comment by jwhui** [comment]
@Vandoul , can you try with the latest main branch and see if this issue still exists? Thanks.

**Comment by jwhui** [comment]
Closing stale issue.
