### ISSUE TITLE
RCP has disconnected from a network and now fails to connect to that network

### ISSUE THREAD

**Issue by vijayrao1988** [openthread/ot-br-posix#854]
**Description**
I have a RCP + SBC device operating as a Border Router (OTBR) in a network of 18 devices. This network has been stable since the past 3 weeks. Since this morning, the Border Router device has been disconnected from the network. I can see all 17 devices on scan.

I have rebuilt otbr-posix on the SBC and done several resets and factory resets on the RCP through CLI (ot-ctl) but nothing seems to let the RCP attach to the established network of the 17 other devices. I have also seen messages related to different partitionid in the logs, but cannot find how I can change the partitionid of this RCP.

syslog output for otbr-agent shows something peculiar, as follows:

```
Received IPv6 UDP msg, len:84, chksum:f984, from:d64989268897f84b, sec:no, prio:net, rss:-29.0
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     src:[fe80:0:0:0:d449:8926:8897:f84b]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:2]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-PLAT----: processReceive: OK
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MLE-----: Receive Parent Request (fe80:0:0:0:d449:8926:8897:f84b)
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [WARN]-MLE-----: Failed to process Parent Request: Drop
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----: Received IPv6 UDP msg, len:84, chksum:8c80, from:e617a18459bb1d24, sec:no, prio:net, rss:-38.0
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     src:[fe80:0:0:0:e417:a184:59bb:1d24]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:2]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-PLAT----: processReceive: OK
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MLE-----: Receive Parent Request (fe80:0:0:0:e417:a184:59bb:1d24)
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [WARN]-MLE-----: Failed to process Parent Request: Drop
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----: Received IPv6 UDP msg, len:84, chksum:127d, from:a26714800096071c, sec:no, prio:net, rss:-35.0
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     src:[fe80:0:0:0:a067:1480:96:71c]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:2]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-PLAT----: processReceive: OK
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MLE-----: Receive Parent Request (fe80:0:0:0:a067:1480:96:71c)
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [WARN]-MLE-----: Failed to process Parent Request: Drop
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----: Received IPv6 UDP msg, len:84, chksum:62dc, from:9e4b67dc05de22fe, sec:no, prio:net, rss:-42.0
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     src:[fe80:0:0:0:9c4b:67dc:5de:22fe]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:2]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-PLAT----: processReceive: OK
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MLE-----: Receive Parent Request (fe80:0:0:0:9c4b:67dc:5de:22fe)
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [WARN]-MLE-----: Failed to process Parent Request: Drop
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----: Received IPv6 UDP msg, len:84, chksum:960d, from:439e4f5342c78c94, sec:no, prio:net, rss:-34.0
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     src:[fe80:0:0:0:419e:4f53:42c7:8c94]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:2]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-PLAT----: processReceive: OK
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MLE-----: Receive Parent Request (fe80:0:0:0:419e:4f53:42c7:8c94)
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [WARN]-MLE-----: Failed to process Parent Request: Drop
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----: Received IPv6 UDP msg, len:84, chksum:81c0, from:1ec6cca2bd84157c, sec:no, prio:net, rss:-46.0
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     src:[fe80:0:0:0:1cc6:cca2:bd84:157c]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:2]:19788
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-PLAT----: processReceive: OK
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [INFO]-MLE-----: Receive Parent Request (fe80:0:0:0:1cc6:cca2:bd84:157c)
May 19 22:53:13 NPT-gateway-8 otbr-agent[533]: [WARN]-MLE-----: Failed to process Parent Request: Drop
```

**To Reproduce**
I have not seen this issue previously and do not know how to reproduce this situation.

IEEE 802.15.4 hardware platform: Silicon Labs MGM12P SoC

Network topology: Mesh - All devices are currently mounted on a wall like framework to test functionality.

**Expected behavior**
In the past 3 weeks, the Border Router has been functioning fine. And this operation is expected to continue.

**Console/log output**
Console log output is attached above.

**Comment by jwhui** [comment]
@vijayrao1988 , can you provide more detail on your setup?

Are the other devices Full Thread Devices (FTDs) or Minimal Thread Devices (MTDs)?

I would look into [MleRouter::HandleParentRequest()](https://github.com/openthread/openthread/blob/178ac739389a296246e53c8e38108dd6bc79dbc1/src/core/thread/mle_router.cpp#L1550) to see which of the conditions that result in `kErrorDrop` are occuring.

**Comment by vijayrao1988** [comment]
The setup consists of 18 devices: 17 Full Thread Devices running a Thread stack off a Silicon Labs SDK and 1 RCP running a OpenThread Thread stack.
Physically, they are put on frame with 4 rows of 4 devices each and a 5th row with 1 device. The OpenThread RCP sits below this frame. The txpower on the devices is 0dBm as is the case with the RCP.
They were working fine for 3 weeks.
I must add that initially there were 20 devices and 3 were physically removed from the setup leaving the rest in tact. It was almost immediately after removing those 3 devices that we saw the connection drop off.
I have reinstalled otbr-posix, done resets and factory resets on the RCP through ot-ctl and rebooted the SBC a few times.

Is it possible that these devices have been put in some sort of a blocked list?

**Comment by vijayrao1988** [comment]
How do I look for more details from MleRouter::HandleParentRequest() in the logs?

**Comment by jwhui** [comment]
> How do I look for more details from MleRouter::HandleParentRequest() in the logs?

You would either need to add additional logging or use a debugger to inspect which condition is failing.

If all the devices are FTDs, then I'm surprised as to why devices would be sending Parent Request messages to the RCP? The FTDs should already have formed a network among themselves and the RCP should be joining that network.

**Comment by vijayrao1988** [comment]
Fair point. I think the devices entered some sort of an error state, in this case, where they weren't joining a network with matching parameters nor letting any other device join their network.

Update: We introduced 2 new devices to the network; 1 device running the same firmware as the Silicon Labs FTDs and another OpenThread RCP. This seemed to cause some sort of a brokering which unblocked the standoff. We now have a network of 20 devices. I still do not understand what caused the erroneous non-communicative state and how introducing 2 new devices resolved it. Could this some sort of blocked-list?

I think the problem is because of an old Thread stack in our firmware that Silicon Labs hasn't updated in a long time and don't maintain any more as they have moved to OpenThread. As a solution to avoid this situation in the future, we will move our device firmware out of Silicons Labs Thread stack in the coming few months.

**Comment by vijayrao1988** [comment]
The error has reoccured. I'm attaching the syslog output for otbr. Any observations that can help to resolve this issue?

In this log file, the initial part shows the presence of the devices through a scan. There are several Frame RX errors as well in the log. Could this be the problem?

[syslog-IsolatedBorderRouter.txt](https://github.com/openthread/ot-br-posix/files/6523532/syslog-IsolatedBorderRouter.txt)

**Comment by jwhui** [comment]
From the logs, it appears that OTBR is not able to join the existing partition. It sends MLE Parent Request messages, without receiving any MLE Parent Response.

From the logs, it's not clear why the other nodes are not responding to OTBR's MLE Parent Request message. Perhaps this is an issue with the legacy Thread implementation that you are using on the other devices?

**Comment by vijayrao1988** [comment]
Could someone help me with this please?

```
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:173, type:Data, src:0xf400, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:174, type:Data, src:0xf400, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:175, type:Data, src:0xf400, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:137, type:Data, src:0x2400, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:114, type:Data, src:0x0000, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:249, type:Data, src:0xb000, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:115, type:Data, src:0x0000, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:138, type:Data, src:0x2400, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:195, type:Data, src:0xcc00, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:250, type:Data, src:0xb000, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:196, type:Data, src:0xcc00, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:116, type:Data, src:0x0000, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:251, type:Data, src:0xb000, dst:0xffff, sec:yes, ackreq:no
May 21 16:49:03 NPT-gateway-8 otbr-agent[155571]: [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:100, seqnum:139, type:Data, src:0x2400, dst:0xffff, sec:yes, ackreq:no
```

**Comment by abtink** [comment]
@vijayrao1988 the log line `Frame rx failed, error:UnknownNeighbor, ...` simply shows that device received a secure frame from an unknown neighbor/device (a device not yet in neighbor table) and therefore it is dropping it. This log line itself is not bad and not necessarily a bug or issue. It's just a notification to show what's happening. That's expected when you have devices/neighbors in another partition.

As @jwhui mentioned, the logs indicate that other devices continue to try to attach and not be able to process the "Parent Response" from the OTBR.

**Comment by jwhui** [comment]
Closing stale issue.
