### ISSUE TITLE
libdns is missing in focal docker image

### ISSUE THREAD

**Issue by deimi** [openthread/ot-br-posix#859]
**Describe the bug** 
The focal docker image is missing libdns.  
![image](https://user-images.githubusercontent.com/8256985/119162522-c3384580-ba5a-11eb-869c-5f5ed850c6ee.png)

Relevant apt package is not installed:
![image](https://user-images.githubusercontent.com/8256985/119162129-5329bf80-ba5a-11eb-98a7-96bffed16c5e.png)

**Expected behavior** 

Same as for the bionic image:
![image](https://user-images.githubusercontent.com/8256985/119162157-5c1a9100-ba5a-11eb-9419-59847059c26e.png)

**Comment by jwhui** [comment]
@deimi , are you using the Docker Hub images?

https://openthread.io/guides/border-router/docker#get_the_otbr_docker_image

**Comment by deimi** [comment]
@jwhui yes

**Comment by deimi** [comment]
hmmm ok, it seems that libdns_sd.so is in the focal image, despite the apt package is not installed. So the problem probably is somewhere in our own image.

I will update this issue as soon as I found out more

**Comment by deimi** [comment]
@jwhui Sorry for the inconvenience, it was basically a fault in our image
