### ISSUE TITLE
mDNS service for OTBR

### ISSUE THREAD

**Issue by vijayrao1988** [openthread/ot-br-posix#864]
**Possible Use Case**
Thread mesh networks typically result in dynamic router tables and the intention of the self-forming and self-healing routing algorithm allows devices to pick up IP addresses as per availability. Border Routers being gateways, usually host important end-points and would benefit from publishing and discovering RCPs. For instance, I have a network with multiple RCP+OTBR and would like to be able to ping them as otbr1.local, otbr2.local, otbr3.local, etc. assuming their hostnames are otbr1, otbr2, etc.

**Alternatives I have considered**
I have tried configuring avahi to allow mdns through wpan0 but haven't succeeded. Is there something that needs to be added or is there something I'm doing incorrectly?

**Comment by wgtdkp** [comment]
@vijayrao1988 Do you want to ping from Thread end devices or Wi-Fi/ethernet hosts?

For ping from Thread end devices, @abtink @simonlingoogle I believe the "ping otbr1.local (otbr1.default.service.arpa)" function can be implemented with the OpenThread DNS client and server.

**Comment by vijayrao1988** [comment]
I would like to ping from Thread end devices.

The Thread network is completely made up of [_RCP + OTBR (Single Board Computer)_] devices.

**Comment by jwhui** [comment]
> @abtink and @simonlingoogle, would you be able to point me in the right direction please with the DNS Client and Server that @wgtdkp mentioned? I would also like to see how much of an overhead this would generate.

@vijayrao1988 , take a look at our [Thread Border Router - Bidirectional IPv6 Connectivity and DNS-Based Service Discovery](https://openthread.io/codelabs/openthread-border-router#0) Codelab.

**Comment by simonlingoogle** [comment]
To ping otbr from thread devices using domain names, I would suggest to use SRP instead of mDNS. 
- Each otbr should register a SRP service
```
srp client host name otbr1
srp client host address ML-EID
srp client service add otbr1 _br._udp <port>
```
- Now, you can browse or resolve the services from any thread device:
```
dns config <srp-server-up>
dns browse _br._udp.default.service.arpa 
dns service otbr1 _br._udp.default.service.arpa 
dns resolve otbr1.default.service.arpa 

```

**Comment by jwhui** [comment]
Closing stale issue.

**Comment by dakhnod** [comment]
Thanks for your help!
