### ISSUE TITLE
The `On-Mesh Prefix` is not transmit to thread devices

### ISSUE THREAD

**Issue by caipiblack** [openthread/ot-br-posix#872]
**Describe the bug**

When I create a new network using the WebClient or command line client (`ot-ctl`), the `On-Mesh Prefix` is configured, but when I connect a board into the Thread network, the board doesn't receive the `On-Mesh` IPV6. **So, I can't ping the Thread board from the border router or the RPI because it didn't have any accessible IPV6**

**To Reproduce**:

- Commit ID: 18b34dac9aef60e608712ae5125fe9c060ec9a6f
- IEEE 802.15.4 hardware platform: Wireless Starter Kit Mainboard (BRD4001A Rev A01) using EFR32MG12 Radio Board (BRD4162A Rev A02) 
- Network topology: 
  - `Raspberry PI4` + `Wireless Starter Kit Mainboard` + `BRD4162A`: This is the border router
  - `Wireless Starter Kit Mainboard` + `BRD4162A`: Runs the `lighting-app` exemple from (connectedhomeip).

![CHIP_Problem](https://user-images.githubusercontent.com/29680146/120002288-f471c200-bfd4-11eb-9aab-8b9dacd71849.png)

- Build steps:

Based on https://openthread.io/guides/border-router/build and https://www.silabs.com/documents/public/application-notes/an1256-using-sl-rcp-with-openthread-border-router.pdf

Get the repository:

```
git clone https://github.com/openthread/ot-br-posix
cd ot-br-posix
git submodule update --init
```

Setup the OTBR:

```
./script/bootstrap
INFRA_IF_NAME=eth0 ./script/setup
```

Content of `/etc/default/otbr-agent`:

```
pi@raspberrypi:~ $ cat /etc/default/otbr-agent
# Default settings for otbr-agent. This file is sourced by systemd

# Options to pass to otbr-agent
OTBR_AGENT_OPTS="-I wpan0 -B eth0 spinel+hdlc+uart:///dev/ttyACM0 trel://eth0"
```

After reboot, the services are running and the raspberry interfaces are like this:

![image](https://user-images.githubusercontent.com/29680146/119967606-d2644980-bfac-11eb-9a2c-925cb40ebf9c.png)

Then I use the web page to form a thread network.

![image](https://user-images.githubusercontent.com/29680146/119966747-e9ef0280-bfab-11eb-8e84-c2cc9be7ef12.png)

Now i run `ifconfig` again and got this:

![image](https://user-images.githubusercontent.com/29680146/119967883-1a836c00-bfad-11eb-872c-9be59270eaf5.png)

The `ot-ctl ipaddr` on the RaspberryPI return this: 

![image](https://user-images.githubusercontent.com/29680146/119967971-34bd4a00-bfad-11eb-80a8-e66edf7561b9.png)

On the Thread device, `ipaddr` only returns this:

![image](https://user-images.githubusercontent.com/29680146/119972176-31788d00-bfb2-11eb-9ffc-bacecd6c57e9.png)

**Expected behavior**

The thread device is suppose to receive the IP like "fd11:..." and it does not receive it

**Console/log output**

/

**Additional context**

/

**Comment by wgtdkp** [comment]
The Thread end device and the Thread Border Router (the Raspberry Pi) are not in the same Thread Network.

To join the Thread end device to the Network formed by the OTBR:
1. Get the Active Operational Dataset on the OTBR:
```txt
sudo ot-ctl dataset active -x
0e080000000000000000000300000f35060004001fffe0020811111111222222220708fd11111111220000051000112233445566778899aabbccddeeff030f4f70656e5468726561642d3832306201021234041023b0f18571ab84e1e1fa14e5d6a6c6c10c0402a0fff8
```
2. Copy the HEX string
3. connect to your Thread end device and set the same Active Operational Dataset:
```txt
> dataset set active 0e080000000000000000000300000f35060004001fffe0020811111111222222220708fd11111111220000051000112233445566778899aabbccddeeff030f4f70656e5468726561642d3832306201021234041023b0f18571ab84e1e1fa14e5d6a6c6c10c0402a0fff8
Done
> ifconfig up
Done
> thread start
Done
```

Wait a minute and make sure the end device goes to state `child` or `router` (use command `state`).
You should be able to ping the `fd68:5f8a....` addresses of OTBR from the end device.

**Comment by caipiblack** [comment]
> The Thread end device and the Thread Border Router (the Raspberry Pi) are not in the same Thread Network.
> 
> To join the Thread end device to the Network formed by the OTBR:
> 
> 1. Get the Active Operational Dataset on the OTBR:
> 
> ```
> sudo ot-ctl dataset active -x
> 0e080000000000000000000300000f35060004001fffe0020811111111222222220708fd11111111220000051000112233445566778899aabbccddeeff030f4f70656e5468726561642d3832306201021234041023b0f18571ab84e1e1fa14e5d6a6c6c10c0402a0fff8
> ```
> 
> 1. Copy the HEX string
> 2. connect to your Thread end device and set the same Active Operational Dataset:
> 
> ```
> > dataset set active 0e080000000000000000000300000f35060004001fffe0020811111111222222220708fd11111111220000051000112233445566778899aabbccddeeff030f4f70656e5468726561642d3832306201021234041023b0f18571ab84e1e1fa14e5d6a6c6c10c0402a0fff8
> Done
> > ifconfig up
> Done
> > thread start
> Done
> ```
> 
> Wait a minute and make sure the end device goes to state `child` or `router` (use command `state`).
> You should be able to ping the `fd68:5f8a....` addresses of OTBR from the end device and there should
> be `fd68:5f8a...` addresses on the end device as well.


Hello,
I tried what you write, but doing this I am still unable to ping my thread device from the border router or the RaspberryPI.

This is the result of `sudo ot-ctl ipaddr` on the BR:

```
pi@raspberrypi:~ $ sudo ot-ctl ipaddr
fda1:fccd:98cd:e6c5:0:ff:fe00:fc11
fda1:fccd:98cd:e6c5:0:ff:fe00:fc38
fda1:fccd:98cd:e6c5:0:ff:fe00:fc10
fd11:22:0:0:abab:a7d8:7a0a:e278
fda1:fccd:98cd:e6c5:0:ff:fe00:fc00
fda1:fccd:98cd:e6c5:0:ff:fe00:5c00
fda1:fccd:98cd:e6c5:6478:698:4101:82f8
fe80:0:0:0:e3:59af:9a1:fd9a
Done
pi@raspberrypi:~ $ sudo ot-ctl dataset active -x
0e080000000000000000000300000f35060004001fffe0020811111111222222220708fda1fccd98cde6c5051000112233445566778899aabbccddeeff030e4f70656e54687265616444656d6f01021234041061e1206d2c2b46e079eb775f41fc72190c0402a0fff8
Done
```

Configuration of the thread device: 

```
> factoryreset

> dataset set active 0e080000000000000000000300000f35060004001fffe0020811111111222222220708fda1fccd98cde6c5051000112233445566778899aabbccddeeff030e4f70656e54687265616444656d6f01021234041061e1206d2c2b46e079eb775f41fc72190c0402a0fff8
Done
> ifconfig up
Done
> thread start
Done
> ipaddr
fda1:fccd:98cd:e6c5:6b76:3e64:8a5c:3cf0
fe80:0:0:0:d4a7:9afd:4a50:16b
Done
```

A few moments later, the `ipaddr` command, return this:

```
> ipaddr
fda1:fccd:98cd:e6c5:0:ff:fe00:fc00
fda1:fccd:98cd:e6c5:0:ff:fe00:6400
fda1:fccd:98cd:e6c5:6b76:3e64:8a5c:3cf0
fe80:0:0:0:d4a7:9afd:4a50:16b
Done
```

I try to ping all of these addresses without success from the raspberry PI (using `ping` and `ot-ctl ping`)

```
pi@raspberrypi:~ $ sudo ot-ctl
> ping fda1:fccd:98cd:e6c5:0:ff:fe00:fc00
> 1 packets transmitted, 0 packets received. Packet loss = 100.0%.
Done
> ping fda1:fccd:98cd:e6c5:0:ff:fe00:6400
> 1 packets transmitted, 0 packets received. Packet loss = 100.0%.
Done
> ping fda1:fccd:98cd:e6c5:6b76:3e64:8a5c:3cf0
> 1 packets transmitted, 0 packets received. Packet loss = 100.0%.
Done
> ping fe80:0:0:0:d4a7:9afd:4a50:16b
> 1 packets transmitted, 0 packets received. Packet loss = 100.0%.
Done
```

What is wrong with my network ? Is there something to enable during the setup of `ot-br-posix` ? 

In a document I see:

`Each Thread node can be assigned a least one GUA when the upstream infrastructure for delegating a global prefix via a border router is available.`

How to know if this is implemented ? 

Notice: When I connect my thread device to a Thread 1.1 Border Router, it correctly receive an IPV6 compliant with the `On-Mesh Prefix` (like `fd11:...`) and we can ping the device from the raspberry PI. But when I use the latest version of `ot-br-posix` with thread 1.2 the device don't receive the GUA and cannot be ping from the BR or outside.

**Comment by wgtdkp** [comment]
> Wait a minute and make sure the end device goes to state child or router (use command state).

Can you confirm this on the end device?

**Comment by caipiblack** [comment]
> > Wait a minute and make sure the end device goes to state child or router (use command state).
> 
> Can you confirm this on the end device?

It's strange when the end device enter in the thread network it became leader.

The configuration of the BR:

![image](https://user-images.githubusercontent.com/29680146/120179462-e7d6af00-c20a-11eb-9cfd-a6abf7cea67a.png)

The configuration of the end device (to join thread network):

![image](https://user-images.githubusercontent.com/29680146/120179826-587dcb80-c20b-11eb-9752-e3111274b4bd.png)

**Comment by caipiblack** [comment]
> > Wait a minute and make sure the end device goes to state child or router (use command state).
> 
> Can you confirm this on the end device?

Every time I enter the command that you gave me previously (`dataset set active ....`) the 'end device' become a leader ! And if he was previously connected to the Border Router, he is disconnected. 

Exemple:

```
pi@raspberrypi:~ $ sudo ot-ctl ipaddr
fd1e:7a47:b13:1762:0:ff:fe00:fc11
fd1e:7a47:b13:1762:0:ff:fe00:fc38
fd1e:7a47:b13:1762:0:ff:fe00:fc10
fd11:22:0:0:d535:a50c:6e9c:6859
fd1e:7a47:b13:1762:0:ff:fe00:fc00
fd1e:7a47:b13:1762:0:ff:fe00:8400
fd1e:7a47:b13:1762:367c:56ae:768c:8d07
fe80:0:0:0:5806:c747:2bee:199a
Done
pi@raspberrypi:~ $ sudo ot-ctl dataset active -x
0e080000000000000000000300000f35060004001fffe0020811111111222222220708fd1e7a470b131762051000112233445566778899aabbccddeeff030e4f70656e54687265616444656d6f01021234041061e1206d2c2b46e079eb775f41fc72190c0402a0fff8
Done
pi@raspberrypi:~ $ sudo ot-ctl child table
| ID  | RLOC16 | Timeout    | Age        | LQ In | C_VN |R|D|N|Ver|CSL|QMsgCnt| Extended MAC     |
+-----+--------+------------+------------+-------+------+-+-+-+---+---+-------+------------------+
|   1 | 0x8401 |        240 |         17 |     3 |  239 |1|1|1|  2| 0 |     0 | daec2b6d25a7d2cc |

Done
```

Then I enter the command on the end-device, and it is disconnected.

```
pi@raspberrypi:~ $ sudo ot-ctl child table
| ID  | RLOC16 | Timeout    | Age        | LQ In | C_VN |R|D|N|Ver|CSL|QMsgCnt| Extended MAC     |
+-----+--------+------------+------------+-------+------+-+-+-+---+---+-------+------------------+

Done
```

Proof:

```
pi@raspberrypi:~ $ sudo ot-ctl factoryreset
pi@raspberrypi:~ $ sudo ot-ctl scan
| J | Network Name     | Extended PAN     | PAN  | MAC Address      | Ch | dBm | LQI |
+---+------------------+------------------+------+------------------+----+-----+-----+
| 0 | OpenThreadDemo   | 1111111122222222 | 1234 | daec2b6d25a7d2cc | 15 | -30 | 255 |
| 0 | NEST-PAN-6D78    | dd4573e038658bf6 | 001e | 18b430000083fed7 | 26 | -34 | 255 |
| 0 | NEST-PAN-6D78    | dd4573e038658bf6 | 001e | 18b43000013502ca | 26 | -56 | 255 |
Done
```

**Comment by caipiblack** [comment]
Note that when I connect the "end device" to the thread network without using your command. The "end device" state change to "detached".

```
> state
detached
Done
```

**Comment by wgtdkp** [comment]
@caipiblack This seems not reasonable to me. Is it possible for you to try with two new boards?

**Comment by caipiblack** [comment]
> @caipiblack This seems not reasonable to me. Is it possible for you to try my commands with two **new** boards?

What i know is that if i use another border router from another raspberry pi image, it works with the same end device: 

- The end device get the `fd11:...` IPV6 automatically. 
- It can be ping from the BR using this IPV6

But it's a pre-mounted border router and from another manufacturer: Qorvo.

That's why I think the problem is with the border router configuration or HW but not around the "end device".

When I connect the "end device" to the thread network, using sillabs instructions i got this:

![image](https://user-images.githubusercontent.com/29680146/120282074-02b42c80-c2ba-11eb-831a-0f212ac1b3e9.png)

What is "detached" state ?

At this point, is there something wrong with this, except for the missing IPV6 ?

I will receive some NRF52840 dongles next days, so I will try with it.

**Comment by caipiblack** [comment]
After some debugging using another ot-rcp board (NRF52840), I just realized that the manufacturers implementation of ot-rcp is not up-to-date, and makes troubles with last versions of ot-br-posix.

When I use the implementations from `openthread` repository, it works perfectly!

**Conclusion:**

1. Use this to build ot-rcp firmware:

```
https://github.com/openthread/ot-efr32
https://github.com/openthread/ot-nrf528xx
...
```

2. Do not use this: [AN1256](https://www.silabs.com/documents/public/application-notes/an1256-using-sl-rcp-with-openthread-border-router.pdf), even with Thread 1.2 configured, the ot-rcp does not work with current versions.

**Comment by silabs-sebastien** [comment]
> After some debugging using another ot-rcp board (NRF52840), I just realized that the manufacturers implementation of ot-rcp is not up-to-date, and makes troubles with last versions of ot-br-posix.
> 
For your RCP and OTBR to be compatible, you would need to use compatible sources. In the case of EFR32-based radio boards (Silicon Labs), you would need to either use RCP and OTBR code from the same GSDK version _or_ RCP and OTBR code from the public repos (ex: [ot-efr32](https://github.com/openthread/ot-efr32) for the EFR32 radio boards). Mixing and matching the two code sources will most certainly lead to issues since they are not tested together and use different commits.

> Do not use this: [AN1256](https://www.silabs.com/documents/public/application-notes/an1256-using-sl-rcp-with-openthread-border-router.pdf), even with Thread 1.2 configured, the ot-rcp does not work with current versions.
This is unfortunately not clear in the current version of the document, but AN1256 is only meant to be used with code provided in the GSDK and thus is not compatible with the latest on the public repos. I'll pass along this info to the appropriate people to make this clearer with the next update to the documentation.

**Comment by suveshpratapa** [comment]
@caipiblack AN1256 is meant for use with stable ot-br-posix and openthread commits that we test and link against our Silicon Labs GSDK releases.  If you are using ot-rcp that comes with Simplicity Studio for a given release, it is compatible with the version of ot-br-posix that also comes with that release.

If you do want to use the latest openthread code, you're right, please build your applications using [ot-efr32](https://github.com/openthread/ot-efr32)

This repo was only created recently, so we will be adding these updates to our application notes starting with our next release.
