### ISSUE TITLE
Allow runtime setting of vo= and vd= meshcop record attributes

### ISSUE THREAD

**Issue by gabekassel** [openthread/ot-br-posix#885]
**Is your feature request related to a problem? Please describe.** 
vo= and vd= are useful to customize in the meshcop service. it would be helpful to be able to easily set these at runtime.

**Describe the solution you'd like** 
A CLI to set vo/vd.

**Comment by wgtdkp** [comment]
@gabekassel Not sure if there are still the requests for this feature, we added d-bus APIs for adding arbitrary vendor-specific TXT entries to the MeshCoP mDNS service (https://github.com/openthread/ot-br-posix/pull/1081), though we didn't add CLI commands for it.

You can take a look at
https://github.com/openthread/ot-br-posix/blob/7d61390a30e184ed4f9b8381656a6ef84dd05cef/tests/dbus/test-client#L60-L82
For how to interact via gdbus.
