### ISSUE TITLE
ninja: error: loading 'build.ninja' when building the ot-br-posix for openwrt

### ISSUE THREAD

**Issue by silabs-NikhilS** [openthread/ot-br-posix#894]
Hi,

I am trying to build the border router for openwrt with instructions mentioned in the readme.md  here -> ot-br-posix/tree/main/etc/openwrt/openthread-br. I am getting error following error in Step 3 during compiling. I am building on machine running Ubuntu20.04.

ninja: Entering directory `/home/nikhils/OpenwrtTest/openwrt/build_dir/target-x86_64_musl/openthread-br-1.0'
ninja: error: loading 'build.ninja': No such file or directory

See the attached build log for more information.
[build_log_openwrt-ot-br-posix.txt](https://github.com/openthread/ot-br-posix/files/6658069/build_log_openwrt-ot-br-posix.txt)

Has anyone come across similar issue before? Any help would be much appreciated.
Thanks Nikhil

**Comment by jwhui** [comment]
We noticed the issue as well. This line seems to indicate that there is an issue with the version of git being used. In particular, the following error in the log file:
```
fatal: --dirty is incompatible with commit-ishes
```
@bukepo , thoughts on how best to addres?

**Comment by silabs-NikhilS** [comment]
Thanks @bukepo I have just tried it and I can confirm I can build the otbr for openwrt now.
