### ISSUE TITLE
otbr-agent fails with RCP capabilities error for CC2538

### ISSUE THREAD

**Issue by Hard1kPrajapat1** [openthread/ot-br-posix#900]
Hello team,

I am working on the custom board where CC2538 is connected on UART. I want my board to work as a border router.
I have cross-compiled the RCP binary for CC2538 from the below repository:
[https://github.com/openthread/ot-cc2538.git]()

I have also cross-compiled the otbr-agent from the below link to create my board as BR.
[https://github.com/openthread/ot-br-posix](url)

But, as soon as I start otbr-agent, it fails with RCP capabilities error as following:

```
# otbr-agent -I wpan0 -B eth0 spinel+hdlc+uart:///dev/ttyS8?uart-baudrate=115200 trel://eth0 -v
otbr-agent[1415]: [INFO]-UTILS---: Running 0.3.0-8ef580a-dirty
otbr-agent[1415]: [INFO]-UTILS---: Thread version: 1.2.0
otbr-agent[1415]: [INFO]-UTILS---: Thread interface: wpan0
otbr-agent[1415]: [INFO]-UTILS---: Backbone interface: eth0
otbr-agent[1415]: [INFO]-UTILS---: Radio URL: spinel+hdlc+uart:///dev/ttyS8?uart-baudrate=115200
otbr-agent[1415]: [INFO]-UTILS---: Radio URL: trel://eth0
otbr-agent[1415]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
otbr-agent[1415]: [NOTE]-PLAT----: RCP API Version: 3
otbr-agent[1415]: [CRIT]-PLAT----: RCP is missing required capabilities: tx-security tx-timing
otbr-agent[1415]: [CRIT]-PLAT----: CheckRadioCapabilities() at ../third_party/openthread/repo/src/lib/spinel/radio_spinel_impl.hpp:384: RadioSpinelIncompatible
```

Can you please help me to solve these errors? JFYI, I am using the latest source at both sides with OT version 1.2.

Thanks,
Hardik

**Comment by jwhui** [comment]
@Hard1kPrajapat1 , yes, this is expected since the CC2538 example does not currently implement required Thread 1.2 features. One option is to downgrade OTBR to Thread 1.1. See the discussion here for how to do that: https://github.com/openthread/ot-cc2538/issues/53

**Comment by Hard1kPrajapat1** [comment]
@jwhui, thank you very much for pointing me out the exact reason. I will switch back to an older version. 
I am closing this thread.
