### ISSUE TITLE
Add support to build Openthread version 1.1.1

### ISSUE THREAD

**Issue by daniel-nicolai-hansten** [openthread/ot-br-posix#905]
When building otbr there is no good switches to build agains openthread version 1.1.
As there is some compability issues with ot devices with thread 1.1 and 1.2 otbr it would be nice to have an option to build the otbr agent with ot 1.1.

**Comment by OlivierGre** [comment]
Hi Daniel,
Did you find a way to build against openthread version 1.1?

**Comment by gabekassel** [comment]
Can’t you simply pass in the cmake flag —DOT_THREAD_VERSION=1.1 ?

**Comment by OlivierGre** [comment]
I have tried but it doesn't work. I have described what I have done in another ticket:
https://github.com/openthread/openthread/issues/7162#issuecomment-972686884

A side comment:
I have used
`INFRA_IF_NAME=wlan0 OTBR_OPTIONS="-DOT_THREAD_VERSION=1.1" ./script/setup`
which is slightly different from wht you advised.

**Comment by wgtdkp** [comment]
The answer is `BACKBONE_ROUTER=0 OTBR_OPTIONS="-DOT_THREAD_VERSION=1.1" ./script/setup`

Fixed by https://github.com/openthread/openthread/issues/7162.
