### ISSUE TITLE
OTBR-WEB is getting aborted as soon as I start the web page.

### ISSUE THREAD

**Issue by Hard1kPrajapat1** [openthread/ot-br-posix#908]
Hello Team,

I have checked in the new source of **ot-br-posix** and cross-compiled for my customized board. The **otbr-agent** is working as expected but **otbr-web** exited with an error(invalid pointer) as soon as I start the web page.

Any help would be appreciated, please check the below logs for more details:
```
roo:~# otbr-web
otbr-web[1398]: [INFO]-WEB-----: Running 0.3.0-8ef580a-dirty
interfaceName not specified, using default wpan0
listenAddr not specified, using default 0.0.0.0
http port not specified, using default 80
otbr-web[1398]: [INFO]-WEB-----: Border router web started on wpan0
free(): invalid pointer
Aborted (core dumped)
```

Thanks,
Hardik

**Comment by bukepo** [comment]
could you provide the backtrace of the core dump?

**Comment by Hard1kPrajapat1** [comment]
[Crash_Report_OT-WEB.txt](https://github.com/openthread/ot-br-posix/files/6699875/Crash_Report_OT-WEB.txt)

Crash report and backtrace log is attached, please find it.

**Comment by Hard1kPrajapat1** [comment]
Is there any update on this?

**Comment by Hard1kPrajapat1** [comment]
Hi,

Just to add on that, I have also tested the same otbr-web binary on Raspberry Pi 3B but that is also showing the same error. So it seems like there is something we need to tweak in ot-br-posix source.

```
root@raspberrypi:/tmp# ./otbr-web -d 4
interfaceName not specified, using default wpan0
listenAddr not specified, using default 0.0.0.0
http port not specified, using default 80

*** Error in `./otbr-web': free(): invalid pointer: 0x0206e3ec ***
Aborted
```
JFYI, RasPI is booted with the OTBR package released by them and that is working. But newly cross-compiled from ot-br-posix source is not working. Please help.

Thanks,
Hardik

**Comment by Hard1kPrajapat1** [comment]
Hello,

Found the root cause. This issue I was facing because of some dependencies. However, it was not showing in error that on which it is dependent. Anyway, I am listing out the dependencies that I had to install to make it run, this may help others:

- avahi
- libnetfilter
- libnfnetlink
- libmnl

Thank you,
Hardik
