### ISSUE TITLE
Wifi access point fails providing IP addresses after reboot.

### ISSUE THREAD

**Issue by canisLupus1313** [openthread/ot-br-posix#915]
When Following [this](https://openthread.io/guides/border-router/access-point) instruction. After performing reboot of Raspberry Pi WIFI acces point do not work correctly  (fails to provide IP addresses).

**To Reproduce**
Install WiFi AP according to [this](https://openthread.io/guides/border-router/access-point) instruction.
Form Thread network.
Reboot Raspberry Pi.

Commit of ot-br to reproduce: f6c9b481004c1a0525973e10250350090319a4a5

**Expected behavior** After reboot network AP comes up without issues.

Failure to obtain the IP address is most probably related to:
```
pi@raspberrypi:~ $ sudo systemctl status dnsmasq
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```

In my case updating `/lib/systemd/system/otbr-agent.service` with `After=dnsmasq.service`.
And invoking `sudo systemctl enable dnsmasq`.
Solves the issue.

It would be helpful to update the instruction with this information.

**Comment by jwhui** [comment]
@canisLupus1313 , thanks for raising this issue. Would you like to submit a PR with the proposed change?

**Comment by canisLupus1313** [comment]
Hi,
I would be glad to do it. Just one newbie question before doing it.
Where is the source code of this instruction?

**Comment by jwhui** [comment]
> I would be glad to do it. Just one newbie question before doing it.
> Where is the source code of this instruction?

See the following files:

1.  [src/agent/otbr-agent.service.in](https://github.com/openthread/ot-br-posix/blob/main/src/agent/otbr-agent.service.in)
2. [script/_network_manager](https://github.com/openthread/ot-br-posix/blob/main/script/_network_manager)

I'm wondering if the proposed change will also help with #914

**Comment by canisLupus1313** [comment]
One more question does the docker image of [ot-br-posix](https://hub.docker.com/r/openthread/otbr). Does it contain and has the need for `dnsmasq`?

> I'm wondering if the proposed change will also help with #914
The problem there is that `dnsmasq` and network-manager is not installed by default on RPi image, nor the bootstrap script installs it. So I don't think it will be solved.

**Comment by jwhui** [comment]
> One more question does the docker image of [ot-br-posix](https://hub.docker.com/r/openthread/otbr). Does it contain and has the need for `dnsmasq`?

I think OTBR only installs dnsmasq to support Wi-Fi AP when `NETWORK_MANAGER=1`.

> The problem there is that `dnsmasq` and network-manager is not installed by default on RPi image, nor the bootstrap script installs it. So I don't think it will be solved.

In https://github.com/openthread/ot-br-posix/issues/914#issuecomment-871477292, you indicated setting `NETWORK_MANAGER=1`. Are you doing that here as well?

**Comment by jwhui** [comment]
> Yes. In both cases.

The Docker image for RPi does not support Wi-Fi AP mode and, as a result, does not include `dnsmasq`.

As mentioned, we looking to remove Wi-Fi AP configuration from the OpenThread Border Router guide.

**Comment by canisLupus1313** [comment]
Hi @jwhui sorry for delay. I think I know what to do I will try to prepare PR soon.

**Comment by jwhui** [comment]
> Hi @jwhui sorry for delay. I think I know what to do I will try to prepare PR soon.

@canisLupus1313 , https://openthread.io/guides/border-router/build has been updated to remove the Wi-Fi AP setup content. Thanks.
