### ISSUE TITLE
Yocto build fail: error: writing 16 bytes into a region of size 12

### ISSUE THREAD

**Issue by caipiblack** [openthread/ot-br-posix#931]
**Describe the bug**

Last week (July 8 2021), I was able to build otbr-agent with Yocto using the receipt from this issue:  https://github.com/openthread/ot-br-posix/issues/818

Today (15 July 2021) I get an error during the build:

```
.../third_party/openthread/repo/src/posix/platform/netif.cpp
| In file included from /home/user/Yocto-lab/build-rpi/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/otbr-agent/1.0.0+AUTOINC+8f44b8ceb2-r0/recipe-sysroot/usr/include/string.h:519,
|                  from /home/user/Yocto-lab/build-rpi/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/otbr-agent/1.0.0+AUTOINC+8f44b8ceb2-r0/git/third_party/openthread/repo/src/posix/platform/platform-posix.h:44,
|                  from /home/user/Yocto-lab/build-rpi/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/otbr-agent/1.0.0+AUTOINC+8f44b8ceb2-r0/git/third_party/openthread/repo/src/posix/platform/netif.cpp:35:
| In function 'void* memcpy(void*, const void*, size_t)',
|     inlined from 'void AddRtAttr(nlmsghdr*, uint32_t, uint8_t, const void*, uint8_t)' at /home/user/Yocto-lab/build-rpi/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/otbr-agent/1.0.0+AUTOINC+8f44b8ceb2-r0/git/third_party/openthread/repo/src/posix/platform/netif.cpp:534:15,
|     inlined from 'otError DeleteExternalRoute(const otIp6Prefix&)' at /home/user/Yocto-lab/build-rpi/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/otbr-agent/1.0.0+AUTOINC+8f44b8ceb2-r0/git/third_party/openthread/repo/src/posix/platform/netif.cpp:630:14,
|     inlined from 'void UpdateExternalRoutes(otInstance*)' at /home/user/Yocto-lab/build-rpi/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/otbr-agent/1.0.0+AUTOINC+8f44b8ceb2-r0/git/third_party/openthread/repo/src/posix/platform/netif.cpp:688:41,
|     inlined from 'void platformNetifStateChange(otInstance*, otChangedFlags)' at /home/user/Yocto-lab/build-rpi/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/otbr-agent/1.0.0+AUTOINC+8f44b8ceb2-r0/git/third_party/openthread/repo/src/posix/platform/netif.cpp:747:29:
| /home/user/Yocto-lab/build-rpi/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/otbr-agent/1.0.0+AUTOINC+8f44b8ceb2-r0/recipe-sysroot/usr/include/bits/string_fortified.h:29:33: error: writing 16 bytes into a region of size 12 [-Werror=stringop-overflow=]
|    29 |   return __builtin___memcpy_chk (__dest, __src, __len,
|       |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
|    30 |      __glibc_objsize0 (__dest));
|       |      ~~~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated due to -Wfatal-errors.
| cc1plus: all warnings being treated as errors
```

The error is a possible overflow or a wrong detection: `error: writing 16 bytes into a region of size 12`

**To Reproduce**

1. Git commit: The last ot-br-posix commit : 8f44b8ceb2a49041680d73621ea527f535a7ac2a
2. HW: RaspberryPI3 with Yocto
3. Build steps: Use the Yocto receipt from https://github.com/openthread/ot-br-posix/issues/818 and build the yocto image with otbr-agent included.
4. Network topology: None

**Expected behavior** 

The sources are supposed to build

Attached you will find the full logs

[log.do_compile.txt](https://github.com/openthread/ot-br-posix/files/6822957/log.do_compile.txt)

**Comment by caipiblack** [comment]
I bypass the problem adding this to the receipt:

```
TARGET_CFLAGS += "-Wno-stringop-overflow -Wno-error"
```

Like this the compilation is OK, but someone need to check if it's an error or a false positive.

**Comment by jwhui** [comment]
@caipiblack , thanks for raising this issue.

It appears the offending line is here: https://github.com/openthread/openthread/blob/f7fd2b08132e3626a3b79c11abee30505f3f30f4/src/posix/platform/netif.cpp#L534

@superwhd , can you help take a look?

**Comment by gabekassel** [comment]
@caipiblack fyi to potentially unblock you while that's looked at, the previous commit builds without errors for me. you can define the commit in yocto like this
```
SRCREV = "6e5576e9cb6f0da71ae96e3948a59683c58f5b11"
```

**Comment by gabekassel** [comment]
@superwhd @caipiblack is this still open? was about to try to move to a newer commit.

**Comment by superwhd** [comment]
@gabekassel It's still open. I'm investigating this issue but I haven't got much idea yet.

**Comment by superwhd** [comment]
@gabekassel Setting `OPENTHREAD_POSIX_CONFIG_INSTALL_EXTERNAL_ROUTES_ENABLE` as 0 should be a valid workaround if you'd like to use a newer commit.

https://github.com/openthread/openthread/blob/main/src/posix/platform/openthread-posix-config.h#L166

**Comment by jwhui** [comment]
@caipiblack @gabekassel , please review the proposed fix in https://github.com/openthread/openthread/pull/6840.
