### ISSUE TITLE
RCP ot-br don't send 802.15.4 ack

### ISSUE THREAD

**Issue by HeFeng1947** [openthread/ot-br-posix#935]
**Describe the bug：RCP-Host(ot-br) don't send 802.15.4 ack**

MTD child sends 802.15.4 Data Request to leader but leader(ot-br-RCP) don't send 802.15.4 ack. 

**I tried to build the ot-br on OpenWrt and Raspberry Pi, and both problems came up**.

**I have tried the hardware devices of Nordic and Silabs respectively, and the same problem appears in both of them.**

**I tried ncp-host(ot-br) and the problem didn't appear either.**

**I roll back to last year's commit(07e971761549416aca17bc209ba5ed08806033a2) and the issue is gone.**
![image](https://user-images.githubusercontent.com/42663554/126256034-b2cf981e-8962-462c-8ece-5b1f8cfc5602.png)

**To Reproduce**

1. Git commit id: f6c9b481004c1a0525973e10250350090319a4a5
2. IEEE 802.15.4 hardware platform: nrf52840、efr32mg21
3. Build steps: 
   1. ot-br create thread network
   2. mtd join the thread network(as child)
   3. mtd set mode n and childtimeout 15(This makes it easier to repeat the problem)
   4. ot-br don'n ack the child 802.15.4 data request so child change its short id frequently
4. Network topology: A leader and a MTD child

**Expected behavior** ot-br should ack its child 802.15.4 data request

**Console/log output** 

**ot-br cli log**

```
> dataset init new
Done
> dataset commit active
Done
> dataset
Active Timestamp: 1
Channel: 24
Channel Mask: 0x07fff800
Ext PAN ID: c4cf3905eef45a48
Mesh Local Prefix: fdbf:12c0:5949:a9a5::/64
Network Key: 28e2915f3cd837f1cf94a2a73b10fc06
Network Name: OpenThread-9271
PAN ID: 0x9271
PSKc: 1210540070d718bbb26e292fe5c231e7
Security Policy: 672 onrcb
Done
> ifconfig up
Done
> thread start
Done
> state
detached
Done
> state
leader
Done
```

**mtd log**

```
> dataset networkkey 28e2915f3cd837f1cf94a2a73b10fc06
Done
> dataset panid 0x9271
Done
> dataset commit active
Done
> ifconfig up
Done
> thread start
Done
> state
child
Done
> mode n
Done
> childtimeout 15
Done
```

**otbr-agent log**
[ot-br-agent-log.txt](https://github.com/openthread/ot-br-posix/files/6845249/ot-br-agent-log.txt)

**Additional context** 

wireshark+sniffer log
[thread-network-log.zip](https://github.com/openthread/ot-br-posix/files/6845245/thread-network-log.zip)

**Comment by HeFeng1947** [comment]
Add a test item:
**After child join the network, I kill the otbr-agent and the problem don't appear**

My guess is that the agent mistakenly thought the child node timeout and kicked it out of the network.

**Comment by HeFeng1947** [comment]
I tested the abtink's commit, but it didn't work.

add a new message:
I've tried dozens of this year's commit versions and found **OPENTHREAD_CONFIG_ANNOUNCE_SENDER_ENABLE** turned on in this openthread commit(e086cf5c8887f126d171f929988d3e478ace9a20). 
**If I set OPENTHREAD_CONFIG_ANNOUNCE_SENDER_ENABLE 0 , it works well.**

What do you think of this option? @jwhui @abtink

**Comment by jwhui** [comment]
@HeFeng1947 , for clarity, https://github.com/openthread/openthread/pull/6837 applies to the RCP. Did you update your RCP build to include the proposed change in https://github.com/openthread/openthread/pull/6837?

**Comment by jwhui** [comment]
@HeFeng1947 , the latest Thread specifications (1.2 and higher) will require the announce sender feature, which is why we have recently enabled it by default.

Can you confirm the steps you used to incorporate https://github.com/openthread/openthread/pull/6837 into your build?

**Comment by HeFeng1947** [comment]
> @HeFeng1947 , the latest Thread specifications (1.2 and higher) will require the announce sender feature, which is why we have recently enabled it by default.
> 
> Can you confirm the steps you used to incorporate [openthread/openthread#6837](https://github.com/openthread/openthread/pull/6837) into your build?

Yesterday's test seems to be wrong, I add these code(src/lib/spinel/radio_spinel_impl.hpp) based on abtink's commit, there is no problem in the test at present.

```
   - }
   + error = Set(SPINEL_PROP_PHY_CHAN, SPINEL_DATATYPE_UINT8_S, aChannel);
   + SuccessOrExit(error);
   + mChannel = aChannel;
```

**Comment by jwhui** [comment]
> Yesterday's test seems to be wrong, I add these code(src/lib/spinel/radio_spinel_impl.hpp) based on abtink's commit, there is no problem in the test at present.

@HeFeng1947 , great to hear. Thanks!
