### ISSUE TITLE
OTBR WEB on YOCTO Project

### ISSUE THREAD

**Issue by Holegon** [openthread/ot-br-posix#958]
Hello.

I have a question for you.

I am trying to include open thread in a YOCTO project.
The compilation is going well with a recipe found on the internet that I can provide.

Only, I'm trying to integrate the OTBR Web feature at the same time and it's causing me some problems.

Again I can provide the local.conf file if needed.

The first build told me that I needed the NPM package, so I included it in my configuration. And, during my second compilation I had no more errors. Only, I could not find the trace of the OTBR Web element on my compiled image.

Do you have an advice or a solution to give me?

Thanks

**Comment by Endag** [comment]
In my case it 's helped adding following dependencies to otrb recipe:

DEPENDS  - nodejs-native
RDEPENDS - nodejs

**Comment by jwhui** [comment]
Closing stale issue.
