### ISSUE TITLE
CLI to set vendor and product name for MeshCoP service name

### ISSUE THREAD

**Issue by gabekassel** [openthread/ot-br-posix#964]
**Is your feature request related to a problem? Please describe.**
https://github.com/openthread/ot-br-posix/pull/946 changed generation of the MeshCoP service name using hard coded values (OpenThread BorderRouter). It would be helpful to provide a CLI or runtime means to customize this at launch. 

**Describe the solution you'd like** 
CLI or runtime args to set service name

**Describe alternatives you've considered** 
We could fork and set this, but have been preferring to build against upstream.

**Comment by wgtdkp** [comment]
@gabekassel Do we need to change the names at runtime or being able to change it at compile-time is enough?

**Comment by gabekassel** [comment]
Compile time works! I thought of that then forgot to mention it. Simple CMake args would probably do the trick.

**Comment by gabekassel** [comment]
@wgtdkp is a compile time option easy to add?

**Comment by wgtdkp** [comment]
Sorry that I missed the response here! I added https://github.com/openthread/ot-br-posix/pull/975 to specify the vendor and product name with `OTBR_VENDOR_NAME` and `OTBR_PRODUCT_NAME`.
